### ISSUE TITLE
[Correção] API 2.1.0 rc0 - vencimento e expiração

### ISSUE THREAD

**Issue by SeanWykes** [bacen/pix-api#100]
Algumas dúvidas sobre o YAML v2.1.0-rc0

CobSolicitada: 
- o "required:' indica "expiracao" e "dataDeVencimento", mas consta somente "calendario" como subitem. 
- ambos são mesmo obrigatórios na solicitação?
- o campo "validadeAposVencimento" é novo. Este deve ser enviado na solicitação ou será formado pelo somatório do "expiracao" e "datadeValidade", conforme comentado em outro issue?

**Comment by ninrod** [comment]
> o "required:' indica "expiracao" e "dataDeVencimento", mas consta somente "calendario" como subitem.

existe uma relação `oneOf` entre os dois elementos

> ambos são mesmo obrigatórios na solicitação?

Não, são mutuamente excludentes ("oneOf")

> o campo "validadeAposVencimento" é novo. Este deve ser enviado na solicitação ou será formado pelo somatório do "expiracao" e "datadeValidade", conforme comentado em outro issue?


É novo. Ele indica os dias corridos após "dataDeVencimento" em que a cobrança ainda poderia ser paga.

**Comment by SeanWykes** [comment]
@ninrod Hi. Na linha 1260 do yaml, você tem:
      required: ["valor", "chave", "calendario", "expiracao", "dataDeVencimento"]
no entanto, expiracao e dataDeVencimento são propriedades "filhas" do calendario e não diretamente abaixo na hierarquia.

Desculpe o meu desconhecimento, mas é permitido referenciar propriedades filhas? Não encontrei definição clara sobre isso no JSON Schemas e OpenAPI. 

Não deveria ser "calendario/expiracao" etc?

**Comment by ninrod** [comment]
@SeanWykes , 

> @ninrod Hi. Na linha 1260 do yaml, você tem:
required: ["valor", "chave", "calendario", "expiracao", "dataDeVencimento"]

Ok vamos verificar.

**Comment by ninrod** [comment]
@SeanWykes , essa linha está com campos sobrando, realmente: o `expiração` e `dataDeVencimento` serão removidos desta linha required. Devo publicar uma nova RC em alguns intstantes. Obrigado pelo reporte.

**Comment by ninrod** [comment]
corrigido por 49b1f4ff45bc1c1daa49587bc27428574cb27a3c
