### ISSUE TITLE
Pattern txid - pattern: [a-zA-Z0-9]{26,35}

### ISSUE THREAD

**Issue by felipecamargo** [bacen/pix-api#101]
O pattern do txid deveria ser [a-zA-Z0-9]{**25**,35}.

O TLV usado no EMVco Merchant Presented Mode para o txid é o reference label que é limitado a 25 caracteres.

Referencia: https://www.emvco.com/terms-of-use/?u=/wp-content/uploads/documents/EMVCo-Merchant-Presented-QR-Specification-v1-1.pdf
Pag. 22, tabela 3.7  Data Objects for Additional Data Field Template (ID "62")

**Comment by rubenskuhl** [comment]
Se o limite do TxID estático é 25 caracteres, o dinâmico precisa ser 26-35 mesmo...

**Comment by ninrod** [comment]
boa tarde @felipecamargo 

> O TLV usado no EMVco Merchant Presented Mode para o txid é o reference label que é limitado a 25 caracteres.

O txid a que você se refere é o txid relacionado a uma cobrança. Diz respeito ao QR dinâmico e não ao estático. O spec EMV não se aplica neste caso. Estabelecer um um mínimo de 26 para o txid dinâmico evita colisões com QRs estáticos.
