### ISSUE TITLE
PUT /cob - comportamento default quando não se passar o loc

### ISSUE THREAD

**Issue by franciscotfmc** [bacen/pix-api#102]
![image](https://user-images.githubusercontent.com/1483404/96625502-a67d3900-12e4-11eb-9a1d-e0b3e15c56a3.png)

Podemos assumir que, caso o integrador não forneça `"loc": { "id": "789" }`, iremos gerar um location normalmente, conforme versão 2.0?

**Comment by ninrod** [comment]
@franciscotfmc 

> Podemos assumir que, caso o integrador não forneça "loc": { "id": "789" }, iremos gerar um location normalmente, conforme versão 2.0?

Exatamente, esta é a ideia. O usuário recebedor, neste caso,  gera um loc para o usuário recebedor, normalmente. Observe que o  `loc` é obrigatório no response.
