### ISSUE TITLE
Webhooks

### ISSUE THREAD

**Issue by llatsch** [bacen/pix-api#103]
Se o Webhook é uma configuração de uma preferência na Conta e é sempre única, não faz sentido ter um endpoint para registrá-lo. Esse registro poderia ser feito via interface de usuário por exemplo.
Além disso, essa modalidade é muito pouco flexível e não permite o recebimento de notificações de cobranças em ENDPOINTs diferentes. Partindo do princípio de facilidade de integração e flexibilidade, se o usuário recebedor puder informar a URL na qual deseja receber as informações no payload do PUT da cobrança, ele terá 3 endpoints a menos pra integrar, as APIs de recebimento ficarão consideravelmente mais simples e mais flexíveis.

**Comment by ninrod** [comment]
@llatsch , o `webhook` é único por client_id, não é por "conta", mas acredito que você quer contribuir na issue #62 , que está concentrando os pleitos relativos a webhooks.

**Comment by llatsch** [comment]
Já incluímos este ponto lá, mas ele havia se perdido um pouco, por isso abri uma nova issue.
Aproveitando, tem alguma previsão de publicação oficial da versão 2.1? Pergunto porque estávamos desenvolvendo a versão 2.0, e existem mudanças significativas já na geração da cobrança.

**Comment by ninrod** [comment]
@llatsch , hoje pela manhã publicamos a 2.1.0-rc.1
