### ISSUE TITLE
[Duvida] Api.Pix 2.1 - campos txIdPresente e locationPresente

### ISSUE THREAD

**Issue by mariapessoacalda** [bacen/pix-api#104]
Estou bastante confusa quanto ao funcionamento dos campos locationPresente, txIdPresente e como devem ser vinculados.

Entendo que o objeto Location foi criado para permitir multiplos pagamentos com mesma imagem.

Sendo assim, quando um txid (que é opcional na criação da location) estiver vinculado a url, só pode ser utilizado uma unica vez para pagamento. Caso contrario (sem o txid preenchido), a url poderá ser utilizada várias vezes. Mas por uma cobrança de cada vez. 

O conceito está correto?

No pagamento dessa cobrança é exigido que seja desvinculada a url do txid "concluído"?  (Ficará com a flag locationpresente false)

Poderá ser desvinculada uma url de uma cobrança "ativa" e vinculada a outra url? Podem haver cobranças ativas sem url?

Txidpresente trata-se de um campo q indica que a location pode sofrer multiplos pagamentos ou indica o txid que está sendo exibido "naquele.momento" pela url?

Como consultar todos os txids que já utilizaram aquela url (vários pagamentos para aquela imagem, sendo que o txid foi trocado). Nao deveria ser mantido o vinculo, mas exibido apenas o txid "ativo" vinculado a essa location?

Obrigada

**Comment by rubenskuhl** [comment]
Um txIDpresente é o de GETs em /pix, para selecionar Pix recebidos que tenham/não tenham txID. Mas o contexto da pergunta sugere que seja o txIDpresente de Location, que realmente eu também não entendi.

**Comment by ninrod** [comment]
bom dia @mariapessoacalda ,

> Estou bastante confusa quanto ao funcionamento dos campos locationPresente, txIdPresente e como devem ser vinculados.

Perfeito, vamos aperfeiçoar a documentação.

> Entendo que o objeto Location foi criado para permitir multiplos pagamentos com mesma imagem.

Correto. 

> Sendo assim, quando um txid (que é opcional na criação da location) estiver vinculado a url, só pode ser utilizado uma unica vez para pagamento. Caso contrario (sem o txid preenchido), a url poderá ser utilizada várias vezes. Mas por uma cobrança de cada vez.

Observe que o txid é inexistente na criação da location. Por outro lado, você me ajudou a notar que é um bug da API dizer que o txid é opcional no retorno, porque no POST, na criação, nunca deveria ser retornada uma location com o txid preenchido. Então não há o que se falar em termos de retornar um txid no response do POST. Consertaremos hoje.

A URL, o "location", pode ser utilizada várias vezes, mas uma cobrança por vez, correto. Uma forma de pensar que facilita o entendimento é pensar na "location" como uma "vitrine" em que pode-se apresentar nada, ou uma cobrança por vez. O usuário recebedor escolhe o que apresenta nesta "vitrine", que é o location, entidade gerenciada nos endpoints `/loc`. 

> No pagamento dessa cobrança é exigido que seja desvinculada a url do txid "concluído"? (Ficará com a flag locationpresente false)

Não é obrigatório, não. Contudo, existe uma regra que acredito que pode ficar clara na documentação: não pode existir a situaçao em que duas  (ou mais) cobranças diferentes estejam vinculadas a uma mesma location, porque uma location exibe uma e apenas uma cobrança em um dado momento do tempo. Por tanto, para associar uma location a uma cobrança, aquela location precisa, necessariamente, não estar associada a outra cobrança. 

> Poderá ser desvinculada uma url de uma cobrança "ativa" e vinculada a outra url? Podem haver cobranças ativas sem url?

Sim. Uma cobrança pode estar ativa, porém sem estar exibida em uma location (talvez temporariamente). Você pode desvincular a cobrança `1` de sua location e vincular uma outra location à cobrança `1` (tirou da vitrine A e colocou na vitrine B). 

> Txidpresente trata-se de um campo q indica que a location pode sofrer multiplos pagamentos ou indica o txid que está sendo exibido "naquele.momento" pela url?

`txidPresente`, parâmetro de busca que pode ser aplicado como em `GET /loc?txidPresente=true`, permite que o usuário recebedor consulte as locations que estejam exibindo cobranças. `txidPresente=false` retorna as locations que não estão exibindo cobranças. 

`locationPresent`, parâmetro de busca que pode ser aplicado por exemplo em `GET /cob?locationPresente=true`, permite que se filtre cobranças que estão associadas a um location. 


> Como consultar todos os txids que já utilizaram aquela url (vários pagamentos para aquela imagem, sendo que o txid foi trocado). Nao deveria ser mantido o vinculo, mas exibido apenas o txid "ativo" vinculado a essa location?

Não existe a relação de pagamentos "para aquela imagem". Os pagamentos estão relacionados à cobrança, que pode ser exibida em uma imagem ou não. Em Pix, o QR Code Dinâmico, a "imagem', é apenas um veículo para que o usuário recebedor possa apresentar ao pagador os elementos que constituem a cobrança. 

Dito isso, nada impede de estabeleceremos um "histórico de txids exbidos nesta location", mas não identificamos um caso de uso que justificasse adicionar mais esta camada de complexidade à API.

**Comment by ninrod** [comment]
corrigido em https://github.com/bacen/pix-api/commit/beb1fa5d7b724363a1fdcf251ef49bbc47784b73
