### ISSUE TITLE
Post/Loc - Criar Location do Payload

### ISSUE THREAD

**Issue by llatsch** [bacen/pix-api#106]
Entendo que na criação de uma Location, método Post/Loc nenhum dado é informado no Request.
Em que situação poderíamos devolver o TXId no response? Essa informação seria criada pelo PSP Recebedor?

**Comment by franciscotfmc** [comment]
@llatsch, o txid é criado do lado do recebedor. O PSP simplesmente garantirá a unicidade do txid _(que também deve ser garantido por quem está gerando)_.

**Comment by llatsch** [comment]
O @ninrod respondeu a minha pergunta na issue #104 :

Sendo assim, quando um txid (que é opcional na criação da location) estiver vinculado a url, só pode ser utilizado uma unica vez para pagamento. Caso contrario (sem o txid preenchido), a url poderá ser utilizada várias vezes. Mas por uma cobrança de cada vez.

Observe que o txid é inexistente na criação da location. Por outro lado, você me ajudou a notar que é um bug da API dizer que o txid é opcional no retorno, porque no POST, na criação, nunca deveria ser retornada uma location com o txid preenchido. Então não há o que se falar em termos de retornar um txid no response do POST. Consertaremos hoje.
