### ISSUE TITLE
Dúvida - Cobrança de Juros

### ISSUE THREAD

**Issue by nataliapaivafreitas** [bacen/pix-api#109]
Olá!

Para os pagamentos de Pix, caso o vencimento ocorra num dia não útil e o devedor pague somente no próximo dia útil, deve ser realizada a cobrança de juros?

**Comment by ninrod** [comment]
@nataliapaivafreitas, boa tarde.

> Para os pagamentos de Pix, caso o vencimento ocorra num dia não útil e o devedor pague somente no próximo dia útil, deve ser realizada a cobrança de juros?

Não deverá ser realizada a cobrança de juros. Recomendo aguardar a publicação da nova versão do manual de iniciação que endereçará estas questões.

**Comment by ninrod** [comment]
> Interessante essa dúvida. A premissa do Pix é estar disponível 24/7/365.

> Nesse sentido, penso que não há que se verificar se é dia útil ou não. Passou o vencimento, cobra-se juros e/ou multa. Mas essa é somente minha reflexão.

Não funciona assim por questões jurídicas que não posso abordar aqui. A cobrança considerará o dia útil respeitando o domicílio bancário do pagador.

**Comment by ninrod** [comment]
@nataliapaivafreitas , 

> Pergunto, pois o artigo 1º da Lei 7089/83 proíbe a cobrança de juros de mora, por estabelecimentos bancários e instituições financeiras com vencimento sábado, domingo ou feriado, desde que quitado no primeiro dia útil subsequente.

> Mas como o Pix funcionará 24/7, fiquei em dúvida.

Não deverá ser realizada a cobrança de juros em dia não útil. Para maiores detalhes, realmente temos que esperar o Manual de Iniciação.

**Comment by nataliapaivafreitas** [comment]
@ninrod certo, muito obrigada!
