### ISSUE TITLE
Dúvida no QR Code - Assinatura Payload

### ISSUE THREAD

**Issue by evertongodoi** [bacen/pix-api#110]
**Descreva sua dúvida ou problema**
Durante a assinatura do Payload a documentação diz que deve-se realizar a assinatura do payload, e após devemos inserir o conteúdo da assinatura no campo assinatura dentro do payload.

Porem realizando essa operação invalidamos a assinatura realizada anteriormente, pois o conteúdo do payload é alterado com a inserção do conteúdo no campo assinatura.

Gostaria de uma confirmação se devemos realmente prosseguir desta forma com o payload do QR Code?

Obrigado.

**Sistema ou Área**
QR Code

**Comment by dmkamers** [comment]
@evertongodoi podes por gentileza apontar em qual manual e página isto está escrito dessa forma?
"a documentação diz que deve-se realizar a assinatura do payload, e após devemos inserir o conteúdo da assinatura **no campo assinatura dentro do payload**."

**Comment by dmkamers** [comment]
A título informativo, esclarecemos que o [Manual de Padrões para Iniciação do Pix](https://www.bcb.gov.br/content/estabilidadefinanceira/pix/Regulamento_Pix/II.ManualdePadroesparaIniciacaodoPix-versao2.0.pdf) especifica (link do Manual de Segurança acrescentado):

> 1.6.15. O campo 9.assinatura
> Todos os campos, excluído o campo assinatura, compõem um payload JSON assinado. Maiores
> detalhes sobre a assinatura desse payload JSON podem ser encontrados no [Manual de Segurança](https://www.bcb.gov.br/content/estabilidadefinanceira/cedsfn/Manual%20de%20Seguranca%20do%20PIX%20v3.1.pdf) do
> SFN. 

O procedimento especifico de assinatura deve ocorrer segundo o padrão JWS, tal como especificado no Manual de Segurança.
