### ISSUE TITLE
QR Codes Estáticos - notificar em qual webhook URL ?

### ISSUE THREAD

**Issue by franciscotfmc** [bacen/pix-api#111]
Boa tarde!

Já foi esclarecido que um QR Code Estático, caso possua um txid, deve ser notificado via webhooks. 

Pensando melhor nesse ponto, veio a dúvida de qual URL utilizar, tendo em vista que uma conta possa ter várias credenciais (clientId/clientSecret) diferentes, cada uma com sua URL de webhook.

Como o PSP do Recebedor desconhece o estático, não existe a relação txid/client_id neste momento, certo?

Está me parecendo uma situação na qual se faz necessária uma URL padrão para notificações de txid's desvinculados das cobranças. Nada impede que o recebedor defina a mesma URL em ambos os casos, porém é uma decisão que deveria partir dele.

**Comment by ninrod** [comment]
@franciscotfmc , 

Você coloca um ponto interessante. Outros feedbacks interessantes também estão listados em #62 e em algumas outras issues. Obrigado.

**Comment by rubenskuhl** [comment]
Talvez um clientId null para informar que esse é o webhook dos Pix sem cobranças ?

**Comment by ninrod** [comment]
O problema colocado aqui é que todos os pix não associados a uma cobrança seriam trafegados por todas as URLs webhook de todos os clients_ids. Ou seja, todos os pix associados a um estático seriam notificados em todas as URLs do usuário recebedor. 

Pensando aqui, não sei se necessariamente é um problema.

**Comment by renatofrota** [comment]
> O problema colocado aqui é que todos os pix não associados a uma cobrança seriam trafegados por todas as URLs webhook de todos os clients_ids. Ou seja, todos os pix associados a um estático seriam notificados em todas as URLs do usuário recebedor.
> 
> Pensando aqui, não sei se necessariamente é um problema.

[Neste comentário](https://github.com/bacen/pix-api/issues/62#issuecomment-713043559) o volume de requisições aos webhooks parecia um problema.

E como o webhook poderia ser atribuído a um client_id null se o corpo do request para o endpoint `/webhook` sequer acompanha o client_id - e este é automaticamente inferido a partir da própria autenticação?

Aqui está mais uma razão clara para mover o webhook para a Chave Pix e para as Cobranças, como eu (e outros) sugerimos no #62.

**Comment by ninrod** [comment]
> Neste comentário o volume de requisições aos webhooks parecia um problema.

O volume de servers diferentes com os quais o PSP recebedor teria que estabelecer conexões seguras é que parece um problema.

**Comment by renatofrota** [comment]
> > Neste comentário o volume de requisições aos webhooks parecia um problema.
> 
> O volume de servers diferentes com os quais o PSP recebedor teria que estabelecer conexões seguras é que parece um problema.

Você não está confundindo essa necessidade de "estabelecer conexões seguras"? Não creio que isso exista no contexto dos webhooks. São URLs https:// para onde serão enviados requests simples, com alguns dados de notificação e nada mais.

Estas URL não passam por um processo de aprovação como as comunicações dos PSP para com o BACEN.

**Comment by ninrod** [comment]
> Você não está confundindo essa necessidade de "estabelecer conexões seguras"? Não creio que isso exista no contexto dos webhooks. São URLs https:// para onde serão enviados requests simples, com alguns dados de notificação e nada mais.
> Estas URL não passam por um processo de aprovação como as comunicações dos PSP para com o BACEN.

Devo evitar comentar questões jurídicas ou normativas neste fórum. Até acho que posso ter quebrado esta regra algumas vezes, aqui, mas devo observá-la.

**Comment by rubenskuhl** [comment]
> O problema colocado aqui é que todos os pix não associados a uma cobrança seriam trafegados por todas as URLs webhook de todos os clients_ids. Ou seja, todos os pix associados a um estático seriam notificados em todas as URLs do usuário recebedor.
> 
> Pensando aqui, não sei se necessariamente é um problema.

Eu confesso que não me agrada essa replicação de mensagens para todos os webhooks. Talvez isso até por ser default, mas que deva existir a opção de designar um específico para os sem client_id.

**Comment by rubenskuhl** [comment]
> > > Neste comentário o volume de requisições aos webhooks parecia um problema.
> > 
> > 
> > O volume de servers diferentes com os quais o PSP recebedor teria que estabelecer conexões seguras é que parece um problema.
> 
> Você não está confundindo essa necessidade de "estabelecer conexões seguras"? Não creio que isso exista no contexto dos webhooks. São URLs https:// para onde serão enviados requests simples, com alguns dados de notificação e nada mais.
> 
> Estas URL não passam por um processo de aprovação como as comunicações dos PSP para com o BACEN.

A questão não é jurídica IMHO, é de segurança da informação e eu concordo com o @ninrod disso ser um problema.

**Comment by renatofrota** [comment]
> > > > Neste comentário o volume de requisições aos webhooks parecia um problema.
> > > 
> > > 
> > > O volume de servers diferentes com os quais o PSP recebedor teria que estabelecer conexões seguras é que parece um problema.
> > 
> > 
> > Você não está confundindo essa necessidade de "estabelecer conexões seguras"? Não creio que isso exista no contexto dos webhooks. São URLs https:// para onde serão enviados requests simples, com alguns dados de notificação e nada mais.
> > Estas URL não passam por um processo de aprovação como as comunicações dos PSP para com o BACEN.
> 
> A questão não é jurídica IMHO, é de segurança da informação e eu concordo com o @ninrod disso ser um problema.

Acho que quando ele falou de questões jurídicas, se referia às "conexões seguras". Não aos webhooks.

E é justamente isso que eu acho que ele está fazendo confusão. Pelo manual de iniciação do Pix, as URLs cadastradas como webhook não passam por qualquer validação. É o recebedor que determina qual a URL que será notificada pelo PSP recebedor. Não tem relação nenhuma com a forma como PSPs e BACEN se comunicam entre si.

**Comment by rubenskuhl** [comment]
> E é justamente isso que eu acho que ele está fazendo confusão. Pelo manual de iniciação do Pix, as URLs cadastradas como webhook não passam por qualquer validação. É o recebedor que determina qual a URL que será notificada pelo PSP recebedor. Não tem relação nenhuma com a forma como PSPs e BACEN se comunicam entre si.

Mesmo sem validação mandatória, a autenticação mTLS garante que nenhum comando HTTP vai ser enviado se não houverem reconhecimento mútuo de que o PSP é o PSP e o cliente é o cliente. Então mesmo que alguém coloque um parâmetro incorreto, a conexão vai ser tentada e fechar. Não dá para instruir o PSP por exemplo a abrir www.whitehouse.gov/osamabinladen , pois a conexão mTLS não vai fechar.

**Comment by renatofrota** [comment]
> > E é justamente isso que eu acho que ele está fazendo confusão. Pelo manual de iniciação do Pix, as URLs cadastradas como webhook não passam por qualquer validação. É o recebedor que determina qual a URL que será notificada pelo PSP recebedor. Não tem relação nenhuma com a forma como PSPs e BACEN se comunicam entre si.
> 
> Mesmo sem validação mandatória, a autenticação mTLS garante que nenhum comando HTTP vai ser enviado se não houverem reconhecimento mútuo de que o PSP é o PSP e o cliente é o cliente. Então mesmo que alguém coloque um parâmetro incorreto, a conexão vai ser tentada e fechar. Não dá para instruir o PSP por exemplo a abrir [www.whitehouse.gov/osamabinladen](http://www.whitehouse.gov/osamabinladen) , pois a conexão mTLS não vai fechar.

Isso não é mencionado em nenhum documento (que eu tenha lido até agora), e eu já li o Manual de Padrões de Iniciação Pix, o Manual de Segurança e vários outros documentos. Não é mencionado em nenhum momento qualquer limitação em relação a quais URLs o cliente recebedor pode cadastrar usando o endpoint `/webhook`.

**Comment by rubenskuhl** [comment]
> > > E é justamente isso que eu acho que ele está fazendo confusão. Pelo manual de iniciação do Pix, as URLs cadastradas como webhook não passam por qualquer validação. É o recebedor que determina qual a URL que será notificada pelo PSP recebedor. Não tem relação nenhuma com a forma como PSPs e BACEN se comunicam entre si.
> > 
> > 
> > Mesmo sem validação mandatória, a autenticação mTLS garante que nenhum comando HTTP vai ser enviado se não houverem reconhecimento mútuo de que o PSP é o PSP e o cliente é o cliente. Então mesmo que alguém coloque um parâmetro incorreto, a conexão vai ser tentada e fechar. Não dá para instruir o PSP por exemplo a abrir [www.whitehouse.gov/osamabinladen](http://www.whitehouse.gov/osamabinladen) , pois a conexão mTLS não vai fechar.
> 
> Isso não é mencionado em nenhum documento (que eu tenha lido até agora), e eu já li o Manual de Padrões de Iniciação Pix, o Manual de Segurança e vários outros documentos. Não é mencionado em nenhum momento qualquer limitação em relação a quais URLs o cliente recebedor pode cadastrar usando o endpoint `/webhook`.

mTLS está mencionado em muitos lugares... e da maneira que mTLS funciona, há múltiplas camadas impedindo qualquer requisição HTTP de ser enviada:
- Se o certificado do servidor não for o do PSP, o cliente já tem que derrubar a sessão
- Qualquer site que não peça client certificate já também não vai fechar sessão mesmo que o passo anterior seja esquecido, pois no mTLS só após o servidor solicitar um client certificate que o client deve apresentar um e então fazer requisições, o client não pode mandar um cliente certificate não solicitado. 

Só com a conexão mTLS fechada que uma URI poderia ser solicitada, GET /osamabinladen nesse exemplo. 

O que não está na documentação e poderia ser uma adição interessante seria já na ativação do webhook fazer uma chamada de teste. Mas bastando a chamada ao webhook ter um back-off (discutido em outra issue já fechada) isso não é essencial, só talvez uma boa prática.

**Comment by ninrod** [comment]
@renatofrota 

> Isso não é mencionado em nenhum documento (que eu tenha lido até agora), e eu já li o Manual de Padrões de Iniciação Pix, o Manual de Segurança e vários outros documentos. Não é mencionado em nenhum momento qualquer limitação em relação a quais URLs o cliente recebedor pode cadastrar usando o endpoint /webhook.

Obrigado pelo reporte. Vou revisar esta questão para deixar mais claro o requisito do mTLS nos manuais.

**Comment by ninrod** [comment]
@rubenskuhl 

> A questão não é jurídica IMHO, é de segurança da informação e eu concordo com o @ninrod disso ser um problema.

Apenas complementando, a questão "normativa" seria mais em relação a se o BACEN teria ou não autoridade para determinar esse callback no PSP.

**Comment by rubenskuhl** [comment]
> @rubenskuhl
> 
> > A questão não é jurídica IMHO, é de segurança da informação e eu concordo com o @ninrod disso ser um problema.
> 
> Apenas complementando, a questão "normativa" seria mais em relação a se o BACEN teria ou não autoridade para determinar esse callback no PSP.

Entendo. O que posso dizer é que quanto mais equacionadas as questões de segurança da informação estejam na API, mais uma medida não mandatória será adotada, e menos uma medida mandatória será protestada. Então sendo ou não mandatório, o direcionamento é o mesmo.

**Comment by ninrod** [comment]
@rubenskuhl, perfeito. 

Prezados, fechando esta issue em favor de #120 cc: @franciscotfmc .
