### ISSUE TITLE
Criação de uma cobrança sem Loc

### ISSUE THREAD

**Issue by llatsch** [bacen/pix-api#112]
Em que caso de uso teríamos uma cobrança sem location?
Ou seja, caso o usuário recebedor chame o endpoint /Cob, e não informe um LOC, nós não temos a obrigação de criá-lo certo? A cobrança fica sem um location associado.

Se sim, como o usuário recebedor utilizaria essa cobrança? Como ele conseguiria recuperar o PAYLOAD URL? Somente quando atualizasse essa cobrança e a vinculasse a um LOC, certo?

**Comment by ninrod** [comment]
> Ou seja, caso o usuário recebedor chame o endpoint /Cob, e não informe um LOC, nós não temos a obrigação de criá-lo certo? 

Tem a obrigação de criá-la se o usuário não disser nada. Se o usuário indicar uma loc, usa-se a que ele indicou.

**Comment by llatsch** [comment]
Então no método GET/Cob, quando o campo LocationPresence for FALSE, não retornaremos nada certo? Dado que não existem cobranças sem Location. 

Você pode ter uma LOCATION sem cobrança, o método GET/Loc -> campo TXId presente, faz sentido. Mas não deveríamos ter uma cobrança sem Location.

**Comment by ninrod** [comment]
> Então no método GET/Cob, quando o campo LocationPresence for FALSE, não retornaremos nada certo? Dado que não existem cobranças sem Location.

Depende. o usuário pode desvincular uma location de uma cobrança, depois de criada a cobrança.

**Comment by llatsch** [comment]
Entendido, Obrigada!!!
