### ISSUE TITLE
[Dúvida] Sobre os retornos de erros da API

### ISSUE THREAD

**Issue by MatheusCorreia96** [bacen/pix-api#113]
Existe algum template ou padrão para os retornos de erros da API? Ou fica a cargo de cada PSP? 

Além disso eles devem ser apresentados em português?

(Imaginamos que os erros específicos fica a cargo do PSP, a pergunta é sobre um template genérico dos erros)

**Comment by ninrod** [comment]
@MatheusCorreia96 , acredito que você tratando do contexto de UX. 

O Manual de requisitos mínimos para a experiência do usuário responde sua questão?

**Comment by franciscotfmc** [comment]
@ninrod acho que a dúvida do @MatheusCorreia96 é que a spec da API define as respostas de sucesso. Caberia ali a definição de respostas de erro? Ou cada PSP pode "acrescentar" na doc os possíveis erros para cada endpoint?

**Comment by ninrod** [comment]
> Ou cada PSP pode "acrescentar" na doc os possíveis erros para cada endpoint?

Olhando atentamente, acredito que a especificação pode melhorar em termos de erros listados que deveriam ser observados, sim. Se a API não define, acredito que o PSP recebedor está livre para estabelecer erros específicos e observar a RFC [7231](https://tools.ietf.org/html/rfc7231#section-6.1).

**Comment by christianf2029** [comment]
Eu entendo que os **tipos de erros** e **informações adicionais** vão além do escopo dessa especificação que o BACEN está trazendo. Parte dos erros de consumo certamente estarão associados às regras de negócio de cada PSP e outra parte à erros comuns a todos (como um `GET /cob/:txid` em um `txid` que não exista, por exemplo).

No entanto, me imaginando como um usuário recebedor integrando à um PSP A, no mínimo eu iria querer partir do pressuposto de que os erros retornados nos consumos seguem **um formato padrão**, ainda que as **informações** e **valores** em si fiquem a cargo de cada PSP personalizar. Digo isto pelo fato de que hoje eu posso integrar com o PSP A, mas amanhã eu troco para o PSP B e a minha preocupação será somente com os **tipos dos erros** e **informações adicionais**, e não com o leiaute da mensagem de erro, tradução de campos para a minha aplicação, etc.

Ao mesmo tempo, ao redigir esse comentário me veio o pensamento de que eu, como integrador, inevitavelmente terei que me guiar por alguma documentação específica do PSP para saber seus **tipos de erros** e **informações adicionais** específicas. Talvez o trabalho de se estabelecer um padrão de erros seja o menor dos problemas, já que terei que olhar uma documentação específica de toda forma.

Enfim, só pensamentos meus aqui.

**Comment by ninrod** [comment]
Você coloca pontos relevantes @christianf2029. acredito que o ponto aqui é queaA API Pix padroniza a integração __até um certo ponto razoável__. Não se pode avançar muito além deste ponto sob pena de limitar de maneira não desejável a implementação do PSP recebedor. 

Erros temporários por janela de indisponibilidade, ou, por exemplo, por exceder o rate-limit, por exemplo, são questões que não estabelecemos aqui; me parece que são questões muito específicas que dizem respeito à infra particular daquele PSP. E sim, concordo com você quanto à observância destes manuais específicos, sem dúvida eles existirão. Contudo, a API já padroniza uma boa parte da experiência de integração, então parte do trabalho já estaria especificado: você já saberia o que esperar. 

Dito isso, encontrei alguns erros específicos de negócio, de semântica estabelecida pela API que poderiam constar. Por exemplo, poderia-se argumentar que não faz sentido o envio de um `PATCH` mudando o status de uma cobrança para removido e ao mesmo tempo alerar a location desta cobrança. HTTP 406, possivelmente.

**Comment by christianf2029** [comment]
Isso @ninrod , concordo que erros de consumo que estão relacionados à boa parte da experiência de integração que a API já padroniza, como você disse, deveriam estar descritos na documentação (como o exemplo que você trouxe).

Os demais, se a API não define e não proíbe, ficam a cargo do PSP.
