### ISSUE TITLE
[Dúvida] APi Pix 2.1 - Cálculo do valor final à ser recebido

### ISSUE THREAD

**Issue by mariapessoacaldas** [bacen/pix-api#114]
Em outra issue foi informado que o valor final á ser cobrado passará a ser calculado pelo PSP pagador e que as regras estarão descritas no novo Manual de Iniciação à ser divulgado.

Percebi que o valor Final não se encontra no GET/{pixUrlAcessToken}. Esse campo será excluído do payload da URL?

**Comment by ninrod** [comment]
@mariapessoacaldas , 

Peço que aguarde a versão oficial da release. 

Estamos tentando encontrar uma maneira de tornar fácil esse cálculo para o PSP pagador e ao mesmo tempo permitir uma flexibilidade para o PSP recebedor.
