### ISSUE TITLE
RTRID - ReturnIdentification

### ISSUE THREAD

**Issue by llatsch** [bacen/pix-api#115]
Podem esclarecer melhor a função do campo rtrId no response de uma solicitação de devolução?

**Comment by ninrod** [comment]
Semântica da ISO 20.022. um pedido de devolução precisa de um rtrId por parte do PSP recebedor. o rtrId está para o pedido de devolução do pix assim como o e2eid está para o pix. O rtrId idempotentemente identifica o pedido de devolução no arranjo.

**Comment by thiagolvlsantos** [comment]
Dúvida aparentemente esclarecida.

Atenciosamente,
Thiago Santos.
