### ISSUE TITLE
TXId duplicado - Response /Cob

### ISSUE THREAD

**Issue by llatsch** [bacen/pix-api#116]
No response do método /COB, temos o TXId retornando duas vezes, uma delas no nó LOC. Faz sentido?

**Comment by ninrod** [comment]
deve ser algum bug, vamos verificar.

**Comment by ninrod** [comment]
@llatsch, não consegui confirmar. Aparece um txid só no responso do PUT /cob{txid}. Pode citar a linha específica do erro?

**Comment by llatsch** [comment]
@ninrod Pode desconsiderar, acabei de atualizar a documentação e não está mais duplicado, não está mais no nó do LOC.
