### ISSUE TITLE
Dúvida no QR Code - Geração do QRCode Estático

### ISSUE THREAD

**Issue by quilombodigital** [bacen/pix-api#117]
Olá,

Eu tenho interesse em gerar QrCodes estáticos gratuitamente para uso no comércio de rua por pessoas de baixa renda, portanto qualquer custo envolvido inviabilizaria esta ação.

Ao começar a ler a documentação eu fiquei um pouco confuso porquê no vídeo abaixo é dito que o qrcode estático também tem que utilizar um PSP e comunicar a sua geração ao sistema PIX:
https://youtu.be/6Tor9r6F9kM?t=395

Em uma thread daqui do github um dos usuários disse que o acesso ao backend poderia ser "opcional".
https://github.com/bacen/pix-api/issues/57

Mas eu gostaria de uma informação oficial respondendo a pergunta:

**Um QRCODE Estático pode ser gerado sem qualquer comunicação e com apenas a informação da chave pix do usuário e detalhes da compra(valor,descrição)? Preciso de um PSP, ou do ID dele para um qrcode estático?** 

Obrigado, Ricardo Andere de Mello

**Comment by ninrod** [comment]
Obrigado @renatofrota
