### ISSUE TITLE
Melhoria (menor) na API e no webhook: chamada nula

### ISSUE THREAD

**Issue by rubenskuhl** [bacen/pix-api#118]
Para permitir que um PSP possa checar a situação de um atendedor de webhook, e para o cliente checar a situação operacional do PSP, poderia haver uma chamada nula. O método, tanto na API do PSP quanto do webhook, poderia ser /timestamp, que retornaria a hora corrente na visão desse servidor do PSP ou do cliente. Apesar da requisição não ter idempotência(que poderia ser adicionada com um nonce mas não vejo necessidade), a resposta tem, permitindo que fim-a-fim ela o tenha. 

Casos de uso:
- Configurar um monitor de disponibilidade para saber a situação operacional
- Na ativação do webhook, fazer uma chamada de teste para confirmar sua ativação
- Identificar problemas de sincronização de relógio
- Poder ser usado para um eventual back-off de chamadas ao webhook

**Comment by rubenskuhl** [comment]
Algo que me ocorreu é se isso permitiria ou não ataques do tipo "known plaintext" à sessão TLS; porém, como há um requisito de que apenas algoritmos com "forward secrecy" sejam usados, não vejo como isso possa ser explorado,  mesmo que haja um observador indesejado no caminho da conexão.

**Comment by ninrod** [comment]
@rubenskuhl, as propostas em #120 endereçam o seu ponto aqui? Sugiro concentramos a discussão sobre aprimoramento do webhook em #120 ok?
