### ISSUE TITLE
Boas práticas adicionais de segurança - API Pix

### ISSUE THREAD

**Issue by rubenskuhl** [bacen/pix-api#122]
Diferente das interfaces DICT, ICOM e ARQ que rodam sob uma rede segregada (RSFN) e com CA própria (certificados do tipo SPB), a API Pix está no amplo mundo da Internet. Assim, além das práticas já mencionadas na documentação como OWASP Top-N, sugiro incluir estas práticas como recomendadas, apesar de não mandatórias. Gestão de risco é algo bem único e cabe a clientes escolherem PSPs que melhor respondam a isso na visão deles e a PSPs assumirem o risco de não utilizá-las. 

1. DNSSEC
Todo domínio de exposição da API PIx, tanto de payload quanto de interfaces autenticadas, deveria ser assinado com DNSSEC. Em caso de falha de renovação da assinatura, um cliente poderia adicionar um NTA (Negative Trust Anchor) ou entrada no arquivo hosts para manter o funcionamento temporário da interface autenticada enquanto o problema é sanado; já na interface não autenticada, o mais simples é remover DNSSEC temporariamente e retornar quando estiver reestabelecido corretamente a cadeia de confiança. Hoje DNSSEC já é exigido em domínios b.br (bancos), jus.br (Justiça) e alguns outros tipos de domínio, mas é opcional nos demais domínios (br ou não br). 

2. RPKI
Todo IP para o qual resolvem os endpoints deveria ser anunciado com assinatura do anúncio de roteamento, para evitar casos de IP Hijacking (já acontecidos no Brasil tendo instituições financeiras e operadores de DNS como alvos). Em caso de falha de renovação da assinatura, o PSP poderia revogar temporariamente o RPKI até que o problema seja sanado. 
Hoje RPKI já é fornecido sem custo adicional por todas as autoridades de designação de endereços, inclusive os endereços brasileiros. 

3. Faixas de IPs
O PSP deve fornecer a seus clientes as faixas de IPs onde são possíveis as conexões diretas e de onde vem as conexões reversas (webhook) da API Pix. Isso permite que os clientes configurem firewalls, ferramentas de monitoração de DNS e ACLs no web server do webhook

**Comment by ninrod** [comment]
@rubenskuhl , obrigado pela contribuição.

**Comment by dmkamers** [comment]
@rubenskuhl as sugestões foram encaminhadas para o time de segurança, obrigado.
