### ISSUE TITLE
Mutual TLS

### ISSUE THREAD

**Issue by llatsch** [bacen/pix-api#124]
O mutual TLS se aplica para o endpoint GET /{pixUrlAcessToken}? Pois entendemos que quem utilizará este endpoint será o PSP Pagador, diferente dos demais endpoints.

**Comment by llatsch** [comment]
Também entendemos que não haverá escopo do OAuth para este endpoint, correto?

**Comment by ninrod** [comment]
> O mutual TLS se aplica para o endpoint GET /{pixUrlAcessToken}?

Não. é aberto. 

> Também entendemos que não haverá escopo do OAuth para este endpoint, correto?

Correto.
