### ISSUE TITLE
Juros da Cobrança

### ISSUE THREAD

**Issue by llatsch** [bacen/pix-api#125]
Teremos um período específico para cobrança de Juros sobre o valor original?
Ex:
Valor original: 200
Juros: 1% ao dia

Ou dado que recebemos essa informação, simplesmente a aplicamos uma única vez sobre o valor original?

**Comment by ninrod** [comment]
> Teremos um período específico para cobrança de Juros sobre o valor original?
Ex:
Valor original: 200
Juros: 1% ao dia

> Ou dado que recebemos essa informação, simplesmente a aplicamos uma única vez sobre o valor original?

Olá @llatsch , ainda sendo desenhado. Muito provavelmente, será "ao dia"
