### ISSUE TITLE
Qr code estático com expiração e Consulta txId Global (fora do PSP Recebedor)

### ISSUE THREAD

**Issue by rodrigonunes100** [bacen/pix-api#127]
@ninrod, de acordo com seu comentário em https://github.com/bacen/pix-api/issues/107#issuecomment-713613793 ,  o PSP recebedor não será obrigado a fornecer acesso a criação de QR code dinamico, seja pela API PIX , ou de qualquer outra forma. Tenho as seguintes perguntas:
1- Como será feita a consulta de txId para  QR code estático ?
2- Como será a expiração ou vencimento de QR code estático com txId ? 
3- Como bloquear, depois de emitido um QR code estático com txId ?
 Até o momento me parece que o equilibrio (grandes empresas e pequenos comerciantes)  do PIX fica atrelado a critérios comerciais do  PSP recebedor. As duas primeiras questões seriam excelentes se pudessem ser implementadas, pois no ambito do comercio online traria segurança jurídica. Imagina vender um produto num estoque online com QR code estático com as limitações presente ?

**Comment by rubenskuhl** [comment]
> @ninrod, de acordo com seu comentário em [#107 (comment)](https://github.com/bacen/pix-api/issues/107#issuecomment-713613793) , o PSP recebedor não será obrigado a fornecer acesso a criação de QR code dinamico, seja pela API PIX , ou de qualquer outra forma. Tenho as seguintes perguntas:
> 1- Como será feita a consulta de txId para QR code estático ?

Não há consulta de QR code estático, pois ele é gerado dentro do ambiente do cliente. 

> 2- Como será a expiração ou vencimento de QR code estático com txId ?

Não há parâmetros como expiração e vencimento. 

> 3- Como bloquear, depois de emitido um QR code estático com txId ?

O PSP só pode bloquear recebimento de TxID duplicado se o estabelecimento solicitar, e se o PSP dispuser desse recurso, que não é mandatório. Então isso parece um poor man's QR-Code dinâmico. 

> Até o momento me parece que o equilibrio (grandes empresas e pequenos comerciantes) do PIX fica atrelado a critérios comerciais do PSP recebedor. As duas primeiras questões seriam excelentes se pudessem ser implementadas, pois no ambito do comercio online traria segurança jurídica. Imagina vender um produto num estoque online com QR code estático com as limitações presente ?

Parece que a solução mais simples é buscar um PSP que tenha a qualidade de serviço necessária. Você pode achar em #76 uma lista inicial.

**Comment by rodrigonunes100** [comment]
@rubenskuhl, obrigado pela resposta, mas estamos há poucos dias do lançamento do PIX com 50 milhões de chaves já cadastradas e não vejo nenhum PSP recebedor com alguma solução de "teste ou sandbox" . Não está claro quais os critérios que o PSP recebedor irá adotar para adesão do cliente, como por exemplo: Pessoas pessoas físicas poderão ter acesso ao API PIX PSP RECEBEDOR ?  Como será cobrado a adesão para acesso do comerciante ao API PIX PSP RECEBEDOR ? Uma solução seria o BACEN a obrigar a pelo menos todo PSP RECEBEDOR a  dar acesso ao API PIX para consulta de txId recebido (pago)  seja ele estático ou dinâmico.  Um novo modelo de QR code estático(que pode ser criado pelo cliente) com uma espécie de LIMITE de tempo arbitrário curto (5 minutos) estabelecido pelo Bacen, em que o não pagamento deste QR code estático no prazo estabelecido, cancelaria o pagamento no PSP pagador.

**Comment by renatofrota** [comment]
> @rubenskuhl, obrigado pela resposta, mas estamos há poucos dias do lançamento do PIX com 50 milhões de chaves já cadastradas e não vejo nenhum PSP recebedor com alguma solução de "teste ou sandbox" . Não está claro quais os critérios que o PSP recebedor irá adotar para adesão do cliente, como por exemplo: Pessoas pessoas físicas poderão ter acesso ao API PIX PSP RECEBEDOR ? Como será cobrado a adesão para acesso do comerciante ao API PIX PSP RECEBEDOR ? Uma solução seria o BACEN a obrigar a pelo menos todo PSP RECEBEDOR a dar acesso ao API PIX para consulta de txId recebido (pago) seja ele estático ou dinâmico.

Os PSP poderão decidir se ofertarão ou não a API Pix bem como o custo - se houver. Se o seu PSP de preferência não oferecer a API (ou não a um preço que te agrade), você pode simplesmente mudar de PSP.

Lembrando que um QR Code estático não tem qualquer vinculo com o PSP que o gerou (e pode, inclusive, ser gerado de forma autônoma pelo próprio dono da Chave PIX - ou, ainda, um terceiro).

**Comment by masyaf** [comment]
O qr code estático pode ou não ter um txId vinculado, uma vez que ele foi gerado e vinculado à um qr code estático, o app do psp pagador vai trafegar essa informação e consequentemente será possível realizar consultas via api pix para obter as informações através dos métodos já documentados na API, esse é o meu entendimento.

**Comment by rubenskuhl** [comment]
> @rubenskuhl, obrigado pela resposta, mas estamos há poucos dias do lançamento do PIX com 50 milhões de chaves já cadastradas e não vejo nenhum PSP recebedor com alguma solução de "teste ou sandbox" . Não está claro quais os critérios que o PSP recebedor irá adotar para adesão do cliente, como por exemplo: Pessoas pessoas físicas poderão ter acesso ao API PIX PSP RECEBEDOR ? Como será cobrado a adesão para acesso do comerciante ao API PIX PSP RECEBEDOR ? Uma solução seria o BACEN a obrigar a pelo menos todo PSP RECEBEDOR a dar acesso ao API PIX para consulta de txId recebido (pago) seja ele estático ou dinâmico.

Há sim PSPs com sandbox já funcional, inclusive um banco vermelho... há poucos de fato por alguns motivos:
- Os PSPs não haviam entendido o que para mim já estava claro de que o BACEN padronizaria a API Pix. Isso custou alguns meses onde PSPs que acreditavam que poderiam ter APIs proprietárias não investiram no desenvolvimento do padrão. 
- A API Pix para o lançamento ainda não está fechada (deve ser a 2.0.1), e o desenvolvimento estilo waterfall - que ainda é forte no mercado financeiro - depende de especificações completas.

Sobre pessoas físicas,  há impedimento algum. Só que não está coberto pela gratuidade, pois se há uma coisa que caracteriza atividade comercial é a emissão de cobranças... 

- Não há definição do BACEN se há ou não taxa de adesão, isso é decisão do PSP. Todo PSP que quis me cobrar taxa de adesão eu descartei, mas foi a minoria. A maioria não cobra. 

- Não há PSPs recebedores ou pagadores no geral, só numa transação específica. No geral só há PSPs; o BACEN não pode obrigar oferta de um serviço que a organização já não oferecia. Por exemplo, dos 100+ PSPs diretos, só aproximadamente metade tinha serviço de cobrança via boleto. Um número ainda menor tinha API para cobrança via boleto. 

Eu prefiro ter várias soluções sólidas no mercado para escolher entre elas, do que obrigar todos os PSPs e termos muitas soluções meia-boca, inclusive comprometendo a reputação do arranjo. Por exemplo, PSPs que levam até 20 minutos para notificar no webhook que um Pix foi recebido... esse número é de caso real que não posso mencionar de qual PSP, mas dá um relance de "cuidado com o que você deseja, você pode conseguir".

**Comment by ninrod** [comment]
@rodrigonunes100 , 

boas respostas aqui nessa thread. Vou responder uma em específico: 

> 1- Como será feita a consulta de txId para QR code estático ?
R: se você quiser saber se um QR Estático foi pago: `GET /pix?txid={txid_do_qr_estatico}`.  A premissa é que o QR Estático tem que ter sido gerado com um txid válido para o pix: `[a-zA-Z0-9]{1,25}`.
