### ISSUE TITLE
Caracteres especiais no qrcode PIX

### ISSUE THREAD

**Issue by caio-bos-ifood** [bacen/pix-api#128]
São permitidos caracteres especiais/latinos na geração de qrcodes? Em campos como Merchant Name e Merchant City, a documentação EMV específica o formato do campo como alphanumeric special(ans). No [EMV4 book](https://www.emvco.com/wp-content/uploads/2017/05/EMV_v4.3_Book_4_Other_Interfaces_20120607062305603.pdf) eles descrevem o conjunto de caracteres aceitos e citam que pode ou não haver o suporte a caracteres latinos(ISO/IEC 8859).

Ao fazer testes de leitura com meu próprio celular e outras ferramentes online de um qrcode próprio gerado no formato EMV, os caracteres latinos não foram propriamente decodificados. Talvez, com a leitura sendo feita por PSP nacionais, isso não acontecerá.

Existe alguma recomendação do Bacen quanto a isso?

**Comment by ninrod** [comment]
@caio-bos-ifood, bom dia. 

> São permitidos caracteres especiais/latinos na geração de qrcodes? Em campos como Merchant Name e Merchant City, a documentação EMV específica o formato do campo como alphanumeric special(ans). No EMV4 book eles descrevem o conjunto de caracteres aceitos e citam que pode ou não haver o suporte a caracteres latinos(ISO/IEC 8859).

> Ao fazer testes de leitura com meu próprio celular e outras ferramentes online de um qrcode próprio gerado no formato EMV, os caracteres latinos não foram propriamente decodificados. Talvez, com a leitura sendo feita por PSP nacionais, isso não acontecerá.

> Existe alguma recomendação do Bacen quanto a isso?

O BR Code segue a especificação [EMV para QR Codes](https://www.emvco.com/emv-technologies/qrcodes/), merchant presente mode. 

Na seção `1.4.3 Encoding`:

> For conversion of a character to its binary representation, this specification uses UTF-8
encoding as defined by [Unicode]...

Tanto o gerador do QR quanto o leitor do QR devem seguir a spec e utilizar codificação UTF-8.

**Comment by SeanWykes** [comment]
@ninrod Até onde sei, segundo o EMV Book 4, o "common character set" é ASCII simples, e os campos "Merchant Name" e "Merchant City" devem obedecer a essa regra. Há campos adicionais para localização (Merchant Name - Alternate Language) em que vale Unicode em UTF-8.

**Comment by ninrod** [comment]
@SeanWykes , bom dia.

A especificação é esta: https://www.emvco.com/emv-technologies/qrcodes/. A regra geral, é o uso de unicode. 

Alguns campos específicos, como por exemplo, os campos sob o id 62, apresentam restrições adicionais. Para maoire detalhes, consultar a especificação.

**Comment by SeanWykes** [comment]
@ninrod bom dia.

Beleza. :) Estava apenas buscando esclarecer esse ponto pois a leitura que fizemos não é igual. Aproveitei a tua dica e reli a especificação e confirmei a minha colocação acima, pois embora a especificação EMV Merchant Presented QR realmente verse sobre UTF-8 no caso geral, ela define formato "ans" para muitos campos comuns e se refere à especificação EMV Book 4 (v4.3, Annex B, page 137) onde este "Common Character Set" está definido como o conjunto de caracteres ASCII.

Nas páginas 38 e 39 da referida especificação QR, está definido Merchant Name (59) e City (60) como "ans".

Portanto, concluímos que não é permitido acentuados nestes campos, e se colocar, corre-se o risco de ter o QR rejeitado ou exibido de forma errada pelo APP do pagador, o que pode impactar a UX.

**Comment by ninrod** [comment]
> Nas páginas 38 e 39 da referida especificação QR, está definido Merchant Name (59) e City (60) como "ans".

> Portanto, concluímos que não é permitido acentuados nestes campos, e se colocar, corre-se o risco de ter o QR rejeitado ou exibido de forma errada pelo APP do pagador, o que pode impactar a UX.

Exatamente, o `ans`, ou `Alpha Numeric Special` deve ser respeitado nestes campos sob pena de estar o QR fora da spec.

Adicioalmente, eu ressaltaria que o manual de iniciação adiciona restrições adicionais, por exemplo, no campo `62-05`, para o estático, especificando que para o Pix deve ser respeitada a regex `[a-zA-Z0-9]`.

**Comment by caio-bos-ifood** [comment]
Bom dia, obrigado a ambos pela ótima dicussão suportada pela documentação, que realmente pode gerar interpretação ambígua.

No Anexo B do EMV Book 4 que específica os caracteres que definem o tipo `Alpha Numeric Special`, também está descrito abaixo da **Common Character Set**:

> If the terminal supports Part 1 of ISO/IEC 8859 (the Latin 1 alphabet) and
> supports the display of the standard messages in French, when a card indicates
> in its Language Preference that French is the preferred language, the terminal
> can display the ‘APPROVED’ message as ‘ACCEPTÉ’, using the appropriate
> diacritic marks

O que gera de novo a dúvida se o padrão [ISO/IEC 8859-1](https://pt.wikipedia.org/wiki/ISO/IEC_8859-1) não é suportado ou se pode ser, dependendo do 'terminal'.

**Comment by ninrod** [comment]
@caio-bos-ifood, 

Eu recomendo seguir o EMV para QR Codes. Usaria o o Anexo B do Book 4 apenas para descobrir o que é "ANS". Essa questão de "terminal" não se aplica no pix.

**Comment by caio-bos-ifood** [comment]
Vamos seguir então suportando apenas a tabela de **Common Character Set** para ANS, o que significa não suportar caracteres  ISO/IEC 8859-1.

**Comment by ninrod** [comment]
> Vamos seguir então suportando apenas a tabela de Common Character Set para ANS, o que significa não suportar caracteres ISO/IEC 8859-1.

@caio-bos-ifood, O BR Code é unicode, exceto nos campos em que especificamente é dito que se usa ANS.

**Comment by dmkamers** [comment]
![image](https://user-images.githubusercontent.com/52418777/97213301-31a47600-17a0-11eb-87bb-25b047fdcb1f.png)

**Comment by dmkamers** [comment]
> @ninrod bom dia.
> 
> Beleza. :) Estava apenas buscando esclarecer esse ponto pois a leitura que fizemos não é igual. Aproveitei a tua dica e reli a especificação e confirmei a minha colocação acima, pois embora a especificação EMV Merchant Presented QR realmente verse sobre UTF-8 no caso geral, ela define formato "ans" para muitos campos comuns e se refere à especificação EMV Book 4 (v4.3, Annex B, page 137) onde este "Common Character Set" está definido como o conjunto de caracteres ASCII.
> 
> Nas páginas 38 e 39 da referida especificação QR, está definido Merchant Name (59) e City (60) como "ans".
> 
> Portanto, concluímos que não é permitido acentuados nestes campos, e se colocar, corre-se o risco de ter o QR rejeitado ou exibido de forma errada pelo APP do pagador, o que pode impactar a UX.

Unicode UTF-8 é compatível com ASCII. A simples presença de um caractere fora do conjunto 'ANS' não deveria ter nenhum impacto específico para qualquer leitor preparado para UTF-8, embora esteja não-conforme. Especificamente para os campos EMV na raiz (root) "Mechant Name/City", seria apropriado adotar uma estratégia tolerante, especialmente no caso de ser um BRCode com Pix - QR Dinâmico (porque neste caso as informações mais detalhadas são recuperadas via URL).

**Comment by caio-bos-ifood** [comment]
@ninrod sim, o qrcode é unicode mas a dúvida era exatamente qual conjunto de caracteres são suportados para os campos **ANS**. Pela documentação, a limitação desse tipo de campo em seguir o "Common Character Set" do EMV Book 4 acaba restringindo o uso de caracteres da ISO/IEC 8859-1 nesses campos. Pelo menos foi esse o entendimento que tive da doc e da dicussão como um todo. 

@dmkamers nos meus testes tive exatamente esse comportamento. Apesar de não ser conformante, não tive problemas na leitura desses qrcodes, somente os caracteres não suportados que não foram corretamente decodificados.

**Comment by dmkamers** [comment]
> @ninrod sim, o qrcode é unicode mas a dúvida era exatamente qual conjunto de caracteres são suportados para os campos **ANS**. Pela documentação, a limitação desse tipo de campo em seguir o "Common Character Set" do EMV Book 4 acaba restringindo o uso de caracteres da ISO/IEC 8859-1 nesses campos. Pelo menos foi esse o entendimento que tive da doc e da dicussão como um todo.
> 
> @dmkamers nos meus testes tive exatamente esse comportamento. Apesar de não ser conformante, não tive problemas na leitura desses qrcodes, somente os caracteres não suportados que não foram corretamente decodificados.

Os 256 primeiros códigos Unicode são idênticos aos do padrão ISO 8859-1, de forma que é trivial converter texto ocidental existente. Os 96 caracteres 'ANS' são um subconjunto disso. Não é muito relevante discutir se esses caracteres são 'ANS', ASCII, ISO, ou UTF-8, pois são codificações compatíveis. Qualquer leitor de QR EMV deveria ser capaz de ler Unicode UTF-8, então não se espera que ocorra nada muito 'estranho' com a presença de um caractere ASCII (ou mesmo UTF-8) não-esperado em determinado campo. Mas é uma duvida pertinente, quanto ao que fazer nesses casos. Em um primeiro momento, parece apropriado uma abordagem tolerante, especialmente em campos que são 'informativos' (por exemplo, apenas excluindo da apresentação os eventuais caracteres 'ilegais'), sem rejeitar o QR. O Manual de Padrões para Iniciação do Pix define explicitamente que o campo "Merchant Name" (que seria o 'nome do recebedor') deve ser ignorado, e o que deve ser apresentado é o 'nome do recebedor' associado à chave do recebedor (nome esse recuperado do DICT).

**Comment by gpneto** [comment]
Eu também tive estas mesmas dúvidas e tinha aberto a issue https://github.com/bacen/pix-perguntas-e-respostas/issues/132

a resposta foi: "BR Code segue o EMV e nesse sentido, qualquer caracter UTF8 é aceito."

**Comment by dmkamers** [comment]
> Eu também tive estas mesmas dúvidas e tinha aberto a issue [bacen/pix-perguntas-e-respostas#132](https://github.com/bacen/pix-perguntas-e-respostas/issues/132)
> 
> a resposta foi: "BR Code segue o EMV e nesse sentido, qualquer caracter UTF8 é aceito."

@gpnet sim, um BRCode não deve ser 'rejeitado' pelo simples fato de conter caracteres UTF8. Valem, para cada campo específico, restrições adicionais: por exemplo, o campo 'txid' (id da transação) é bastante restrito no contexto do Pix. Já o 'Merchant Name' deve ser ignorado (vale o nome do recebedor que consta no DICT).

**Comment by AugustoResende** [comment]
@dmkamers e outros interessados.

Aparentemente o Banco Inter não aceita um QR Code Pix se a cidade tiver caracteres especiais.

**Comment by AugustoResende** [comment]
@dmkamers @ninrod @thiagolvlsantos
Confirmado, Inter não lê quando o merchantCity possui caracteres especiais (exemplo, São Paulo), após removido (Sao Paulo) funciona normalmente
