### ISSUE TITLE
[PIX Link] - Contribuições técnicas

### ISSUE THREAD

**Issue by felipecn** [bacen/pix-api#129]
**Descreva sua dúvida ou problema**
Pelo que li nas especificações de iniciação do PIX, entendi que o Banco Central irá registrar o aplicativo de cada PSP para ativar App Links (para Android) e Universal Links (para iOS).
A documentação sempre trabalha com a premissa de que o sistema operacional irá permitir ao usuário escolher a aplicação que irá abrir aquele link (ou definir um padrão) dentre as que tem instalado. O que é válido para o Android.
Porém, no iOS, não é possível escolher o aplicativo aberto por um universal link.
Meu entendimento é que o primeiro aplicativo listado no _https://pix.bcb.gov.br/.well-known/apple-app-site-association_ que o usuário tiver instalado será aberto.

Isso dito, tenho duas dúvidas:

1. Qual será a ordem usada no _https://pix.bcb.gov.br/.well-known/apple-app-site-association_ para listar os aplicativos de cada PSP? Tinha a impressão de ser na ordem alfabética pelo nome de cada instituição mas não achei a especificação.
2. Existe alguma intenção de mitigar esse caso? Creio um usuário ter mais um aplicativo compatível com PIX Links será um cenário bastante comum.

**Sistema ou Área**
PIX Link

**Comment by ninrod** [comment]
> Uma imagem do QR Code, poderia ser lida em formato de arquivo (ou da área de transferência) pela mesma lib que avalia a imagem capturada pela câmera do dispositivo.

> É até relativamente simples fazer com que a string do QR Code seja copiada para a área de transferência com um mero clique, em se tratando dos navegadores mobile (só um comandinho JS e pronto).

> Mas poder ler diretamente uma imagem em formato de QR Code facilitaria, por exemplo, o pagamento de QR Codes enviados por aplicativos de mensagem ou por e-mail ("mídias" onde a string do QR Code em formato texto vão, muito provavelmente, se quebrar, especialmente quando esta contiver os *** previstos para reserva de campo txid sem conteúdo).

@renatofrota , entendo que este fluxo já estaria endereçado agora para o go live;  é assim que funcionaria, bastando, é claro, que os aplicativos em questão implementem esta capacidade de "copiar a string do QR para a área de transferência". 

Exemplo: 

0. O app de mensagens instantâneas implementa a funcionalidade do "toque e copia string do QR". 
1. O pagador `A` recebe uma "imagem" de QR Code do Recebedor `R` via app de mensagens instantâneas.
2. O pagador `A` toca no QR e, com isso, a string é copiada para a área de trasnferência. 
3. O pagador `A` sabe que seu PSP apresentará, em algum lugar, uma funcionalidade para colar essa string. 
4. O pagador `A` abre seu app de seu PSP preferido e cola a string.

**Comment by renatofrota** [comment]
> > Uma imagem do QR Code, poderia ser lida em formato de arquivo (ou da área de transferência) pela mesma lib que avalia a imagem capturada pela câmera do dispositivo.
> 
> > É até relativamente simples fazer com que a string do QR Code seja copiada para a área de transferência com um mero clique, em se tratando dos navegadores mobile (só um comandinho JS e pronto).
> 
> > Mas poder ler diretamente uma imagem em formato de QR Code facilitaria, por exemplo, o pagamento de QR Codes enviados por aplicativos de mensagem ou por e-mail ("mídias" onde a string do QR Code em formato texto vão, muito provavelmente, se quebrar, especialmente quando esta contiver os *** previstos para reserva de campo txid sem conteúdo).
> 
> @renatofrota , entendo que este fluxo já estaria endereçado agora para o go live; é assim que funcionaria, bastando, é claro, que os aplicativos em questão implementem esta capacidade de "copiar a string do QR para a área de transferência".
> 
> Exemplo:
> 
>     1. O app de mensagens instantâneas implementa a funcionalidade do "toque e copia string do QR".
> 
>     2. O pagador `A` recebe uma "imagem" de QR Code do usuário Recebedor `R` via app de mensagens instantâneas.
> 
>     3. O pagador `A` toca no QR e, com isso, a string é copiada para a área de trasnferência.
> 
>     4. O pagador `A` sabe que seu PSP apresentará, em algum lugar, uma funcionalidade para colar essa string.
> 
>     5. O pagador `A` abre seu app de seu PSP preferido e cola a string.

Realmente, faz bastante sentido que os aplicativos passem a oferecer a possibilidade de copiar o conteúdo de um QR. Já demorou muito pra isso acontecer, na verdade.

Obrigado.

**Comment by rubenskuhl** [comment]
> @rubenskuhl
> 
> > https://tools.ietf.org/html/rfc8905 tem formas padronizadas de construção de link de pagamento com o método payto. Há inclusive um utilizado no primo indiano do Pix, o UPI.
> 
> Também já tínha sido mapeado. O problema é que qualquer aplicativo pode dizer que abre links do tipo `payto`. Além disso, esse link não é "renderizado" por padrão nos apps.

A questão de linkificação é de Universal Acceptance, problema que foi enfrentado também no programa de novos gTLDs (vide https://uasg.tech/). Como há outros meios de pagamento usando, a tendência é isso se resolver graças a esses outros ao longo do tempo. Mas isso vem depois de que já está sendo usado, se colocar como condicionante, nunca será adotado por plataformas. Por exemplo, se fosse adotado algo como "pix://", ia levar algum tempo até ver isso linkificado... o payto pode ter esse caminho mais curto, mas pela data da RFC ele acabou de ser iniciado.

**Comment by ninrod** [comment]
> Mas isso vem depois de que já está sendo usado, se colocar como condicionante, nunca será adotado por plataformas.

Ponto interessante. Novamente, nada impede que o `payto` ou o `pix` sejam incorporados no roadmap.

**Comment by rubenskuhl** [comment]
> > Mas isso vem depois de que já está sendo usado, se colocar como condicionante, nunca será adotado por plataformas.
> 
> Ponto interessante. Novamente, nada impede que o `payto` ou o `pix` sejam incorporados no roadmap.

Dada a RFC, sugiro o payto mesmo, inclusive colocando o pix como meio de pagamento no IANA registry. A RFC tem apenas a lista inicial do IANA registry de meios de pagamento.

**Comment by renatofrota** [comment]
> > bom dia @renatofrota ,
> > > Pensei nisso hoje ao fazer um pagamento de boleto. Copiei a linha digitável e o app do banco reconheceu automaticamente que o conteúdo da área de transferência era uma LD de boleto, sugerindo o pagamento do mesmo.
> > 
> > 
> > Está prevista sim a obrigatoriedade de implementação, por parte dos PSPs pagadores, da funcionalidade "Pix Copia e Cola". Que seria justamente algo como "a linha digitável". O que é copiado é a string do BR Code.
> 
> bom dia, @ninrod
> 
> Pois então, na mensagem acima eu citei isso:
> 
> > adicionalmente à possibilidade já prevista de copiar a string do QR Code
> 
> Uma **imagem** do QR Code, poderia ser lida em formato de arquivo (ou da área de transferência) pela mesma lib que avalia a imagem capturada pela câmera do dispositivo.
> 
> É até relativamente simples fazer com que a string do QR Code seja copiada para a área de transferência com um mero clique, em se tratando dos navegadores mobile (só um comandinho JS e pronto).
> 
> Mas poder ler diretamente uma imagem em formato de QR Code facilitaria, por exemplo, o pagamento de QR Codes enviados por aplicativos de mensagem ou por e-mail ("mídias" onde a string do QR Code em formato texto vão, muito provavelmente, se quebrar, especialmente quando esta contiver os `***` previstos para reserva de campo txid sem conteúdo).

O Banco Inter tá de olho aqui e implantou minha sugestão de ler imagem salva na galeria e detectar QR Code na imagem.

Por outro lado... foi um dos poucos que não implantou o envio de Pix via chave aleatória (que era um método não exigido pelo manual de UX, mas achei relaxo... é basicamente ctrl+c ctrl+v dos demais métodos de envio via chave, muito mais fácil do que implantar a leitura de imagem da galeria).

**Comment by gustavorps** [comment]
> https://tools.ietf.org/html/rfc8905 tem formas padronizadas de construção de link de pagamento com o método payto. Há inclusive um utilizado no primo indiano do Pix, o UPI.
> 
> O do Pix poderia ser algo payto://pix/chave?amount=BRL:200&TxID=TxID (Estático) ou payto://pix/?link=https://{fdqnPSPRecebedor}/{pixEndpoint}/v2/{pixUrlAcessToken} (Dinâmico)
> 
> Hat tip to @rturk.

Gostei muito da sugestão do @rubenskuhl extender um RFC é dos caminhos mais adeguados na minha opnião
Atualmente um padrão de deep link está fazendo muita falta.

Também gosto do padrão HTTP, seguindo dominio do Banco Central `https://pix.bcb.gov.br?code=<PIX_CODE>`, pode colocar um SPA (index.html) para renderizar o básico das informações em um CDN, praticamente não agrega custo.

**Comment by brazilianbytes** [comment]
Url-scheme payto://pix/<brcode> seria perfeito. Na minha humilde opinião, seria só o BCB definir o padrão e os apps de banco iriam correr para implementar. se a pessoa tiver mais de um banco, tem de ter o cuidado para não deixar como default. Cópia e Cola em celular alternando aplicativo é nível hard para muitas pessoas.

Estou implementando aqui na minha plataforma de telemedicina, e sempre nossa preocupação é facilitar a interface para pessoas mais velhas/humildes.

Estou acompanhando essa discussão agora.

**Comment by rubenskuhl** [comment]
Eu tenho a sensação de que o mercado e o BC estão apostando no ITP (Iniciador de Transação de Pagamento) para reduzir a necessidade do Copia e Cola, e por isso teriam deixado o PixLink no fundo da pilha do backlog... porque o app link seria do aplicativo do ITP (ex: Mercado Livre), e a conexão via OpenBanking garantiria que foi um ITP autorizado que fez um redirecionamento para o site do banco (onde a senha da conta confirma a transação). 

Eu gosto mais do payto://pix/, pq é mais Web "raiz"... mas vamos ver no que vai dar o ITP para que o caso de uso possa ser reavaliado.

**Comment by renatofrota** [comment]
ITP é o típico "para quê simplificar se dá pra complicar?". payto://pix é
uma solução infinitamente superior.

Em ter, 7 de jun de 2022 22:41, Rubens Kuhl ***@***.***>
escreveu:

**Comment by geekley** [comment]
@ninrod
> Adicionalmente, há uma questão de segurança envolvendo app links, falando especificamente de Android. É mais flexível e menos seguro do que Universal Links.
> 
> No app links, qualquer app consegue dizer que gerencia um pix link e funciona. Não adianta o BCB estabelecer uma lista restrita em um arquivo https://pix.bcb.gov.br/.well-known/assetlinks.json. Essa questão habilita alguns cenários de fraude que merecem uma discussão mais detida.

Não entendo muito disso (só li essa thread por alto), mas se o problema é qualquer app poder abrir o link e a intenção é permitir só apps autorizados pelo BCB, não seria só quem gerar o link criptografar a informação usando algum tipo de chave pública do BCB, de modo que só os apps permitidos conseguem de alguma forma descriptografar e entender a informação contida no link?

Ex.: `payto://pix/encrypted?type=rsa4096&bits=<string em base64>`
Só os apps autorizados conseguem descriptografar essa string, por exemplo um JSON:
`{"amount": 123.45, "currency": "BRL", "receiver": ... }`

**Comment by felipecn** [comment]
O problema é que não é garantido que o usuário possa escolher o PSP para efetuar o pagamento, seja com app links ou com o payto://

No iOS certamente não pode, e no Android depende de inúmeros fatores (versão do OS, customizações da fabricante etc)

**Comment by rubenskuhl** [comment]
> @ninrod
> 
> > Adicionalmente, há uma questão de segurança envolvendo app links, falando especificamente de Android. É mais flexível e menos seguro do que Universal Links.
> > No app links, qualquer app consegue dizer que gerencia um pix link e funciona. Não adianta o BCB estabelecer uma lista restrita em um arquivo https://pix.bcb.gov.br/.well-known/assetlinks.json. Essa questão habilita alguns cenários de fraude que merecem uma discussão mais detida.
> 
> Não entendo muito disso (só li essa thread por alto), mas se o problema é qualquer app poder abrir o link e a intenção é permitir só apps autorizados pelo BCB, não seria só quem gerar o link criptografar a informação usando algum tipo de chave pública do BCB, de modo que só os apps permitidos conseguem de alguma forma descriptografar e entender a informação contida no link?
> 
> Ex.: `payto://pix/encrypted?type=rsa4096&bits=<string em base64>` Só os apps autorizados conseguem descriptografar essa string, por exemplo um JSON: `{"amount": 123.45, "currency": "BRL", "receiver": ... }` Mesmo se um app fraudulento consegue interceptar o link (assim como qualquer outro link payto), não conseguiria tirar nenhum proveito das informações contidas nele.

Se a questão é integridade e não sigilo, poderia ser usada assinatura ao invés de criptografia. Mas o problema dessa idéia é que tanto os merchants quanto os PSPs precisariam de uma API exposta diretamente pelo Banco Central para geração e consumo dos links payto://pix, o que parece não ser o modelo desejado pelo BACEN.

**Comment by geekley** [comment]
> Se a questão é integridade e não sigilo, poderia ser usada assinatura ao invés de criptografia. Mas o problema dessa idéia é que tanto os merchants quanto os PSPs precisariam de uma API exposta diretamente pelo Banco Central para geração e consumo dos links payto://pix, o que parece não ser o modelo desejado pelo BACEN.

@rubenskuhl Usando chaves assimétricas, não precisaria de API para geração. Só precisaria saber a chave pública, que não é algo que muda o tempo todo. Ela seria pública mesmo, qualquer um poderia ver na especificação. E a criptografia é necessária, pois um app que interceptasse o link poderia alterar o recebedor e gerar outro link válido, exatamente por a chave ser pública.
No lado do PSP, aí sim, o app precisaria de uma API se ele não tem acesso a essa chave privada correspondente.

**Comment by geekley** [comment]
> O problema é que não é garantido que o usuário possa escolher o PSP para efetuar o pagamento, seja com app links ou com o payto://
> No iOS certamente não pode, e no Android depende de inúmeros fatores (versão do OS, customizações da fabricante etc)

Considerando que Android tem a maior fatia de mercado ([~85.35%](https://gs.statcounter.com/os-market-share/mobile/brazil)) no Brasil, que [versões novas](https://gs.statcounter.com/android-version-market-share/mobile/brazil) do Android são bem mais comuns que antigas (além de que nem todo mundo se encaixa no caso de mais de um PSP), será que requerer o "app redirecionador central" apenas nesses casos não seria uma solução aceitável?
Ou seja, tanto os PSPs quanto esse app redirecionador usariam payto\://pix ou pix\://. Daria pra especificar que quando um PSP responde a esse Pix Link e se encaixa nesses casos onde o usuário não tem a opção de escolher outro app, ele deve mostrar uma opção permitindo a instalação desse app central do BCB. Ex.:
> Queria pagar por outro app? Use o [app do BACEN](#) para escolher.

O link vai pra store se ele já não estiver instalado; se está (e não for o padrão) redireciona para ele.

**Comment by rubenskuhl** [comment]
> > Se a questão é integridade e não sigilo, poderia ser usada assinatura ao invés de criptografia. Mas o problema dessa idéia é que tanto os merchants quanto os PSPs precisariam de uma API exposta diretamente pelo Banco Central para geração e consumo dos links payto://pix, o que parece não ser o modelo desejado pelo BACEN.
> 
> @rubenskuhl Usando chaves assimétricas, não precisaria de API para geração. Só precisaria saber a chave pública, que não é algo que muda o tempo todo. Ela seria pública mesmo, qualquer um poderia ver na especificação. No lado do app do banco, aí sim, o app precisaria de uma API se ele não tem acesso a essa chave privada correspondente.
> 
> E imaginei que a criptografia é necessária, pois um app fraudulento que interceptasse o link poderia alterar o recebedor e gerar outro link válido, exatamente por a chave ser pública. Mas como disse, não entendo muito disso e não sei se ajudaria muito a dificultar fraudes - talvez só ele interceptar o link já seja um problema de qualquer forma.

Mesmo com chave assimétrica, para gerar algo digitalmente assinado precisa da chave privada. 
Senão não tem contra o que validar. 

E a interceptação do link depende apenas do método (payto: ou pix:) não depende de nada do conteúdo.

**Comment by rubenskuhl** [comment]
> > O problema é que não é garantido que o usuário possa escolher o PSP para efetuar o pagamento, seja com app links ou com o payto://
> > No iOS certamente não pode, e no Android depende de inúmeros fatores (versão do OS, customizações da fabricante etc)
> 
> Considerando que Android tem a maior fatia de mercado ([~85.35%](https://gs.statcounter.com/os-market-share/mobile/brazil)) no Brasil, que [versões novas](https://gs.statcounter.com/android-version-market-share/mobile/brazil) do Android são bem mais comuns que antigas (além de que nem todo mundo se encaixa no caso de mais de um PSP), será que requerer o "app redirecionador central" apenas nesses casos não seria uma solução aceitável? Ou seja, tanto os PSPs quanto esse app redirecionador usariam payto://pix ou pix://. Daria pra especificar que quando um PSP responde a esse Pix Link e se encaixa nesses casos onde o usuário não tem a opção de escolher outro app, ele deve mostrar uma opção permitindo a instalação desse app central do BCB. Ex.:


O BACEN já gongou essa idéia de app central dele. Tem tanto no histórico deste issue quanto nas apresentações do Fórum Pix.

**Comment by geekley** [comment]
> Mesmo com chave assimétrica, para gerar algo digitalmente assinado precisa da chave privada.
> Senão não tem contra o que validar.

A intenção não era assinar digitalmente, apenas proteger a info dentro do link de outros apps não reconhecidos pelo BCB. Ao criptografar com a chave pública, apenas a privada pode descriptografar. Apenas os apps PSP reconhecidos poderiam chamar a API do BCB para descriptografar no caso (isso seria só para obter os dados para a transferência, não para realizar, claro).

> E a interceptação do link depende apenas do método (payto: ou pix:) não depende de nada do conteúdo.

Sei. Por isso acho que seria mesmo um problema quanto a fraudes.

> O BACEN já gongou essa idéia de app central dele. Tem tanto no histórico deste issue quanto nas apresentações do Fórum Pix.

Isso inclui a solução de link https para um domínio oficial do BCB que redireciona? Me parece a solução que faz mais sentido.

**Comment by rubenskuhl** [comment]
> > Mesmo com chave assimétrica, para gerar algo digitalmente assinado precisa da chave privada.
> > Senão não tem contra o que validar.
> 
> A intenção não era assinar digitalmente, apenas proteger a info dentro do link de outros apps não reconhecidos pelo BCB. Ao criptografar com a chave pública, apenas a privada pode descriptografar. Apenas os apps PSP reconhecidos poderiam chamar a API do BCB para descriptografar no caso (isso seria só para obter os dados para a transferência, não para realizar, claro).

https://pt.wikipedia.org/wiki/Criptografia_de_chave_p%C3%BAblica

> > E a interceptação do link depende apenas do método (payto: ou pix:) não depende de nada do conteúdo.
> 
> Sei. Por isso acho que seria mesmo um problema quanto a fraudes.

O que iria mais para o lado de não ter PixLink nenhum, que foi a decisão do BACEN até o momento. 

> > O BACEN já gongou essa idéia de app central dele. Tem tanto no histórico deste issue quanto nas apresentações do Fórum Pix.
> 
> Isso inclui a solução de link https para um domínio oficial do BCB que redireciona? Me parece a solução que faz 
mais sentido.

Não, essa eu não lembro de já ter sido gongada. Não significa porém que seja bem-vista, apenas que não me recordo de objeção clara. Mas agora imagine o necessário para fazer isso: sabendo o CPF do pagador, o BACEN precisaria fazer pesquisa reversa na base do Registrato para mostrar apenas as instituições onde o pagador tem conta, aleatorizar a ordem e gerar os links para os respectivos apps. Ou então mostrar uma lista de 800 instituições para todo mundo...

**Comment by geekley** [comment]
Pois é, no próprio link da Wikipédia faz essa distinção que eu falei; eu me referia ao 1o uso e não ao 2o:
> Dois dos usos mais conhecidos de criptografia de chave pública são:
> - Encriptação de chave pública, na qual a mensagem é encriptada com a chave pública do destinatário. A mensagem não pode ser decriptada por ninguém que não possua a chave privada correspondente, o qual é presumidamente o proprietário da chave e a pessoa associada com a chave pública. Isto é utilizado numa tentativa de assegurar [confidencialidade](https://pt.wikipedia.org/wiki/Confidencialidade).
> - [Assinaturas digitais](https://pt.wikipedia.org/wiki/Assinatura_digital), [...]

Mas, enfim.

> BACEN precisaria fazer pesquisa reversa na base do Registrato para mostrar apenas as instituições onde o pagador tem conta, aleatorizar a ordem e gerar os links para os respectivos apps. Ou então mostrar uma lista de 800 instituições para todo mundo...

Sim, eu penso que seria OK carregar todas as 800 instituições, porém mostrar só uma barrinha pesquisável localmente, e, como já foi sugerido acima, salvar apenas em cache local a(s) escolha(s) do usuário. Basicamente tudo feito no frontend mesmo, sem salvar ou processar nada no backend. Daria até pra permitir o usuário reordenar como quisesse.

**Comment by rubenskuhl** [comment]
> Pois é, no próprio link da Wikipédia faz essa distinção que eu falei; eu me referia ao 1o uso e não ao 2o:

Mas independente de encriptação ou assinatura, pense quem tem a custódia da chave privada e como ela precisaria ser usada, para ver pq isso não dá certo. 

> > BACEN precisaria fazer pesquisa reversa na base do Registrato para mostrar apenas as instituições onde o pagador tem conta, aleatorizar a ordem e gerar os links para os respectivos apps. Ou então mostrar uma lista de 800 instituições para todo mundo...
> 
> Sim, eu penso que seria OK carregar todas as 800 instituições, porém mostrar só uma barrinha pesquisável localmente, e, como já foi sugerido acima, salvar apenas em cache local a(s) escolha(s) do usuário. Basicamente tudo feito no frontend mesmo, sem salvar ou processar nada no backend. Daria até pra permitir o usuário reordenar como quisesse.

Aí necessariamente a apresentação precisaria ser em ordem alfabética, o que quebraria um requisito que o BACEN já comentou sobre o processo de não privilegiar um banco em detrimento de outro. Aí o passo seguinte é alguém abrir o AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA Banco.

**Comment by renatofrota** [comment]
É meio discutível essa questão de que aparecer primeiro numa lista que é **alfabética** seria um privilégio...

**Comment by felipecn** [comment]
Quanto menos esforço o usuário precisa pra escolher uma instituição, maior é a probabilidade dela ser escolhida.

**Comment by geekley** [comment]
> Aí necessariamente a apresentação precisaria ser em ordem alfabética

Quando eu disse "mostrar ***só*** uma barrinha pesquisável" eu quis dizer que nenhum resultado apareceria até que o usuário comece a pesquisar. Quando começar a digitar, aí sim lista em uma ordem qualquer, pode até ser alfabética. Já vi várias UX fazendo isso, é normal. Pense "autocompletar tipo o da barra de pesquisa do Google". Se o usuário *quiser* listar todas em ordem alfabética ou outra ordem qualquer, não tem problema botar um botão pra isso também. Mas não haveria privilégio porque nenhum aparece por padrão, a não ser a lista dos que o user já escolheu anteriormente, salvo em cookie.

> pense quem tem a custódia da chave privada e como ela precisaria ser usada, para ver pq isso não dá certo.

Se isso foi gongado, não importa.
Mas pra explicar o que eu queria dizer, seria algum servidor do BCB que decripta. Talvez não ficou claro o fluxo:
1. Site/app geraria o link payto/pix, encriptando com chave pública do BCB
2. Ao clicar, nenhum app consegue decifrar a info, pois só o server do BCB tem a chave privada. Um app só consegue saber que é payto e pix (o que como mencionado antes ainda talvez seja um problema, etc, enfim)
3. Mas apps de PSP reconhecidos podem mandam o link encriptado por uma API do BCB (usando autenticação normal HTTPS, algum token de API, o que for) e ele responde com as informações decriptadas (via HTTPS).
4. App apresenta as informações (igual se user tivesse usado QR ou Copia/Cola) e user altera ou não o que precisar
5. Usuário confirma a transação, etc

**Comment by rubenskuhl** [comment]
> > Aí necessariamente a apresentação precisaria ser em ordem alfabética
> 
> Quando eu disse "mostrar _**só**_ uma barrinha pesquisável" eu quis dizer que nenhum resultado apareceria até que o usuário comece a pesquisar. Quando começar a digitar, aí sim lista em uma ordem qualquer, pode até ser alfabética. Já vi várias UX fazendo isso, é normal. Pense "autocompletar tipo o da barra de pesquisa do Google". Se o usuário _quiser_ listar todas (sem digitar nada) em ordem alfabética ou outra ordem qualquer, não tem problema botar um botão pra isso também. Mas não haveria privilégio porque nenhum aparece por padrão, a não ser a lista dos que o user já escolheu anteriormente, salvo em cookie.

Nesse caso o efeito de ordem alfabética, apesar de existente, é bem menor. Se menor o suficiente para o BACEN, só o BACEN pode dizer... mas já é menos impactante. E tem precedente, o OpenFinance, onde também há uma tela dessas. 

> Se isso foi gongado, não importa. 

O que foi gongado é um API exposta publicamente fora da RSFN. Tem como adaptar sua proposta para rodar dentro da RSFN, e vou citar como abaixo. 

> Mas pra explicar o que eu queria dizer, seria algum servidor do BCB que decripta. Talvez não ficou claro o fluxo:
> 
> 1. Site/app geraria o link payto/pix, encriptando com chave pública do BCB

Ok, chave poderia ficar publicada no site do BACEN. Isso pode ter alguma letargia nos roll-over de chave, mas dá para publicar duas chaves iniciando vigência em anos alternados e ir fazendo phase-out das antigas. 

> 2. Ao clicar, nenhum app consegue decifrar a info, pois só o server do BCB tem a chave privada. Um app só consegue saber que é payto e pix (o que como mencionado antes ainda talvez seja um problema, etc, enfim)
> 3. **Apenas apps de PSP reconhecidos poderiam mandar o link encriptado por uma API do BCB** (usando autenticação normal HTTPS, algum token de API, o que for) **e ele responde com as informações decriptadas via HTTPS**.

Uma adaptação aqui seria a consulta ao DICT, que já é feita via RSFN, ser esse mecanismo. O banco envia via RSFN para o BACEN esse blob criptografado e um e2eid, e o BACEN já na mesma tacada decriptografa, faz look-up da chave no DICT e devolve os dados bancários correspondentes e o BRCode(EMV) do pagamento. Então o app do PSP continua falando apenas com o back-end do PSP, e o back-end do PSP falando com o BACEN. E nem precisaria de uma nova interface no arranjo. 


> 4. App apresenta as informações (igual se user tivesse usado QR ou Copia/Cola) e user altera ou não o que precisar
> 5. Usuário confirma a transação, etc
