### ISSUE TITLE
/pix Vs. /cob

### ISSUE THREAD

**Issue by renato-farias** [bacen/pix-api#13]
Mais dúvida do que issue, a publicação da V2 trouxe um endpoint para cobrança e outro para o Pix, poderiam descrever qual a diferença e o real caso de uso para as ambas atualmente e no futuro.

Aproveitando o ticket também gostaria de entender: porque o `/pix/*` requer um `e2eid` de `PACS00*.` Se eu nesse caso eu sou um **gateway**/**facilitador** como ficaria minha utilização desses endpoints? Eu receberia somente `e2eid` uma vez que a cobrança está paga?

**Comment by ninrod** [comment]
Boa tarde @renato-farias , 

o endpoint `/cob` tem a função de gerenciar cobranças que podem ser pagas via pix. Com esse endpoint pode-se definir valor, informações adicionais, expiração e informações correlatas à cobrança. 

o `pix` serve para gerenciar apenas pix. Nesse endpoint, você consegue gerenciar qualquer pix recebido, não apenas aqueles iniciados via QR Code. Há ainda, via esse endpoint, a possibilidade de se devolver um pix, integral ou parcialmente. Você não consegue criar um QR Code apenas com esse endpoint. 

Em se tratando de qr dinâmico, o fluxo normal é usar o endpoint `PUT /cob/{txid}` para criar a cobrança. Depois é só verificar o status dessa cobrança via `GET /cob/{txid}` para verificar o pagamento.

> Aproveitando o ticket também gostaria de entender: porque o /pix/* requer um e2eid de PACS00*. Se eu nesse caso eu sou um gateway/facilitador como ficaria minha utilização desses endpoints? Eu receberia somente e2eid uma vez que a cobrança está paga?

No fluxo normal você utilizaria esse endpoint somente no caso de uso envolvendo QR Estático. Para verificar o pagamento iniciado via QR Estático você utilizaria `GET /pix?txid={txid}`, por exemplo. Além disso, usando o endpoint `/pix` é possível efetuar devoluções.

**Comment by renato-farias** [comment]
Obrigado pela explicação detalhada @ninrod . Tudo esclarecido.
