### ISSUE TITLE
[Dúvida] API 2.1.0 Reutilização do location

### ISSUE THREAD

**Issue by GustavoBraz** [bacen/pix-api#130]
Boa tarde.
Partindo do pressuposto que o location pode ser alterado, as reviews anteriores ainda mantém os locations antigos? Por exemplo:

> [PUT /cob] Cobrança **A** -> Review **0** -> location **12**
[PATCH /cob] Cobrança **A** -> Review **1** -> location **NULL**
[PUT /cob] Cobrança **B** -> Review **0** -> location **12**

Se realizar a consulta da cobrança **A** Review **0** o location retornado deve ser igual a **12**?

Outra dúvida: Por que deixar exposto o id do location, sendo que o próprio token é único?

Obrigado.

**Comment by ninrod** [comment]
@GustavoBraz , 

> Se realizar a consulta da cobrança A Review 0 o location retornado deve ser igual a 12?

Sim, correto. 

> Outra dúvida: Por que deixar exposto o id do location, sendo que o próprio token é único?

O "pixUrlAcessToken" não é necessariamente único porque pode se repetir em diferentes domínios. 

exemplo: 

```txt
  "location1": "pix.example.com/qr/2353c790-eefb-11ea-adc1-0242ac120002",
  "location2": "meunovoserver.example.com/qr/2353c790-eefb-11ea-adc1-0242ac120002",
```

As duas locations são válidas.
