### ISSUE TITLE
[Dúvida] Certificados no envio de webhooks

### ISSUE THREAD

**Issue by thomazfeitoza** [bacen/pix-api#131]
Prezados,

Estive acompanhando as issues relacionadas a webhooks mas não encontrei nenhuma que explique de forma mais detalhada o uso de certificados durante o mTLS no envio de webhooks.

Ao ler o manual de padrões do Pix ficou claro para mim o processo de emissão de certificados e também o uso desse certificado pelo integrador ao realizar chamadas nos endpoints da API Pix usando mTLS. O que não entendi bem é o mTLS no fluxo inverso, quando o PSP envia uma requisição para uma url do integrador (webhook). O que consegui refletir até agora mas que talvez não esteja correto é o seguinte:

1. O integrador deve conseguir acessar de alguma forma a cadeia que assinou o certificado de cliente usado pelo PSP no envio do webhook, sendo ela reconhecida internacionalmente ou gerada pelo próprio PSP. O integrador precisa dessa cadeia para que seu servidor TLS valide se quem está fazendo a requisição é quem diz ser.
2. O integrador deve usar o certificado gerado no PSP para servir seu endereço https. Na verdade, esta é minha principal dúvida, qual certificado o integrador deve usar em seu servidor?
3. O PSP deve verificar se a url do integrador obriga o uso do mTLS. Mais uma dúvida aqui, é responsabilidade do PSP fazer essa verificação?

Conto com a ajuda de vocês!

**Comment by rubenskuhl** [comment]
1. A hipótese de certificado gerado pelo PSP foi removida da especificação, então precisa ser certificado por CA reconhecida
2. O certificado de atendimento da API Pix e do webhook podem ser potencialmente diferentes, ou iguais. Me parece que é uma escolha do PSP, mas qualquer que seja ela, precisa ser informado ao cliente para saber qual certificado esperar. 
3. Pelo que lembro do manual é responsabilidade do PSP, mas não diz quando fazer; isso poderia ser feito no momento da ativação ou mudança do webhook ao invés de em toda requisição. Eu como cliente preferiria um PSP que fizesse isso nesse momento ao invés de toda requisição tentar um método HTTP antes de mandar client-certificate, ver que foi recusado, e só então mandar o client-certificate.

**Comment by thomazfeitoza** [comment]
Obrigado pela resposta @rubenskuhl.

> 1. A hipótese de certificado gerado pelo PSP foi removida da especificação, então precisa ser certificado por CA reconhecida

Na seção 5.1, item 2.a [deste manual](https://www.bcb.gov.br/content/estabilidadefinanceira/pix/Regulamento_Pix/II.ManualdePadroesparaIniciacaodoPix-versao2.0.pdf) deu a entender que o PSP pode gerar e assinar o certificado por conta própria se assim ele quiser. Tem algum outro local que diz o contrário?

> 2. O certificado de atendimento da API Pix e do webhook podem ser potencialmente diferentes, ou iguais. Me parece que é uma escolha do PSP, mas qualquer que seja ela, precisa ser informado ao cliente para saber qual certificado esperar.

Entendi, e acredito que o integrador tratar o certificado de seu servidor sem o envolvimento do PSP torne o processo mais flexível.

> 3. Pelo que lembro do manual é responsabilidade do PSP, mas não diz quando fazer; isso poderia ser feito no momento da ativação ou mudança do webhook ao invés de em toda requisição. Eu como cliente preferiria um PSP que fizesse isso nesse momento ao invés de toda requisição tentar um método HTTP antes de mandar client-certificate, ver que foi recusado, e só então mandar o client-certificate.

Concordo. Verificar em cada requisição realmente não seria bom para o integrador pois dobraria a carga na url dele. Uma verificação periódica de baixa frequência também é uma opção a mais que o PSP poderia usar para garantir esse requisito.

**Comment by franciscotfmc** [comment]
> A hipótese de certificado gerado pelo PSP foi removida da especificação, então precisa ser certificado por CA reconhecida

Também não tive esse entendimento. Como é um canal fechado entre o PSP e o Recebedor, penso que o PSP pode gerar e assinar o certificado. @ninrod consegue nos ajudar nessa questão?

**Comment by rubenskuhl** [comment]
Depende de qual certificado estamos falando. 
- O certificado do servidor da API do PSP precisa ser emitido por CA reconhecida, conforme manual de segurança do Pix
- O certificado cliente para acesso à API do PSP pode ser de uma CA reconhecida ou emitido pelo PSP, mas não pode ser auto-assinado pelo cliente
- O certificado do servidor do webhook do cliente não parece estar especificado, mas parece prudente adotar o mesmo requisito do servidor da API do PSP. Mas o BACEN poderia especificar o mesmo requisito do certificado cliente. 
- O certificado cliente do PSP para acessar o servidor do webhook não parece estar especificado, mas parece prudente adotar o mesmo requisito do certificado cliente para acesso à API do PSP.

**Comment by franciscotfmc** [comment]
> O certificado do servidor da API do PSP precisa ser emitido por CA reconhecida, conforme manual de segurança do Pix
Concordo.

> O certificado cliente para acesso à API do PSP pode ser de uma CA reconhecida ou emitido pelo PSP, mas não pode ser auto-assinado pelo cliente
> O certificado do servidor do webhook do cliente não parece estar especificado, mas parece prudente adotar o mesmo requisito do servidor da API do PSP. Mas o BACEN poderia especificar o mesmo requisito do certificado cliente.
> O certificado cliente do PSP para acessar o servidor do webhook não parece estar especificado, mas parece prudente adotar o mesmo requisito do certificado cliente para acesso à API do PSP.

Eu estava com esses outros em mente quando questionei.

**Comment by dmkamers** [comment]
Prezados, é prudente tratar qualquer definição relativa à webhooks com cautela. De qualquer forma, as observações do @rubenskuhl vão direto ao ponto. Note-se o seguinte: um mesmo certificado pode ter o 'papel' de 'server' (é o típico), mas também de 'client' (raro, exceto sistema-sistema). Mas jamais você usa o certificado 'do outro'. Você *pode* usar o _seu_ certificado TLS e autenticar-se como cliente de _outro_ servidor TLS. Isso vale para os dois lados. Só que dificuldades operacionais, conveniência, ou política de segurança podem exigir que se usem certificados distintos/dedicados. Em um primeiro momento, parecia trivial que o 'cliente' da API (que já é obrigado a ter um certificado TLS no papel de 'cliente TLS') utilizasse este mesmo certificado no papel de 'servidor TLS' no seu serviço-webhook. Mas uma definição mais precisa da 'regra' exige fechar melhor a questão 'webhook' antes, sobre a qual muitos pontos relevantes foram levantados pela comunidade.

**Comment by dmkamers** [comment]
> Depende de qual certificado estamos falando.
> 
> * O certificado do servidor da API do PSP precisa ser emitido por CA reconhecida, conforme manual de segurança do Pix
> * O certificado cliente para acesso à API do PSP pode ser de uma CA reconhecida ou emitido pelo PSP, mas não pode ser auto-assinado pelo cliente
> * O certificado do servidor do webhook do cliente não parece estar especificado, mas parece prudente adotar o mesmo requisito do servidor da API do PSP. Mas o BACEN poderia especificar o mesmo requisito do certificado cliente.
> * O certificado cliente do PSP para acessar o servidor do webhook não parece estar especificado, mas parece prudente adotar o mesmo requisito do certificado cliente para acesso à API do PSP.

@rubenskuhl está pertinente, mas note que, dependendo da modelagem do webhook, talvez não seja tão importante algum desses requisitos de segurança. Depende quem consome as informações e sua natureza (públicas, sensíveis...), os riscos associados e as mitigações exigidas ou possíveis. A proposta inicial tinha um modelo à vista, em que o mesmo 'sistema-cliente' da API recebe a notificação, num cenário em que um TLS 'reverso' seria trivial de ser implementado com os mesmos certificados. Como estamos falando de tecnologia 'web', há bastante liberdade de implementação e as soluções estão 'dadas'. Cabe aos PSPs e sistemas-cliente efetivarem seu melhor esforço. Apenas definimos uma 'linha mínima' de interoperabilidade, que significa exigir que o serviço webhook não seja 'público', e que a chamada (https) parta de um cliente 'autenticado' (o PSP chamando o serviço-webhook).

**Comment by thomazfeitoza** [comment]
Como essas definições não estão muito relacionadas a especificação da API Pix mas sim à implementação de cada PSP, considero que minha dúvida foi solucionada. Achei as sugestões do @rubenskuhl muito válidas e acredito que elas servem como um modelo de implementação.

Agradeço a todos pelos esclarecimentos!
