### ISSUE TITLE
[DÚVIDA] Endpoint: GET Recuperar o payload JSON que representa a cobrança.

### ISSUE THREAD

**Issue by rodrigoma** [bacen/pix-api#135]
Pelo entendimento o path parameters **pixUrlAccessToken** é o campo **location** retornada na criação da cobrança.

no exemplo de retorno da criação de cobrança é algo desse tipo
`"location": "pix.example.com/qr/9d36b84f-c70b-478f-b95c-12729b90ca25"`

minha duvida é no conteúdo desse **pixUrlAccessToken** que vai ser passado pro endpoint de GET

pegando ainda o exemplo de path completo desse endpoint é esse
`https://{fdqnPSPRecebedor}/{pixEndpoint}/v1/{pixUrlAcessToken}`

o replace do pixUrlAcessToken ficaria assim?
`https://{fdqnPSPRecebedor}/{pixEndpoint}/v1/pix.example.com/qr/9d36b84f-c70b-478f-b95c-12729b90ca25`

ou assim?
`https://{fdqnPSPRecebedor}/{pixEndpoint}/v1/9d36b84f-c70b-478f-b95c-12729b90ca25`

Obrigado!

**Comment by ninrod** [comment]
@rodrigoma , 


> https://{fdqnPSPRecebedor}/{pixEndpoint}/v1/9d36b84f-c70b-478f-b95c-12729b90ca25


ficaria assim: 

fdqnPSPRecebor = full qualified domain name PSP recebedor = meu.exemple.com
pixEndpoint = qualquer path que se queira utilizar, por exemplo /pix
v1 = v2 (porque não tem mais v1 a partir da 2.1.x
pixUrlAcessToken = 9d36b84f-c70b-478f-b95c-12729b90ca25

total: 

`https://meu.example.com/pix/v2/9d36b84f-c70b-478f-b95c-12729b90ca25`

**Comment by rodrigoma** [comment]
Obrigado pela resposta!

**Comment by ninrod** [comment]
> Obrigado pela resposta!

Apenas complementado: 

Essas duas location são válidas __e__ diferentes: 

`example.com/1/v2/meu9d36b84fc70b478fb95c12729b90ca25`

e 

`example.com/2/v2/meu9d36b84fc70b478fb95c12729b90ca25`
