### ISSUE TITLE
[Dúvida] txId ser gerado exclusivamente pelo cliente recebedor

### ISSUE THREAD

**Issue by jrdevgyn** [bacen/pix-api#136]
É possível que o txId seja gerado pelo PSP recebedor? Imaginamos usar a geração do txId como mecanismo para distribuição/balanceamento de QR Codes entre vários servidores sem um nó central para direcionar a localização do txId. Caso o txId venha a ser exclusivamente informado pelo cliente recebedor, não poderemos usar tais técnicas, o que significa uma perda de qualidade ofertada para o cliente final, como a alta performance com baixo custo computacional. 
Nossa sugestão é que, além de manter a possibilidade do envio do txId pelo cliente recebedor conforme especificação atualizada, exista também a possibilidade do cliente recebedor delegar essa definição do txId ao seu PSP Recebedor, não sendo necessário informar o txId nesses casos. Temos situações concretas onde marketplaces, em situações de “stress” como Black Friday, vão preferir a melhor performance na distribuição de QR Codes em diversos servidores, do que a possibilidade de permitir que o cliente recebedor defina um txId próprio, cabendo ao PSP devolver esse txId. Dessa forma deixamos o cliente final recebedor arbitrar sobre a melhor solução para ele, o que permite atender aos diferentes casos de uso.

Sobre a garantia de unicidade do txId pelo PSP Recebedor: quando o usuário recebedor informa esse parâmetro, isso exigirá armazenamento “eterno” de todos txIds gerados por aquele recebedor junto ao PSP. No exemplo de um PSP que atende a um grande e-commerce (que gera milhões de vendas por mês), isso significaria a necessidade de registro de uma quantidade gigantesca de txIds após 10 ou 15 anos de relacionamento com aquele cliente. Flexibilizar casos de uso como esse para que o PSP possa gerar o txId, resolve questões como essa. Adicionalmente pode-se pensar em garantir essa unicidade apenas por períodos (mês, semana, ano), incluindo a data no conjunto de informações que deve ser único.

**Comment by rubenskuhl** [comment]
Como já respondido em issues anteriores, a geração do TxID pelo PSP causa perda de idempotência. Eu concordo 100% com o BACEN de manter esse parâmetro gerado pelo cliente. 

Dá para fazer load-balancing sem usar o TxID; do lado do atendedor dos PUT de geração de cobranças, qualquer LB por hash por número de porta origem e IP de origem já vai dar uma distribuição significativa. Já no webhook, é o PSP que inicia a conexão, então ele pode fazer qualquer método de LB que queira... basta que todos os servidores estejam autorizados a conectar aos pontos de tratamento do cliente.

**Comment by ninrod** [comment]
> É possível que o txId seja gerado pelo PSP recebedor?

Não é possível. Essa já foi uma questão fechada pelo negócio.
