### ISSUE TITLE
Consulta QR code estático gerado fora do PSP recebedor

### ISSUE THREAD

**Issue by rodrigonunes100** [bacen/pix-api#137]
Sabendo que a consulta de QR code estático pago (gerado fora do PSP recebedor)
pode ser feita com GET /pix?txid={txid}, minha pergunta é o seguinte:
Todo PSP recebedor é obrigado e liberar esse endpoint ? Pela issues anteriores me parece que não. Acho esse um ponto importante, onde a consulta do QR code estático (gerado fora do PSP recebedor) possa ser feita fora do PSP recebedor e de uma maneira central, como uma consulta FEDEX ou correios por exemplo.

**Comment by ninrod** [comment]
@rodrigonunes100 

> Todo PSP recebedor é obrigado e liberar esse endpoint ? 

Sim.

Se oferecer a API, tem que implementar esse endpoint, assim como todos os outros especificados. Cabe ressaltar que o PSP recebedor não é obrigador a oferecer integração automatizada e nem há uma data obrigatória para que estas APIs sejam ofertadas. 

> a consulta do QR code estático (gerado fora do PSP recebedor) possa ser feita fora do PSP recebedor e de uma maneira central, como uma consulta FEDEX ou correios por exemplo.

Essa possibilidade já tinha sido mapeada no início do projeto, internamente, e também já apareceu em outras issues neste repositório. No presente momento não se vislumbra esse caminho de integração.
