### ISSUE TITLE
[Dúvida no QR Code Estático]

### ISSUE THREAD

**Issue by simonevirgilio** [bacen/pix-api#139]
Sobre os QRCode estáticos eles podem possuir a funcionalidade de serem pagos apenas uma vez igual aos dinâmicos?
No caso utilizando a intrução "Point of Initiation Method" com o valor 12 (não deve ser utilizado mais de uma vez).
Se a resposta for sim, é uma funcionalidade obrigatória para os usuários ou podemos utilizar o padrão? (Aceita mais de um pagamento)

**Sistema ou Área**
QR Code

**Comment by ninrod** [comment]
@simonevirgilio , bom dia. 

> Sobre os QRCode estáticos eles podem possuir a funcionalidade de serem pagos apenas uma vez igual aos dinâmicos?

Não. 

> No caso utilizando a intrução "Point of Initiation Method" com o valor 12 (não deve ser utilizado mais de uma vez).

É uma semântica EMV. No caso do Pix, é apenas uma indicação para que o PSP pagador informe ao pagador, de alguma maneira, que aquele QR é para ser pago somente uma vez pelo pagador.

>  utilizar o padrão? (Aceita mais de um pagamento)

Sim, utiliza-se o padrão, qr estático é sempre multi-pagamentos.
