### ISSUE TITLE
Auth Scopes

### ISSUE THREAD

**Issue by renato-farias** [bacen/pix-api#14]
Poderiam colocar na spec o retorno dos endpoints de geração e refresh token, acredito que não deve ser diferente de

```json
{
    "access_token": "....",
    "refresh_token": "...."
}
```

Podem só afirmar como será o retorno dos escopos de autenticação.

**Comment by ninrod** [comment]
@renato-farias, boa tarde. 

acredito que isso não faz parte da API Pix e sim de especificação que consta nas RFCs [6749](https://tools.ietf.org/html/rfc6749) e [6750](https://tools.ietf.org/html/rfc6750#section-4).
