### ISSUE TITLE
[Dúvida] Consultar Pix que contenha devoluções

### ISSUE THREAD

**Issue by GustavoBraz** [bacen/pix-api#140]
Boa tarde, prezados.

Ao consultar Pix são listadas todas as informações, inclusive um array contendo todas as devoluções, certo?
Por exemplo, se houve uma devolução referente a um Pix feita pela API e outra devolução referente ao mesmo Pix feita no aplicativo, ambas devem constar na consulta? Tenho esta dúvida, pois no endpoint `GET /pix/{e2eid}` se houver devolução o campo id da devolução (que é gerado pelo cliente) aparece como required, e uma devolução que não foi gerada pela API não possui este id de devolução. Como ficaria este caso?

Muito obrigado.

**Comment by ninrod** [comment]
> Por exemplo, se houve uma devolução referente a um Pix feita pela API e outra devolução referente ao mesmo Pix feita no aplicativo, ambas devem constar na consulta?

Sim. 

> Tenho esta dúvida, pois no endpoint GET /pix/{e2eid} se houver devolução o campo id da devolução (que é gerado pelo cliente) aparece como required, e uma devolução que não foi gerada pela API não possui este id de devolução. Como ficaria este caso?

Nesse caso o PSP do recebedor fica livre para estabelecer um valor para este campo.

**Comment by franciscotfmc** [comment]
Será que o id não poderia ser opcional na resposta? (nesse caso, me parece fazer sentido nem retorná-lo)

**Comment by ninrod** [comment]
> Será que o id não poderia ser opcional na resposta? (nesse caso, me parece fazer sentido nem retorná-lo)

@franciscotfmc , não é que ele é "retornado", o problema é que ele faz parte do "path".
