### ISSUE TITLE
Dúvida - Array PIX - Response do método get/cob/txid

### ISSUE THREAD

**Issue by llatsch** [bacen/pix-api#142]
O Pagador, que aparece no array PIX, response do método get/cob/txid, corresponde a quem efetivamente realizou o pagamento certo? Que pode ser diferente do devedor.
O campo infopagador, também no mesmo array PIX, é um conjunto de informações que o próprio pagador pode preencher?

**Comment by ninrod** [comment]
@llatsch , bom dia.

>  O Pagador, que aparece no array PIX, response do método get/cob/txid, corresponde a quem efetivamente realizou o pagamento certo? Que pode ser diferente do deved

Correto. 

> O campo infopagador, também no mesmo array PIX, é um conjunto de informações que o próprio pagador pode preencher?

O campo infopagador é a resposta que o usúario pagador preenche quando instado a prencher alguma coisa em função do texto que consta em "solicitacaoPagador". 

Exemplo: 

solicitacaoPagador = "Preencha seu código de milhagens!"
infoPagador = "123456789".
