### ISSUE TITLE
[Dúvida] Entendimento do fluxo de geração de Cobrança pela SoftwareHouse/TefHouse

### ISSUE THREAD

**Issue by filipehcds** [bacen/pix-api#143]
Olá pessoal, poderiam confirmar pra mim se o meu entendimento quanto ao fluxo de geração de Cobrança através da API de Recebimentos PIX está correto?

Passo 1 - SoftwareHouse (De posso das credenciais do EC/Lojista) bate na API de Recebimentos PIX do PSP Recebedor para gerar a Cobrança
Passo 2 - PSP Recebedor gera a Cobrança e associa à uma URL (location) e devolve as informações da Cobrança juntamente com a URL (location)
Passo 3 - SoftwareHouse utiliza a URL (location) para geração do QrCode Dinãmico e apresenta a imagem em um terminal/monitor/etc..
Passo 4 - Usuário Pagador efetuar a leitura do QrCode Dinâmico com o APP do PSP Pagador
Passo 5 - APP do PSP Pagador extrai a URL (location) da imagem e efetua um GET para recuperação do JWS (Possui o payload assinado pelo PSP Recebedor)
Passo 6 - APP do PSP Pagador efetua uma séria de verificações de segurança, como por exemplo, se o certificado atrelado naquele dominio está cadastrado no BACEN
Passo 7 - APP do PSP Pagador extrai a URL JWKS de dentro do parâmetro "jku" localizado no Header do JWS e efetua um GET para recuperação da chave publica
Passo 8 - APP do PSP Pagador utiliza a chave publica recuperada no passo anterior para verificar a assinatura do JWS
Passo 9 - APP do PSP Pagador utiliza a chave PIX contido dentro do Payload para bater no DICT e obter os dados da conta transacional daquela chave
Passo 10 em diante - APP do PSP Pagador exibe as informações de pagamento na tela do APP para o usuário Pagador confirmar.. e depois rola toda aquela troca de mensagens entre o PSP e o SPI..
...
...

O entendimento está correto?

**Comment by ninrod** [comment]
> O entendimento está correto?

Está correto.
