### ISSUE TITLE
Erro no Manual de Padrões para Iniciação do Pix versão 2.0

### ISSUE THREAD

**Issue by feinstein** [bacen/pix-api#144]
Na página 14 vemos a entrada 3.3 da tabela:

![image](https://user-images.githubusercontent.com/8120472/97645068-b60a2980-1a2a-11eb-83f7-526d4631d76c.png)

Onde aparece que o nome do devedor é *obrigatório*.

Mais na frente no texto na página 15 vemos:

>nome: [opcional] determina o nome da instituição ou pessoa a quem a cobrança
está endereçada. O preenchimento do campo devedor.nome é obrigatório se o campo
devedor.cpf ou o campo devedor.cnpj estiver preenchido.

Logo ele somente é obrigatório se um CPF ou um CNPJ foi fornecido. A tabela deve ser alterada para mostrar que o item nome é opcional, talvez com uma nota abaixo ou um "*" para indicar que é obrigatório somente em alguns casos.

**Comment by rubenskuhl** [comment]
Me parece que a falha pode ser estar listado como [opcional], quando é mandatório já que um entre CPF ou CNPJ obrigatoriamente está presente.

**Comment by feinstein** [comment]
Mas o texto diz que CPF ou CNPJ são opcionais também:

>Os campos aninhados sob o objeto devedor são opcionais

>Se o campo devedor.nome está preenchido, então deve existir ou um devedor.cpf ou um campo devedor.cnpj preenchido.

Não encontrei no texto onde fala que CPF ou CNPJ do devedor são obrigatórios. 

Nem faria sentido ao meu ver, pois se eu quiser colocar um QR Code dinâmico numa máquina de venda de refrigerante, para pegar o preço mais recente do refrigerante pela URL, como eu vou saber o CPF de quem vai querer comprar o refrigerante? Me pareceria um impedimento grande.

**Comment by rubenskuhl** [comment]
> Mas o texto diz que CPF ou CNPJ são opcionais também:
> 
> > Os campos aninhados sob o objeto devedor são opcionais
> 
> > Se o campo devedor.nome está preenchido, então deve existir ou um devedor.cpf ou um campo devedor.cnpj preenchido.
> 
> Não encontrei no texto onde fala que CPF ou CNPJ do devedor são obrigatórios.
> 
> Nem faria sentido ao meu ver, pois se eu quiser colocar um QR Code dinâmico numa máquina de venda de refrigerante, para pegar o preço mais recente do refrigerante pela URL, como eu vou saber o CPF de quem vai querer comprar o refrigerante? Me pareceria um impedimento grande.

Aí são casos de uso distintos. Então pode ser que na API 2.1 onde há reuso de location no QR-Code dinâmico isso possa ser endereçado. Para a cobrança dita online da API 2.0 alguém precisa estar sendo cobrado.

**Comment by feinstein** [comment]
Eu estou na metade do "Manual de Padrões para Iniciação do Pix versão 2.0" e não vi que é obrigatório ter um CPF no QR Code dinâmico, isso está definido então na API?

Me parece algo bem limitado, qual o motivo? No QR Code estático não há a necessidade de um CPF, logo não vejo por que um QR Code precisaria e outro está bem em não ter.

Eu fico pensando na burocracia extra de você querer ir num restaurante e o garçom pedir o teu CPF antes de gerar um Pix, claro que isso mata o uso do Pix, todo mundo vai achar um saco fazer um Pix. Nesse sentido somente usaríamos QR Code estáticos no dia a dia pela praticidade não precisar botar o CPF, mas com isso se perde funcionalidades interessantes do QR Code dinâmico.

**Comment by ninrod** [comment]
@feinstein , obrigado pela contribuição. Ficará mais claro na 2.1.

**Comment by feinstein** [comment]
@ninrod você pode adiantar aqui a explicação oficial?

**Comment by ninrod** [comment]
@feinstein , a 2.1.0 agrega uma diferenciação bastante explicita entre cobrança imediata e cobrança "com vencimento". 

Na cobrança imediata o devedor é opcional.

**Comment by feinstein** [comment]
Ok... E na 2.0?

**Comment by ninrod** [comment]
na 2.0 está assim:

Não é obrigatório o preenchimento do "devedor" na 2.0. 

Optando-se por preenchê-lo, deve-se obrigatoriamente preencher o nome e [CPF XOR CNPJ].

**Comment by feinstein** [comment]
Perfeito, obrigado.
