### ISSUE TITLE
[Dúvida] Requisitos e como ter acesso à API?

### ISSUE THREAD

**Issue by renaro** [bacen/pix-api#145]
Gostaria de prover um serviço para PF.
Entendi que existem duas maneiras de acessar a API:
 - Se tornar um `Provedores de Serviços de Tecnologia da Informação (PSTI)`
 -  Utilizar um "proxy/terceiro" que ja tenha acesso a rede do sistema financeiro (RSFN) e pagar uma taxa por isso.

Nao encontrei porém a documentação de como se tornar um PSTI e quais os requisitos.

Onde posso encontro tais informações?
Existe alguma outra forma gratuita de acessar a RSFN?

**Comment by rubenskuhl** [comment]
O acesso à API definido neste repositório é para correntistas de PSPs cujos PSPs disponibilizem alguma API. 

O acesso às interfaces DICT, ICOM e ARQ é exclusivo dos PSPs, e esses PSPs podem ou não usar PSTIs para tanto. Ser um PSTI não te dá acesso a essas interfaces, só a prestar conectividade para os PSPs. Apenas os PSPs são autorizados pelo BACEN a utilizar essas interfaces, mesmo que usando conectividade e tecnologia dos PSTIs.

**Comment by osgregs** [comment]
Estou aguardando a API da GerenciaNet para saber o que vai poder ser utilizado

**Comment by ninrod** [comment]
> O acesso à API definido neste repositório é para correntistas de PSPs cujos PSPs disponibilizem alguma API.

> O acesso às interfaces DICT, ICOM e ARQ é exclusivo dos PSPs, e esses PSPs podem ou não usar PSTIs para tanto. Ser um PSTI não te dá acesso a essas interfaces, só a prestar conectividade para os PSPs. Apenas os PSPs são autorizados pelo BACEN a utilizar essas interfaces, mesmo que usando conectividade e tecnologia dos PSTIs.

exatamente. Obrigado @rubenskuhl
