### ISSUE TITLE
Endpoint de recuperação do payload JSON no contexto de um PSTI

### ISSUE THREAD

**Issue by reinaldoalkimim** [bacen/pix-api#146]
No contexto de um PSTI que oferte endpoints para participantes diretos, especificamente o endpoint utilizado pelo PSP do pagador para recuperar o payload JSON que representa uma cobrança, ele pode ser publicado no PSTI de forma apartada dos endpoints disponibilizadas para os participante diretos que realizam as integrações de mensagens do SPI e DICT? Visto que o acesso será público para o PSP do Pagador.

Neste caso, o endpoint de recuperação do payload JSON não poderia utilizar uma VPN como nos endpoints do SPI e DICT disponibilizados por um PSTI para seus participantes diretos, correto?

Desde já agradeço explicações sobre este assunto.

**Comment by rubenskuhl** [comment]
O acesso ao payload JSON se dá pelo app do PSP pagador, não pela infra-estrutura RFSN do PSP pagador. Ele precisa estar exposto à Internet, e seguir o especificado no manual de segurança que inclui certificado EV (Extended Validation).

**Comment by ninrod** [comment]
> O acesso ao payload JSON se dá pelo app do PSP pagador, não pela infra-estrutura RFSN do PSP pagador. Ele precisa estar exposto à Internet, e seguir o especificado no manual de segurança que inclui certificado EV (Extended Validation).

Exatamente. Obrigado @rubenskuhl .
