### ISSUE TITLE
[Dúvida] PIX automatizados via sistema

### ISSUE THREAD

**Issue by wzomer** [bacen/pix-api#147]
Está previsto ou existe alguma forma de ser automatizado um pagamento do PIX? Pelo que pude entender pela definição atual o pagamento de um PIX é sempre algo feito manualmente por um indivíduo.

Exemplo: automatizar via sistema uma transferência PIX via chave do DICT.

**Comment by rubenskuhl** [comment]
Essa previsão de padronização é prevista para o papel Iniciador de Pagamento no Open Banking. 
Por enquanto, as instituições podem ofertar APIs de pagamento não padronizadas, pois não há padrão.
