### ISSUE TITLE
[Dúvida] Motivo de negativa na consulta de devolução PIX

### ISSUE THREAD

**Issue by cinrcazangi** [bacen/pix-api#148]
Na consulta de uma devolução PIX, caso o status da devolução seja "NAO_REALIZADO" por qualquer motivo, não há no payload de resposta um motivo da negativa. 

Como o cliente da API saberá o motivo após ter recebido a resposta inicial como "EM_PROCESSAMENTO", visto que este status é justamente para permitir um processamento assíncrono da requisição?

**Comment by ninrod** [comment]
@cinrcazangi , obrigado pela contribuição. Estamos analisando para a 2.1.0.

**Comment by ninrod** [comment]
@cinrcazangi , já está na master.
