### ISSUE TITLE
Location

### ISSUE THREAD

**Issue by ikenofh** [bacen/pix-api#149]
Na resposta da criação de cobrança (POST /cob/{txid}), o PSP é sempre obrigado a retornar a URL de consulta da cobrança  no objeto "location"?
Ou ele só é obrigado a retornar o "location" se enviarmos no request o objeto "loc"?

**Comment by rubenskuhl** [comment]
> Na resposta da criação de cobrança (POST /cob/{txid}), o PSP é sempre obrigado a retornar a URL de consulta da cobrança no objeto "location"?
> Ou ele só é obrigado a retornar o "location" se enviarmos no request o objeto "loc"?

A criação de cobrança usa um método PUT, não um método POST. Um método PUT só pode omitir location na resposta se o objeto criado tiver a mesma URI da chamada de criação.

**Comment by ninrod** [comment]
@ikenofh , bom dia.

o loc.location sempre deve estar preenchido no retorno do `PUT /cob/{txid}`. 

A semântica é que se o usuário não especificar, o PSP cria um loc.location. Se o usúario especificar um loc.id, aí utiliza-se o loc.location associado a este loc.id. 

Com relação ao location "HTTP location" e não ao location da cobrança, é o que o @rubenskuhl disse.
