### ISSUE TITLE
Webhook mTLS authentication 

### ISSUE THREAD

**Issue by renato-farias** [bacen/pix-api#15]
Na spec informa que a forma de autenticação entre o PSP Recebedor e o gateway deverá ser realizado utilizando mTLS, mas não está claro quem irá prover a chave e o certificado para realizar está autenticação. Essa autenticação deverá ser definida pelo PSP Recebedor?

**Comment by rubenskuhl** [comment]
O que está no manual de iniciação de pagamentos é usar ou uma CA própria do PSP ou CAs de mercado reconhecidas. 
Numa estrutura de PKI a chave privada é sempre da parte e apenas as chaves públicas equivalentes são assinadas pelas respectivas CAs.

**Comment by ninrod** [comment]
@renato-farias , boa tarde. 

> Na spec informa que a forma de autenticação entre o PSP Recebedor e o gateway deverá ser realizado utilizando mTLS, mas não está claro quem irá prover a chave e o certificado para realizar está autenticação. Essa autenticação deverá ser definida pelo PSP Recebedor?

exatamente.
