### ISSUE TITLE
Roadmap pix-api

### ISSUE THREAD

**Issue by rodrigonunes100** [bacen/pix-api#150]
Existe algum roadmap ou data de liberação da release pix api 2.1.0. Todos PSPs recebedores que obtive contato até agora, só liberarão suas respectivas api pix após a liberação da pix api 2.1.0 release pelo BACEN. Obrigado.

**Comment by rubenskuhl** [comment]
Há duas versões mencionadas pelo BACEN como a caminho: 2.0.1 e 2.1.0. A 2.0.1 deve ser a versão preferida para lançamento, e a 2.1.0 com algum prazo de implantação após o release. 

Os PSPs com que tenho tido contato não estão se limitando à 2.1.0 e estão mirando 2.0.x. Eu me pergunto se essa tentativa de sequenciar à versão 2.1.0 não é uma tentativa de justificar atrasos na implementação da API, tentando repassar a culpa.

**Comment by renatofrota** [comment]
> Há duas versões mencionadas pelo BACEN como a caminho: 2.0.1 e 2.1.0. A 2.0.1 deve ser a versão preferida para lançamento, e a 2.1.0 com algum prazo de implantação após o release.
> 
> Os PSPs com que tenho tido contato não estão se limitando à 2.1.0 e estão mirando 2.0.x. Eu me pergunto se essa tentativa de sequenciar à versão 2.1.0 não é uma tentativa de justificar atrasos na implementação da API, tentando repassar a culpa.

Não acho que é um repasse de culpa por parte dos PSPs. O Pix vai começar a funcionar amanhã para clientes selecionados. Eu acho, inclusive, que a API andou (e ainda está) sofrendo alterações em um ritmo bastante incomum para um produto prestes a ter seu release público. Qualquer Product Owner de um projeto que envolve tantos players estaria bastante nervoso com a [in|e]stabilidade a essa altura.

**Comment by rodrigonunes100** [comment]
@rubenskuhl , existe alguma lista de PSPs que estão liberando suas respectivas PIX API ? , seja para  sandbox, ou seja para produção ?  Obrigado.

**Comment by rubenskuhl** [comment]
> @rubenskuhl , existe alguma lista de PSPs que estão liberando suas respectivas PIX API ? , seja para sandbox, ou seja para produção ? Obrigado.

Neste tópico eu postei e atualizei uma lista de quem disse que teria Pix API:
https://github.com/bacen/pix-api/issues/76

**Comment by masyaf** [comment]
@rubenskuhl  você tem conhecimento de algum PSP que tenha a API aberta ao público? Que não seja necessário enviar e-mail solicitando.

**Comment by rubenskuhl** [comment]
> @rubenskuhl você tem conhecimento de algum PSP que tenha a API aberta ao público? Que não seja necessário enviar e-mail solicitando.

Como a API usa mTLS e o OAuth, de qualquer forma algum procedimento de onboarding é necessário. Mas nenhum tem pedido assinatura de contrato ou compromisso comercial, no máximo NDA.

**Comment by ninrod** [comment]
> Existe algum roadmap ou data de liberação da release pix api 2.1.0

Prezados, não tenho autorização para expor uma data. 

Recomendo buscar o DECEM para obter alguma posição oficial.
