### ISSUE TITLE
Formato dos dados recebidos no Webhook

### ISSUE THREAD

**Issue by feinstein** [bacen/pix-api#152]
Lendo a a API e o Manual de Padrões para Iniciação do Pix versão 2.0, não consigo ver um exemplo de como deve ser o formato dos dados que o destino do webhook ira receber.

Esse padrão está definido em algum lugar ou ainda está por definir?

Se não fui claro: estou querendo desenvolver um servidor que irá receber mensagens por meio de webhooks. Porém como não consigo achar uma documentação que aponte qual é o formato dessas mensagens, não consigo preparar o servidor para desserializar os avisos dos Pix recebidos.

**Comment by rubenskuhl** [comment]
A visão HTML da API confunde às vezes. Se você olhar a versão JSON, lá tem a descrição de array de Pix Recebidos, que é o informado para o Webhook. O que tem sido mais prático para mim é abrir o JSON no Firefox, que faz um bom trabalho de "beautifying" do JSON. 

Em resumo, o Webhook recebe um array de 1 ou mais Pix.

**Comment by feinstein** [comment]
Eu joguei o yaml no editor do swagger e não tinha nada lá mesmo.

Obrigado @rubenskuhl.

**Comment by feinstein** [comment]
@rubenskuhl onde voce ta pegando esse JSON? Você diz já num webhook funcionando? Eu ainda não tenho um funcionando com um PSP, ainda estou escolhendo um PSP.

**Comment by rubenskuhl** [comment]
> @rubenskuhl onde voce ta pegando esse JSON? Você diz já num webhook funcionando? Eu ainda não tenho um funcionando com um PSP, ainda estou escolhendo um PSP.

Cada release tem 5 arquivos, um deles o JSON. Por exemplo, para a release 2.0.0:
https://github.com/bacen/pix-api/releases/download/2.0.0/spec.json

**Comment by feinstein** [comment]
Ah, ok eu não vi o release, obrigado!

**Comment by ninrod** [comment]
obrigado @rubenskuhl
