### ISSUE TITLE
Disponibilização de Url de QR code dinâmico ou JWS válido para homologação

### ISSUE THREAD

**Issue by jocimarcan** [bacen/pix-api#154]
Prezados,

Há alguma URL de QR code dinâmico com resposta JWS válido que possa ser disponibilizada? Alguém já está gerando QR code dinâmico?
Ou ainda, há algum exemplo de JWS, com parâmetros jku e jwk set válidos, que siga o mesmo formato estipulado no manual de segurança?

**Comment by SeanWykes** [comment]
O Alexandre Mota está juntando dados válidos, de vários PSPs, para uso em testes. Dê uma olhada no
https://github.com/alexandremot/compartilhamento-dados-pix

Lá tem uma pasta de qr-codes dinâmicos, contendo strings e tbm bitmaps. Aí, é só puxar do servidor.

Montei tbm uma ferramenta online para testes de QR-CODE PIX, que por enquanto só funciona no chrome. Tu cola o QR como string e ela desmonta QR-CODES, faz uma validação meia-boca e ainda tem botão para buscar e abrir o payload. Ainda é um "work in progress" ..

https://pix.nascent.com.br/tools/pix-qr-decoder/

Talvez ajude.

**Comment by jocimarcan** [comment]
@SeanWykes Obrigado! Com certeza vai ajudar muito na homologação
