### ISSUE TITLE
Preview dos Breaking Changes da Release 2.1

### ISSUE THREAD

**Issue by feinstein** [bacen/pix-api#155]
Tenho ouvido sobre a futura versão 2.1 da API e me parece que haverão breaking changes, como por exemplo a remoção do CPF e nome do pagador no array de Pix.

Como muitos de nós estamos desenvolvendo sistemas agora baseados na versão 2.0, breaking changes na 2.1 podem ser significativos e gerar muito retrabalho em alguns poucos meses.

Vocês poderiam por favor listar aqui quais as Breaking Changes sendo contempladas e quais já são definitivas, para que alguém desenvolvendo na versão 2.0 não seja pego de surpresa?

**Comment by ninrod** [comment]
@feinstein , vamos liberar a 2.1.0-RC5 juntamente com um changelog. O caso do pix.pagador não está decidido ainda.

**Comment by feinstein** [comment]
@ninrod tem data pra esse release? Ou uma expectativa?

**Comment by rubenskuhl** [comment]
> @feinstein , vamos liberar a 2.1.0-RC5 juntamente com um changelog. O caso do pix.pagador não está decidido ainda.

Mas haverá uma 2.0.1 como antes sugerido ?

**Comment by ninrod** [comment]
> Mas haverá uma 2.0.1 como antes sugerido ?

está se pensando na linha de sair  tudo na  2.1.0 mesmo.

**Comment by rubenskuhl** [comment]
> > Mas haverá uma 2.0.1 como antes sugerido ?
> 
> está se pensando na linha de sair tudo na 2.1.0 mesmo.

Então a API para o GoLive é a 2.0.0 mesmo ?

**Comment by feinstein** [comment]
> Então a API para o GoLive é a 2.0.0 mesmo ?

Além disso, quanto tempo a 2.0.0 ficará válida?

**Comment by ninrod** [comment]
> Então a API para o GoLive é a 2.0.0 mesmo ?

Não necessariamente. Depende da velocidade com a qual publicarmos a 2.1.0. 

Para o golive poderia ser obrigatória a 2.1.0 somente com a função "cobrança imediata", que na prática, é mesma coisa que a 2.0.0. Não sei exatamente como o DECEM vai estabelecer o regramento. 

Em tempo, entendo a preocupação de vocês, sem dúvida.

**Comment by rubenskuhl** [comment]
> Não necessariamente. Depende da velocidade com a qual publicarmos a 2.1.0.
> 
> Para o golive poderia ser obrigatória a 2.1.0 somente com a função "cobrança imediata", que na prática, é mesma coisa que a 2.0.0. Não sei exatamente como o DECEM vai estabelecer o regramento.

A cobrança com vencimento/juros da 2.1.0 depende de nova versão do payload e de atualização dos apps dos PSPs pagadores para reconhecer e usar essa nova versão ? 

> Em tempo, entendo a preocupação de vocês, sem dúvida.

Algo a valorizar com uma definição rápida é a capacidade dos PSPs que já estão prontos para API; atrasos favorecem os PSPs que hoje estão atrasados. Num recurso opcional, o primeiro parece mais apropriado.

**Comment by franciscotfmc** [comment]
>Algo a valorizar com uma definição rápida é a capacidade dos PSPs que já estão prontos para API; atrasos favorecem os PSPs que hoje estão atrasados. Num recurso opcional, o primeiro parece mais apropriado.

Exatamente! Entendemos que o correto é o Go Live ser com a 2.0 mesmo, pois já atende diversos casos de uso. Inclusive, bater o martelo na 2.0 reconhece o esforço de todos os PSPs que correram atrás do prazo do 16/11.

**Comment by tuliospuri** [comment]
Perfeito, @franciscotfmc. Já tem PSP com a API pronta só aguardando o Go Live.

QR Code produção.
![2020-11-05 17_57_47-QR Code Generator](https://user-images.githubusercontent.com/11793072/98295838-d9842580-1f90-11eb-8457-5be2e623561e.png)

**Comment by ninrod** [comment]
> Algo a valorizar com uma definição rápida é a capacidade dos PSPs que já estão prontos para API; atrasos favorecem os PSPs que hoje estão atrasados. Num recurso opcional, o primeiro parece mais apropriado.

Certamente você tem um ponto @rubenskuhl.  

> Exatamente! Entendemos que o correto é o Go Live ser com a 2.0 mesmo, pois já atende diversos casos de uso. Inclusive, bater o martelo na 2.0 reconhece o esforço de todos os PSPs que correram atrás do prazo do 16/11. @ninrod

Ok, recado recebido. 

> A cobrança com vencimento/juros da 2.1.0 depende de nova versão do payload e de atualização dos apps dos PSPs pagadores para reconhecer e usar essa nova versão ?

Sim. 

Vejam que se lançada a 2.1.0, a "cobrança imediata", que é a que realmente está colocada na `2.0.0` não é afetada. (além de estabelecermos que tem que ser `v2` e não `v1`, nada muda. E, talvez, o pix.pagador, ser removido, a ver. Mas era um campo opcional de qualquer maneira).

**Comment by feinstein** [comment]
pix.pagador era um campo opcional a ser incluído no QR Code, mas pelo o que eu entendi pela API ele sempre é enviado quando um webhook é chamado.

**Comment by rubenskuhl** [comment]
> pix.pagador era um campo opcional a ser incluído no QR Code, mas pelo o que eu entendi pela API ele sempre é enviado quando um webhook é chamado.

Na cobrança é o cob.devedor, no Pix que liquida a cobrança é o pix.pagador. Na 2.0.0 obrigatório, e tema do issue #153 .

**Comment by feinstein** [comment]
Exato.

**Comment by ninrod** [comment]
> Na cobrança é o cob.devedor, no Pix que liquida a cobrança é o pix.pagador. Na 2.0.0 obrigatório, e tema do issue #153 .

@rubenskuhl , na 2.0.0 o pix.pagador não é obrigatório, é __[opcional](https://github.com/bacen/pix-api/blob/9cba3cb1589512b694a8d92a9408aed44a3ab0af/openapi.yaml#L1000)__.

**Comment by feinstein** [comment]
@ninrod é opcional ao PSP enviar o pix.pagador ao webhook?

**Comment by ninrod** [comment]
@feinstein , na 2.0.0 é a assim que está.

**Comment by feinstein** [comment]
Eu não tinha entendido que haviam campos opcionais ao PSP decidir de envia ou não, acho que isso causa inconsistências ao se mudar de PSP, mas ok, entendo a liberdade que querem dar.

**Comment by ninrod** [comment]
> Eu não tinha entendido que haviam campos opcionais ao PSP decidir se envia ou não, acho que isso causa inconsistências ao se mudar de PSP, mas ok, entendo a liberdade que querem dar.

Concordo. teria que ficar claro em que situação a informação vem ou não. Mais um motivo para revermos a questão.

**Comment by rubenskuhl** [comment]
> > Eu não tinha entendido que haviam campos opcionais ao PSP decidir se envia ou não, acho que isso causa inconsistências ao se mudar de PSP, mas ok, entendo a liberdade que querem dar.
> 
> Concordo. teria que ficar claro em que situação a informação vem ou não. Mais um motivo para revermos a questão.

+1 para homogeneidade. Isso só deveria ser opcional se o pagador tiver a opção de enviar ou não, não por decisão dos PSPs pagador e/ou recebedor.

**Comment by feinstein** [comment]
E o Manual do Pix devia ter isso incluído.

**Comment by ninrod** [comment]
Prezados: https://github.com/bacen/pix-api/blob/master/changelog.md

**Comment by feinstein** [comment]
@ninrod o Manual de Padrões para Iniciação do Pix e seus anexos vão ser atualizados pra refletir essas mudanças? Por exemplo, não há qualquer menção nele quanto a o que é um "location".

**Comment by ninrod** [comment]
> @ninrod o Manual de Padrões para Iniciação do Pix e seus anexos vão ser atualizados pra refletir essas mudanças? Por exemplo, não há qualquer menção nele quanto a o que é um "location".

Boa noite @feinstein. Já está [atualizado](https://www.bcb.gov.br/content/estabilidadefinanceira/pix/Regulamento_Pix/II-ManualdePadroesparaIniciacaodoPix-versao2-1.pdf) e há várias menções.

**Comment by feinstein** [comment]
Perfeito @ninrod. Boa noite e bom feriado.
