### ISSUE TITLE
Possivel issue na 2.1.0-rc-5

### ISSUE THREAD

**Issue by rubenskuhl** [bacen/pix-api#158]
A consulta de webhooks cadastrados está usando scope payloadlocation.read , mas me parece que deveria ser webhook.read. 

Consultar webhooks cadastrados.
Endpoint para consultar webhooks cadastrados

AUTHORIZATIONS:
OAuth2 (payloadlocation.read)

**Comment by ninrod** [comment]
@rubenskuhl , certo obrigado.

**Comment by ninrod** [comment]
Corrigido. Obrigado @rubenskuhl
