### ISSUE TITLE
Múltiplos Webhooks

### ISSUE THREAD

**Issue by HMPannuti** [bacen/pix-api#16]
Um determinado usuário recebedor pode utilizar sistemas de mais de um fornecedor, integrados a API de Recebimento do mesmo PSP, para receber Pix (por exemplo, um sistema utilizado para os frentes de caixa, de loja física; e outro utilizado para e-commerce).
Assim, os 2 sistemas podem configurar diferentes URLs para receber as notificações de Pix realizados via Webhook.

Considerando que os 2 sistemas autentifiquem-se perante o PSP com credenciais diferentes, porém ambas associadas à mesma conta transacional, como deve ser o comportamento do envio dos Webhooks?

1 - Cada URL de Webhook estará associada a uma credencial, de modo que cada sistema receberá apenas os Pix associados à cobranças iniciadas por ele mesmo.

2 - Ambos os sistemas receberão todos os Pix realizados, nos 2 sistemas.

Entendo que será o cenário 2, já que o primeiro cenário tem várias limitações. Por exemplo, não seria possível identificar para qual URL deveriam ser enviados Pix não associados a cobranças.

**Comment by rubenskuhl** [comment]
Eu acho que algo mais simples é ter contas transacionais distintas, mesmo que com o mesmo PSP, e ter uma URL de webhook para cada uma delas como "conta1.exemplo.com.br" e "conta2.exemplo.com.br" e ter credenciais distintas.

**Comment by ninrod** [comment]
@HMPannuti , boa tarde. 

Entendo que a resposta do @rubenskuhl é interessante. Se duas contas transacionais não resolver, você pode escrever um software cliente que particione os "txids" e realize o "balanceamento" entre os dois sistemas.

**Comment by HMPannuti** [comment]
@ninrod , sim, entendo que, do lado do usuário recebedor, a solução mais simples seria utilizar contas transacionais diferentes, conforme a resposta do @rubenskuhl.

Mas, do ponto de vista do PSP Recebedor, qual deve ser o comportamento, caso seja registrada mais de uma URL de um webhook para a mesma conta transacional? 
Ele deve replicar as notificações em todas as URL?
Deve negar a criação da segunda URL?
Ou outro comportamento?

**Comment by ninrod** [comment]
> Mas, do ponto de vista do PSP Recebedor, qual deve ser o comportamento, caso seja registrada mais de uma URL de um webhook para a mesma conta transacional?

Isso é impossível, por design. Apenas uma URL por vez pode ser cadastrada. Em outras palavras, olhando para um ponto específico na linha do tempo, uma e apenas uma URL está cadastrada por usuário recebedor por PSP recebedor.

**Comment by ninrod** [comment]
Pessoal, posso responder mais alguma questão?
