### ISSUE TITLE
[Dúvida] BRCode - Documentação 2.0.0 x 2.0.1 - Char  `@` no E-mail

### ISSUE THREAD

**Issue by fbbergamo** [bacen/pix-api#161]
Olá, Fiz uma implementação baseada no documento do BRCode 2.0.0 para o QRCode Estático  e tenho duas dúvidas:

1)  Lendo a 2.0.1 fique na dúvida se o email ainda precisa trocar o  `@` por espaço em branco na geração do código BRCode, e tambem comparando o QRCode com alguns bancos vi que alguns estão incluindo o `@`

2) A documentação 2.0.1 é a mais atualizada? onde consigo ver os ultimos lançamentos? Só encontrei por meio do google.

**Comment by ninrod** [comment]
> Lendo a 2.0.1 fique na dúvida se o email ainda precisa trocar o @ por espaço em branco na geração do código BRCode, e tambem comparando o QRCode com alguns bancos vi que alguns estão incluindo o @

Não é preciso. Ver versão 2.0.1

> A documentação 2.0.1 é a mais atualizada? onde consigo ver os ultimos lançamentos? Só encontrei por meio do google.

Sim. Você encontra [aqui](https://www.bcb.gov.br/estabilidadefinanceira/arranjosintegrantesspb)
