### ISSUE TITLE
[Dúvida] no [BR Code] - Onde encontrar o documento "manual do BR Code"?

### ISSUE THREAD

**Issue by feinstein** [bacen/pix-api#162]
O Manual de Padrões para Iniciação do Pix versão 2.1 menciona o "manual do BR Code", mas olhando os documentos [aqui](https://www.bcb.gov.br/estabilidadefinanceira/participantespix), não consigo encontrar esse manual.

Eu gostaria de consultar o manual para ver se os caracteres são ASCII ou Unicode, já que o QR Code possui limite de tamanho e não sei se "ç" é permitido ou se ocupa 1 caractere ou 2.

**Comment by ninrod** [comment]
@feinstein, você encontra [aqui](https://www.bcb.gov.br/estabilidadefinanceira/arranjosintegrantesspb)

**Comment by feinstein** [comment]
@ninrod está na versão 2.0.1, ele vai seguir a API e ser lançado um 2.1 ou o versionamento dele é independente?

**Comment by rubenskuhl** [comment]
> @ninrod está na versão 2.0.1, ele vai seguir a API e ser lançado um 2.1 ou o versionamento dele é independente?

Como o BR Code se aplica a qualquer arranjo de pagamento operando no Brasil, independente de ser Pix ou não, eu entendo o versionamento dele como independente.

**Comment by ninrod** [comment]
> Como o BR Code se aplica a qualquer arranjo de pagamento operando no Brasil, independente de ser Pix ou não, eu entendo o versionamento dele como independente.

Exatamente. obrigado @rubenskuhl
