### ISSUE TITLE
Dúvidas - Endpoint Get/Cob/Txid

### ISSUE THREAD

**Issue by llatsch** [bacen/pix-api#164]
O campo devedor, disponível no response do endpoint Get/Cob/Txid, está meio estranho, em uma das opções eu tenho tanto CPF como CNPJ como obrigatórios.
É isso mesmo?

**Comment by rubenskuhl** [comment]
Não é a questão de que se o campo existe, aí ou um CPF ou CNPJ é obrigatório ? Mas o campo pode não existir.

**Comment by ninrod** [comment]
@llatsch , boa tarde. É um ou outro: 

![image](https://user-images.githubusercontent.com/8352747/98576087-cfb43800-2298-11eb-8ea2-fbff07f67cdc.png)
