### ISSUE TITLE
Endpoint - Get/PIX, campo txIdPresente

### ISSUE THREAD

**Issue by llatsch** [bacen/pix-api#165]
Em que situação o TXId não estaria presente? Para o cenário de escolhermos disponibilizar somente os endpoints compatíveis com a versão 2.0.0 em 16/11, temos algum caso de uso?

**Comment by rubenskuhl** [comment]
Um QR-Code estático pode não ter TxID, uma transferência manual também não. 
Eu recomendo dar suporte por escopos da versão 2.1.0 e não para a versão 2.0.0; por exemplo, não ter (ainda) os escopos cobv (cobrança com vencimento), lotecobv (lote de cobranças com vencimento) e payloadlocation (QR-Code dinâmico com reuso de location), mas os escopos suportados (pix, cob e webhook no caso acima) serem suportados exatamente como na versão corrente no lançamento, que é a 2.1.0.

**Comment by ninrod** [comment]
> Um QR-Code estático pode não ter TxID, uma transferência manual também não.

@llatsch , é o que o @rubenskuhl disse.
