### ISSUE TITLE
Dúvida sobre headers CORS

### ISSUE THREAD

**Issue by SeanWykes** [bacen/pix-api#166]
Caros, não encontrei nenhuma recomendação sobre a necessidade de um PSP retornar os headers "CORS" do endpoint de recuperação do payload PIX.

Estou vendo que alguns PSPs não estão retornando o "Access-Control-Allow-Origin" header, o que significa (até onde observei e pesquisei) que o browser, rodando JS, não será capaz de recuperar o payload. 

Perdi um tempo com isso, pois ao colar o URL no browser, ele consegue pegar o JWS de boas. Só no JS mesmo que falha e imagino que o webview mobile sofrerá do mesmo problema, embora ainda não testei.

1. Alguém por aqui consegue me indicar uma forma de contornar isso?
2. Senão tem jeito, penso ser interessante incluir alguma recomendação ou mesmo obrigatoriedade nos manuais.

Exemplo - https://qrcodepix-h.bb.com.br/pix/766b3e9c-7d5b-4a2c-b912-6f34cb4b0f4c

**Comment by ninrod** [comment]
@SeanWykes , obrigado pela contribuição. 

Vamos verificar.

**Comment by franciscotfmc** [comment]
Interessante esse caso aí @SeanWykes. Não havia pensado nesse problema.

Uma solução, por hora, seria você buscar o payload via backend mesmo _(apesar de que tá fazendo sentido o header que você mencionou)_.

**Comment by ninrod** [comment]
@SeanWykes , no caso do "webview", não é que você esteja exatamente "em um website". Você está em um aplicativo que escolhe utilizar um browser embutido para apresentar a interface. Qual seria o "origin" nesse caso? 

No caso do internet banking, a chamada teria que ocorrer via backend mesmo.

**Comment by franciscotfmc** [comment]
Verdade @ninrod , até pelas validações de segurança necessárias. (envolve até o ARQ)

**Comment by SeanWykes** [comment]
@ninrod @franciscotfmc Com certeza em muitos casos será pelo backend, inclusive pelas questões de segurança na validação do JWS, e pela lista de domínios ativados. 

No entanto, do jeito que está a configuração de alguns PSPs, parece que fica impossibilitado o acesso através de JS, seja pelo browser seja por um aplicativo móvel híbrido (webview + nativo). 

Na prática, essa questão de CORS surgiu quando foi incluir a funcionalidade de busca do payload em uma ferramenta web (SPA) que estou criando, para testes, geração e validação de QR-EMV PIX e payloads. Não é um caso "real" de PSP pagador per se.

Obrigado.

**Comment by SeanWykes** [comment]
> @SeanWykes , no caso do "webview", não é que você esteja exatamente "em um website". Você está em um aplicativo que escolhe utilizar um browser embutido para apresentar a interface. Qual seria o "origin" nesse caso?

Não sei exatamente o que o webview coloca como origem, depende da origem do js sendo executado pelo jeito, mas AFAIK, o android webview implementa CORS ao acessar sites http por AJAX/fetch, e bloqueia se não receber o header correto. No caso hipotético, poderia pensar em um QR lido pela camera do dispositivo, acessada através de PhoneGap ou Ionic ou algum framework de app híbrido, com o QR parser escrita em JS .. as validações de JWS feitas com JS (jose-js) etc.

**Comment by franciscotfmc** [comment]
> Não sei exatamente o que o webview coloca como origem, depende da origem do js sendo executado pelo jeito, mas AFAIK, o android webview implementa CORS ao acessar sites http por AJAX/fetch, e bloqueia se não receber o header correto. No caso hipotético, poderia pensar em um QR lido pela camera do dispositivo, acessada através de PhoneGap ou Ionic ou algum framework de app híbrido, com o QR parser escrita em JS .. as validações de JWS feitas com JS (jose-js) etc.

Nesse caso, como você garantiria a validação dos domínios ativos?

**Comment by SeanWykes** [comment]
> > Não sei exatamente o que o webview coloca como origem, depende da origem do js sendo executado pelo jeito, mas AFAIK, o android webview implementa CORS ao acessar sites http por AJAX/fetch, e bloqueia se não receber o header correto. No caso hipotético, poderia pensar em um QR lido pela camera do dispositivo, acessada através de PhoneGap ou Ionic ou algum framework de app híbrido, com o QR parser escrita em JS .. as validações de JWS feitas com JS (jose-js) etc.
> 
> Nesse caso, como você garantiria a validação dos domínios ativos?

Mantendo a ideia de um app hipotético, pode baixar uma lista de domínios do backend (contendo hashes dos certs válidos) .. ou enviar o nome do domínio para validação a algum API .. etc. 

No fundo, o meu questionamento, ao me deparar com o comportamento não-CORS de alguns PSPs, é se é interessante restringir ou não as possíveis soluções .. em uma era de fintech / agil / mobile / serverless. 

Pessoalmente, entendo e concordo que será sempre melhor validar a segurança no backend .. e que a resposta para este caso poderá ser "faça a busca do payload no URL" .. inclusive implementamos desta forma (backend) nos sistemas de PSP já em deploy do soft-opening.
[]s
