### ISSUE TITLE
Endpoint PSP Recebedor e Autenticação

### ISSUE THREAD

**Issue by ikenofh** [bacen/pix-api#17]
Boa tarde Srs!
Duas perguntas:

1. A chamada para a API de Cobrança (/cob) será para o endpoint do PSP Recebedor? Ou a chamada deverá ser feita para o endpoint do Bacen, que ficará responsável por rotear para o PSP correspondente?

2. Como será a dinâmica dos tokens para autenticação? Haverá um token por chave do DICT? No caso dos Gateways e TEF, haverá uma forma de transacionar em nome do varejista?

Abcs.

**Comment by ninrod** [comment]
boa tarde @ikenofh 

> A chamada para a API de Cobrança (/cob) será para o endpoint do PSP Recebedor? Ou a chamada deverá ser feita para o endpoint do Bacen, que ficará responsável por rotear para o PSP correspondente?

A API Pix será servida pelo PSP recebedor. 

> Como será a dinâmica dos tokens para autenticação? Haverá um token por chave do DICT? No caso dos Gateways e TEF, haverá uma forma de transacionar em nome do varejista?

Eu não entendi muito bem a pergunta. A autenticação está estabelecida como sendo mTLS + Oauth2. Então funciona assim: 

- Em KYC, o usuário recebedor estabelece quais são os elementos de software que se conectarão à API do PSP recebedor. No caso mais simples, é um cliente só. 
- O PSP cria um client_id e conforme a necessidade, estabelece uma vinculação com os escopos. 
- O PSP entrega um client_id e um client_secret ao usuário recebedor. 
- O PSP estabelece os certificados que serão utilizados para fechar o canal mTLS. 
- O Usuário recebedor, de posse desses elementos, entrega-os para a automação comercial, que realiza as configurações necessárias. 
- O usuário passa a utilizar a API Pix normalmente para gerar cobranças e receber Pix. 

Está mais claro ou posso responder alguma questão adicional?

**Comment by amilcarbra** [comment]
Pelo perfil do público envolvido, não será perigoso circular o client id pelo mercado? Não seria mais adequado um client_id para a automação vinculado a chave do recebedor no backend do PSP? Ou fica a critério do PSP trabalhar com um client_id único para a automação?

Obrigado,

Amilcar

**Comment by amilcarbra** [comment]
> boa tarde @ikenofh
> 
> > A chamada para a API de Cobrança (/cob) será para o endpoint do PSP Recebedor? Ou a chamada deverá ser feita para o endpoint do Bacen, que ficará responsável por rotear para o PSP correspondente?
> 
> A API Pix será servida pelo PSP recebedor.
> 
> > Como será a dinâmica dos tokens para autenticação? Haverá um token por chave do DICT? No caso dos Gateways e TEF, haverá uma forma de transacionar em nome do varejista?
> 
> Eu não entendi muito bem a pergunta. A autenticação está estabelecida como sendo mTLS + Oauth2. Então funciona assim:
> 
> * Em KYC, o usuário recebedor estabelece quais são os elementos de software que se conectarão à API do PSP recebedor. No caso mais simples, é um cliente só.
> * O PSP cria um client_id e conforme a necessidade, estabelece uma vinculação com os escopos.
> * O PSP entrega um client_id e um client_secret ao usuário recebedor.
> * O PSP estabelece os certificados que serão utilizados para fechar o canal mTLS.
> * O Usuário recebedor, de posse desses elementos, entrega-os para a automação comercial, que realiza as configurações necessárias.

Pelo perfil do público envolvido, não será perigoso circular o client id pelo mercado? Não seria mais adequado um client_id para a automação vinculado a chave do recebedor no backend do PSP? Ou fica a critério do PSP trabalhar com um client_id único para a automação?

> * O usuário passa a utilizar a API Pix normalmente para gerar cobranças e receber Pix.
> 
> Está mais claro ou posso responder alguma questão adicional?

Abs

Amilcar

**Comment by ninrod** [comment]
> Pelo perfil do público envolvido, não será perigoso circular o client id pelo mercado? Não seria mais adequado um client_id para a automação vinculado a chave do recebedor no backend do PSP? Ou fica a critério do PSP trabalhar com um client_id único para a automação?

Cabe ressaltar que não é apenas o client_id + secret mas também o canal mTLS que estabelece a segurança. Além disso, nada impede de se fechar, em KYC, um conjunto de chaves específicas restrito para utilização por parte do usuário recebedor: nada fora desse conjunto de chaves poderia ser utilizado em `/cob/{txid}`.

**Comment by ikenofh** [comment]
Obrigado pela resposta @ninrod !
