### ISSUE TITLE
[Dúvida] Formato QrCode padrão BR Code (Ordem IDs)

### ISSUE THREAD

**Issue by etanamati** [bacen/pix-api#174]
Gostariamos de tirar uma dúvida com relação a ordem dos campos presentes no QRCode padrão BR Code.
Nos QRCodes gerados no padrão BR Code há alguma regra que determina se os IDs devem seguir uma ordem? Ou a ordem não é relevante? 

Exemplo considerando a ordem (espaços e quebras de linha extras):

```
0002 01
0414 12345678901234
2658
 0014 BR.GOV.BCB.PIX
 0136 123e4567-e12b-12d1-a456-426655440000
2730
 0012 BR.COM.OUTRO
 0110 0123456789
5204 0000
5303 986
5406 123.45
5802 BR
5917 NOME DO RECEBEDOR
6008 BRASILIA
6108 70074900
6219
 0515 RP12345678-2019
8039
 0012 BR.COM.OUTRO
 0119 0123.ABCD.3456.WXYZ
6304 AD38
```

Exemplo sem considerar a ordem (espaços e quebras de linha extras):

```
0002 01
0414 12345678901234
2658
 0014 BR.GOV.BCB.PIX
 0136 123e4567-e12b-12d1-a456-426655440000
2730
 0012 BR.COM.OUTRO
 0110 0123456789
5303 986
5406 123.45
5204 0000
5802 BR
6008 BRASILIA
5917 NOME DO RECEBEDOR
6219
 0515 RP12345678-2019
6108 70074900
8039
 0012 BR.COM.OUTRO
 0119 0123.ABCD.3456.WXYZ
6304 5110
```

Ambos QRCodes são válidos?

Manual BR Code disponível em: [https://www.bcb.gov.br/estabilidadefinanceira/arranjosintegrantesspb](https://www.bcb.gov.br/estabilidadefinanceira/arranjosintegrantesspb)

**Comment by ninrod** [comment]
@etanamati , 

Neste ponto o Manual do BR Code segue o documento "EMV for QR codes: merchant presented mode". Você pode verificar esta informação diretamente lá.

**Comment by SeanWykes** [comment]
@etanamati Em principio, o único requisito é que na raiz do QR, o campo "00" deve vir em primeiro lugar e o campo "63" deve ser o último no QR. Quanto aos demais campos, não há necessidade de ordená-los. Observe que isso significa que quaisquer campos entre "64" e "99" devem estar ANTES do campo 63.

Dentro de um campo do tipo template (que contém outros campos) não há nenhum requisito de ordenação.

**Comment by ninrod** [comment]
@etanamati , se houver qualquer dúvida por favor não hesite em perguntar.

**Comment by etanamati** [comment]
Obrigado @ninrod @SeanWykes

**Comment by aluisioalves** [comment]
Estou com uma dúvida sobre que calculo ou qual informação tem na posição **62110507**, vale a pena ressaltar que estou utilizando Código da transferência.
00020126360014BR.GOV.BCB.PIX0114123456789123455204000053039865406366.675802BR5909ABCABCABC6012Araguaina-To **62110507** 15139936304D9E4
