### ISSUE TITLE
Software House criação de cobrança usando PIX?

### ISSUE THREAD

**Issue by fabiociaf** [bacen/pix-api#175]
Ola pessoal do PIX, 
Somos uma Software House, e queremos integrar em nosso PDV a opção de cobrança instantânea desse PIX.
Porem estamos com algumas duvidas, quem vai nos oferecer o serviços de homologação e o banco central ou os bancos para essas integração?

E no contexto fala desse link https://www.bcb.gov.br/estabilidadefinanceira/pagamentosinstantaneos porem ele direciona para o https://www.bcb.gov.br/estabilidadefinanceira/pix

Obrigado

**Comment by ninrod** [comment]
bom dia @fabiociaf 

> quem vai nos oferecer o serviços de homologação e o banco central ou os bancos para essas integração?

Os "bancos", chamamos na verdade de PSPs (Prestadores de serviço de pagamentos). 

Você precisa encontrar no mercado um (ou mais) PSP[s] "recebedor(es)" que implementará a API Pix conforme especificada neste repositório. A partir daí, você pode atender clientes (usuário recebedores, lojistas, vendedores, etc...) que detenham conta neste PSP. 

Como a API é padronizada, você encontrará poucas dificuldades para agregar mais de um PSP integrado ao seu software PDV. Alcançando assim, mais usuários recebedores. 

https://www.bcb.gov.br/estabilidadefinanceira/pix é o link correto, sim. 
Procure nesta página o botão "regulamentação relacionada ao Pix". Todos os documentos listados neste botão são interessantes para o entendimento do funcionamento do Pix. 

Boa sorte!

**Comment by fabiociaf** [comment]
Obrigado

**Comment by rubenskuhl** [comment]
@fabiociaf no issue #76 há uma lista de PSPs que informaram que vão ter API Pix.
