### ISSUE TITLE
Metodo Consultar lista de cobranças imediatas. 

### ISSUE THREAD

**Issue by amandaolmr** [bacen/pix-api#177]
Boa tarde!

Gostaria de saber como eu passo os parametros para a requisição GET ​/cob  

https://pix-h.example.com/api/v2/documento/ (os parametros como serão passados aqui?)

**Comment by ninrod** [comment]
@amandaolmr , boa tarde.

O domínio `example.com` é __[só um exemplo](https://www.iana.org/domains/reserved)__. 

API definida aqui deverá ser implementada pelos PSPs (exemplo: Bancos). 

Você, a integradora, deve procurar um PSP que esteja oferecendo implementação da API Pix conforme definida aqui neste repositório e deve procurar disparar suas chamadas contra os servidores deste PSP. 

Apenas reforçando: https://example.com não _funciona_ e __[dificilmente](https://tools.ietf.org/html/rfc2606#section-3)__ algum dia __[funcionará](https://tools.ietf.org/html/rfc6761#section-6.5)__.

**Comment by rubenskuhl** [comment]
@amandaolmr  no issue #76 há uma lista de PSPs que informaram que vão ter API Pix.

**Comment by amandaolmr** [comment]
Obrigada pela Ajuda pessoal!
