### ISSUE TITLE
API Pix: Status Removido pelo usuário recebedor

### ISSUE THREAD

**Issue by grazipellecchia** [bacen/pix-api#179]
Boa noite, por favor no revisar cobrança é possível alterar o status que foi removido pelo usuário recebedor ou removido pelo PSP para ativo?

Complementando, um QR dinâmico cuja data de expiração já foi ultrapassada e seu status está como removido pode ser revisado e com isso voltar a ficar ativo?

obrigada

**Comment by ninrod** [comment]
boa tarde @grazipellecchia 

> Boa noite, por favor no revisar cobrança é possível alterar o status que foi removido pelo usuário recebedor ou removido pelo PSP para ativo?

Não, é um status final.

> Complementando, um QR dinâmico cuja data de expiração já foi ultrapassada e seu status está como removido pode ser revisado e com isso voltar a ficar ativo?

Não, o status removido é final. Ultrapassar o timestamp de expiração não leva o status para "removido", continua ativo, só está "expirado". Pode-se alterar a expiração de um QR ativo.

**Comment by grazipellecchia** [comment]
> boa tarde @grazipellecchia 
> 
> 
> 
> > Boa noite, por favor no revisar cobrança é possível alterar o status que foi removido pelo usuário recebedor ou removido pelo PSP para ativo?
> 
> 
> 
> Não, é um status final.
> 
> 
> 
> > Complementando, um QR dinâmico cuja data de expiração já foi ultrapassada e seu status está como removido pode ser revisado e com isso voltar a ficar ativo?
> 
> 
> 
> Não, o status removido é final. Ultrapassar o timestamp de expiração não leva o status para "removido", continua ativo, só está "expirado". Pode-se alterar a expiração de um QR ativo. 
> 
> 

@ninrod muito obrigada. 
Ofertaram isso para um cliente nosso e realmente achamos estranho.
