### ISSUE TITLE
Pagamento único ou múltiplo

### ISSUE THREAD

**Issue by marcospharaujo** [bacen/pix-api#18]
Gostaria de validar o entendimento abaixo:

1 - A cobrança através de QRcode dinâmico terá o padrão de múltiplos pagamentos;
2 - Não está previsto para versão 2 da API a opção de pagamento único.

Exemplificando:
 - Pagamento único seria conforme é o boleto atualmente e caso alguém for fazer um segundo pagamento este seria recusado;
 - Múltiplos pagamentos. Todo mês seria pago a conta de energia através do mesmo QRcode, porém com dados atualizados relativos ao mês atual.

**Comment by ninrod** [comment]
boa tarde @marcospharaujo 

> 1 - A cobrança através de QRcode dinâmico terá o padrão de múltiplos pagamentos;

Não está correto. A cobrança através de QR dinâmico admite um único pagamento, no momento.

> 2 - Não está previsto para versão 2 da API a opção de pagamento único.

Correto.

> Pagamento único seria conforme é o boleto atualmente e caso alguém for fazer um segundo pagamento este seria recusado;

Correto. 

> Múltiplos pagamentos. Todo mês seria pago a conta de energia através do mesmo QRcode, porém com dados atualizados relativos ao mês atual.

Essa é uma outra questão que está sendo estudada. Seria na verdade tornar dinâmica a URL que está inscrita dentro do QR Code dinâmico. Seria como se a URL que está inscrita dentro do QR Code dinâmico fosse uma espécie de "vitrine" que é capaz de apresentar várias cobranças, cada uma delas identificada por um txid diferente, mas uma de cada vez, dependendo de como essa "vitrine" está configurada. 

Essa é uma possibilidade interessante e talvez entre na próxima versão. Essa é uma funcionalidade que seria interessante para o seu caso de uso? Pode detalhar um pouco mais?

**Comment by rubenskuhl** [comment]
Eu tenho a sensação de que o fato do QR-Code estático poder ter TxID, mesmo não sendo mandatório como no QR-Code dinâmico, resolve a maior parte de casos de uso de reapresentação.

**Comment by ninrod** [comment]
@rubenskuhl o QR Estático não resolve o problema de programação de valor, por exemplo. Você poderia usar um mesmo QR Code dinâmico para pagar todas as suas faturas de energia elétrica para sempre.

**Comment by ninrod** [comment]
Podemos responder alguma questão adicional prezados?
