### ISSUE TITLE
Dúvida exibição dos campos no payload gerados a partir da versão 2.0.0 para 16/11

### ISSUE THREAD

**Issue by monise** [bacen/pix-api#181]
Olá!! Gostaríamos de tirar algumas dúvidas quanto aos campos citados no _[Informe Pix - 070/2020] Geração e tratamento de QR Code dinâmico (e “Pix Copia e Cola”) para cobranças com pagamento imediato_.

![image](https://user-images.githubusercontent.com/5355541/99157924-10062280-26ac-11eb-9725-65b629e4f8cd.png)
 

**Dúvida 1**: Os campos _valor.final, valor.juros,  valor.multa, valor.desconto, valor.permiteAlteracao e calendario.vencimento_, **não devem** ser exibidos em payload JSON que forem gerados a partir da versão **2.0.0?**

Pois de acordo com o manual **_Anexo II - Manual de Padroes para Iniciacao do Pix - versao 2.0.pdf_** os campos citados acima **existem** no payload JSON, conforme apresentado na seção **_1.6.6. O payload JSON_** (página 13).

![image](https://user-images.githubusercontent.com/5355541/99157927-1ac0b780-26ac-11eb-83ed-5dcc909cddb9.png)
 

Como na versão **2.0.0** não existia uma especificação clara que há diferentes payloads JSON de acordo com a finalidade da cobrança (cobrança imediata e cobrança com vencimento), entendemos que não é um problema exibir os campos acima, no paylaod JSON.

**Dúvida 2:** Nosso entendimento acima está correto?

**Dúvida 3:** Os payloads que podem ser apresentados a partir de 16/11/2020 são os payloads gerados tanto seguindo a especificação da versão **2.0.0** quanto da versão **2.1.0**? 

**Dúvida 4:** Os payloads JSON gerados a partir da versão **2.0.0** serão aceitos a partir de 16/11/2020?

**Comment by ninrod** [comment]
Boa noite @monise 

> Dúvida 1: Os campos valor.final, valor.juros,  valor.multa, valor.desconto, valor.permiteAlteracao e calendario.vencimento, não devem ser exibidos em payload JSON que forem gerados a partir da versão 2.0.0?

Exatamente. Perceba que na API `2.0.0` esses campos não existem e que no manual de iniciação `2.0` estão marcados como "em discussão e podem mudar" (nota 36).

> Pois de acordo com o manual Anexo II - Manual de Padroes para Iniciacao do Pix - versao 2.0.pdf os campos citados acima existem no payload JSON, conforme apresentado na seção 1.6.6. O payload JSON (página 13).

> Como na versão 2.0.0 não existia uma especificação clara que há diferentes payloads JSON de acordo com a finalidade da cobrança (cobrança imediata e cobrança com vencimento), entendemos que não é um problema exibir os campos acima, no paylaod JSON.

Apenas observando a tabela realmente não fica claro que estes campos estavam _"em dicussão e poderiam mudar"_; esta observação está na nota __36__.

> Dúvida 2: Nosso entendimento acima está correto?

conforme expliquei acima, não.

> Dúvida 3: Os payloads que podem ser apresentados a partir de 16/11/2020 são os payloads gerados tanto seguindo a especificação da versão 2.0.0 quanto da versão 2.1.0? 

Sim, conforme API Pix 2.0.0 e 2.1.0. 


> Dúvida 4: Os payloads JSON gerados a partir da versão 2.0.0 serão aceitos a partir de 16/11/2020?

Sim @monise. E apenas para ficar muito claro, os campos:

•	valor.final
•	valor.juros
•	valor.multa
•	valor.desconto
•	valor.permiteAlteracao
•	calendario.vencimento
•	calendario.recebivelAposVencimento

__Não__ existem na versão 2.0.0 (e superior), conforme pode-se observar __[aqui](https://github.com/bacen/pix-api/tree/2.0.0)__.

**Comment by monise** [comment]
@ninrod Segundo a nota 36, os campos estavam em revisão no ambiento da API Pix. Se tivermos uma API proprietária para geração de QR code dinâmico via aplicativo, é um erro exibir esses campos?

![image](https://user-images.githubusercontent.com/5355541/99162327-40b18080-26db-11eb-864e-7f1675309055.png)

**Comment by ninrod** [comment]
> @ninrod Segundo a nota 36, os campos estavam em revisão no âmbito da API Pix. Se tivermos uma API proprietária para geração de QR code dinâmico via aplicativo, é considerado um erro exibir esses campos?

Sim, @monise é um erro. Veja, nesse caso, não importa como o QR Dinâmico foi criado: se o app do Pagador notar campos estranhos no payload JSON, depois de acessar a "location", há grandes chances de descarte do QR e, assim, o pagamento não será realizado. O PSP pagador e o PSP recebedor não serão necessariamente os mesmos, por isso é muito importante respeitar a API Pix.

**Comment by rodrigonunes100** [comment]
@ninrod QR code Dinâmico sem PIX API, perdi alguma coisa?

**Comment by thiagolvlsantos** [comment]
Dúvida aparentemente esclarecida.

Atenciosamente,
Thiago Santos.
