### ISSUE TITLE
Dúvida sobre QRCode - Como lidar com GRU?

### ISSUE THREAD

**Issue by arthurd2** [bacen/pix-api#182]
Olá Pessoal,
Resumidamente: 
Como nós (autarquias aleatórias) podemos gerar um QRCode de pagamento para a Conta Unica da União (substituindo o ~bom e velho~ GRU) e verificar se ele foi pago?

Acredito que ***vários*** orgão governamentais passarão por esta situação.
É possível documentar?

**Comment by rubenskuhl** [comment]
Acho que aderindo ao PagTesouro, não ? 

https://www.gov.br/tesouronacional/pt-br/gru-e-pag-tesouro/pagtesouro

https://www.diariodepernambuco.com.br/noticia/economia/2020/11/pagtesouro-comeca-a-disponibilizar-pix-como-forma-de-pagamento.html

**Comment by arthurd2** [comment]
Valeu @ninrod e @rubenskuhl 
Realmente, identifiquei que a [API do PagTesouro](https://valpagtesouro.tesouro.gov.br/simulador/#/pages/api) já esta suportando o PIX.
Excelente isto! 
=D
