### ISSUE TITLE
Confirmação de pagamentos

### ISSUE THREAD

**Issue by jozephbrasil** [bacen/pix-api#186]
Olá. Alguém sabe se tem como automatizar a confirmação de pagamento pelo PIX para integração com sistemas e sites sem ter que fornecer dados bancários para operadores de caixa, por exemplo.

**Comment by rubenskuhl** [comment]
O objetivo da API Pix é esse mesmo... os acessos facultados na API são restritos a emitir cobranças (opcional dependo do fluxo de pagamento) e consultar Pix recebidos. Mas nem todo banco, ou PSP na nomenclatura mais geral usada no Pix, dispõe dessa API... uma lista não-oficial (o BACEN não mantém esse tipo de lista) pode ser observada em #76 .

**Comment by ninrod** [comment]
@jozephbrasil , é isso que o @rubenskuhl disse mesmo. 

Recomendo dar uma olhada nesta [pagina](https://www.bcb.gov.br/estabilidadefinanceira/pix), em especial, procure pelo botão "regulamentação associada ao Pix".
