### ISSUE TITLE
Lista de PSPs recebedores PIX API

### ISSUE THREAD

**Issue by rodrigonunes100** [bacen/pix-api#187]
Existe alguma lista de PSPs recebedores que estão disponibilizando a PIX API  ? Seria interessante essa lista. Em muitos sites de PSPs recebedores não existe essa informação,  O ônus ficou com o empreendedor e desenvolvedor buscar essa informação. Vamos começar:

GerenciaNet - SIM
Cielo - ? - Dizem que estão implementando, mas não divulgam a data.
Santander - ?
Bradesco - ?
Itaú - ?
Iti Itáu - ?
BB - ?
PagSeguro - ?
BS2 -  SIM
Nubank - ?
MercadoPago - ?
C6 - ?
Caixa - ?
PicPay - ?
Algum outro ?

**Comment by rubenskuhl** [comment]
Mantida pelo BACEN, não, que já informei não imaginar ter esse tipo. Eu tenho mantido o #76 atualizado.

**Comment by rodrigonunes100** [comment]
Obrigado @rubenskuhl . O MercadoPago e PagSeguro estão disponibilizando a PIX API? não vejo nenhuma informação em nenhum site dos citados.  Em https://dev.pagseguro.uol.com.br/ do PagSeguro não encontramos nenhuma referencia ao PIX , em https://www.mercadopago.com.br/developers/pt/guides do mercado pago também não. No Bradesco não acho nenhuma informação

**Comment by rubenskuhl** [comment]
> Obrigado @rubenskuhl . O MercadoPago e PagSeguro estão disponibilizando a PIX API? não vejo nenhuma informação em nenhum site dos citados. Em https://dev.pagseguro.uol.com.br/ do PagSeguro não encontramos nenhuma referencia ao PIX , em https://www.mercadopago.com.br/developers/pt/guides do mercado pago também não. No Bradesco não acho nenhuma informação

PagSeguro disponibilizou um link no getpostman com a documentação, e uma conexão com uma API mock-up; já pedi uma atualização para eles e ainda não tenho um posicionamento atualizado. 

MercadoPago disse que teria API, mas como eles cobram por % e não quiseram fazer um acordo específico, não demos continuidade. Então até nova informação os manterei listados. 
[Manual_API_Recebimentos_PIX_V2.pdf](https://github.com/bacen/pix-api/files/5553711/Manual_API_Recebimentos_PIX_V2.pdf)


Bradesco eu recebi via gerente de relacionamento, mas imagino que se você pedir para suporte.api@bradesco.com.br eles te enviem. O documento se chama "Manual e Layout API de Recebimentos Pix". Anexei aqui o que eu tinha, mas fica o disclaimer de que eles podem e devem ter uma versão mais atualizada.

**Comment by rodrigonunes100** [comment]
@rubenskuhl . Valeu.

**Comment by masyaf** [comment]
Itaú já possui API na v2, estamos utilizando inclusive em nosso ambiente de testes.

**Comment by rubenskuhl** [comment]
> Itaú já possui API na v2, estamos utilizando inclusive em nosso ambiente de testes.

O que me reportaram foram algumas divergências da API deles para a V2.1.2 como sistemas de credenciais, métodos e headers. Por enquanto estou imaginando apenas os escopos cob, pix e webhook como mandatórios. Ou seja, suporte mínimo a cobranças imediatas, tendo ou não suporte a cobranças com vencimento e em lote, mas já com configuração de webhook por chave.

**Comment by flaviolenz** [comment]
Nao vejo problema cobrar em % do valor da transacao.
Os cartoes hoje fazem assim e se for pra substitui-los, pode ficar extremamente interessante.
Cobrar valor fixo eh que inviabiliza usar PIX pra recebimento em negocios onde o ticket medio eh pequeno.

**Comment by flaviolenz** [comment]
> [Manual_API_Recebimentos_PIX_V2.pdf](https://github.com/bacen/pix-api/files/5553711/Manual_API_Recebimentos_PIX_V2.pdf)

Alguem chegou a evoluir algo aqui?
Olha o mTLS, que pesado!!!

No caso, certificado auto-assinado eh dureza.
Porque nao fez logo pela ICP-Brasil.
Toda empresa ja tem um e faz conexao com a SEFAZ pra emitir NF-e.

Nesse caso ai tem que ser um por estabelecimento ou pode ser um pro ERP e com ele, se conectar pra todos os estabelecimentos?

**Comment by rubenskuhl** [comment]
> Nao vejo problema cobrar em % do valor da transacao.
> Os cartoes hoje fazem assim e se for pra substitui-los, pode ficar extremamente interessante.
> Cobrar valor fixo eh que inviabiliza usar PIX pra recebimento em negocios onde o ticket medio eh pequeno.

Isso foi endereçado por alguns operadores colocando um preço fixo em função do valor, limitando a um valor máximo. Um exemplo: https://gerencianet.com.br/tarifas/ .

Notar que % baixo talvez até fosse factível, mas 1% dói.

**Comment by rubenskuhl** [comment]
> > [Manual_API_Recebimentos_PIX_V2.pdf](https://github.com/bacen/pix-api/files/5553711/Manual_API_Recebimentos_PIX_V2.pdf)
> 
> Alguem chegou a evoluir algo aqui?

Teve gente sim que conseguiu integrar. Não foi o meu caso então deixo para quem foi se manifestar, caso queira. 

> Olha o mTLS, que pesado!!!

O mTLS padronizado é pesado, mas o descrito aí é pior mesmo. 

> No caso, certificado auto-assinado eh dureza.

Isso é um dos motivos pelo qual listei o Bradesco em #76 como tendo API proprietária, pois o manual do Pix claramente veda isso. 

> Porque nao fez logo pela ICP-Brasil.
> Toda empresa ja tem um e faz conexao com a SEFAZ pra emitir NF-e.

Isso não funciona tão bem assim... o certificado A-3 é um pesadelo de interoperabilidade para sistemas automatizados. Usávamos uma interface de boletos registrados que exigia ICP-Brasil, por sinal a do próprio Bradesco, e foi um alívio migrar para outra. 

> Nesse caso ai tem que ser um por estabelecimento ou pode ser um pro ERP e com ele, se conectar pra todos os estabelecimentos?

Um por correntista. Há um issue propondo Authorization Credential Flow que talvez enderece melhor um terceiro autorizado a saber informação de recebimento.

**Comment by flaviolenz** [comment]
Muita gente paga mais que isso de Debito.
E de credito, eh comum pagar mais de 2%.
E ainda recebe so no dia seguinte.

Com a concorrencia, tende a baixar MUITO.

**Comment by rubenskuhl** [comment]
> Muita gente paga mais que isso de Debito.
> E de credito, eh comum pagar mais de 2%.
> E ainda recebe so no dia seguinte.
> 
> Com a concorrencia, tende a baixar MUITO.

As bandeiras de cartão tem muitas bocas para alimentar, o objetivo do Pix é exatamente diminuir isso e permitir uma operação mais eficiente de comércio e serviços. Quem quiser cobrar percentagem, cobrará assim e o mercado irá dizer como prefere. Tanto que mantenho prestadores com cobrança de % em #76 , esse caso específico foi da minha experiência e em as pessoas sabendo que opções tem e quanto cada uma custa, tomarão suas decisões.

**Comment by pnegri** [comment]
Só um ponto pessoal, dependendo do ticket médio, a % passa a ser diversas vezes menor que uma cobrança de centavos. No geral a % passa a não ser interessante com tickets médios altos. Com um ticket de 50 reais, não é um absurdo deixar 1% na mesa. Existe um custo aí de infraestrutura, links, custo por banda na própria mensageria do bacen que não torna a transação tão de graça assim. Muita gente olha só pro 1 cent de custo de 10 transações, mas esquece de todo o custo regulatório para manter uma IP ou IF, o custo de toda parte de rede (Que é pesado), e afins. Só pra ter uma idéia, iugu demorou 3 anos para conseguir a licença, e o custo para manter a infra sem usar ultrapassava 100 mil reais por mês, e tivemos que manter durante todo este tempo, isso sem falar do custo regulatório, compliance, auditoria interna, auditoria externa, controles internos etc.  E nem estou pondo na conta o custo de capital regulatório de IP (2% de tudo que entra e que sai). Só funciona na escala.

**Comment by rubenskuhl** [comment]
Quem quiser pagar 1% pode pagar se preferir, mas sugiro observar a lista do #76 e através de pesquisa de mercado diminuir bem em relação a isso. Tipo, 5 ou 10 vezes menos. A API padronizada é um forte indutor de competição, que os estabelecimentos comerciais podem e devem ter a seu favor.

**Comment by aifabio** [comment]
Palhaçada o BBC que bagunça está virando um monopólio ficando a mesma coisa, em vez de nos ajudar a integração estamos tendo que ficar dependente de toda forma e ainda dando mais trabalho
