### ISSUE TITLE
Response do Consultar locations cadastradas

### ISSUE THREAD

**Issue by MatheusCorreia96** [bacen/pix-api#191]
Boa tarde.

Levando em conta a especificação da API, no endpoint de` Consultar locations cadastradas` um dos filtros existentes é o de `tipoCob`.

![image](https://user-images.githubusercontent.com/31870431/99840569-89d65a00-2b4b-11eb-9025-1e42a7027e58.png)

Porém no response da mesma rota, existe um campo de `parametros`, sendo um campo com os Parâmetros de consulta de locations, mas o filtro `tipoCob` não aparece no response. 
 
![image](https://user-images.githubusercontent.com/31870431/99840948-31538c80-2b4c-11eb-8f5b-9266d689a6d7.png)

O filtro `tipoCob` deve aparecer no response ou não?

**Comment by ninrod** [comment]
> O filtro tipoCob deve aparecer no response ou não?

@MatheusCorreia96 , acredito que você encontrou um bug. Estamos verificando.

**Comment by MatheusCorreia96** [comment]
@ninrod não consegui entender ainda, atualmente o campo `tipoCob` deve aparecer no `response` então?

**Comment by ninrod** [comment]
> @ninrod não consegui entender ainda, atualmente o campo tipoCob deve aparecer no response então?

Exatamente.

**Comment by thiagolvlsantos** [comment]
Demanda já atendida na ApiPix.

Atenciosamente,
Thiago Santos
