### ISSUE TITLE
Itau Crashando com Este QR Code Fixo

### ISSUE THREAD

**Issue by AugustoResende** [bacen/pix-api#192]
```00020101021126580014br.gov.bcb.pix0136f8b4dbf6-c619-42fb-9f2f-0134209842d85204000053039865802BR5921Biscoint.io - NAX TEC6009SAO PAULO62070503***63042D6F``` no formato de QR Code e Copia e Cola, ao ler, estava crashando no app Itau Android, última versão, dia 20/11/2020.

Aparentemente agora está funcionando corretamente, ao menos o novo que gerei para testes:
```00020101021126580014br.gov.bcb.pix0136d6f1ca1f-9c50-4e1b-85af-611febcc0adc5204000053039865802BR5921Biscoint.io - NAX TEC6009SAO PAULO62070503***6304D501```

**Comment by rubenskuhl** [comment]
Reproduzido:
![image](https://user-images.githubusercontent.com/3913097/99850308-ea6d9300-2b5b-11eb-92a9-7418766358af.png)

**Comment by rubenskuhl** [comment]
Aplicativos mobile C6 e Gerencianet não tiveram problema com esse QR.

**Comment by loja5combr** [comment]
Eu também estou com problemas similares, crio o código estático de acordo o padrão brcode/guia do pix tudo certinho como no manual de desenvolvedor por eles fornecido mas alguns bancos funciona outros não, principalmente nubank, bb e bradesco sempre retorna retorna problema de que não foi possível realizar o procedimento e tals.

**Comment by rubenskuhl** [comment]
> Eu também estou com problemas similares, crio o código estático de acordo o padrão brcode/guia do pix tudo certinho como no manual de desenvolvedor por eles fornecido mas alguns bancos funciona outros não, principalmente nubank, bb e bradesco sempre retorna retorna problema de que não foi possível realizar o procedimento e tals.

Poderia postar QRs com esse comportamento aqui no tópico ?

**Comment by loja5combr** [comment]
00020126540014BR.GOV.BCB.PIX0123suportedaloja@gmail.com020535061520400005303986540510.915802BR5925ALISSON BRUNO NUNES DE AL6008TERESINA62070503***63047B6C

**Comment by rubenskuhl** [comment]
Gerencianet reconheceu como código válido, mas não pude finalizar por falta de saldo. Indicou banco e CPF então entendo que o lookup da chave no DICT também aconteceu com sucesso.

**Comment by AugustoResende** [comment]
Aparentemente está funcionando, ao menos o novo que testei. Infelizmente excluí a chave aleatória anterior, então o primeiro QR não é mais válido. 

```00020101021126580014br.gov.bcb.pix0136d6f1ca1f-9c50-4e1b-85af-611febcc0adc5204000053039865802BR5921Biscoint.io - NAX TEC6009SAO PAULO62070503***6304D501```

**Comment by loja5combr** [comment]
Seria com bom que o Bacen possuíssem uma espécie de validação/homologação, assim como é atualmente em boletos com registro qual alguns bancos possuem um validador de remessas de registro, assim checando se a mesma esta de acordo com os padrões aceitos por eles ou não onde caso não esteja replica as partes fora do padrão.

Ex: https://wspf.bradesco.com.br/wsValidadorTeleBanco/ValidadorRemessa.aspx

Pois assim fica mais simples de identificar se o problema é por parte do PIX gerado (código errado ou fora do padrão) ou se é algo do PSP (problemas internos ou diferenças de padrões).

**Comment by ninrod** [comment]
> Aparentemente está funcionando, ao menos o novo que testei. Infelizmente excluí a chave aleatória anterior, então o primeiro QR não é mais válido.

@AugustoResende , obrigado.
