### ISSUE TITLE
PayloadLocation - formato da url do location no response para o tipo "cobv"

### ISSUE THREAD

**Issue by tjbarbosa** [bacen/pix-api#193]
Boa noite,

De acordo com os exemplos de resposta para as rotas do PayloadLocation, a propriedade "location" demonstra diferentes padrões variando de acordo com o "tipoCob".
Para tipoCob = cob:
![url_cob](https://user-images.githubusercontent.com/6126720/99848960-78944a00-2b59-11eb-8719-5d66d9675854.png)

Para tipoCob = cobv:
![url_cobv](https://user-images.githubusercontent.com/6126720/99849055-9cf02680-2b59-11eb-9341-7d9d19f4d7b9.png)

De acordo com o schema e os exemplos, não fica explicito a recomendação da utilização do padrão url/versao/cobv/ nos casos de tipoCob = cobv:
![url_schema](https://user-images.githubusercontent.com/6126720/99849475-68c93580-2b5a-11eb-84b6-c6abc1d852e5.png)

Os valores de "location" no response devem demostrar o tipo na url quando for cobv, e deixar default para tipo cob?
Ou devem demonstrar o tipo na url para ambos os tipos?
Ou não devem demonstrar nenhum tipo na url pois o tipo é retornado no próprio response?

ps: Sugestão, adicionar a recomendação na descrição do "location" no schema:
![locationSchema](https://user-images.githubusercontent.com/6126720/99851250-9d8abc00-2b5d-11eb-96ae-5297af3e1f9b.png)

Obrigado.

**Comment by ninrod** [comment]
@tjbarbosa , bem pontuado. 

> Os valores de "location" no response devem demostrar o tipo na url quando for cobv, e deixar default para tipo cob?

Se uma cobrança é com vencimento, o fragmento `cobv` deve estar presente. 
Se uma cobrnaça é "imediata", depois do framento de versão, deve-se imediamente seguir com o fragmento `pixUrlAccessToken`. 

Exemplos: 

`pix.example.com/v2/abcdef1234abcdef1234abcdef1234ab` -> é uma cobrança imediata. 

`pix.example.com/v2/cobv/abcdef1234abcdef1234abcdef1234ab` -> é uma cobrança com vencimento, então eu, PSP pagador, tenho que realizar a chamada agregando os parâmetros `codMun` e `DPP`, se aplicável. 

` GET pix.example.com/v2/cobv/abcdef1234abcdef1234abcdef1234ab?codMun={codMun}&&DPP={DPP}`

**Comment by ninrod** [comment]
Vamos ajustar os exemplos para a próxima release.

**Comment by tjbarbosa** [comment]
@ninrod mto obrigado.
