### ISSUE TITLE
Conjunto de caracteres do BR Code

### ISSUE THREAD

**Issue by tuliospuri** [bacen/pix-api#197]
Olá.

O [Manual do BR Code](https://www.bcb.gov.br/content/estabilidadefinanceira/SiteAssets/Manual%20do%20BR%20Code.pdf), na página 8, trás o conjunto de caracteres que podem ser usados:

```
letras: de A a Z (somente maiúsculas);
dígitos de 0 a 9;
os seguintes caracteres especiais: $ % * + - . / :
o caractere de espaço em branco.
```

Como fica a explicação para o uso do `@` [arroba] nos QR Codes estáticos que usam chave DICT do tipo "email"?

**Comment by rubenskuhl** [comment]
A versão mais atual do BR Code não é essa

**Comment by tuliospuri** [comment]
Perfeito, obrigado @rubenskuhl.

Encontrei a [versão 2.0.0](https://www.bcb.gov.br/content/config/Documents/BR_Code_MANUAL_Version_2_May_2020.pdf) do Manual do BR Code.

**Comment by renatofrota** [comment]
Na verdade o mais atual é esse: [2.0.1](https://www.bcb.gov.br/content/estabilidadefinanceira/spb_docs/ManualBRCode.pdf).

**Comment by tuliospuri** [comment]
> Na verdade o mais atual é esse: [2.0.1](https://www.bcb.gov.br/content/estabilidadefinanceira/spb_docs/ManualBRCode.pdf).

Obrigado, @renatofrota, editei o comentário.

**Comment by renatofrota** [comment]
Pra facilitar, o link pra versão mais atual está sempre [aqui](https://www.bcb.gov.br/estabilidadefinanceira/arranjosintegrantesspb).
