### ISSUE TITLE
[Dúvida] na [API Pix] - Devedor x Pagador

### ISSUE THREAD

**Issue by rubenskuhl** [bacen/pix-api#2]
**Descrição da Dúvida**
Na API 2.0.0, alguns campos mudaram de Pagador para Devedor, mas outros se mantiveram. Isso significa que no caso de Pagador que a informação será a do efetivo pagador e não a de contra quem a cobrança foi emitida ? Essa informação virá em inteiro teor ou parcialmente mascarada ? 

**Sistema ou Área**
API PIx

**Identificador do Problema**
Exemplo de inconsistência local em /cob/

devedor | Pessoa Física (object) or Pessoa Jurídica (object)Os campos aninhados sob o objeto devedor são opcionais e identificam o devedor, ou seja, a pessoa ou a instituição a quem a cobrança está endereçada. Não identifica, necessariamente, quem irá efetivamente realizar o pagamento. Um CPF pode ser o devedor de uma cobrança, mas pode acontecer de outro CPF realizar, efetivamente, o pagamento do documento. Não é permitido que o campo pagador.cpf e campo pagador.cnpj estejam preenchidos ao mesmo tempo. Se o campo pagador.cnpj está preenchido, então o campo pagador.cpf não pode estar preenchido, e vice-versa. Se o campo pagador.nome está preenchido, então deve existir ou um pagador.cpf ou um campo pagador.cnpj preenchido.
-- | --

Exemplo de inconsitência cruzada em /pix/

"endToEndId": "E12345678202009091221abcdef12345",
"txid": "cd1fe328-c875-4812-85a6-f233ae41b662",
"valor": "100.00",
"horario": "2020-09-10T13:03:33.902Z",
"pagador": {
"cnpj": "12345678000195",
"nome": "Empresa de Serviços SA"
},
"infoPagador": "Reforma da casa",
"devolucoes": [
{}
]

**Comment by rubenskuhl** [comment]
Obrigado @ninrod . A informação do pagador no /pix/ é completa (Ex: 111.111.111-11) ou mascarada (Ex: 111.***.***-11) ?

**Comment by ninrod** [comment]
@rubenskuhl completa

**Comment by ninrod** [comment]
@rubenskuhl, o texto está resolvido e deve sair consertado na versão `2.1.0`, obrigado pelo reporte.
