### ISSUE TITLE
Dúvida: Expiração QRCode Dinâmico

### ISSUE THREAD

**Issue by gfauth** [bacen/pix-api#201]
Pessoal, qual o limite de tempo para expiração de um QRCode dinâmico? Sei que o default é 86.400 segundos (24 horas), mas gostaria de saber qual o limite, se é que temos limites.
Quero saber se posso mandar como expiração 1 ano (31.536.000 segundos).

Valeu!

**Comment by ninrod** [comment]
>  se é que temos limites.

bom dia @gfauth 

O limite é o valor máximo que poderia ser denotado pelo tipo "integer" no JSON.

**Comment by gfauth** [comment]
> > se é que temos limites.
> 
> bom dia @gfauth
> 
> O limite é o valor máximo que poderia ser denotado pelo tipo "integer" no JSON.

Obrigado pela informação!
