### ISSUE TITLE
Dúvida - Cálculos COBRANCA_PIX   x   Boletos Código de Barras 

### ISSUE THREAD

**Issue by eduardosomavilla** [bacen/pix-api#205]
Boa Tarde, 

Podem me ajudar nas dúvidas abaixo nos cálculos? Fiz exemplos para facilitar o entendimento.

**Exemplo 1:**  Boleto de Cobrança tradicional com código de barras, no valor de R$ 100,00, juros diários de R$ 1,00 (dia corrido) e vencimento no dia 27/11/2020 (sexta-feira).
- Atualmente se ele for pago no Internet Banking via código de barras no dia 28/11/2020 (sábado), ele paga com data de 30/11/2020 (segunda-feira) e três dias de mora diária, totalizando R$ 103,00.
**Dúvida: Para uma Cobrança PIX com mesmas características, o cálculo deve ser da mesma forma? Ou devemos calcular apenas um dia de juros se ele for pago no dia 28/11/2020 (sábado)?**

**Exemplo 2:**  Boleto de Cobrança tradicional com código de barras, no valor de R$ 100,00, juros diários de R$ 1,00 (dia corrido) e vencimento no dia 28/11/2020 (sábado).
- Atualmente se ele for pago no Internet Banking via código de barras no dia 29/11/2020 (domingo) ou dia 30/11/2020 (segunda) ele paga sem cálculo de juros, a cobrança de juros só inicia a partir do dia 01/12/2020.
**Dúvida:  Para uma Cobrança PIX, o cálculo deve ser da mesma forma? Ou devemos calcular juros para pagamento do dia 29/11/2020 (domingo)?**

**Exemplo 3:**  Boleto de Cobrança tradicional com código de barras, no valor de R$ 100,00 e desconto de R$ 30,00 até dia 28/11/2020 e com vencimento no dia 28/11/2020 (sábado).
- Atualmente se ele for pago no Internet Banking via código de barras nos dias 28/11/2020, 29/11/2020 (domingo) ou 30/11/2020 (segunda) ele paga com o desconto normalmente.
**Dúvida:  Para a Cobrança PIX, o cálculo deve ser da mesma forma? Ou devemos conceder desconto somente até o próprio dia 28/11/2020?**

**Comment by ninrod** [comment]
> Atualmente se ele for pago no Internet Banking via código de barras no dia 28/11/2020 (sábado), ele paga com data de 30/11/2020 (segunda-feira) e três dias de mora diária, totalizando R$ 103,00.
Dúvida: Para uma Cobrança PIX com mesmas características, o cálculo deve ser da mesma forma? Ou devemos calcular apenas um dia de juros se ele for pago no dia 28/11/2020 (sábado)?

@eduardosomavilla , bom dia. Não vou entrar no mérito de como funciona esse exemplo no boleto porque há diversas formas de se configurar uma cobrança em boleto. 

Neste exemplo, no pix, deveria ser apenas um dia de mora. Estamos assumindo aqui que não há feriados bancários na sexta-feira. 

> Atualmente se ele for pago no Internet Banking via código de barras no dia 29/11/2020 (domingo) ou dia 30/11/2020 (segunda) ele paga sem cálculo de juros, a cobrança de juros só inicia a partir do dia 01/12/2020.
Dúvida: Para uma Cobrança PIX, o cálculo deve ser da mesma forma? Ou devemos calcular juros para pagamento do dia 29/11/2020 (domingo)?

nesse caso, não há cobrança de juros. 

> Atualmente se ele for pago no Internet Banking via código de barras nos dias 28/11/2020, 29/11/2020 (domingo) ou 30/11/2020 (segunda) ele paga com o desconto normalmente.
Dúvida: Para a Cobrança PIX, o cálculo deve ser da mesma forma? Ou devemos conceder desconto somente até o próprio dia 28/11/2020?

No Pix, sendo dia não-útil desloca-se a data para o próximo dia útil. Deve-se conceder o desconta se pago dia 30.11.2020. 

deve-se considerar, também, feriados.

**Comment by llatsch** [comment]
@ninrod Fiquei confusa com a sua última resposta, apenas confirmando:

--------------------------------------------------------------------------------------------------------------------------------------------------
Atualmente se ele for pago no Internet Banking via código de barras nos dias 28/11/2020, 29/11/2020 (domingo) ou 30/11/2020 (segunda) ele paga com o desconto normalmente.
Dúvida: Para a Cobrança PIX, o cálculo deve ser da mesma forma? Ou devemos conceder desconto somente até o próprio dia 28/11/2020?

No Pix, sendo dia não útil, desloca-se a data para o próximo dia útil. Deve-se conceder o desconta se pago dia 30.11.2020.
Deve-se considerar, também, feriados.

--------------------------------------------------------------------------------------------------------------------------------------------------

Para desconto, seguindo as modalidades 1 e 2, e já que estamos falando de um pagamento instantâneo que poderia ser feito aos finais de semana e feriados, faz sentido o desconto ser concedido no próximo dia útil? E não somente até o próprio sábado dia 28?

**Comment by llatsch** [comment]
@ninrod Também não entendi a resposta abaixo:

-------------------------------------------------------------------------------------------------------------------------------------
Atualmente se ele for pago no Internet Banking via código de barras no dia 29/11/2020 (domingo) ou dia 30/11/2020 (segunda) ele paga sem cálculo de juros, a cobrança de juros só inicia a partir do dia 01/12/2020.
Dúvida: Para uma Cobrança PIX, o cálculo deve ser da mesma forma? Ou devemos calcular juros para pagamento do dia 29/11/2020 (domingo)?

nesse caso, não há cobrança de juros.

-------------------------------------------------------------------------------------------------------------------------------------

Em qual cenário se aplicam os juros por dias corridos então? Modalidades 2 e 6?

**Comment by llatsch** [comment]
Aproveitando para incluir mais uma pergunta, só para "morrer de certeza". Os dias corridos e úteis que exemplificam os cenários de juros ao mês e ao ano na documentação, devem ser usados como padrão? Ou são apenas um exemplo? 
Entendo que são apenas exemplos e que devo considerar as variações, meses com o dia 31, ano bissexto e etc. É isso mesmo?

n: 1, 30 ou 360, conforme a taxa de juros seja diária, mensal ou anual
n: 1, 21 ou 252, conforme a taxa de juros seja diária, mensal ou anual;

**Comment by ninrod** [comment]
> Para desconto, seguindo as modalidades 1 e 2, e já que estamos falando de um pagamento instantâneo que poderia ser feito aos finais de semana e feriados, faz sentido o desconto ser concedido no próximo dia útil? E não somente até o próprio sábado dia 28?

Entendo o raciocínio, mas existe uma lei que versa sobre essas questões. Qual é exatamente a lei, artigo alínea, etc... eu não consigo informar, seria interessante consultar o DECEM

**Comment by ninrod** [comment]
> Em qual cenário se aplicam os juros por dias corridos então? Modalidades 2 e 6?

Eu respondi errado. Se utilizadas as modalidades `1, 2, 3 e 4`, aplica-se o juro.

**Comment by ninrod** [comment]
> Aproveitando para incluir mais uma pergunta, só para "morrer de certeza". Os dias corridos e úteis que exemplificam os cenários de juros ao mês e ao ano na documentação, devem ser usados como padrão? Ou são apenas um exemplo?
Entendo que são apenas exemplos e que devo considerar as variações, meses com o dia 31, ano bissexto e etc. É isso mesmo?

São apenas exemplos. 

> n: 1, 30 ou 360, conforme a taxa de juros seja diária, mensal ou anual
n: 1, 21 ou 252, conforme a taxa de juros seja diária, mensal ou anual;

A pergunta é interessante. Vou passar para o DECEM.

**Comment by ninrod** [comment]
@llatsch 

> n: 1, 30 ou 360, conforme a taxa de juros seja diária, mensal ou anual
n: 1, 21 ou 252, conforme a taxa de juros seja diária, mensal ou anual;

É por aí mesmo, esse aspecto é padronizado exatamente deste jeito.
