### ISSUE TITLE
Inconsistencia entre string e integer no payload

### ISSUE THREAD

**Issue by rubenskuhl** [bacen/pix-api#208]
Na API 2.1.2, os schemas definem revisao e expiracao como integer. Porém, os exemplos de expiracao estão todos como strings... já os exemplos de revisao estão quase todos como integer, mas há ao menos um como string. 

Levando claro em conta o princípio da robustez de que os apps pagadores deveriam aceitar ambos, quais formatos deveriam ser seguidos estritamente pelos PSPs recebedores ?

**Comment by ninrod** [comment]
@rubenskuhl 

> Na API 2.1.2, os schemas definem revisao e expiracao como integer. Porém, os exemplos de expiracao estão todos como strings... já os exemplos de revisao estão quase todos como integer, mas há ao menos um como string.

Bem apontado. Vamos revisar estes exemplos para a próxima versão.

**Comment by ninrod** [comment]
@rubenskuhl , duplicada porque já reportada em #207

**Comment by rubenskuhl** [comment]
Vou só adicionar lá no #207 a revisao.

**Comment by ninrod** [comment]
ok, bem lembrado.
