### ISSUE TITLE
[Dúvida] na Iniciação de Pagamentos - Scopes de OAuth no client

### ISSUE THREAD

**Issue by dncosta** [bacen/pix-api#21]
**Descreva sua dúvida ou problema**

Segundo a documentação das APIs:

```No processo de adesão, o Client_ID disponibilizado pelo PSP deve possuir um conjunto de escopos que determinarão as funcionalidades às quais o Usuário Recebedor terá acesso. Os critérios de autorização nos escopos são de responsabilidade do PSP, que pode criar critérios diferenciados em função das características do Usuário Recebedor. Dessa forma, é possível, por exemplo, que determinadas funcionalidades estejam acessíveis apenas por usuários que cumpram requisitos adicionais de segurança estipulados por cada PSP.```

Faz sentido um Usuário Recebedor criar um Client no PSP e utilizar o accessToken desse Client para autenticar nas APIs. Porém, o conceito de scope aqui não se aplica. Scopes são utilizados primariamente quando um Client solicita permissão de um terceiro para executar determinadas ações em nome desse terceiro, o que não é o caso aqui. O Usuário Recebedor, tem total liberdade para usar todos os endpoints da API, pq ele teria que gerar scopes de permissão pra si mesmo?
Qualquer tipo de permissão que possa ser concedida ou negada a esse usuário, é feita via processo de KYC, anterior a etapa de de autenticação.

Existe algum caso de uso claro com scopes no OAuth?

**Comment by dncosta** [comment]
@ninrod, Obrigado pela resposta.
O uso do client_id e secret ficou claro sim, só o scope que eu ainda discordo, pois é uma subversão do OAuth 2.0.

RFC:
```Client credentials are used as an authorization grant
   typically when the client is acting on its own behalf (the client is
   also the resource owner)```

Ou seja, o client está agindo em seu próprio nome.
Se esse é o caso, não faz sentido ele limitar seu próprio acesso em alguns cenários e não em outros. Ele poderia ter vários clients se quiser separar as operações de alguma maneira, mas a existência ou não de um escopo nesse cenário é pouco relevante.

A impressão que eu tenho é que essa opção aí aumenta o escopo de desenvolvimento, afeta as aplicações de OAuth daqueles que seguem a RFC (só pra atender o PIX) e é pouco fundada.
Por enquanto não tenho mais nenhuma questão a respeito, só esse reflexão mesmo.

Mais uma vez, obrigado.

**Comment by ninrod** [comment]
@dncosta , boa noite.

> Client credentials are used as an authorization grant typically when the client is acting on its own behalf (the client is also the resource owner)

Não vejo problemas nessa frase. Especificamente não vejo motivo para impedir o resource owner de escolher seus scopes para seus clients apenas porque "o client está agindo em seu próprio nome".  Não entendo que isso seja uma "subversão" da spec porque desconheço algum trecho de texto na RFC em que esteja escrito que no credentials flow deve-se esquecer que existam os scopes. 

Pelo contrário, copio aqui o texto da seção 3.3 da RFC 6749: 

>  The authorization server MAY fully or partially ignore the scope
   requested by the client, based on the authorization server policy or
   the resource owner's instructions.  If the issued access token scope
   is different from the one requested by the client, the authorization
   server MUST include the "scope" response parameter to inform the
   client of the actual scope granted.

O que é perfeitamente aderente à especificação da API Pix. Entendo que se houvesse algum problema com scopes nesse contexto estaria claramente especificado na RFC. 

Cabe ressaltar que esse uso de escopos exatamente dessa maneira está sendo conversado com o GT-SEG há meses e não foi reportado nenhum problema nesse sentido. 

Há algum texto específico na RFC que corrobore com a linha que você está colocando?

**Comment by ninrod** [comment]
Prezados, posso responder alguma questão adicional?

**Comment by franciscotfmc** [comment]
Bom dia pessoal.

Apenas para esclarecer a implementação dos scopes, vejam se concordam comigo. 
Estamos falando de 2 passos.

1º Criar a credencial (client_id, client_secret), atribuindo nesse momento os scopes que ela pode permitir;
2º Gerar um access_token, passando o client_id/client_secret, limitando, opcionalmente, os scopes que o token poderá acessar;

Isso significa que:

- Se eu não passar o scope no passo 2, meu access_token virá com scope máximo (de acordo com o que foi atribuído no passo 1)
- Se eu passar o scope, meu access_token estará limitado naquilo que eu solicitei.


Procede?

**Comment by ninrod** [comment]
@franciscotfmc , bom dia. 

Sim essa descrição está bem aderente com o que a spec coloca. 

Cabe ressaltar que scope "máximo" é o conjunto de scopes que foram definidos no passo 1 em onboarding, que pode ser uma menor quantidade do que do que todos os scopes possíveis, dependendo da vontado do usúario recebedor e PSP recebedor. 

Na prática, acredito que não se usará essa funcionalidade de entrar com os scopes no passo 02 no endpoint `POST /token`. E aí o que acaba sendo retornado é o conjunto de scopes definidos em onboarding para aquele client_id.

**Comment by lucasbt** [comment]
Bom dia pessoal!

@ninrod, então os escopos devem estar vinculados ao 'application' (registro do aplicativo cliente) na plataforma de autorização do PSP, a partir disso emitir AT somente para os escopos permitidos a mesma em confronto com o que foi requisitado no /token, correto? 
Essa abordagem não é clara para mim na RFC. Inclusive no link da Okta que você apresentou, eles informam que para o grant client credentials nem todas plataformas dão suporte a 'client scopes'.
Alguns APIM's e Auth Servers vinculam scopes apenas nos recursos das APIs e emitem ATs com os devidos scopes requisitados, balizando pelas subscrições do client. Pode ser que alguns PSP's não tenham a 'feature' de vínculo de client scopes out of box.

Obrigado pelo apoio e presteza!

**Comment by lucasbt** [comment]
Obrigado pela resposta @ninrod, entendido.

> Não entendi muito bem o trecho Auth Servers vinculam scopes apenas nos recursos das APIs. Entendo que quem provê a API é o RS, não o AS.
Ajustei o comentário anterior pra não ficar ambíguo, a ideia ali era relatar plataformas de apis com servidor de autorização embutido, como o All in One do WSO2.

Obrigado.

**Comment by ninrod** [comment]
@lucasbt , ok! 

@dncosta , posso responder alguma dúvida adicional?
