### ISSUE TITLE
[Dúvida] no [QR Code] - Regras QR Code Dinamico

### ISSUE THREAD

**Issue by simonevirgilio** [bacen/pix-api#212]
No QRCode estático o TXID possue as seguintes regras:
Os caracteres permitidos no contexto do Pix para o campo txId (EMV 62-05) são:
• Letras minúsculas, de ‘a’ a ‘z’
• Letras maiúsculas, de ‘A’ a ‘Z’
• Dígitos decimais, de ‘0’ a ‘9’
 
1 - Estamos na dúvida se ESPAÇOS em BRANCO podem ser utilizados (para separar uma frase como exemplo: XPTO QRCODE)?
 

No caso do QRCode Dinâmico a regra no manual é a seguinte:
O campo txId, no caso do QR Dinâmico, deve ter, no mínimo, 26 caracteres e, no máximo, 35 caracteres.
 
2 - No QRCode dinâmico deve seguir as mesmas regras de caracteres permitidos do QRCode estático?

**Sistema ou Área**
QR Code

**Comment by ninrod** [comment]
> 1 - Estamos na dúvida se ESPAÇOS em BRANCO podem ser utilizados (para separar uma frase como exemplo: XPTO QRCODE)?

`[A-Za-z0-9]` não admite espaços em branco.

> 2 - No QRCode dinâmico deve seguir as mesmas regras de caracteres permitidos do QRCode estático?

Sim. Mas o tamanho é diferente. 

Estático: `[1..25]`
dinâmico: `[26..35]`

**Comment by thiagolvlsantos** [comment]
Dúvida aparentemente esclarecida.

Atenciosamente,
Thiago Santos.
