### ISSUE TITLE
[Dúvida] validadeAposVencimento

### ISSUE THREAD

**Issue by llatsch** [bacen/pix-api#217]
No Gitbub, o campo "validadeAposVencimento", tem a seguinte descrição:

Trata-se da quantidade de dias corridos após o vencimento em que a cobrança poderá ser paga. Caso vencido este período e a cobrança não tenha sido paga, esta continuará ATIVA.

Se ela continua ATIVA ela aceita um novo pagamento não? Podemos aceitar pagamentos de cobranças vencidas? E com a validade após vencimento fechada?

**Comment by ninrod** [comment]
> Se ela continua ATIVA ela aceita um novo pagamento não?

Não, mas pode ser alterada, esse é o ponto. 

> Podemos aceitar pagamentos de cobranças vencidas?

Sim, e inclusive, aplicar multas, etc...

> E com a validade após vencimento fechada?

A intenção da validadeAposVencimento é justamente fechar a porta para novas cobranças. Mas pode-se alterar esse parâmetro enquanto a cobrança estiver ATIVA.

**Comment by llatsch** [comment]
A validação para não permitirmos um pagamento de cobrança com data de vencimento e validade após o vencimento "estouradas", mas ativas, é do PSP recebedor certo?
Só para garantir que não é responsabilidade do PSP Pagador!

**Comment by ninrod** [comment]
> A validação para não permitirmos um pagamento de cobrança com data de vencimento e validade após o vencimento "estouradas", mas ativas, é do PSP recebedor certo?
Só para garantir que não é responsabilidade do PSP Pagador!

@llatsch Responsabilidade é dos dois: tanto recebedor quanto pagador. O pagador tem condições de validar esse procedimento via calendario.validadeAposVencimento que ele recebe no payload JSON. 

O Recebedor realiza a checagem também, para garantir a funcionalidade caso aconteça um erro na ponta pagadora em que não se observe essa regra.
