### ISSUE TITLE
[Dúvida] no [QRCode] - Como identificar que um recebimento é de um QRCode?

### ISSUE THREAD

**Issue by mvleandro** [bacen/pix-api#22]
**Descreva sua dúvida ou problema**
Já fiz uma ponderação aqui de que o campo txid do QRCode estático não deveria ser preenchido pelo usuário, mas sim pelo PSP e deveria ser único, desta forma seria possível correlacionar diversos recebimentos a um único QRCode estático. Isto traria uma experiência de usuário muito mais fluida para o usuário final. Ex.:

1) Usuário A gera um QRCode para dividir a conta de um bar e envia para os amigos;
2) Amigos escaneam e pagam este QRCode;
1) Usuário A consegue ver todos os pagamentos recebidos a partir daquele QRCode específico, gerado para esta ocasião.

Meu primeiro ponto é: É realmente a palavra final do BACEN este ponto a respeito do txid? Porque deixar o identificador aberto (e não único) só torna a experiência mais complicada para o usuário final. Ele terá que ficar vendo várias entradas soltas no extrato e procurando pelo identificador que ele mesmo criou (e que pode ser repetido, o que torna as coisas mais confusas ainda).

Bem, tirando o ponto acima, o manual de experiência do usuário diz que no extrato eu devo diferenciar visualmente quando uma transação recebida é referente a um QRCode gerado. A despeito de tudo o que eu falei acima, qual é a melhor forma de identificar isso? Procurar pela presença do txid? A presença dele garante que aquele Pix partiu de um QRCode?

Outra dúvida: É vedado o envio do txid quando uma transação não partir de um QRCode?

Mais uma dúvida: O QRCode dinâmico também possui um txid. Assumindo a natureza transacional dele, posso assumir que, no caso do dinâmico, este txid é fornecido pelo PSP e é único e não é fornecido pelo usuário final, correto? Até porque, pela api de recebimento o txid é a chave principal utilizada. Meu entendimento está correto?

**Comment by ninrod** [comment]
@mvleandro , posso responder alguma questão adicional?

**Comment by mvleandro** [comment]
A respeito deste assunto não, @ninrod Obrigado!
