### ISSUE TITLE
AuthorizationServer - Autenticação Mútua mTLS

### ISSUE THREAD

**Issue by raffamz** [bacen/pix-api#220]
Caros amigos,
Tenho dúvida quanto ao item de segurança do manual pág 34 , item 5.1 2a, onde diz:

**"Cada PSP deve possuir seu próprio Authorization Server e Resource Server associado à API Pix, e ambos devem implementar TLSmútuo."**

Utilizamos um Manager com SaaS, e eles provem a parte de authorization server e resource server. Podemos utilizá-lo, ou como é um SaaS, teremos que construir um novo authorization server?

Obg antecipadamente.

**Comment by ninrod** [comment]
@raffamz , esta é uma liberalidade do PSP recebedor. Você, como PSP recebedor, decide que tipo de software vai utilizar para implementar a especificação. Se é um software escrito por vocÊ mesmo ou se é um software escrito por terceiros, não importa à luz da especificação. O que é importante é seguir a especificação.
