### ISSUE TITLE
[Dúvida] sobre a validação de campos da cobrança por parte do PSP pagador

### ISSUE THREAD

**Issue by jocimarcan** [bacen/pix-api#221]
Caros,

O PSP do pagador, ao ler um QR code dinâmico que representa uma cobrança de pagamento com data de vencimento, é obrigado a acatar a cobrança, conforme resposta em outras issues.

Minha dúvida é sobre a validação de campos da cobv pelo PSP pagador:

1) O PSP pagador é obrigado a fazer as validações para se certificar que o valor final está correto? Nesse caso ele precisaria considerar todas as regras de cálculo especificadas, considerando codMun, DPP, fuso horário, etc; e mesmo assim ele não conseguiria validar com precisão o valor final, uma vez que o PSP pagador não tem controle sobre o tempo que a PACS levará para chegar ao PSP recebedor - tempo suficiente para alterar o dia, o que impacta no valor final. 

2) Caso o PSP pagador não seja obrigado a fazer essas validações sobre o valor final, ele poderia mesmo assim negar o pagamento de uma cobrança com cálculo errado? Ou ele deveria acatar a cobrança mesmo assim?

Obrigado

**Comment by rubenskuhl** [comment]
O caso 1 tem duas possibilidades de acontecer: 
- Pagamentos entre 23h59m50s e 23h59m59s.999999, pois o tempo de pagamento esperado do Pix é até 10s. 
- Pagamentos entre 23h00 e 23h59, caso caia na malha fina que permite até 60 minutos para avaliação. 

Acho que levar em conta o horário atual é importante para alertar o pagador dessa possibilidade de girar o dia.

**Comment by franciscotfmc** [comment]
Pegando o bonde na dúvida do @jocimarcan .

No caso em que o usuário pagador seleciona uma data de pagamento anterior ao vencimento, qual o comportamento adequado? Consumir novamente o payload? _(de forma que o valor final seja recalculado pelo PSP recebedor..)_

**Comment by ninrod** [comment]
> O PSP pagador é obrigado a fazer as validações para se certificar que o valor final está correto?

Não. 

> Caso o PSP pagador não seja obrigado a fazer essas validações sobre o valor final, ele poderia mesmo assim negar o pagamento de uma cobrança com cálculo errado?

Acho que não entendi. Além de o PSP pagador não ser obrigado a fazer as validações, ele nem tem condições de fazê-lo então não haveria nem justificativa para "negar" o pagamento com base nisso.

**Comment by jocimarcan** [comment]
@franciscotfmc eu também levantei essa dúvida/preocupação em outra issue #203  e infelizmente parece que o Bacen não pensou nessa experiência ainda. 
Não vejo outra saída senão ter que fazer duas chamadas:
A primeira, usando a DPP com a data atual de consulta e oferencendo ao usuário a possibilidade de agendamento ao exibir os dados da cobrança atual;
A segunda, quando o usuário selecionar pagar numa outra data, essa chamada deverá ser realizada com a DPP igual a data selecionada pelo usuário. 
Caso o Bacen não se manifeste a tempo, esta parece ser a melhor alternativa para os PSPs.

**Comment by ninrod** [comment]
> No caso em que o usuário pagador seleciona uma data de pagamento anterior ao vencimento, qual o comportamento adequado? Consumir novamente o payload? (de forma que o valor final seja recalculado pelo PSP recebedor..)

Exatamente. Não há outra maneira.
