### ISSUE TITLE
Status de Cobrança - REMOVIDA x REMOVIDO

### ISSUE THREAD

**Issue by HMPannuti** [bacen/pix-api#222]
A partir da v 2.1.0-rc.0, os valores possíveis para o status da Cobrança passaram a ser:
- ATIVA
- CONCLUIDA
- REMOVID**O**_PELO_USUARIO_RECEBEDOR
- REMOVID**O**_PELO_PSP

Até a versão 2.0.0, os valores eram:
- ATIVA
- CONCLUIDA
- REMOVID**A**_PELO_USUARIO_RECEBEDOR
- REMOVID**A**_PELO_PSP
Ou seja, todos os status no feminino.

Alguns PSPs estão utilizando apenas status no feminino, conforme a versão anterior daAPI Pix. 
Outros, estão seguindo a 2.1, com os REMOVIDO_*.

Os PSPs que ainda estão seguindo a 2.0 em ambiente de produção estão incorretos, certo?
Ou seja, todos devem utilizar apenas os status de Cobrança redefinidos na versão 2.1?

**Comment by randrade86** [comment]
Para mim ficou bem estranho... Entendo que o `status` é sempre da cobrança, então deveria ser sempre no gênero feminino. 

Inclusive, se falarmos de versionamento semântico, a versão 2.1.x não poderia quebrar as implementações de 2.0.x

**Comment by christianf2029** [comment]
Perfeitamente @randrade86, compartilho das suas considerações.

**Comment by ninrod** [comment]
@HMPannuti , 

Esse é um bug da 2.1.X. Tem que ser tudo no feminino, conforme você aponta. 

Vamos consertar na 2.2.0, pedimos perdão pelo transtorno, acabou passando em nossa revisão. É um bug mesmo, não tem muito o que fazer a não ser consertarmos o mais rápido possível.

**Comment by ninrod** [comment]
consertado na 2.2.0, a ser lançada em instantes, mais uma vez, pedimos desculpas pelo transtorno.

**Comment by renatofrota** [comment]
2.0.0 era tudo feminino
2.1.0-rc.0 'splitou' pra feminino/masculino (e permanece até a 2.1.2)
2.2.0 vai voltar pro feminino

A única explicação que vejo: a 2.1.0-rc.0 "partiu" de um código que não era a 2.0.0.

Sugestão para evitar isso: sempre trabalhar em uma nova versão partindo da última versão **publicada** e não de outro código interno qualquer que não tenha sido publicado, por qualquer razão que seja (controle de versão! :stuck_out_tongue_closed_eyes:)
