### ISSUE TITLE
Status das cobranças ao detalhar os lotes

### ISSUE THREAD

**Issue by christianf2029** [bacen/pix-api#224]
Olá, boa tarde.

Encontrei uma situação que julguei estranha na especificação das cobranças com vencimentos e seus lotes:
- O atributo `status` das **cobranças com vencimentos** pode ter os seguintes valores:
`["ATIVA", "CONCLUIDA", "REMOVIDO_PELO_USUARIO_RECEBEDOR", "REMOVIDO_PELO_PSP"]`;

![image](https://user-images.githubusercontent.com/16386736/101047782-e0d32a80-3560-11eb-80ac-aa8baa958adb.png)

- O atributo `status` do _array_ **de cobranças de um lote** pode ter os seguintes valores: 
`["EM_PROCESSAMENTO", "CRIADA", "NEGADA"]`;

![image](https://user-images.githubusercontent.com/16386736/101048061-1a0b9a80-3561-11eb-97eb-de1526002544.png)

Eu imagino que seja um problema, até porque desconheço esses novos status **ao detalhar os lotes**, não os vi em nenhuma documentação. 

É realmente um BUG? Devo seguir ao detalhar os lotes **os status já conhecidos das cobranças**?

**Comment by ninrod** [comment]
seria o "status da cobrança no contexto de sua criação via lote". 

redação será corrigida na 2.2.0, obrigado pelo reporte @christianf2029

**Comment by christianf2029** [comment]
Então realmente são novos status @ninrod ?

**Comment by christianf2029** [comment]
Conferi a 2.2.0-rc0 e agora fez sentido para mim, obrigado.
