### ISSUE TITLE
Validação do Valor - Cobrança com Vencimento

### ISSUE THREAD

**Issue by eduardosomavilla** [bacen/pix-api#228]
Bom dia!

No recebimento de uma pacs.008 vinda de um PSP PAGADOR referente a uma COBRANCA COM VENCIMENTO, caso a PSP RECEBEDORA deseje previamente validar o valor, antes de confirmar e creditar o valor para o cliente final, vimos que não há o campo referente ao código do município que é utilizado nos cálculos das cobranças com vencimento.

**Como poderíamos proceder nesses casos para validar o valor?** (entendemos que esse cenário ocorre quando por exemplo a aplicação do PSP pagador tenha alguma vulnerabilidade e permita que seu front altere o valor no momento do pagamento).

**Comment by ninrod** [comment]
@eduardosomavilla , bom dia. 

Já respondido na #199: https://github.com/bacen/pix-api/issues/199#issuecomment-733066883
