### ISSUE TITLE
[Dúvida] API PIX - Padronização

### ISSUE THREAD

**Issue by mariapessoacaldas** [bacen/pix-api#23]
**Descreva sua dúvida ou problema**
1) Vocês já nos responderam que não é possível o envio de campos adicionais na API. Gostaria de entender se tivermos todas as APIs padronizadas no portfólio (exatamente iguais), se poderemos ter outras APIs com objetivos diferentes das padrões (exemplo API para geração de QR Code Estático ou consultas com visões distintas). 

No mesmo cenário (onde o PSP possui a APi padrão), poderia oferecer outra API para complementar serviços adicionais oferecidos pel participante? 
Exemplo: Emissão de QR Code com disparo da fatura para lista de emails indicado

**Sistema ou Área**
APi Pix, QR code

**Comment by ninrod** [comment]
@mariapessoacaldas , 

Seria interessante aguardar a versão final da regulamentação, mas posso adiantar que o Bacen estaria obrigando os PSPs recebedores que ofertarem integrações via software com o arranjo Pix a implementar esta API conforme definida aqui.
