### ISSUE TITLE
Payload após pagamento : erro ou CONCLUIDA ?

### ISSUE THREAD

**Issue by rubenskuhl** [bacen/pix-api#232]
Algo que a API 2.2.0 não parece ter clarificado é se para um payload que foi criado por cob (e não por payloadlocation), se após a cobrança ser paga ela deve passar a retornar CONCLUIDA ou um código de erro. 
Há algo em outro instrumento especificando isso ?

**Comment by ninrod** [comment]
Essa "descrição do funcionamento da máquina de estados" é um gap mesmo, apesar de ser uma máquina de estados bem simples. Estou pensando em adicionar a explicação na descrição do endpoint na 2.2.1. 

Ë assim: se a cobrança está ATIVA e aí recebeu um pagamento __de qualquer valor__, passa para CONCLUÍDA.

**Comment by rubenskuhl** [comment]
> Essa "descrição do funcionamento da máquina de estados" é um gap mesmo, apesar de ser uma máquina de estados bem simples. Estou pensando em adicionar a explicação na descrição do endpoint na 2.2.1.
> 
> Ë assim: se a cobrança está ATIVA e aí recebeu um pagamento **de qualquer valor**, passa para CONCLUÍDA.

Mas se o valor for diferente do da cobrança, o PSP recebedor não tem que recusar o pagamento e manter a cobrança ATIVA ?

**Comment by ninrod** [comment]
> Mas se o valor for diferente do da cobrança, o PSP recebedor não tem que recusar o pagamento e manter a cobrança ATIVA. 

Sim, teria que recusar. Mas por erro, pode ser que entre uma cobrança com valor diferente. E lembre-se que uma cobrança com vencimento pode apresentar "vários valores corretos".

**Comment by rubenskuhl** [comment]
> > Mas se o valor for diferente do da cobrança, o PSP recebedor não tem que recusar o pagamento e manter a cobrança ATIVA.
> 
> Sim, teria que recusar. Mas por erro, pode ser que entre uma cobrança com valor diferente. E lembre-se que uma cobrança com vencimento pode apresentar "vários valores corretos".

Se eu já estava convencido a usar cobrança imediata ao invés de cobrança com vencimento, agora tenho certeza... ;-)
Acho que a questão está resolvida e vou fechar o issue.

**Comment by ninrod** [comment]
Ok @rubenskuhl. É importante realmente analisar qual é o instrumento que mais se encaixa no seu caso de uso. 

A cobrança com vencimento é bem mais complexa. Só vale a pena em cenários que requeiram esta sofisticação.
