### ISSUE TITLE
Dúvida - Divergências entre nomenclatura do txId nas versões 2.0 e 2.1

### ISSUE THREAD

**Issue by rafaelchagasb** [bacen/pix-api#237]
Ao consumir os serviços de qrcode dinâmico das instituições verifiquei uma falta de padronização na escrita do atributo txId do payload JSON.

Percebi que existem divergências nas próprias documentações do Bacen e queria saber qual é a correta nomenclatura do campo TransactionIdentification<txId> visto que em cada fonte o campo está de uma maneira diferente.

Visto que os payloads da versão 2.x são compatíveis entre si, os nomes devem ser iguais entre as versões.

Segue prints e relação das nomenclaturas.

### **2.0.0**

Open API: https://github.com/bacen/pix-api/releases/download/2.0.0/spec.yaml
Example value: **txId**
Schema: **txid**
Manual de Iniciação 2.0:  **txid**

![api200_doc](https://user-images.githubusercontent.com/724699/101485436-eacaa400-3939-11eb-9e16-41615ac38d72.png)
![api200_example](https://user-images.githubusercontent.com/724699/101485439-ebfbd100-3939-11eb-8e3b-5eb1532aaf45.png)
![api200_manual](https://user-images.githubusercontent.com/724699/101485442-ec946780-3939-11eb-8aa3-1a5cfc981b26.jpg)

### **2.1.0** 

Open API: https://github.com/bacen/pix-api/releases/download/2.1.0/spec.yaml
Example value: **txid**
Schema: **txid**
Manual de Iniciação 2.1: **txId**

![api210_doc](https://user-images.githubusercontent.com/724699/101485490-fe760a80-3939-11eb-966d-8e50ff27ff0c.png)
![api210_example](https://user-images.githubusercontent.com/724699/101485492-ff0ea100-3939-11eb-83d3-8677ed35b0e6.png)
![api210_manual](https://user-images.githubusercontent.com/724699/101485497-ffa73780-3939-11eb-98ad-f85b34d53cb0.jpg)

**Comment by ninrod** [comment]
> 2.0.0
Open API: https://github.com/bacen/pix-api/releases/download/2.0.0/spec.yaml
Example value: txId
Schema: txid
Manual de Iniciação 2.0: txid

o Schema está correto. O "exemplo" tem um "typo". é i minúsculo mesmo. 

> 2.1.0
Open API: https://github.com/bacen/pix-api/releases/download/2.1.0/spec.yaml
Example value: txid
Schema: txid
Manual de Iniciação 2.1: txId

Aqui o manual de iniciação apresenta um "typo". O schema continua correto.

**Comment by rubenskuhl** [comment]
Quais PSPs estão incorretamente apresentando txId ao invés de txid ?
