### ISSUE TITLE
Geração do QRCode

### ISSUE THREAD

**Issue by raffamz** [bacen/pix-api#238]
Amigos,
Boa tarde!
Estou implementando a API PIX, tag de **cobrança imediata**. Eu entendia que a criação da cobrança imediata gerava um _qrcode_ e salvava em um domínio ( o mesmo da url do _location_).
Na  leitura da documentação, o psp receber pode gerar o _qrcode_, mas nao nos recursos da cobrança imediata.
Dúvidas:
- temos que gerar o _qrcode_ base64?
- _location_ guarda uma imagem do _qrcode_ ou é um get para um json com dados da cobrança?

Obrigado antecipadamente pela ajuda!

**Comment by rubenskuhl** [comment]
O ideal para ter maior portabilidade é você mesmo gerar o EMV/BRCode e você mesmo gerar a imagem do QR-Code a partir do EMV. O location é JSON com dados de cobrança, que é ligado pelo PSP pagador para entender os parâmetros da cobrança.

**Comment by raffamz** [comment]
Obrigado pela informação.

-O EMV/BRCode é uma necessidade/especificação da API PIX? 
-A url do location é direcionada para o recurso da API PIX CobPayload (/{pixUrlAcessToken})?

Abs

**Comment by rubenskuhl** [comment]
> Obrigado pela informação.
> 
> -O EMV/BRCode é uma necessidade/especificação da API PIX?

É uma necessidade para todos os arranjos de pagamento no Brasil, inclusive o Pix. 
https://www.bcb.gov.br/content/estabilidadefinanceira/spb_docs/ManualBRCode.pdf

> -A url do location é direcionada para o recurso da API PIX CobPayload (/{pixUrlAcessToken})?

Isso mesmo.

**Comment by rubenskuhl** [comment]
Alguns sites que ajudam a montar/desmontar o EMV do Pix:
https://gerarqrcodepix.com.br/
https://pix.ae
https://pix.nascent.com.br/tools/pix-qr-decoder/
https://openpix.com.br/qrcode/scanner/
https://openpix.com.br/qrcode/debug/

**Comment by mauruco** [comment]
Bom dia, amigos.
Tenho uma dúvida de nomenclatura.
{pixUrlAcessToken} não deveria se chamar txid?
Ou {pixUrlAcessToken} é um token temporário que lava a o txid?
Obrigado
