### ISSUE TITLE
[Dúvida] no [PIX] - Motivos de devolução

### ISSUE THREAD

**Issue by Jenicrist** [bacen/pix-api#24]
No documento de Requisitos Mínimos para experiência do usuário, informa a obrigatoriedade de o usuário selecionar, entre a lista de motivos padronizados, o motivo da devolução.

Contudo, não está na documentação nem na API quais são os motivos padronizados.

**Sistema ou Área**
Iniciação de Pagamentos

**Comment by ninrod** [comment]
@Jenicrist , estamos verificando essa questão. Obrigado por ter reportado.

**Comment by Jenicrist** [comment]
Temos alguma previsão de entrega desses motivos?

**Comment by ninrod** [comment]
@Jenicrist , boa tarde. 

>  Temos alguma previsão de entrega desses motivos?

Sim, esta questão será resolvido na `2.1.0`.

**Comment by ninrod** [comment]
fechando porque já existe #10
