### ISSUE TITLE
cash back

### ISSUE THREAD

**Issue by scoobiii** [bacen/pix-api#255]
Olá,
API PLIM Monetizador da economia circular no ato da compra

Dúvida: Como programar e aplicar cashback no pix?

Atores:

Cliente:
Vendedor:  de marreteiro vendendo refrigerante cerveja agua na rua a Hipermercado Físico ou Marktplace passando por qualquer coisa produzida e embalada no pib global.
Agente de Reciclagem Móvel: o homem do saco, carroceiro, tiozinho da pirua, ..., ..., ...., ......
Agente de Reciclagem Fixo: caçambas esparramadas pela cidade,..,supermercados,..,.ecoponto$..,....S.A

Transações: R - CVREP - Pensa em Reciclar, depois.... Comprar, Vender, Receber, Entregar e Pagar
 
C (familia B ou C, A, ...) compra R$1600,00 mensalmente de V
V vende pix de R$1600,00 sendo R$16,00 (1% valor intrínseco das embalagens. Ref. O mercado paga R$0,05 por latinha vazia de coca cola de alumínio, ou 1% do valor do produto)
C recebe produtos de V
C paga pix de R$1600 a V
C consome os produtos, entrega as embalagens a ARF.
ARF paga R$16 pix a C
C, com preguiça, aciona ARM
C paga R$16 + custo logístico de deslocamento do ARM. Sim, enquanto o homem do saco (garimpadores) e carroceiros não forem remunerado pelo deslocamento, assim como o Uber é, continuarão invisíveis e fora do sistema financeiro.
ARM recebe R$16 pix e a distancia logística

https://github.com/scoobiii/hackathon-apicon-2020-plimm
https://github.com/scoobiii/PLIMM-Bank

**Comment by rubenskuhl** [comment]
Me parece que o split payment já comentado em #66 e #229 atenderia o cashback imediato, e que os posteriores poderiam ser atendidos pelo #254 . 
O resto me parecem regras de negócios de uma cadeia de valor específica.
