### ISSUE TITLE
Agendamento de Pix Cobrança Vencimento + alteração via patch /cobv

### ISSUE THREAD

**Issue by franciscotfmc** [bacen/pix-api#256]
Boa tarde!

Uma vez que eu tenha agendado um Pix referente a uma cobrança com vencimento para uma data futura, o PSP Pagador provavelmente terá anotado o valor do pagamento que deverá ser liquidado.

Nesse meio tempo, o PSP Recebedor pode, a qualquer momento, alterar a cobrança, de forma que o valor final anotado pelo PSP Pagador não mais condiz com valor real esperado.

Quais os pensamentos a respeito disso?
- Envia-se a ordem assim mesmo e espera-se que o recebedor a recuse?
- Consulta-se novamente o payload para novo cálculo do valor final imediatamente antes do envio ao SPI? _Nesse caso, me parece necessária uma nova confirmação do usuário pagador. Só de escrever isso já não me parece o melhor caminho..._ 😄

**Comment by rubenskuhl** [comment]
Eu tenderia mais à primeira opção... porém, o conhecimento prévio permitiria ação do pagador dentro do prazo ainda sem juros. Dilema complexo.

**Comment by franciscotfmc** [comment]
Boa tarde @ninrod! Tudo bem?

Algum insight sobre essa questão?

**Comment by ninrod** [comment]
> Boa tarde!

> Uma vez que eu tenha agendado um Pix referente a uma cobrança com vencimento para uma data futura, o PSP Pagador provavelmente terá anotado o valor do pagamento que deverá ser liquidado.

> Nesse meio tempo, o PSP Recebedor pode, a qualquer momento, alterar a cobrança, de forma que o valor final anotado pelo PSP Pagador não mais condiz com valor real esperado.

> Quais os pensamentos a respeito disso?

> Envia-se a ordem assim mesmo e espera-se que o recebedor a recuse?
Consulta-se novamente o payload para novo cálculo do valor final imediatamente antes do envio ao SPI? Nesse caso, me parece necessária uma nova confirmação do usuário pagador. Só de escrever isso já não me parece o melhor caminho... 😄

Bom dia @franciscotfmc , desculpe a demora em responder sua questão. 

O usuário recebedor que está alterando sua cobrança deve ter em mente este cenário de "agendamentos" e providenciar adequadamente um "tempo hábil" para ajustes por parte do usúario pagador, informar apropriadamente, etc...

Dito isto, a "solução" seria negar o pagamento caso o valor seja o valor da revisão antiga, por exemplo, porque supõe-se que o usuário pagador teve tempo hábil, foi comunicado adequadamente quanto à mudança (inclusive, pode ter sido uma mudança de comum acordo).

**Comment by ninrod** [comment]
> Eu tenderia mais à primeira opção... porém, o conhecimento prévio permitiria ação do pagador dentro do prazo ainda sem juros.

Entendo que uma vez que  uma cobrança esteja "no ar", ela está "valendo", podendo ser paga a qualquer momento. Se a partir de um monento xyz na linha do tempo o usuário recebedor entendeu que a cobrança está errada, ele pode tomar algumas ações, mas sempre entendendo que durante o período em que a cobrança está no ar, ela está "valendo".

**Comment by franciscotfmc** [comment]
Boa tarde, obrigado @ninrod!

Acreditamos também que seja o melhor caminho: recusa-se a revisão antiga, pois a que tá valendo é a última.
