### ISSUE TITLE
GET /{pixUrlAccessToken} e o mTLS - acesso via PSP Pagador

### ISSUE THREAD

**Issue by raffamz** [bacen/pix-api#257]
Caros amigos,

Minha dúvida sobre o acesso do GET /{pixUrlAccessToken} , com boa parte do assunto tratado aqui:
https://github.com/bacen/pix-api/issues/78#issuecomment-708589080

Porém, ainda nao ficou claro para mim como PSP pagador vai acessar isso, já que o acesso está protegido por client credentials e mTLS. Ou está é uma url aberta pra internet?

Agradeço antecipadamente!

Abs

**Comment by rubenskuhl** [comment]
É aberto, não tem mTLS, e o endpoint nem precisa ser o mesmo da API Pix autenticada.

**Comment by raffamz** [comment]
Rubenskuhl, Obrigado!!
