### ISSUE TITLE
Dúvida no QRCode - Lista dos domínios autorizados a gerarem QR Codes no âmbito do SFN

### ISSUE THREAD

**Issue by anderjoy** [bacen/pix-api#26]
**Descreva sua dúvida ou problema**
No documento de especificações versão 6.2, página 36, nota de rodapé 12, tem a seguinte citação:

> A URL/URI está hospedada no domínio do PSP do Recebedor. As validações de segurança incluem
> a verificação da validade do certificado apresentado no domínio e a verificação da presença do
> domínio na lista dos domínios autorizados a gerarem QR Codes no âmbito do SFN. Caso as
> validações sejam positivas, o aplicativo também recupera a chave pública do PSP/domínio em
> questão.

Nada foi especificado sobre essa **lista dos domínios autorizados a gerarem QR Codes no âmbito do SFN**.

- Onde estará hospedado?
- Como recuperar/consultar?
- Como cadastrar um domínio do PSP no âmbito do SFN?

**Sistema ou Área**
QR Code

**Comment by ninrod** [comment]
@ccmario essa comunicação acontecerá no sistema `ARQ` via ICOM, tanto para informar quanto para consultar. Maiores informações serão disponibilizadas em breve.

**Comment by ninrod** [comment]
@ccmario, @anderjoy  e demais, resposta oficial: 

> Até o dia 06/10, será realizada publicação de nova versão do Manual de Segurança do Pix contendo algumas informações adicionais sobre o processo de validação dos certificados de sites de QR Code.
Nesta data, será também enviado um comunicado disponibilizado o processo de recepção dos arquivos CERTQRC, bem como a possibilidade de download do arquivo contendo os certificados associados aos sites de QR Code dos demais PSPs.
