### ISSUE TITLE
[Sugestão] Chave aleatória especifica para conciliação.

### ISSUE THREAD

**Issue by ezequielsp** [bacen/pix-api#260]
Minha sugestão é ter uma chave "aleatória" que apenas aceite pagamentos com txid, então se um usuário utilizar um App que não envia o txid ou tentar fazer um pix direto para chave não conseguiria. 

Cenário 1: 
   - Como está hoje um usuário gera um qrcode dinâmico mas na hora de pagar o App não informa o txid ou ele faz direto para a chave mesmo. Então tenho que fazer uma busca por nome de usuário e valor para fazer a devolução.
   - Se existisse essa chave específica informaria o erro e o usuário poderia pagar de outro App.
 
Cenário 2:
   - Rejeitar pagamentos de cpf divergente. Gostaria também que fosse opcional aceitar ou rejeitar pagamentos que o cpf do pagador seja diferente do devedor. Nesse caso essa chave poderia indicar essa regra também.

Não sei dizer se seria uma boa prática ter chaves que comecem com T por exemplo para esse caso, mas é uma ideia.

Talvez isso deveria ser implementado nos PSPs mas deixo registrado aqui minha sugestão.

**Comment by ninrod** [comment]
@ezequielsp , 

isso já é possível hoje. bastaria o PSP implementar essa funcionalidade e disponiblizar essa "flag" de chave em seu dashboard. Chegou uma PACS.008 para aquela chave, sem txid, rejeita.

**Comment by ezequielsp** [comment]
Excelente, obrigado por responder, de qualquer forma então é como pensei, o PSP deve implementar.

**Comment by ninrod** [comment]
Não seria nem apenas para "aquela chave", mas também fechando por "agencia e conta", para contornar o caso em que PSPs pagadores também não enviam a informação de "proxy" (chave dict) na PACS.008.

**Comment by rubenskuhl** [comment]
> Excelente, obrigado por responder, de qualquer forma então é como pensei, o PSP deve implementar.

Deve não no sentido de ser obrigado, mas de que o PSP pode se assim se assim quiser atender demandas como essa. 
Pelo menos um PSP já manifestou vontade de disponibilizar esse recurso em algum momento.

**Comment by ezequielsp** [comment]
E poderia ser por cpf do devedor divergente do cpf do pagador?

**Comment by ninrod** [comment]
> E poderia ser por cpf do devedor divergente do cpf do pagador?

Essa é uma excelente pergunta. 

O PSP do recebedor tem uma gama de critérios a sua disposição para negar uma pacs, mas não acredito que este conjunto de critérios esteja 100% claro, cristalino e definido. 

Você já começa aqui a trilhar um terreno que beira os limites do caminho batido. Eu recomendo consultar o decem em pix@bcb.gov.br.

**Comment by ezequielsp** [comment]
Digo isso porque como está eu teria que receber, buscar o txid + cpf do devedor e caso não encontrar o pagamento, cancelar o pagamento e fazer a devolução. Agora se o PSP rejeita, permite que o usuário pague da sua conta, com seu cpf.
