### ISSUE TITLE
[DUVIDA] O PSP Itaú tem negado QRCodes Estáticos com txId

### ISSUE THREAD

**Issue by rfbastos** [bacen/pix-api#263]
Olá

Fiz um teste gerando um QRCODE Estático dentro do APP Do banco. Com a linha copia e cola em maos eu desmembrei para pegar cada campo de forma separada e poder jogar no meu sistema para testar.

Fiz um teste gerando por dentro do meu sistema com os mesmos dados desta linha copia e cola e OK, também funcionou.

A linha contempla chave cpf ou cnpj (testei apenas com estas)
Valor = 0.01, 1.00 , 5.00 e 10.00 (testado com esses valores)
txId = gerado (tam 15) ou ***

Ao alterar valor e usar mesmo TXID da erro.
Ao alterar txId e mesmo valor da erro
Ao enviar txid = *** também da erro.

Na pagina https://qrcodepix.tk/  vocês podem testar a geração do QRcode estático exatamente como tenho utilizado.

Todos os outros bancos testados funcionaram perfeitamente.

A linha chega a ser Lida, traz os dados (nome, valor, e etc) mas ao finalizar recebo a mensagem

"Pagamento rejeitado pelo PSP do recebedor"

Tentando pagar para o ITAU do

NEXT - BRADESCO
CAIXA

Ao usar NUBANK para pagar recebo a mensagem

"A instituição de destino não está respondendo" (com um txid aleatorio)

Com o txId = *** funciona normalmente pelo nubank.

Apenas pelo nubank, caixa e bradesco continuam negando

**Comment by grudnitzki** [comment]
Dá uma olhada em #214 onde descrevo exatamente este problema.

**Comment by rfbastos** [comment]
Muitíssimo obrigado. É exatamente a mesma coisa vou fechar e acompanhar pela #214
