### ISSUE TITLE
Tarifas Pix cobradas pelos PSPs

### ISSUE THREAD

**Issue by grudnitzki** [bacen/pix-api#266]
Seria interessante ter uma tabela comparativa das tarifas de serviços relacionados ao Pix cobradas pelos bancos e pelos demais PSPs.

Sou correntista do Itaú. Segue minha contribuição para a tabela:

ITAÚ
=======
Cada transferência recebida pelo Pix será tarifada pelo banco em 1,45% do valor pago.
O valor mínimo da tarifa por transação é R$1,75 e o valor máximo é R$10,00
Referência: https://www.itau.com.br/content/dam/itau/empresas/tarifas/tabela-geral-pj.pdf

Peço que ajudem enviando as tarifas que tiverem acesso. Vou compilar todas em uma planilha. Pode ser útil para escolher onde receber seus Pix e apontar abusos como o do Itaú.

**Comment by rubenskuhl** [comment]
Gerencianet: 0.99%, limitado a 0,89. QR-Code dinâmico gerado adiciona 0,01. Fonte: https://gerencianet.com.br/tarifas/

**Comment by rubenskuhl** [comment]
Mercado Pago: 0.99%, o céu é o limite. Fonte: https://www.mercadopago.com.br/ajuda/custo-receber-pagamentos_220

**Comment by rubenskuhl** [comment]
Adyen: 12 centavos de dólar mais 50 centavos de Real. Fonte: https://www.adyen.com/pt_BR/metodos-pagamento/pix
(Obs.: Recebimento não imediato, prazo similar a cartão de débito, e em nome da Adyen)

**Comment by rubenskuhl** [comment]
PagHiper (também não PSP, pagamento vai para a conta deles): R$ 0,99. Tarifa não pública, aparece para quem tem conta em https://www.paghiper.com/painel/detalhes-da-conta/ .

**Comment by grudnitzki** [comment]
Obrigado @rubenskuhl 

Entendi que o Banco Central cobrará dos bancos **1 centavo** para cada **10 transações** no Pix. Daí o banco multiplica este custo **por mil** e cobra uma exorbitância do correntista, para manter a bolada que sempre faturou com DOC, TED e boleto.

Ainda tenho esperança que alguma fintech cobre zero pelo Pix e não participe deste verdadeiro conluio.

**Comment by rubenskuhl** [comment]
Custar 0.001 pagos ao BACEN não significa que custa só isso... há diversos custos bem reais. Então zero eu não gostaria de pagar, pq eu quero ser o cliente e não o produto... mas pagar pouco sim. ;-)

**Comment by grudnitzki** [comment]
@rubenskuhl  Cobrar zero nem sempre significa que você é o produto. No caso dos bancos, eles já faturam **MUITO** com os valores recebido nas contas correntes. Estes valores muitas vezes são mantidos em conta pelo correntistas e aplicados em investimentos do próprio banco. Por isto é provável que algumas fintechs cobrem zero pelo Pix recebido, sem limites mensais.
