### ISSUE TITLE
Consultas em GET /pix não admite uso do parâmetro txid para buscar Pix recebidos via QR estático

### ISSUE THREAD

**Issue by renatofrota** [bacen/pix-api#269]
Boa tarde,

A especificação do endpoint `GET /pix` só admite consultas por `txid` de comprimento {26,35}, impossibilitando consultas a Pix recebidos via QR Code estático (com txid de comprimento {1,25}), forçando o uso de polling com escopo muito mais abrangente (sem txid), o que é muito mais oneroso tanto para o PSP quanto para o EC.

**Comment by ninrod** [comment]
Bom dia @renatofrota , 

Se está assim é um bug na regex. Deveria ser {1,35}. Consertaremos na `2.2.1`.

**Comment by ninrod** [comment]
O bug está ali no item circulado. Muito bem apontado @renatofrota.

Deveria ser `[a-zA-Z0-9]{1,35}`

![image](https://user-images.githubusercontent.com/8352747/103357293-97a7c500-4a91-11eb-8321-16358d92a34d.png)

**Comment by ninrod** [comment]
já no master.
