### ISSUE TITLE
[Dúvida] no [API Pix] - Quem pode consumir a API

### ISSUE THREAD

**Issue by CharlesMendes** [bacen/pix-api#27]
**Descreva sua dúvida ou problema**
Na [documentação Iniciação Pix](https://www.bcb.gov.br/content/estabilidadefinanceira/pix/Regulamento_Pix/II_ManualdepadroesparainiciacaodoPix-versao1.1.pdf), é especificado que a API Pix é oferecida pelo PSP Recebedor, nesse caso, o Participante Indireto poderia ter credenciais para acesso a API Pix independente do seu Participante Direto?
![image](https://user-images.githubusercontent.com/1323305/94501032-31cc4880-01d7-11eb-9f21-afb241958505.png)

**Sistema ou Área**
API Pix

**Identificador do Problema**
N/A

**Mensagens Enviadas / Recebidas**
N/A

**URL de conexão**
N/A

**Dados adicionais**
Ou seja, o se um Participante Indireto está relacionado a um Participante Direto que ainda não oferece a API, o Indireto consegue acessar e oferecer ela independentemente?

**Comment by ninrod** [comment]
Prezado @CharlesMendes , boa noite. 

É perfeitamente possível que o PSP indireto ofereça a API Pix. Qualquer PSP que ofereça contas transacionais a seus clientes (como é o caso de PSPs indiretos), pode oferecer a API Pix.

**Comment by rubenskuhl** [comment]
E complementando, não vejo impedimento do PSP Indireto ter API Pix quando o PSP Direto não tem. As APIs entre os PSPs Diretos e Indiretos não são alvo de regulamentação e desde que elas sejam completas o suficiente para propiciar o funcionamento da API Pix no indireto, o fato do PSP Direto não ter API Pix é puramente decisão comercial do PSP Direto.

**Comment by ninrod** [comment]
@rubenskuhl , perfeita a colocação.
