### ISSUE TITLE
PATCH em /cob (cobranças imediatas) 

### ISSUE THREAD

**Issue by rubenskuhl** [bacen/pix-api#272]
Duas dúvidas relativas a cobranças imediatos (rota /cob):
- Ao fazer um PATCH, a data de criação da cobrança deve ser alterada para a data do PATCH ou mantida com a data do PUT que a criou ? 
- Ao fazer um PATCH do campo expiração, a referência para a nova expiração efetiva é a data de criação ou a data do PATCH ? Por exemplo, se for colocada expiração em 600 segundos, isso é 10 minutos depois da criação ou 10 minutos depois de quando foi feito o PATCH ?

**Comment by ninrod** [comment]
> Ao fazer um PATCH, a data de criação da cobrança deve ser alterada para a data do PATCH ou mantida com a data do PUT que a criou ?

Boa pergunta, mas mantém. É data de criação, e não de alteração.

> Ao fazer um PATCH do campo expiração, a referência para a nova expiração efetiva é a data de criação ou a data do PATCH ? Por exemplo, se for colocada expiração em 600 segundos, isso é 10 minutos depois da criação ou 10 minutos depois de quando foi feito o PATCH ?

A referência é sempre a data de criação, que nunca é alterada.
