### ISSUE TITLE
[Dúvida] na [API PIX] - Documentação

### ISSUE THREAD

**Issue by helsen** [bacen/pix-api#28]
Caros, 

Gostaria de tirar uma sobre os endpoints de cobrança:

Para a funcionalidade de criar uma cobrança, utilizando o QRCode dinâmico, em qual etapa do processo, o EMV para renderização do QRCode seria retornado? Ou o consumidor da API deverá montar o QRCode a partir do Response do endpoint de cobrança? Ou existe previsto um endpoint para as próximas versões da API que retorna o EMV?

Obrigado.

**Comment by ninrod** [comment]
> Ou o consumidor da API deverá montar o QRCode a partir do Response do endpoint de cobrança?

Perfeito. De posse do "location", ou do "endpoint" que servirá o payload de cobrança, você consegue montar a string EMV com base na especificação. 

A montagem da string do QR code (tanto estático quanto dinâmico), está fora da API Pix e pode ser oferecida por qualquer elemento de software.
