### ISSUE TITLE
Revisão cobrança com vencimento - edição/exclusão de campos

### ISSUE THREAD

**Issue by renanpto** [bacen/pix-api#281]
Bom dia,

Gostaria de esclarecer uma dúvida sobre qual deve ser o comportamento esperado ao revisar uma cobrança com vencimento.

Por exemplo, inicialmente a cobv foi criada informando todos os campos relacionados a valor (valor original, multa, juros, abatimento, desconto, etc).
`.......
"valor": {
	"original": "567.89",
	"multa": {
                "modalidade" :1,
		"valorPerc" : 2.34
          }
  },......`

No segundo momento, o usuário deseja remover as informações de multa, ao realizar a revisão, como essa "exclusao" de campos deve ser tratada ? Pois ao revisar, a API espera como entrada somente os campos "alterados", como o nó "multa" é opcional, caso não informado, não é possível saber se ele foi excluído ou simplesmente não alterado.

Obrigado!

**Comment by ninrod** [comment]
@renanpto , bom dia.

informa-se com `null`.

**Comment by renanpto** [comment]
no meu entendimento, null ou não informando o nó "multa" seria a mesma coisa, não ?

exemplo:
`"valor": { "original": "567.89", "multa": null },.` ou `"valor": { "original": "567.89" },.`

**Comment by ninrod** [comment]
> no meu entendimento, null ou não informando o nó "multa" seria a mesma coisa, não ?

Não. Tem que explicitamente citar os campos que você quer alterar. Se você não está falando nada sobre multa, então multa fica como está.

**Comment by wesleygonalv** [comment]
Então @ninrod, para remover os valores adicionados anteriormente na multa, seria enviado a multa com os valores nulos?

Exemplo:

"multa": {
      "modalidade": null,
      "valorPerc": null
}

**Comment by ninrod** [comment]
Seria:

```js
  ...
 "multa": null,
  ...
```

**Comment by wesleygonalv** [comment]
Mas @ninrod, isso seria o mesmo de não passar o campo multa.

**Comment by renatofrota** [comment]
> Mas @ninrod, isso seria o mesmo de não passar o campo multa.

Não é. Um campo multa com valor null, é "um campo multa, com valor null". Ele está **definido**, e tem valor nulo. É totalmente diferente de não passar nada. Verifique na sua linguagem de programação aí como verificar se uma chave de array/objeto **existe** ou está **definida** (sem verificar se há qualquer **valor** nela).

**Comment by ninrod** [comment]
> Mas @ninrod, isso seria o mesmo de não passar o campo multa.

A semântica do patch é: você cita os campos que quer mudar e cita também os novos valores. Se você não cita, não quer mudar.

**Comment by wesleygonalv** [comment]
> > Mas @ninrod, isso seria o mesmo de não passar o campo multa.
> 
> Não é. Um campo multa com valor null, é "um campo multa, com valor null". Ele está **definido**, e tem valor nulo. É totalmente diferente de não passar nada. Verifique na sua linguagem de programação aí como verificar se uma chave de array/objeto **existe** ou está **definida** (sem verificar se há qualquer **valor** nela).

Entendi, isso seria refazer o que é transparente para a api, no caso trabalhar em cima de um Serialization para identificar quando o campo está presente.

Estou utilizando jax-rs e a serialização do json para objeto java está transparente, tem alguma ideia de algo existente para esse cenário?

**Comment by renatofrota** [comment]
@wesleygonalv ,

Quando você decodifica o json recebido, tem um array/objeto da sua linguagem. Em seguida, é só testar se o índice `multa` **existe** no array/objeto (independente do seu **valor**). E, somente se existir, adicionar/atualizar (ou remover, se o valor for nulo) a multa na cobrança.

Exemplo (em PHP): https://3v4l.org/Keit8

**Comment by renatofrota** [comment]
[re-enviado, link incorreto na mensagem anterior]

@wesleygonalv ,

Quando você decodifica o json recebido, tem um array/objeto da sua linguagem. Em seguida, é só testar se o índice multa existe no array/objeto (independente do seu valor). E, somente se existir, adicionar/atualizar (ou remover, se o valor for nulo) a multa na cobrança.

Exemplo (em PHP): https://3v4l.org/cepSn
