### ISSUE TITLE
[Dúvida] Endpoint payload cobrança com vencimento - Nomenclatura parâmetros 

### ISSUE THREAD

**Issue by delimafcarol** [bacen/pix-api#287]
Os parâmetros do endpoint referente à cobrança com vencimento devem obrigatoriamente ser "codUm" e "DPP"?

Na documentação está descrito:
"No caso da cobrança referente a pagamento com vencimento, o PSP do pagador irá acessar a URL e
enviar a informação do código do município (codMun) do usuário pagador e a Data de Pagamento
Pretendida (DPP). "

Gostaria de confirmar se podemos assumir essa nomenclatura ("codUm" e "DPP") como regra.

**Comment by rcsilva83** [comment]
Sim, opcionalmente podem ser passados como "query params" os argumentos "codMun" e "DPP". Veja na [documentação do método no Swagger](https://bacen.github.io/pix-api/#/CobPayload/get_cobv__pixUrlAcessToken_) que acredito que ficará mais claro.

**Comment by delimafcarol** [comment]
Opa obrigada @rcsilva83.
Eu havia visto o swagger, só queria ter certeza que esses nomes eram padrão... Mesmo porque, se não fosse, eu teria uma dor de cabeça na hora de ler o QR. :p
Se pudessem deixar isto explicito no manual facilitaria.. Igual o fato da URL por vencimento ter obrigatoriamente o valor "/cobv", não abre marge para dúvidas ^^

**Comment by ninrod** [comment]
@delimafcarol , bom dia. 

> Se pudessem deixar isto explicito no manual facilitaria.. Igual o fato da URL por vencimento ter obrigatoriamente o valor "/cobv", não abre marge para dúvidas ^^

Acredito que a página 10 do manual de iniciação do Pix está redigida de maneira que deixa a questão explicita:

![image](https://user-images.githubusercontent.com/8352747/104736487-c83e5e80-5721-11eb-8dae-48dda8bcedbc.png)

**Comment by delimafcarol** [comment]
@ninrod 
Fiquei na dúvida se estaria apenas referenciando os nomes do swagger como exemplo, ou se era realmente uma regra.

Mas ficou claro agora,
obrigada! :)
