### ISSUE TITLE
Correlação do "ManualdepadroesparainiciacaodoPix" com a API Pix -  Juros e Multa

### ISSUE THREAD

**Issue by gpneto** [bacen/pix-api#29]
No Manual "II_ManualdepadroesparainiciacaodoPix-versao1.1.pdf" consta: 
"O QR Code dinâmico no Pix deve ser gerado por meio da API Pix".

Neste mesmo manual mostra que a cobrança pode ter valores de juros e multas, mas na API Pix não consta a entrada destes campos.

Minha dúvida é, no app iremos apresentar em tela para o usuário criar um QR Code Dinâmico com a opção de incluir Juros e Multa, mas não poderemos usar nesse momento a API Pix para criar a cobrança visto que não consta na API Pix?

**Comment by ninrod** [comment]
@gpneto , boa tarde.

> Neste mesmo manual mostra que a cobrança pode ter valores de juros e multas, mas na API Pix não consta a entrada destes campos.

será disponibilizada uma nova versão da API Pix, provavelmente `2.1.0`, em meados de outubros, que apresentará essa funcionalidade envolvendo juros, multa e afins.
