### ISSUE TITLE
[Dúvida] Autenticação com OAuth2 Mtls

### ISSUE THREAD

**Issue by viniciusxyz** [bacen/pix-api#291]
Bom dia,

Gostaria de confirmar o fluxo planejado para utilização do OAuth2 com Mtls é o descrito abaixo:

1 - O Mtls é realizado entre o cliente e OAuth2 Server.
2  - O OAuth2 Server faz a verificação do client_id e secret_id do usuário.
3 - O OAuth2 Server devolve um token com o membro cnf definido na [RFC 8705](https://tools.ietf.org/html/rfc8705#section-3.1)

Essa dúvida surgiu pois como temos o modelo de Mtls a autenticação pode ser realizada tanto com o client_id+secret_id quando por um client_id+public_key/private_key previamente configurada e segundo a [RFC 6749](https://tools.ietf.org/html/rfc6749#section-2.3) "The authorization server MAY accept any form of client authentication meeting its security requirements.", peço desculpas se perdi algo no meio do caminho.

**Comment by felipesevilhano** [comment]
Estou com a mesma dúvida

**Comment by alvarobacelar** [comment]
Pelo meu entendimento, o fluxo obrigatório exigido pelo Bacen é a utilização do mTLS direto com a API de callback, sem obrigatoriedade do oAuth.
Conforme mencionado nessa issue https://github.com/bacen/pix-api/issues/131#issuecomment-717546652, o minimo exigido é: 

> Apenas definimos uma 'linha mínima' de interoperabilidade, que significa exigir que o serviço webhook não seja 'público', e que a chamada (https) parta de um cliente 'autenticado' (o PSP chamando o serviço-webhook).

Na documentação de referencia da API está também falando que o serviço é protegido por uma camada de autenticação mTLS: 
![image](https://user-images.githubusercontent.com/5667687/105386377-173d3580-5bf3-11eb-9e85-07a7ec8ea65e.png)

**Comment by viniciusxyz** [comment]
@alvarobacelar então a única obrigatoriedade será o mTLS, o método de autenticação no OAuth Server fica a cargo de cada provedor de software das instituições ?

**Comment by alvarobacelar** [comment]
@viniciusxyz , para as notificações do webhook, sim!

**Comment by ninrod** [comment]
> @alvarobacelar então a única obrigatoriedade será o mTLS, o método de autenticação no OAuth Server fica a cargo de cada provedor de software das instituições ?

Grosso modo, está assim:

1) endpoints organizados sob a tag "CobPayload": sem autenticação, são públicos.
2) endpoints organizados sob a tag "webhook": apenas mTLS
3) demais endpoints: mTLS + Oauth2.

**Comment by viniciusxyz** [comment]
@ninrod obrigado pela resposta.
