### ISSUE TITLE
Cálculo da Multa no Qr Code com vencimento

### ISSUE THREAD

**Issue by vivicupola** [bacen/pix-api#297]
Estamos com dúvida no cálculo da Multa, pois no manual não especifica a modalidade de dias úteis ou corridos, porem no cálculo, está descrito que os dias podem ser calculados conforme a equação 9 (dias corridos) ou 10 (dias úteis).

Vm: valor da multa
k(Dα): assume os seguintes valores, em função de Dα
𝒌 =𝑫𝜶 / 𝒎𝒂𝒙(𝟏,𝑫𝜶) (Equação 13) 
Onde:
****
_Dα: calculado conforme descrito na Equação 9 ou na Equação 10, conforme os dias sem juros sejam dias corridos ou dias úteis._

Pergunta: 
1) devemos considerar dias úteis ou corridos conforme a modalidade escolhida nos Juros?
2) Caso não tenha sido configurado Juros, devemos considerar dias úteis ou corridos?

Obrigada.

**Comment by ebilieri** [comment]
Fiquei com a mesma duvida, pois não é possível saber se dever ser calculado em dias uteis ou dias corridos.
As modalidade de multa não permite identificar o tipo de calculo.
Acho não faz muito sentido utilizar modalidade de juros para calcular multa.
Se for selecionado percentual para  multa  e valor fixo para juros como deve ser calculado?

**Comment by mvleandro** [comment]
@ninrod Consegue ajudar a gente com essa dúvida?

**Comment by ninrod** [comment]
> Acho não faz muito sentido utilizar modalidade de juros para calcular multa.

Correta observação. A multa é sempre aplicada à cobrança começando no próximo dia efetivamente útil e é sempre um valor "flat" (definido de maneira fixa ou percentual, mas uma vez definido, não muda em razão da DPP). 

@vivicupola , vou verificar com o DECEM, mas acredito que a redação tenha que ser aprimorada no manual para não deixar margem à dúvida.

**Comment by ebilieri** [comment]
Olá @ninrod  Mais isso ainda não responde se a multa dever ser calculado em dias uteis ou dias corridos. Pois menciona o uso das equações 9 ou 10 para calcular K.
Qual parâmetro deve ser utilizado para calcular (Da) na fórmula K?

**Comment by renatofrota** [comment]
@ebilieri , a multa não é calculada com base no tempo decorrido desde o vencimento. Se o pagamento é realizado até a data limite (até o vencimento ou até o primeiro dia útil subsequente - quando o vencimento for um dia não útil), não tem multa. Do contrário (pago após data limite), há multa. Mas o **valor** da multa é o mesmo para um pagamento realizado 1, 10 ou 100 dias após a data limite.

**Comment by ebilieri** [comment]
Olá @renatofrota nesse caso a documentação esta errada.
![image](https://user-images.githubusercontent.com/48636325/106668752-68e9a680-6589-11eb-917f-e90bd7ee4cf1.png)

**Comment by renatofrota** [comment]
@ebilieri ,

Não faz qualquer diferença para a multa usar Dc (Dias corridos) ou Du (Dias úteis) na equação 13, por isso simplificou-se dizendo que será utilizada a mesma equação 9 ou 10 já utilizada para o cálculo dos juros, pois a equação 13 vai assumir sempre 0 (quando pago até o vencimento) ou 1 (quando pago após vencimento), independente de pagar 1, 10 ou 100 dias após o vencimento.

Veja um exemplo:

Vencimento = 01/02/2021
Multa = R$ 10,00
Pagamento em 08/02/2021 (7 dias corridos, 5 dias úteis após o vencimento)

Se calcular com equação 9 (Dc):

Dc = max (0; (DataCalc-DataVenc))
Dc = max (0; 7)
Dc = 7

Da = Du

k = Da / max (1, Da)
k = 7 / max (1, 7)
k = 7 / 7
k = 1

Vm = Vm x k
Vm = 10 x 1
Vm = 10

E se calcular com equação 10 (Du):

Du = max (0; (DataCalc-DataVenc))
Du = max (0; 5)
Du = 5

Da = Du

k = Da / max (1, Da)
k = 5 / max (1, 5)
k = 5 / 5
k = 1

Vm = Vm x k
Vm = 10 x 1
Vm = 10

No fim, Vm sempre será R$ 10, que é a multa pra qualquer pagamento realizado após o vencimento.

**Comment by ebilieri** [comment]
Obrigado pela explicação @renatofrota

**Comment by vivicupola** [comment]
@ninrod - Muito obrigada pelo retorno.
E agradeço também a todos que contribuíram muito para esclarecer essa dúvida. 
@renatofrota seu exemplo foi ótimo!
Abraços.

**Comment by kennedimalheiros** [comment]
Ajudou bastante [renatofrota](https://github.com/renatofrota), estava com essa dúvida também [vivicupola](https://github.com/vivicupola).
