### ISSUE TITLE
Pagamento com valor diferente do contido no Payload JSON

### ISSUE THREAD

**Issue by HMPannuti** [bacen/pix-api#298]
No "Manual de Requisitos Mínimos para Experiência do Usuário", no item "Pagamento imediato ou com vencimento através de QR Code dinâmico" está descrito que:

"Usuário pagador pode cancelar o pagamento, mas não pode editar dados lidos do QR Code, **à exceção do valor (caso permitido pelo usuário recebedor)**  e do campo de solicitação de informações ao pagador (se houver)."

Isto está correto?

Existe forma de informar, na criação da cobrança, que é permitido o pagamento de um valor diferente do valor.original (no caso de Cobrança Imediata) ou valor.final (no caso de Cobrança com Vencimento) contido no Payload JSON?

**Comment by rubenskuhl** [comment]
No caso da cobrança imediata eu entendo que não seja permitido alterar o valor. Um recebimento com alteração de valor precisaria ser um QR-Code estático, que não é uma cobrança criada via API apesar de reportada via API no Pix que o liquida.
No caso da cobrança com vencimento, precisaria ser uma data pretendida de pagamento que permita um valor menor de acordo com as condições estipuladas.

**Comment by renatofrota** [comment]
Somente ao ler QR Codes **estáticos** o campo de valor pode ser editado pelo pagador (na ausência de valor estipulado no QR Code).

Eu entendo que, com as modificações ocorridas no decorrer do desenvolvimento das especificações de funcionamento dos QR Codes **dinâmicos**, esse "caso" acabou se tornou impossível (resultado final: pagador não pode editar valor de QR Code dinâmico). Inclusive no caso da cobrança com vencimento, já que o valor deveria ser calculado pelo PSP do pagador com base nas regras da cobrança e na data pretendida de pagamento - não sendo informada/editada manualmente pelo pagador.

**Comment by HMPannuti** [comment]
@rubenskuhl , @renatofrota , obrigado.
Eu estava com essa mesma visão, de que não há caso em que o cliente pode alterar o valor a ser pago, quando se trata de QR Codes Dinâmicos, ao contrário do que consta no Manual. Esse texto deve ter sobrado, da época da API v.1.x, quando havia o parâmetro permiteValorDiferente.

**Comment by ninrod** [comment]
@HMPannuti 

>  Eu estava com essa mesma visão, de que não há caso em que o cliente pode alterar o valor a ser pago, quando se trata de QR Codes Dinâmicos, ao contrário do que consta no Manual. Esse texto deve ter sobrado, da época da API v.1.x, quando havia o parâmetro permiteValorDiferente.

Exatamente, correto.
