### ISSUE TITLE
Consulta dos QR Codes Estáticos no API Pix

### ISSUE THREAD

**Issue by gpneto** [bacen/pix-api#30]
No Manual "II_ManualdepadroesparainiciacaodoPix-versao1.1.pdf" consta: 

> "O QR estático pode ser criado diretamente pela automação do usuário recebedor".

Entendemos que o usuário final pode gerar um QR Code Estático manualmente apenas inserindo os dados no formato EMV e gerando o QR Code.

Minha Dúvida:  Esse QR Code Estático que foi criado manualmente pelo usuário e que tenha um txid(por exemplo "Churrasco") vai ser passível de consulta na API Pix? 

Pergunto porque neste mesmo documento consta: 

> "Os Pix recebidos que tenham sido iniciados via QRs Estáticos que estejam associados a um txid podem ser consultados via API Pix".

Neste caso o QR Code Estático tem um txid, mas como que a API Pix vai conseguir consultar os dados deste QR Code Estático, visto que o QR Code Estático não é criado pela API Pix.

**Comment by ninrod** [comment]
@gpneto , boa tarde. 

> Minha Dúvida: Esse QR Code Estático que foi criado manualmente pelo usuário e que tenha um txid(por exemplo "Churrasco") vai ser passível de consulta na API Pix?

Você faria a seguinte chamada: 

```txt
    GET /pix?txid=churrasco
```
