### ISSUE TITLE
 Response Cobv/pixurlaccesstoken X Manual de experiência

### ISSUE THREAD

**Issue by llatsch** [bacen/pix-api#302]
No retorno do endpoint cobv/pixurlaccesstoken, que será consumido pelo PSP Pagador, não temos informações sobre os parâmetros de multa, desconto, abatimento e juros. Não tem por exemplo os percentuais, se atributos considerados ao dia, ao mês, ao ano.
Entretanto no manual de experiência, página 62, todos esses dados são apresentados ao usuário pagador para confirmação do pagamento.
Como o PSP pagador terá acesso a estes dados?

**Comment by ninrod** [comment]
Só via infoAdicionais. 

Está mais claro na versão 4.0 do manual a ser lançada muito em breve.

**Comment by llatsch** [comment]
Ok, Obrigada!
