### ISSUE TITLE
Dúvida: Conceito API PIX

### ISSUE THREAD

**Issue by MagnoCanto** [bacen/pix-api#303]
Ao ler a documentação da API PIX, havia entendido inicialmente que é uma API que o BACEN disponibiliza para que os PSPs recebedores registrem, alterem e consultem as cobranças. 

No entanto, ao ler os posts, analisar o swagger de exemplo, entendo que seja apenas um modelo para que seja construída a API para o PSP Recebedor registrar, gerar, consultar as cobranças. 

Minha dúvida é: API PIX é uma API disponibilizada pelo BACEN ou é um modelo a ser adotado pelas PSPs recebedoras?

**Comment by rubenskuhl** [comment]
O 2o., modelo para PSPs recebedores. Há APIs entre o BACEN e os PSPs como DICT, SPI e ARQ, mas a API Pix é para os PSP recebedores, em 2 ângulos:
- Disponibilização de cobranças para os PSPs pagadores
- Emissão/gestão de cobranças para os estabelecimentos comerciais
-
