### ISSUE TITLE
Idepotência no endpoin  PUT /cobv​/{txid}

### ISSUE THREAD

**Issue by HJulianaSFerreira** [bacen/pix-api#305]
Bom dia!
Uma dúvida quanto ao endpoint PUT/cobv/{txid}:

O endpoint PUT /cobv/{​​​​​​​​txid}​​​​​​​​ será utilizado tanto para criação como alteração completa do recurso, e o PATCH ficaria para alteração parcial da mesma maneira que o Lotecobv​ ?

**Comment by ninrod** [comment]
Bom dia.

> O endpoint PUT /cobv/{​​​​​​​​txid}​​​​​​​​ será utilizado tanto para criação como alteração completa do recurso, e o PATCH ficaria para alteração parcial da mesma maneira que o Lotecobv​ ?

Isso mesmo, correto.

**Comment by christianteixeira** [comment]
@ninrod, então ao fazer um `PUT /cobv` será gerada uma nova revisão da cobrança, assim como no `PATCH`?

**Comment by ninrod** [comment]
se o put alterar algum objeto que altera versão, sim.

**Comment by christianteixeira** [comment]
perfeito 👍
