### ISSUE TITLE
Dúvida - webhook

### ISSUE THREAD

**Issue by erikaaseg** [bacen/pix-api#309]
É permitido apenas um webhook por chave?
Eu não poderia ter 2 webhooks cadastrados para a mesma chave, certo?

**Comment by erikaaseg** [comment]
Eu tenho uma outra pergunta.. para manter a idempotência, no endpoint DELETE \webhook\{chave}, não seria melhor retornar 204 quando tentar cancelar um webhook que não existe? de acordo com a documentação retonaríamos 404 certo?

**Comment by dev-gto** [comment]
> É permitido apenas um webhook por chave?
> Eu não poderia ter 2 webhooks cadastrados para a mesma chave, certo?

Uma dúvida: o que garante que dois PSPs distintos não tenham a mesma chave do cliente recebedor e apontem para webhooks diferentes, como num hipotético caso de fraude?

**Comment by renatofrota** [comment]
> Complementando a dúvida: o que garante que dois PSPs distintos não tenham a mesma chave do cliente recebedor e apontem para webhooks diferentes, como num hipotético caso de fraude?

A chave é um identificador único e não pode estar associada a mais de 1 PSP no DICT ao mesmo tempo. Se outro PSP quiser registrar essa chave, deverá encaminhar o usuário para o processo de portabilidade ou de reinvidicação de posse, conforme for adequado.

**Comment by renatofrota** [comment]
> É permitido apenas um webhook por chave?

Sim.

> Eu não poderia ter 2 webhooks cadastrados para a mesma chave, certo?

Correto.

> Eu tenho uma outra pergunta.. para manter a idempotência, no endpoint DELETE \webhook{chave}, não seria melhor retornar 204 quando tentar cancelar um webhook que não existe? de acordo com a documentação retonaríamos 404 certo?

Não. 204 (No Content) faz sentido num contexto GET onde você quer obter uma informação da API associada a um elemento baseado em path param, este registro está definido ("existe"), mas não tem conteúdo (então fica mais evidente responder com 204 - pra ficar claro que o recurso existe mas tem valor vazio/nulo - do que responder 200 sem conteúdo nenhum).

Já no contexto de DELETE, a resposta 404 evidencia que você está tentando deletar um elemento que **já não existia** (e não foi encontrado para ser deletado).
