### ISSUE TITLE
[Dúvida] Funcionamento da máquina de status da entidade "Cobrança"

### ISSUE THREAD

**Issue by monise** [bacen/pix-api#31]
**Descreva sua dúvida ou problema**

Olá! Gostaria de tirar algumas dúvidas sobre a **API PIX 2.0**

1 - Uma cobrança pode receber **mais de um** PIX desde que os PIXs tenham o **mesmo txId**, correto?

a) Nesse caso, o PSP só pode mudar o status da cobrança para CONCLUIDA quando **o total de PIXs atingir o valor total da cobrança**?
b) Se sim, enquanto a cobrança não passa para concluída, ela fica como ATIVA?
c) O que deve acontecer se o usuário recebedor tentar remover uma cobrança que está ativa, mas que já recebeu alguns PIXs? Os PIXs devem ser devolvidos?

2 - O ato de remover uma cobrança, é **apenas atualizar o status da cobrança**? Ou seja, se o usuário pagador ler a URL, o payload deve ser retornado, mas com a situação REMOVIDA_PELO_USUARIO_RECEBEDOR"  ou "REMOVIDA_PELO_PSP"? ou devemos tornar indisponível o payload?

3 - No serviço que consulta uma lista de cobranças (GET /cob/), se usado como filtro o campo CPF ou CNPJ do pagador, devemos considerar que o pagador é a informação do campo "devedor" disponível no serviço que cria uma cobrança, ou quando realizamos a busca devemos procurar pelo pagador contido na PACS.008?

4 - No serviço que consulta um PIX pelo endToEndId (GET /pix/{e2eid}) pode ser retornado um recebimento mesmo que seja um recebimento que **não tem** txtId?

5 - O endpoint abaixo é o serviço que deve ser implementado pelo usuário recebedor, para que ele possa receber as notificações de recebimento via webhook, correto?
![image](https://user-images.githubusercontent.com/5355541/94595591-6edd1d00-0261-11eb-8fa3-23342d1f0f17.png)

**Sistema ou Área**
QR Code

**Comment by ninrod** [comment]
boa tarde @monise 

> 1 - Uma cobrança pode receber mais de um PIX desde que os PIXs tenham o mesmo txId, correto?

Em tese, sim. Não é acontecimento normal.

> a) Nesse caso, o PSP só pode mudar o status da cobrança para CONCLUIDA quando o total de PIXs atingir o valor total da cobrança?

Se um pix foi recebido, a cobrança está `CONCLUIDA`. Não importa o valor. Normalmente, o valor pago será exatamente o requisitado. A única possibilidade de o valor ser diferente é acontecer um erro tanto no PSP pagador quanto no recebedor. 

> Se sim, enquanto a cobrança não passa para concluída, ela fica como ATIVA?

Exatamente. Pode ser removida também. 

> c) O que deve acontecer se o usuário recebedor tentar remover uma cobrança que está ativa, mas que já recebeu alguns PIXs? Os PIXs devem ser devolvidos?

Não existe essa possibilidade. Se um pix foi recebido, a cobrança está concluida. 

> 2 - O ato de remover uma cobrança, é apenas atualizar o status da cobrança? Ou seja, se o usuário pagador ler a URL, o payload deve ser retornado, mas com a situação REMOVIDA_PELO_USUARIO_RECEBEDOR"  ou "REMOVIDA_PELO_PSP"? ou devemos tornar indisponível o payload?

Por enquanto, fica a critério do PSP recebedor servir o payload mesmo após a remoção. Não há ainda uma regra sobre isso, mesmo porque a API Pix atual, `2.0.0` trata apenas do casos de uso envolvendo `cobrança online` (e não conta de luz e afins). 

Talvez a API Pix versão `2.1.x` que deve sair em meados de outubro trate essa questão mais detidamente. 

> 3 - No serviço que consulta uma lista de cobranças (GET /cob/), se usado como filtro o campo CPF ou CNPJ do pagador, devemos considerar que o pagador é a informação do campo "devedor" disponível no serviço que cria uma cobrança, ou quando realizamos a busca devemos procurar pelo pagador contido na PACS.008?

no endpoint `GET /cob?cpf={cpf}` o CPF e o CNPJ é do [devedor](https://github.com/bacen/pix-api/blob/b9d9cc8fd8cf187dadc2608ea4070568702dea05/openapi.yaml#L969-L976), que é a quem a cobrança está endereçada. 

por outro lado, no endpoint `GET /pix?cpf={cpf}`, o CPF ou o CNPJ é do [pagador](https://github.com/bacen/pix-api/blob/b9d9cc8fd8cf187dadc2608ea4070568702dea05/openapi.yaml#L1083-L1090) do Pix. Esse "pagador" é o mesmo que consta na PACS.008.

> 4 - No serviço que consulta um PIX pelo endToEndId (GET /pix/{e2eid}) pode ser retornado um recebimento mesmo que seja um recebimento que não tem txtId?

Sim, correto. 

> 5 - O endpoint abaixo é o serviço que deve ser implementado pelo usuário recebedor, para que ele possa receber as notificações de recebimento via webhook, correto?

Correto.

Posso ajudar em mais alguma questão?

**Comment by monise** [comment]
@ninrod muito obrigada pelo retorno!

Porém, continuo em duvida ao item 1, se uma cobrança pode estar associada a mais de um PIX desde que seja o mesmo txtId, se eu recebo um PIX e mudo o status para concluída, ao recebedor um segundo PIX não preciso mais alterar o status da cobrança, seria isso?

E se o valor do PIX tem que ser exatamente o valor da cobrança, qual é o cenário que um cobrança tem mais de um PIX associado?

**Comment by ninrod** [comment]
bom dia @monise 

> Porém, continuo em duvida ao item 1, se uma cobrança pode estar associada a mais de um PIX desde que seja o mesmo txtId, se eu recebo um PIX e mudo o status para concluída, ao recebedor um segundo PIX não preciso mais alterar o status da cobrança, seria isso?

Correto. Cabe ressaltar que esse não é um acontecimento normal, houve erro por parte do PSP recebedor, que deveria ter recusado a transação no ato do recebimento da PACS008 com o pagto duplicado. 

> E se o valor do PIX tem que ser exatamente o valor da cobrança, qual é o cenário que um cobrança tem mais de um PIX associado?

Se todos os agentes implementarem corretamente a spec, não acontecerá esse cenário. Porém, erros podem acontecer. 

Cenário:

1) O usuário recebedo emite uma cobrança (Hoje, um QR Dinâmico) no valor de 100 reais. 
2) Premissa: "By design", a API Pix admite um pagamento só. Logo, o PSP recebedor deveria recusar qualquer Pix exceto o Pix inicial de 100 reais associado do `txid` da cobrança.
3) A cobrança apresenta um `status` a partir da versão `2.0.0`. O PSP do pagador deveria checar esse `status` e informar que a cobrança já está paga e não permitir o pagamento duplicado. e.g. regra: Se a cobrança estiver `CONCLUÍDA`, não permito o pagamento. 
4) Mais de um pix estará associado a uma mesma cobrança identificada por um txid se o PSP do pagador permitir que um pagamento seja realizado contra uma cobrança já concluída e se o PSP do recebedor aceitar um pagamento direcionado a uma cobrança já concluída.

**Comment by ninrod** [comment]
Cabe ressaltar que QR Estático não está associado a uma cobrança, apesar de poder estar associado a um txid.

**Comment by HMPannuti** [comment]
@ninrod, sobre esse item:

>> 4 - No serviço que consulta um PIX pelo endToEndId (GET /pix/{e2eid}) pode ser retornado um recebimento mesmo que seja um recebimento que não tem txtId?

> Sim, correto.

Isso significa que a API Pix não é restrita a Pix com txid, certo?
- consulta de Pix recebidos (GET /pix) irá retornar também recebimentos que não tem txid
- poderão ser realizadas devoluções de Pix sem txid
- serão enviadas notificações via Webhook de Pix sem txid

**Comment by ninrod** [comment]
> Isso significa que a API Pix não é restrita a Pix com txid, certo?

correto, o endpoint `/pix` em particular não está limitado a Pix associados a um txid.

> consulta de Pix recebidos (GET /pix) irá retornar também recebimentos que não tem txid

Perfeito. 

> poderão ser realizadas devoluções de Pix sem txid

Exatamente. 

> serão enviadas notificações via Webhook de Pix sem txid

Não está correto. o Webhook trabalha apenas com Pix associados a um txid.
