### ISSUE TITLE
Dúvida em PATCH /lotecobv/{id} alterações parciais

### ISSUE THREAD

**Issue by mvallim** [bacen/pix-api#311]
Olá,

Quando utilizo o `PUT lotecobv/{id}`, para alteração das cobranças, envio todo o payload novamente dessa forma consigo alterar por exemplo as Informações Adicionais de uma cobrança com mais, menos ou nenhuma informação adicional.

No caso do `PATCH lotecobv/{id}` não está claro como eu faria para esse cenário, se desejo remover todas as informações adicionais de uma determinada cobrança, já que o payload pode ser parcial para a manutenção de uma cobrança.

Agora as dúvidas:

1. `cobv.infoAdicionais`, se desejo remover as infoAdicionais o que seria enviado?  Uma vez criado com infoAdicionais só consigo remover usando o `PUT lotecobv/{id}` para o lote todo?
2. `cobv.solicitacaoPagador`, se desejo remover a solicitacaoPagador o que seria enviado? Uma vez criado com solicitacaoPagadoror só consigo remover usando o `PUT lotecobv/{id}` para o lote todo?
3. `valor.multa`, se desejo remover a multa o que seria enviado? Uma vez criado com multa só consigo remover usando o `PUT lotecobv/{id}` para o lote todo?
4. `valor.juros`, se desejo remover o juros o que seria enviado? Uma vez criado com juros só consigo remover usando o `PUT lotecobv/{id}` para o lote todo?
5. `valor.abatimento`, se desejo remover o abatimento o que seria enviado? Uma vez criado com abatimento só consigo remover usando o `PUT lotecobv/{id}` para o lote todo?
6. `valor.desconto`, se desejo remover o desconto o que seria enviado? Uma vez criado com desconto só consigo remover usando o `PUT lotecobv/{id}` para o lote todo?

Ponto relevante é que por se tratar de campos não obrigatórios para o PATCH quando envio algo como:

Ex.

```json
{
  "cobsv": [
    {
      "calendario": {
        "dataDeVencimento": "2020-01-10"
      },
      "txid": "fb2761260e554ad593c7226beb5cb650",
      "valor": {
        "original": "110.00"
      }
    },
    {
      "calendario": {
        "dataDeVencimento": "2020-01-10"
      },
      "txid": "7978c0c97ea847e78e8849634473c1f1",
      "valor": {
        "original": "110.00"
      }
    }
  ]
}
```

Não significar que quero remover os campos de informação adicional, desconto, multa, etc, a falta desses campos no payload quer dizer que são naturalmente nulos (`null`) portando não obrigatórios, e não se consegue identificar exatamente o que deve ser feito, uma remoção ou manter o que já existe.

Para remover determinada propriedade na alteração o ideal é no payload deixar explicito o campo com `null`?

Ex.

```json
{
  "cobsv": [
    {
      "infoAdicionais": null,
      "calendario": {
        "dataDeVencimento": "2020-01-10"
      },
      "txid": "fb2761260e554ad593c7226beb5cb650",
      "valor": {
        "original": "110.00",
        "juros": null,
      }
    },
    {
      "calendario": {
        "dataDeVencimento": "2020-01-10"
      },
      "txid": "7978c0c97ea847e78e8849634473c1f1",
      "valor": {
        "original": "110.00",
        "multa": null
      }
    }
  ]
}
```

Obrigado,

**Comment by ninrod** [comment]
boa tarde @mvallim

> cobv.infoAdicionais, se desejo remover as infoAdicionais o que seria enviado? Uma vez criado com infoAdicionais só consigo remover usando o PUT lotecobv/{id} para o lote todo?

usaria patch com `cobv[x].infoAdicionais = null;`

O mesmo se aplica para as perguntas de 2 a 6. 

> Para remover determinada propriedade na alteração o ideal é no payload deixar explicito o campo com null?

Exatamente.

**Comment by mvallim** [comment]
@ninrod obrigado pelo exclarecimento.
