### ISSUE TITLE
Construção do QrCode Dinamico

### ISSUE THREAD

**Issue by jeancarlosc39** [bacen/pix-api#315]
Bom dia,
sabem algum site onde consiga testar minha payload se está valido para gerar o qrcode dinamico?
Estatico está OK agora o dinâmico  tem algum problema.

**Comment by jeancarlosc39** [comment]
Já resolvi muito obrigado por enquanto a todos ai

**Comment by jeancarlosc39** [comment]
sobre o qrcode dinâmico pelo que notei o bradesco não funciona. Vocês tem a relação de quais bancos não funcionam?

**Comment by renatofrota** [comment]
> sobre o qrcode dinâmico pelo que notei o bradesco não funciona. Vocês tem a relação de quais bancos não funcionam?

Pode ajudar: https://github.com/renatofrota/pix-pendencias/issues/22

Se puder, passa pra nós o QR Code e tentaremos identificar algum problema nele.

Essa ferramenta também pode ajudar: https://pix.nascent.com.br/tools/pix-qr-decoder/
