### ISSUE TITLE
Dúvidas a respeito das violações específicas do endpoint GET /cobv

### ISSUE THREAD

**Issue by marcosf** [bacen/pix-api#316]
Tenho uma dúvida a respeito de duas violações do endpoint GET /cobv, que são estas violações:
- o parâmetro paginacao.paginaAtual indica uma página fora dos limites da atual consulta.
- o parâmetro loteCobVId não corresponde a um lote existente.

Para poder validar as mesmas eu teria que fazer pelo menos dois hits a mais no banco de dados a fim de calcular se a pagina enviada pelo requisitante existe(se não excede o número total de páginas) e para o lote de cobrança tenho que buscar se o id do lote existe. Estas buscas podem inviabilizar requisitos de performance de api, sem contar que teremos acessos ao banco de dados que poderiam ser evitados.

Poderíamos ignorar estas validações? Pois se a pagina for inválida, poderemos enviar um array vazio como response. No caso do lote seria a mesma coisa.

**Comment by ninrod** [comment]
bom dia @marcosf 

> Poderíamos ignorar estas validações? Pois se a pagina for inválida, poderemos enviar um array vazio como response. No caso do lote seria a mesma coisa.

Concordo. Na 2.2.1 elas saem.

**Comment by marcosf** [comment]
@ninrod Muito Obrigado pela resposta.

**Comment by ninrod** [comment]
Já no master
