### ISSUE TITLE
Dúvida Certificado

### ISSUE THREAD

**Issue by MagnoCanto** [bacen/pix-api#317]
O certificado utilizado para assinar as mensagens do SPI também pode ser usado para assinar os payloads JWT?

**Comment by ninrod** [comment]
A seção 5.1 do Manual de Segurança do Pix detalha os requisitos dos certificados digitais a serem utilizados no Pix, incluindo os requisitos do certificado de assinatura do JWS, que são:

* Ser emitido por AC amplamente conhecida pelos diferentes navegadores e clientes de mercado;
* Possuir o valor “Assinatura Digital” (“Digital Signature”) no campo “Uso da Chave” (“Key Usage”).

Então, caso o certificado de assinatura do SPI (CERTPIA) utilizado pelo PSP atenda aos requisitos acima, ele poderia ser utilizado para assinar o payload JWS.

Porém, na seção 5.3 do referido manual, constam as boas práticas quanto à gestão de certificados, e uma das recomendações dessa seção é que "cada instituição utilize certificados distintos, exclusivos para cada finalidade". No entanto, trata-se de uma recomendação, e não uma obrigação. Isto posto, embora não seja recomendado, não há impeditivo de se utilizar o mesmo certificado para diferentes finalidades.
