### ISSUE TITLE
Qrcode gerado com problema

### ISSUE THREAD

**Issue by jeancarlosc39** [bacen/pix-api#318]
Gerei um qrcode até ontem funcionava a geração. Segue payload
00020101021226770014BR.GOV.BCB.PIX2555api.itau/pix/qr/v2/ed71c5c8-6b03-4a13-b780-f9782f774f5252040000530398654061308.95802BR5933LiveRoupasEsportivasLtda.-Me6016JaraguádoSul61088925716062070503***630485B0
alguém sabe onde consiga validar isso

**Comment by dev-gto** [comment]
O Merchant name é no máximo 25, esse tem 33

**Comment by renatofrota** [comment]
> Gerei um qrcode até ontem funcionava a geração. Segue payload
> 00020101021226770014BR.GOV.BCB.PIX2555api.itau/pix/qr/v2/ed71c5c8-6b03-4a13-b780-f9782f774f5252040000530398654061308.95802BR5933LiveRoupasEsportivasLtda.-Me6016JaraguádoSul61088925716062070503***630485B0
> alguém sabe onde consiga validar isso

* Template 54 tá com apenas 1 casa decimal (a documentação admite mas muitos PSP só estão aceitando com 2 casas decimais)
* Template 59 tem limite de 33 caracteres e vc tá usando 33 (adicione espaços e simplesmente ignore os excessos - também pode usar apenas "Live Roupas Esportivas", não precisa ser a razão social)
* Template 60 tá com comprimento calculado errado (e tem caracteres acentuados, cuja documentação admite mas nem todos PSPs estão lidando bem, retire ou faça testes extensivos pra garantir que funciona)

**Comment by renatofrota** [comment]
Dica: https://pix.nascent.com.br/tools/pix-qr-decoder/

**Comment by dev-gto** [comment]
> > Gerei um qrcode até ontem funcionava a geração. Segue payload
> > 00020101021226770014BR.GOV.BCB.PIX2555api.itau/pix/qr/v2/ed71c5c8-6b03-4a13-b780-f9782f774f5252040000530398654061308.95802BR5933LiveRoupasEsportivasLtda.-Me6016JaraguádoSul61088925716062070503***630485B0
> > alguém sabe onde consiga validar isso
> 
>     * Template 54 tá com apenas 1 casa decimal (a documentação admite mas muitos PSP só estão aceitando com 2 casas decimais)
> 
>     * Template 59 tem limite de 33 caracteres e vc tá usando 33 (adicione espaços e simplesmente ignore os excessos - também pode usar apenas "Live Roupas Esportivas", não precisa ser a razão social)
> 
>     * Template 60 tá com comprimento calculado errado (e tem caracteres acentuados, cuja documentação admite mas nem todos PSPs estão lidando bem, retire ou faça testes extensivos pra garantir que funciona)

Na verdade nesse exemplo, o tamanho da template 33 extrapola o buffer, `LiveRoupasEsportivasLtda.-Me` tem 28 letras

**Comment by renatofrota** [comment]
> Na verdade nesse exemplo, o tamanho da template 33 extrapola o buffer, `LiveRoupasEsportivasLtda.-Me` tem 28 letras

Parece que ele está calculando com os espaços e depois omitindo eles.

**Comment by jeancarlosc39** [comment]
vou diminuir o  tamanho valeu pessoal

**Comment by dev-gto** [comment]
Tem outras dicas aqui

https://github.com/bacen/pix-api/issues/189
