### ISSUE TITLE
[Dúvida] no [QR Code] - API de Recebimento (API PIX 2.0.0)

### ISSUE THREAD

**Issue by simonevirgilio** [bacen/pix-api#32]
Estamos com uma dúvida sobre a API de recebimento (Api PIX 2.0.0)

Em revisar cobranças (/api/v1/cob/{txid}) existe o parâmetro Status, na documentação está definido assim:
O único status que pode ser informado na revisão da Cobrança é o REMOVIDA_PELO_USUARIO_RECEBEDOR.

Isso quer dizer que o endpoint de revisar cobrança serve apenas para remover uma cobrança? Ou posso utilizar o endpoint para atualizar a cobrança e deixar o Status vazio para quando desejo modificar algum campo da cobrança, e utilizar o campo Status apenas quando desejo REMOVER a cobrança?

**Sistema ou Área**
 QR Code,

**Comment by ninrod** [comment]
@simonevirgilio, 

você está falando especificamente do endpoint `PATCH /cob/{txid}`, correto? 

Essa "frase" está dizendo que se você enviar o campo status, no PATCH, o valor desse campo status pode ser apenas este.

**Comment by ninrod** [comment]
@simonevirgilio ficou claro? Podemos responder mais alguma dúvida referente a esta questão?

**Comment by simonevirgilio** [comment]
Ficou claro sim. Obrigada !


Enviado do Yahoo Mail para iPhone


Em quarta-feira, setembro 30, 2020, 2:22 PM, Filipe Silva <notifications@github.com> escreveu:




@simonevirgilio ficou claro? Podemos responder mais alguma dúvida referente a esta questão?
