### ISSUE TITLE
Dúvida - alteração de status de cobrança para CONCLUIDA

### ISSUE THREAD

**Issue by erikaaseg** [bacen/pix-api#325]
Ao receber um pix relativo à uma cobrança, devo alterar o status da mesma de ATIVA para CONCLUIDA. Nesse momento, posso gravar uma nova revisão? Ou devo alterar o status sem gerar nova revisão?

**Comment by ninrod** [comment]
alterar o status sem gerar nova revisão. A revisão só é incrementada por conta de alterações por parte do usuário recebedor.
