### ISSUE TITLE
[Dúvida] Request para consulta da URL e decode deve obrigatoriamente ser do aplicativo?

### ISSUE THREAD

**Issue by biancamcardoso** [bacen/pix-api#33]
**Descreva sua dúvida ou problema**
Em fluxo de utilização do QR Code dinâmico pelo usuário pagador - As requests para consulta a URL (decode + validações de segurança) relativas a URL contida no QR CODE DINÂMICO devem ser **obrigatoriamente** disparadas a partir do **aplicativo** do PSP (camada app)??? Ou elas podem estar em uma **camada de backend** onde uma api disponibilizaria as funções de decode e validações ao aplicativo no momento da solicitação de consulta a URL (leitura de um QR Code dinâmico para pagamento)? 

**Sistema ou Área**
Iniciação de Pagamentos, QR Code, Segurança

**Identificador do Problema**
ResourceId - Consulta URL (QR Code Dinâmico (SPI)

**Mensagens Enviadas / Recebidas**
N/D

**URL de conexão**
N/D

**Dados adicionais**

Manual de Segurança do Pix - Versão 3.0 - 4.3. Validações a serem feitas pelos aplicativos - https://www.bcb.gov.br/content/estabilidadefinanceira/cedsfn/Manual%20de%20Seguranca%20do%20PIX%20v3.0.pdf

Especificações técnicas e de negócio do ecossistema de pagamentos instantâneos brasileiro - 1.2.2.2. QR CODE DINÂMICO - https://www.bcb.gov.br/content/estabilidadefinanceira/forumpireunioes/Documento%20de%20especifica%C3%A7%C3%B5es%20-%20vers%C3%A3o%206.1.pdf

**Comment by ninrod** [comment]
> Em fluxo de utilização do QR Code dinâmico pelo usuário pagador - As requests para consulta a URL (decode + validações de segurança) relativas a URL contida no QR CODE DINÂMICO devem ser obrigatoriamente disparadas a partir do aplicativo do PSP (camada app)??? Ou elas podem estar em uma camada de backend onde uma api disponibilizaria as funções de decode e validações ao aplicativo no momento da solicitação de consulta a URL (leitura de um QR Code dinâmico para pagamento)?

@biancamcardoso , boa tarde. 

Funcionaria das duas maneiras. Essa é uma decisão arquitetural que cabe ao PSP e transcende o escopo regulatório estabelecido pelo Bacen.
