### ISSUE TITLE
[URGENTE] Favor informar Txid na PAC008

### ISSUE THREAD

**Issue by LeandroBastos99** [bacen/pix-api#335]
Pessoal, gostaria de fazer uma sugestão que acredito que pode contribuir para mitigar alguns problemas de usabilidade do QR Code dinâmico dentro de canais digitais e e-commerce. 

Recebemos centenas de pagamentos diariamente através de QR Code dinâmico. Eventualmente recebemos alguns pagamentos de usuários onde não está sendo informado o Txid dentro da PAC008. 

Pontualmente estamos entrando em contato com cada instituição que estamos detectando esta falha, porém para nosso cliente, ele crê que a falha é interna e não da if que ele está fazendo o pagamento. 

Peço a gentileza para revisarem o envio do Txid dentro da Pac008 para os Qrcode Dinâmicos.

**Comment by renatofrota** [comment]
A lista de problemáticas que você tem corresponde aos PSPs marcados em https://github.com/renatofrota/pix-pendencias/issues/21 ?

**Comment by rubenskuhl** [comment]
Isso é PSP a PSP mesmo. O SPI não sabe se é ou não um QR-Code dinâmico sem olhar o TxID... a não ser que chaves no DICT pudessem receber flag "só aceita QR-Code dinâmico". Acha possível isso, @ninrod ?

**Comment by LeandroBastos99** [comment]
@renatofrota Pegamos outras ifs que já entramos em contato para correção, porém não estão na lista enviada. Como está gerando problema no e-commerce de clientes, abri chamado aqui para todos verificarem se estão enviados o Txid corretamente.

**Comment by renatofrota** [comment]
É que já tem outro issue neste repositório sobre o assunto, então o seu é uma duplicata.

https://github.com/bacen/pix-api/issues/209

**Comment by rubenskuhl** [comment]
> @renatofrota Pegamos outras ifs que já entramos em contato para correção, porém não estão na lista enviada. Como está gerando problema no e-commerce de clientes, abri chamado aqui para todos verificarem se estão enviados o Txid corretamente.

Mas quais são os PSPs ?

**Comment by renatofrota** [comment]
> > @renatofrota Pegamos outras ifs que já entramos em contato para correção, porém não estão na lista enviada. Como está gerando problema no e-commerce de clientes, abri chamado aqui para todos verificarem se estão enviados o Txid corretamente.
> 
> Mas quais são os PSPs ?

@LeandroBastos99 

Eu ia esperar alguns minutos pra ver se você ia interagir lá no https://github.com/renatofrota/pix-pendencias/issues/21

Mas reforço o pedido do @rubenskuhl. É muito importante sabermos, para mantermos atualizado, também, o https://github.com/renatofrota/pix-pendencias/issues/22

**Comment by LeandroBastos99** [comment]
@renatofrota Você prefere que eu feche aqui e tratamos tudo direto pelo #209?

**Comment by renatofrota** [comment]
Não sou do BACEN. Mas faz sentido.

**Comment by LeandroBastos99** [comment]
Pessoal esse issue será tratado pelo #209.
