### ISSUE TITLE
Tratamento de Erros - campos

### ISSUE THREAD

**Issue by isabellekoga** [bacen/pix-api#339]
Bom dia a todos,
Ficamos em dúvida em relação a estrutura de erros que deve ser retornada, os campos estão em inglês e todos os campos da API estão em português. Há realmente esta diferença? 

Ex:

- `GET /webhook/{chave}` (200)
![image](https://user-images.githubusercontent.com/60149804/109498008-a3a00b00-7a71-11eb-8e1a-51a50e0793f4.png)

- `GET /webhook/{chave}` (403)
![image](https://user-images.githubusercontent.com/60149804/109498057-b31f5400-7a71-11eb-864d-e82eade89994.png)

Muito obrigado

**Comment by ninrod** [comment]
@isabellekoga , boa noite. 

Para a parte de problemas  o BCB adotou a [RFC 7807](https://tools.ietf.org/html/rfc7807), que define estes campos em inglês.

**Comment by isabellekoga** [comment]
Entendi, muito obrigado pelo esclarecimento. :) 

Fiquei em dúvida também no campo `violações` e seus subcampos `razao`, `propriedade `e `valor`,

![image](https://user-images.githubusercontent.com/60149804/109703626-725c3380-7b74-11eb-90e1-709ff4991f79.png)

Estes campos também permanecem traduzidos?

**Comment by ninrod** [comment]
> Estes campos também permanecem traduzidos?

Sim, ficam do jeito que estão apresentados na API.

**Comment by isabellekoga** [comment]
Obrigado pelos esclarecimentos @ninrod 😉
