### ISSUE TITLE
[Dúvida] em [PAGAMENTOS] - Transações em Lote

### ISSUE THREAD

**Issue by Go-Merk** [bacen/pix-api#34]
**Descreva sua dúvida ou problema**
Será possível desenvolver uma espécie de "carrinho de compras" com o PIX no QR dinâmico (o mesmo para o futuro link de pagamentos)? Vejo que ficar fazendo múltiplas transações pra cada produto comprado é inviável, especialmente se essas compras forem a distancia. Por exemplo: Uma seleção com diferentes frutas e vegetais.

Acredito que uma transação em lote pouparia custos para quando esse tipo de operação ocorrer.

**Sistema ou Área**
Iniciação de Pagamentos

**Comment by ninrod** [comment]
boa tarde @Go-Merk , 

> Será possível desenvolver uma espécie de "carrinho de compras" com o PIX no QR dinâmico (o mesmo para o futuro link de pagamentos)? Vejo que ficar fazendo múltiplas transações pra cada produto comprado é inviável, especialmente se essas compras forem a distancia. Por exemplo: Uma seleção com diferentes frutas e vegetais.

Esse cenário já é possível hoje. Basta que, no caixa, cada item seja adicionado a uma lista e no final sejam somados os valores dos itens. A soma final será atribuída à cobrança via `PUT /cob/{txid}` com a possibilidade de adicionar os itens em `infoAdicional` para verificação por parte do pagador.
