### ISSUE TITLE
Erro 403 forbidden na autenticação com o Bradesco.

### ISSUE THREAD

**Issue by Netow** [bacen/pix-api#343]
Alguém que já realizou a integração com o Bradesco e poderia dar uma ajuda sobre o erro 403 forbidden, muito provavelmente relacionado a autenticação com o certificado digital???
Já realizei a integração com o Itaú de forma rápida e sem transtornos.

**Comment by rubenskuhl** [comment]
Não é por causa daqueles headers proprietários onde o Bradesco desobedece o regulamento do BACEN, como os X-Brad-* ?

**Comment by Netow** [comment]
Então, na documentação que eu tenho, não menciona esses headers para obtenção do token. No caso, eu não estou passando nenhum header deste tipo. Apenas Basic authoraztion e o grant_type.
