### ISSUE TITLE
Erro Payload Bancen

### ISSUE THREAD

**Issue by delafonso** [bacen/pix-api#345]
Pessoal, 
Estamos homologando os cenários PIX Cobrança.

Geramos um QRCODE no Banco Central e no momento que vamos realizar o pagamento estamos recebendo o erro:

**Invalid environment for Payload url: qr-h.sandbox.pix.bcb.gov.br/rest/api/v2/249565a6ac08456aaac5de8972a0a0c4 - Detail: Homologation QRCode cannot be read in a production environment with the qr-h.sandbox.pix.bcb.gov.br host.** 

Vocês tem alguma ideia do que pode estar ocorrendo?

Estamos 100% em homologação e mesmo assim esta identificando como produção, pela mensagem de erro

**Comment by erikaaseg** [comment]
O payload desta cobrança está vindo com campos a mais no devedor conforme abaixo:

"devedor": {
    "nome": "Fulano de Tal",
    "cpf": "86133673567",
    "logradouro": "Rua Teste",
    "cidade": "Fortaleza",
    "uf": "CE",
    "cep": "68762843"
  }

A pergunta é: Isso seria possível/permitido? Pois é esperado apenas os atributos cpf/cnpj e nome para o devedor.

**Comment by delafonso** [comment]
Pessoal,
Encontramos o problema
Grato
