### ISSUE TITLE
Sugestao de mais Robustez no lado do PSP recebedor por erros do PSP pagador 

### ISSUE THREAD

**Issue by flaviolenz** [bacen/pix-api#346]
Mais de 3 meses depois de ter entrado no ar, ainda convivemos com erros de PSP pagadores não enviando TxId.
Os poucos que fazem isso, destroem a confiança no sistema como um todo. (nao posso automatizar nada completamente se sempre pode ocorrer algo assim).

Parece haver uma negligencia no acerto desses detalhes por parte de alguns participantes, talvez pelo adiamento das sancoes.
Esse eh o problema como está hoje e talvez isso tenha feito o Pix não se alavancar no lado comercial como achavamos (e torciamos) que iria.

Independente disso, olhando para o futuro, sempre há a possibilidade de algum sistema falhar em toda a cadeia, seja no App, seja na retaguarda de cada um dos participantes, seja por deliberada acao do usuario que extrai a chave de um qrcode e faz uma transferencia por fora.
Entao, sugiro uma melhoria na especificação (ou pelo menos que seja possível, a critério do PSP recebedor), que o titular da conta possa definir critérios para a recusa de recebimento de Pix. 

Exemplos:
1. sem TxId
2. sem ser de QR dinamico
3. TxId fora de uma mascara (uma regex ou wildcard, por exemplo)
4. Valores menores que X ou maiores que Y
5. sem InfoPagador
etc...

Seria de pura responsabilidade do titular da chave ajustar esses parâmetros.
O PSP recebedor faria essas checagens antes de aceitar o pix.

**Comment by rubenskuhl** [comment]
O BACEN já disse em outro tópico que o PSP recebedor pode sim, por liberalidade e a pedido do EC, recusar transações conforme critérios variados. Isso já é feito em alguns PSPs e está sendo implantado em outros. Mas o recurso não é nem obrigatório nem padronizado.

**Comment by ninrod** [comment]
"Art. 39-A.  Uma transação no âmbito do Pix poderá ser rejeitada pelo participante prestador de serviço de pagamento do usuário recebedor quando houver inconsistência entre a transação e os parâmetros atribuídos à cobrança que a originou, quando se tratar do produto Pix Cobrança."

@flaviolenz, o entendemos que esse artigo acima permite o PSP implementar os controles que você descreve. (cc: @rubenskuhl )
