### ISSUE TITLE
Cálculo de Juros com vencimento em finais de semana

### ISSUE THREAD

**Issue by biancaOliveiraSantos** [bacen/pix-api#347]
Bom dia!
Conforme foi detalhado na API como funciona o campos Validade Após o vencimento (na CobV), surgiu a dúvida da aplicação do juros em casos de vencimento no final de semana:
Exemplo: 
-Cobrança venceu no dia 27/02 (sábado)
-Na segunda (01/02) é possível pagar sem juros.
-Na terça (02/02) deve ser aplicado o juros retroativo desde a data de vencimento (aplicar cobrança referente à 3 dias) ou conta a partir da segunda-feira, (aplicação de cobrança de 1 dia de juros)?

Obrigada!

**Comment by ninrod** [comment]
boa tarde @biancaOliveiraSantos. Preciso de um caso concreto. Como seria configurada a cobrança?

**Comment by biancaOliveiraSantos** [comment]
Tenho sim, corrigindo, eu tinha colocado as datas erradas.
**Exemplo:** 
Qr Code dinâmico no valor de R$10,00 com vencimento para o dia 27/02  com R$0,10 de juros por dia corridos de atraso (modalidade 1 de juros).

Se o cliente pagar:
- na segunda (01/03) é possível pagar sem juros, dado que o vencimento foi no fim de semana= **valor a pagar R$10.**
- na terça (02/03), qual valor deve ser cobrado? **R$10,30 ou R$10,10**?
O cálculo para cobrança de juros deve ser retroativo, contando desde o vencimento ou deve considerar a cobrança a partir da terça-feira, resultando em 1 dia de juros?)

Obrigada!

**Comment by ninrod** [comment]
> na segunda (01/03) é possível pagar sem juros, dado que o vencimento foi no fim de semana= valor a pagar R$10.

Correto. 

> na terça (02/03), qual valor deve ser cobrado? R$10,30 ou R$10,10?

Ver Anexo III do manual de iniciação, item 2.2.3. Resposta correta é **10,10**.

**Comment by mzavarize** [comment]
Boa tarde @ninrod,

Para mim na documentação, não ficou claro que devemos considerar para calculo do juros em dias corridos o primeiro dia útil após vencimento, no documento informado acima a formula é 𝑫𝒄 = 𝒎𝒂𝒙(𝟎;(𝑫𝒂𝒕𝒂𝑪𝒂𝒍𝒄 − 𝑫𝒂𝒕𝒂𝒗𝒆𝒏𝒄)) e informa que Datavenc é o campo json calendario.dataDeVencimento,  no exemplo acima esse campo teria a data 27/02.

**Comment by ninrod** [comment]
@mzavarize  e @biancaOliveiraSantos , me desculpem. 

O cálculo para dias corridos é diferente. Erroneamente entendi que era considerando dias úteis. 

Vou reformar minha resposta.

**Comment by isabellekoga** [comment]
Boa tarde @ninrod,
Em relação a essa questão, podemos assumir então que para o cálculo do juros,  o 𝒎𝒂𝒙(𝟎;(𝑫𝒂𝒕𝒂𝑪𝒂𝒍𝒄 − 𝑫𝒂𝒕𝒂𝒗𝒆𝒏𝒄))  :

Considerando: 
𝑫𝒂𝒕𝒂𝒗𝒆𝒏𝒄  = 15/11 (segunda - feira feriado) 
𝑫𝒂𝒕𝒂𝑪𝒂𝒍𝒄 = 17/11

- **modalidades por dia útil (modalidades 5 a 8)**:
   - Se a 𝑫𝒂𝒕𝒂𝒗𝒆𝒏𝒄 é dia de semana ou feriado, é considerado como data de vencimento o primeiro dia úitl após
   - Du = (17-16) = 1
- **modalidades por dia corrido (modalidades 1 a 4)** 
   - Idependente da 𝑫𝒂𝒕𝒂𝒗𝒆𝒏𝒄 ser dia de semana ou feriado, é considerado a data de vencimento original.
   - Dc = (17-15) =2

Este seria o comportamento correto?

**Comment by ninrod** [comment]
> Este seria o comportamento correto?

@isabellekoga, entendo que sim porque na modalidade de dias corridos, como não temos o conceito de dias úteis, o feriado não se aplica. Vou pedir para o DECEM confirmar esse entendimento aqui.

**Comment by ninrod** [comment]
> Bom dia!
Conforme foi detalhado na API como funciona o campos Validade Após o vencimento (na CobV), surgiu a dúvida da aplicação do juros em casos de vencimento no final de semana:
Exemplo:
-Cobrança venceu no dia 27/02 (sábado)
-Na segunda (01/02) é possível pagar sem juros.
-Na terça (02/02) deve ser aplicado o juros retroativo desde a data de vencimento (aplicar cobrança referente à 3 dias) ou conta a partir da segunda-feira, (aplicação de cobrança de 1 dia de juros)?

Prezados, a resposta é 

> Cobrança de 1 dia de juros

**Comment by christianteixeira** [comment]
@ninrod , rapaz agora eu fiquei confuso.

> Prezados, a resposta é
>    > Cobrança de 1 dia de juros

No exemplo citado pela @biancaOliveiraSantos e pela sua conclusão, o entendimento para a contagem dos dias corridos para o cálculo de juros então é o seguinte:
- Quando a cobrança vencer em um dia útil normal, contar dias corridos a risca até a DPP informada;
- Quando a cobrança vencer em um dia não útil, passar a contar os dias corridos a partir da data de vencimento "prorrogada".

É isso?

**Comment by ninrod** [comment]
@cristianokbc , 

Depende da modalidade. Recomendo utilizar um caso concreto e contatar pix@bcb.gov.br (DECEM). 

Eles vão responder perguntas de negócio e concentrar as respostas neste meio.
