### ISSUE TITLE
API Pix - QR Code Dinâmico no Aplicativo

### ISSUE THREAD

**Issue by gpneto** [bacen/pix-api#35]
Entendemos que o usuário final vai poder criar no próprio aplicativo do PSP, um QR Code Dinâmico e também o QR Code Estático.

Na documentação dix:

> O QR Code dinâmico no Pix deve ser gerado por meio da API Pix. A API Pix é uma API padronizada pelo
> BCB com o objetivo de facilitar o processo de integração com soluções de automação, ampliar a
> concorrência no setor e possibilitar menores custos aos usuários finais

No caso da criação de um QR Code pelo usuário recebedor no aplicativo também deve ser utilizado essa a api?

Minha dúvida seria mais na documentação abaixo:

> O txid é criado exclusivamente pelo usuário recebedor e está sob sua responsabilidade. O txid, no
> contexto de representação de uma cobrança, é único por CPF/CNPJ do usuário recebedor. Cabe ao PSP
> recebedor validar essa regra na API Pix.

Se o txid é o usuário recebedor que informa, então no aplicativo tem que ser adicionado um campo para informar o identificador(txid) na criação do QR Code Dinâmico?

Esse txid no caso dos QR Codes gerados pelo usuário no aplicativo não deveria ser um TXID do PSP?

Documento: https://www.bcb.gov.br/content/estabilidadefinanceira/pix/Regulamento_Pix/III.ManualdeFluxosdoProcessodeEfetivacaodoPix-versao1.1.pdf

**Comment by ninrod** [comment]
@gpneto , boa tarde.

> No caso da criação de um QR Code pelo usuário recebedor no aplicativo também deve ser utilizado essa a api?

São dois "fluxos" diferentes. O fluxo via mobile é diferente do fluxo utilizando a API Pix. 

> Se o txid é o usuário recebedor que informa, então no aplicativo tem que ser adicionado um campo para informar o identificador(txid) na criação do QR Code Dinâmico?

Exatamente. 

> Esse txid no caso dos QR Codes gerados pelo usuário no aplicativo não deveria ser um TXID do PSP?

Não está correto. O txid é informado pelo usuário recebedor. Trata-se de uma decisão de negócio. 

Podemos responder alguma dúvida adicional?

**Comment by gpneto** [comment]
@ninrod  Perfeito.

Se:

> São dois "fluxos" diferentes. O fluxo via mobile é diferente do fluxo utilizando a API Pix.

Então os QR Codes Dinâmicos gerados pelo usuário recebedor pelo aplicativo não deve seguir as regras da API Pix na criação do QR Code Dinâmico?

Pergunto isso porque digamos que eu uso o app do meu banco para gerar um QR Code Dinâmico eu possuo o CPF 111111111111, se eu quiser ter acesso à API Pix do meu banco(porque eu tenho contra transacional) vai ser cadastrado o meu CPF 111111111111 como cliente e vou ter acesso a API. Estes QR Codes gerados pelo app com o meu CPF não deverão aparecer para consulta na API Pix? O Aplicativo não seria como uma interface para o usuário recebedor criar os QR Codes Dinâmicos?

Só queria entender qual é a diferença nos fluxos que você mencionou. Por que na teoria a URL e os dados que estará dentro do QR Code Dinâmico e que retornará na API Pix serão a mesma tanto para as cobranças criadas pelo App quando pela API Pix.

**Comment by ninrod** [comment]
@gpneto , 

Entre o `app` do usuário recebedor e o backend do PSP recebedor estará estabelecida uma API que não diz respeito ao Bacen. É uma questão interna. 

No caso levantado por você, qual é exatamente o problema apontado? Não vejo em princípio nenhum problema em o usuário recebedor gerar um QR Dinâmico via "app" e depois consultá-lo via API Pix.

**Comment by gpneto** [comment]
@ninrod,

meu questionamento não seria referente à api entre o app e o backend do PSP, e sim sobre os dados que são criados no QR Code Dinâmico pelo app e pela API Pix.

Tanto o app quando a API Pix vão criar cobrança(QR Code Dinâmico), só que por canais diferentes. Para o app criar o QR Code dinâmico nós estávamos utilizando a documentação "https://www.bcb.gov.br/content/estabilidadefinanceira/forumpireunioes/AnexoI-PadroesParaIniciacaodoPix.pdf" que falava separadamente da criação do QR Code estático na página 11 e sobre a criação do QR Code dinâmico na página 17, ou seja, no mobi estávamos seguindo a documentação para gravar os dados e apresentar em tela o QR Code.

Nesse novo documento não existe mais um capítulo sobre o QR Code Dinâmico, foi substituído pela "A API Pix", ou seja, meu primeiro questionamento:  

> No caso da criação de um QR Code Dinâmico pelo usuário recebedor no aplicativo também deve ser utilizado essa a api?

o qual a resposta foi: 

> São dois "fluxos" diferentes. O fluxo via mobile é diferente do fluxo utilizando a API Pix.

A minha dúvida seria na criação do QR Code Dinâmico no app, qual o documento que devemos seguir se não a API Pix?

**Comment by ninrod** [comment]
@gpneto , o QR Dinâmico está especificado no Manual de iniciação. Então tanto o fluxo mobile quanto o fluxo API devem seguir esse documento. 

Agora a diferença é que o fluxo via API Pix deve seguir, também, a especificação OpenAPI 3.0 definida nesse repositório. 

Já o fluxo via mobile deve seguir, também, o [Documento de Requisitos Mínimos de experiência do Usuário](https://www.bcb.gov.br/content/estabilidadefinanceira/pix/Regulamento_Pix/IV_RequisitosMinimosparaExperienciadoUsuario-versao1.1.pdf). ([link](https://www.bcb.gov.br/estabilidadefinanceira/pagamentosinstantaneos)).

**Comment by gpneto** [comment]
@ninrod, desculpa estar sendo redundante.

É justamente nessa documentação nova do "Manual de iniciação" que estou com dúvidas.

> 1.6. Iniciação do Pix via QR Code Dinâmico
> 1.6.1. A API Pix
> **O QR Code dinâmico no Pix deve ser gerado por meio da API Pix.** A API Pix é uma API padronizada pelo
> BCB com o objetivo de facilitar o processo de integração com soluções de automação, ampliar a
> concorrência no setor e possibilitar menores custos aos usuários finais. 

Por isso meu primeiro questionamento foi "No caso da criação de um QR Code Dinâmico pelo usuário recebedor no aplicativo também deve ser utilizado essa a API?".

Agora entendo que então a trecho "**O QR Code dinâmico no Pix deve ser gerado por meio da API Pix.**" não se aplica para QR Codes Dinamicos gerados pelo Aplicativo, apesar da frase não estar especificando.

Obrigado.

**Comment by ninrod** [comment]
@gpneto , sinta-se a vontade para tirar quaisquer dúvidas que julgue relevante. 

Realmente esse texto "O QR Code dinâmico no Pix deve ser gerado por meio da API Pix" está confundindo. Eu vou alterar agora o documento para já esclarecer a situação. 

Ressalto que o QR dinâmico no fluxo mobile é opcional. Apenas o QR Estático é obrigatório para o fluxo mobile.

**Comment by brunoparis01** [comment]
Boa Tarde Filipe.
Achei esse issue pois tenho a mesma dúvida.

> Agora entendo que então a trecho "**O QR Code dinâmico no Pix deve ser gerado por meio da API Pix.**" não se aplica para QR Codes Dinamicos gerados pelo Aplicativo, apesar da frase não estar especificando.

Em que cenários então o QR code dinâmico deve ser gerado por meio da API Pix? Seria o caso de comércios/e-commerce que não tem nenhuma relação com PIX e dependem de SW de automação comercial para habilitar o PIX como forma de pagamento?

**Comment by ninrod** [comment]
boa tarde @brunoparis01, 

> Em que cenários então o QR code dinâmico deve ser gerado por meio da API Pix? Seria o caso de comércios/e-commerce que não tem nenhuma relação com PIX e dependem de SW de automação comercial para habilitar o PIX como forma de pagamento?

é uma boa pergunta. Você poderia por favor abrir uma issue separada? Estamos tentando organizar os assuntos para tornar mais fácil a busca.

**Comment by brunoparis01** [comment]
Feito.

**Comment by ninrod** [comment]
> Feito.

Obrigado

**Comment by vivicupola** [comment]
Eu tenho uma dúvida relacionada a esse tema, e gostaria de esclarecer:
No item - "O txid é criado exclusivamente pelo usuário recebedor e está sob sua responsabilidade. O txid, no
contexto de representação de uma cobrança, é único por CPF/CNPJ do usuário recebedor. "
No caso de um Qr Code dinâmico gerado no Mobile, posso deixar uma parte do campo de responsabilidade do usuário recebedor, e outra parte dele (por exemplo, as 10 últimas posições) para que o PSP possa garantir a unicidade do campo?
Por exemplo, o usuário digita "Churrasco". Seria de responsabilidade deles, no próximo Qr que ele gerar, ele criar um outro txid, ou o PSP pode criar mecanismos internos para que isso fique transparente ao cliente, que mesmo que ele crie novamente "churrasco", este campo continuaria sendo único, de acordo com algum critério interno?
Obrigada.
