### ISSUE TITLE
campo expiração obrigatório

### ISSUE THREAD

**Issue by Bigua** [bacen/pix-api#351]
O campo expiração, dentro de calendário, consta como obrigatório.

https://bacen.github.io/pix-api/index.html#/CobPayload/get__pixUrlAccessToken_

entretanto na documentação até a versão atual, 2.2 ele consta como opcional

**Comment by ninrod** [comment]
@Bigua , 

Ele é obrigatório apenas no responsa e no _location_. No request em PUT /cob/{txid} ele é opcional.

**Comment by thiagolvlsantos** [comment]
Dúvida aparentemente esclarecida.

Atenciosamente,
Thiago Santos.
