### ISSUE TITLE
Dúvidas em relação à homologação dos qr codes

### ISSUE THREAD

**Issue by erikaaseg** [bacen/pix-api#352]
1) O payload de algumas cobranças do ambiente de teste disponibilizado pelo bacen está vindo com campos a mais no devedor conforme abaixo:

    "devedor": {
        "nome": "Fulano de Tal",
        "cpf": "86133673567",
        "logradouro": "Rua Teste",
        "cidade": "Fortaleza",
        "uf": "CE",
        "cep": "68762843"
    }

A pergunta é: Isso seria possível/permitido? Pois é esperado apenas os atributos cpf/cnpj e nome para o devedor.

2) Existe um teste de qr code inválido para testar o caso de qr code estático com valor 0. Este caso não está coberto na jornada do pagador (Lista de verificação para geração e leitura de QR Codes), e nem vi em outro documento. Existe algum documento que diz que devemos dar erro ao ler qr code estático com valor 0?

**Comment by renatofrota** [comment]
Sobre a pergunta 2: a documentação de padrões de iniciação atualmente não admite valor 0 (se não me falha a memória, por um erro, já foi inserido em um dos exemplos em versão anterior deste documento como sendo um dos valores aceitos). Face a esse cenário, provavelmente devido ao princípio de robustez, tenho visto os PSPs recebedores tratando o valor 0 da mesma forma que tratam o valor ausente (o valor do Pix fica a ser definido pelo pagador), desde que os demais critérios de análise e o CRC16 estejam de acordo.

Obs: não sou BACEN. Comentário colaborativo.

**Comment by ninrod** [comment]
1. @erikaaseg, obrigado pelo reporte. Contudo, acredito que o canal adequado para reportar esse tipo de problema seria o "pix-operacional". 

2. Quem determina essa restrição é o padrão EMV-QRCPS-MPM.

**Comment by rubenskuhl** [comment]
> 1. O payload de algumas cobranças do ambiente de teste disponibilizado pelo bacen está vindo com campos a mais no devedor conforme abaixo:
>    "devedor": {
>    "nome": "Fulano de Tal",
>    "cpf": "86133673567",
>    "logradouro": "Rua Teste",
>    "cidade": "Fortaleza",
>    "uf": "CE",
>    "cep": "68762843"
>    }
> 
> A pergunta é: Isso seria possível/permitido? Pois é esperado apenas os atributos cpf/cnpj e nome para o devedor.
> 
> 1. Existe um teste de qr code inválido para testar o caso de qr code estático com valor 0. Este caso não está coberto na jornada do pagador (Lista de verificação para geração e leitura de QR Codes), e nem vi em outro documento. Existe algum documento que diz que devemos dar erro ao ler qr code estático com valor 0?

Eu entendia que os Pix Cobrança com vencimento tem sim a possibilidade de ter endereço físico. Mas eu estou em dúvida se o Pix Cobrança imediato tem isso como opcional, ou é vedado. @ninrod , poderia esclarecer ?

**Comment by ninrod** [comment]
@rubenskuhl , a @erikaaseg  está mencionando os endpoints abertos. Nos endpoins abertos, o devedor não tem mesmo todas as informações não.
