### ISSUE TITLE
Webhook x devolucao

### ISSUE THREAD

**Issue by rubenskuhl** [bacen/pix-api#354]
O webhook deve ser acionado quando a devolução de um Pix for completada ? Pq quando a devolução é solicitada, a resposta é apenas de que será tentada, e só posteriormente - de forma assíncrona - a devolução irá ou ser concretizada ou não.

**Comment by ninrod** [comment]
boa tarde @rubenskuhl 

> O webhook deve ser acionado quando a devolução de um Pix for completada ?

Entendo que é assim que está especificado: 

![image](https://user-images.githubusercontent.com/8352747/111669231-59e74c80-87f5-11eb-835d-ee2aee5318d1.png)

**Comment by ninrod** [comment]
Tem razão. Acredito que o texto pode ficar mais claro. O webhook deve ser acionado em caso de sucesso ou recusa.

**Comment by ninrod** [comment]
Feito. Obrigado pela contribuição @rubenskuhl  e @joelemanoel .
