### ISSUE TITLE
Deve ser considerado timezone do município para cálculo do pagamento

### ISSUE THREAD

**Issue by monise** [bacen/pix-api#355]
Olá! Para pagamentos de cobrança com vencimento, considerando que o pagador informou o município na obtenção de payload, o PSP recebedor deve considerar o timezone do município informado ao comparar a data/hora do pagamento (recebida via PACS.008) contra o horário atual, ou deve ser considerado apenas o timezone padrão (Brasília)?

**Comment by ninrod** [comment]
@monise, boa tarde. Essa é uma pergunta muito interessante. Não há definição a respeito, no momento. Vou encaminhar a pergunta internamente.

**Comment by ninrod** [comment]
@monise , boa tarde. 

Segue a resposta do DECEM. 

> Para efeitos de cálculo de juros e multa, a informação que deve ser considerada é a do município do pagador – isso vale inclusive para o horário (timezone). No entanto, a informação codMun não trafega na mensagem pacs008, assim apenas o horário de liquidação estará disponível ao PSP recebedor e usuário recebedor.
