### ISSUE TITLE
Filtro CPF/CNPJ  na consulta PIX

### ISSUE THREAD

**Issue by biancaOliveiraSantos** [bacen/pix-api#358]
Bom dia!

Na documentação da API  GET/pix, tem um parâmetro de entrada de CPF/CNPJ, que não sabemos se é o dado do recebedor ou do pagador, além de não retornar no response. Faz sentido mantermos o filtro?

Obrigada!

**Comment by ninrod** [comment]
@boa tarde @biancaOliveiraSantos ,

CPF ou CNPJ é do pagador:


![image](https://user-images.githubusercontent.com/8352747/111832629-d3536d80-88cf-11eb-8c48-82dd35dc88f7.png)


https://github.com/bacen/pix-api/blob/master/openapi.yaml#L1248-L1259

**Comment by biancaOliveiraSantos** [comment]
Obrigada @ninrod!

O campo CPF/CNPJ não retorna no response, vale manter o filtro?

**Comment by rubenskuhl** [comment]
> Obrigada @ninrod!
> 
> O campo CPF/CNPJ não retorna no response, vale manter o filtro?

Com certeza vale, pois ele é essencial para se verificar quem pagou. As únicas opções são com o filtro e com o campo na resposta, e com o filtro mas sem o campo na resposta.

**Comment by ninrod** [comment]
@biancaOliveiraSantos , 

> O campo CPF/CNPJ não retorna no response, vale manter o filtro?

Vale. Há um caso de uso em que o usuário recdebedor quer consultar se um pix foi recebido, porém tudo que se tem em mãos é o CPF/CNPJ do pagador.
