### ISSUE TITLE
[Dúvida] - Segurança e Certificados

### ISSUE THREAD

**Issue by filipehcds** [bacen/pix-api#36]
Estamos com algumas dúvidas relacionadas ao item 5 (Segurança) descrito no documento "II_ManualdepadroesparainiciacaodoPix-versao1.1.pdf"

> a. Os certificados digitais dos clientes da API poderão ser emitidos pelo próprio PSP ou
por ACs externas, conforme definido por cada PSP. Não deverão ser aceitos
certificados auto-assinados pelo cliente.

e

> 8. A credencial de acesso utilizada na autenticação (Client_ID) deve ser vinculada ao CNPJ ou CPF
do usuário recebedor e deve permitir acesso a recursos apenas de contas transacionais de
titularidade do CNPJ ou CPF associado

1 - O certificado será gerado pelo PSP para utilização das empresas de automação comercial ou será gerado em nome do EC?

2 - Referente aos termos "cliente" e "usuário recebedor", trata-se do EC (Estabelecimento Comercial) ou empresa no ramo de automação (Tef House, Software House, etc..)?

3 - Vamos precisar gerar 1 credencial (clientId + certificado) por EC (Dependendo da Adquirente, podem existir centenas de milhares) ou vamos precisar gerar 1 credencial por empresa de automação?

4 - Em caso de precisarmos gerar 1 credencial por EC e levando em consideração que podemos ter mais de 100.000 ECs, os próprios ECs terão que enviar suas credenciais (Certificado + ClientID) para as empresas de automação comercial em nome do EC?

5 - Em caso de precisarmos gerar 1 credencial por empresa de automação, como vai funcionar o fluxo de concessão? Antes eu havia lido na documentação que vocês sugeriram a utilização de FAPI + CIBA mas não sei se fecharam nele, outro caminho válido também poderia ser com Oauth2 Authorization Code Flow, sabem me informar?

**Comment by ninrod** [comment]
boa tarde @filipehcds 

>  O certificado será gerado pelo PSP para utilização das empresas de automação comercial ou será gerado em nome do EC?

Deve ser gerado em nome do EC. 

>2 - Referente aos termos "cliente" e "usuário recebedor", trata-se do EC (Estabelecimento Comercial) ou empresa no ramo de automação (Tef House, Software House, etc..)?

Correto. 

> 3 - Vamos precisar gerar 1 credencial (clientId + certificado) por EC (Dependendo da Adquirente, podem existir centenas de milhares) ou vamos precisar gerar 1 credencial por empresa de automação?

Para cada EC: 1..* client_ids e apenas um certificado. 

> 4 - Em caso de precisarmos gerar 1 credencial por EC e levando em consideração que podemos ter mais de 100.000 ECs, os próprios ECs terão que enviar suas credenciais (Certificado + ClientID) para as empresas de automação comercial em nome do EC?

Correto. 

> 5 - Em caso de precisarmos gerar 1 credencial por empresa de automação, como vai funcionar o fluxo de concessão? Antes eu havia lido na documentação que vocês sugeriram a utilização de FAPI + CIBA mas não sei se fecharam nele, outro caminho válido também poderia ser com Oauth2 Authorization Code Flow, sabem me informar?

A segurança está estabelecida como mTLS + Oauth2. Maiores detalhes estão especificados no __[manual de segurança do Pix](https://www.bcb.gov.br/estabilidadefinanceira/comunicacaodados)__.
