### ISSUE TITLE
Dúvidas do PATCH lotecobv

### ISSUE THREAD

**Issue by wesleygonalv** [bacen/pix-api#360]
Oi pessoal tudo bem?

Quando uma solicitação de um lote de 3000 cobranças com vencimento é realizado com sucesso, na consulta desse lote é retornado as 3000 cobranças com o status de CRIADA, porém no segundo momento, quando o cliente tenta realizar a atualização de 10 cobranças desse mesmo lote pelo endpoint PATCH /lotecobv/{id} e essas 10 cobranças não são atualizadas por causa de algum campo fora do padrão.

Após a ação, o que acontece na consulta do lote?

1 - O cliente na consulta do lote deve receber somente a última solicitação, no caso, a solicitação de atualização das 10 cobranças? ou

2 - O cliente na consulta do lote deve receber as 3000 cobranças e dentre elas as cobranças com tentativas de atualização, no caso as 10, devem está como NEGADA para indicar que a alteração não ocorreu por X motivo? ou

3 - O cliente na consulta do lote deve receber as 3000 cobranças mais as 10 ultimas solicitações de atualizações, totalizando 3010 registros? Sendo que 10 cobranças irão aparecer duas vezes, uma com o registro original de criação e a segunda com a tentativa de revisão com o status NEGADA.

**Comment by ninrod** [comment]
bom dia @wesleygonalv. 

Opção 2.

**Comment by wesleygonalv** [comment]
@ninrod aproveitando ainda a issue sobre o PATCH do lotecobv, quando uma cobrança foi negada na criação, ela pode ser alterada no PATCH do lotecobv?

Seria o cenário em corrigir apenas o que estava errado naquela cobrança.

**Comment by ninrod** [comment]
> @ninrod aproveitando ainda a issue sobre o PATCH do lotecobv, quando uma cobrança foi negada na criação, ela pode ser alterada no PATCH do lotecobv?

@wesleygonalv bom dia. Sim, pode. Não vejo problemas.

**Comment by wesleygonalv** [comment]
Obrigado @ninrod!
