### ISSUE TITLE
Dúvida - Campo "modalidadeAlteracao"

### ISSUE THREAD

**Issue by eduardosomavilla** [bacen/pix-api#365]
Bom dia!

Conforme última versão do manual 2.3.0 foi adicionado o campo "modalidadeAlteraca"o no objeto “valor” para Pix Cobrança para pagamentos imediatos. Há previsão da liberação deste campo também para os PIX Cobrança com vencimento? 

Obrigado!

**Comment by ninrod** [comment]
Bom dia @eduardosomavilla. Não há previsão no momento para essa possibilidade.
