### ISSUE TITLE
[Dúvida] Erro com motivo desconhecido no QRTester

### ISSUE THREAD

**Issue by cicloalcano** [bacen/pix-api#366]
Enviamos um QR para consulta no QRTester e retornou um erro:
Código: **STATUS_ERRO_INTERNO**
Descrição: **<Falha na verificação>**
Mensagem: **Acesso negado: https://...**

Procuramos nos testes de erros possíveis e não encontramos nenhum erro similar.
Consultando pelo browser ou por outros PSPs, conseguimos consultar com sucesso.
Por isso, gostaríamos de entender qual seria o motivo desse erro?

**Comment by ninrod** [comment]
@cicloalcano, boa noite.  Informo que o canal de suporte para o QRTester é pix-operacional.

**Comment by cicloalcano** [comment]
Vou entrar em contato por lá, desculpe!
