### ISSUE TITLE
Campo modalidadeAlteracao

### ISSUE THREAD

**Issue by felipecamargo** [bacen/pix-api#367]
Para o campo novo, **modalidadeAlteracao** da cobrança imediata, da **release 2.3**, vi que o tipo dele é numérico e não booleano, visto que só temos as opções "altera = 1" e "não altera = 0". Existe algum motivo especifico para usarmos dessa forma? no futuro poderemos ter mais modalidades de alteração?

**Comment by ninrod** [comment]
@felipecamargo, boa tarde. 

> no futuro poderemos ter mais modalidades de alteração?

Sim.
