### ISSUE TITLE
Divergência na documentação sobre o campo valor.original

### ISSUE THREAD

**Issue by wesleygonalv** [bacen/pix-api#368]
Oi pessoal, tudo bem?

Estávamos analisando a documentação e verificamos que na página 13 do Manual de padrões para iniciação do pix v2.3.0 possuí exemplos aderentes para o campo valor.original, segue a imagem a baixo:

> ![image](https://user-images.githubusercontent.com/19338037/114087229-00b98880-988a-11eb-92ce-beb00852520c.png)

Já na página 17 do mesmo manual possuí outros exemplos:

> ![image](https://user-images.githubusercontent.com/19338037/114088382-57739200-988b-11eb-9b2b-60a10fbf0bb7.png)

Porém na documentação do swagger a validação está para o pattern: \d{1,10}\.\d{2}

> ![image](https://user-images.githubusercontent.com/19338037/114087812-b258b980-988a-11eb-9ee0-7388d3afe48d.png)

Qual validação deve ser considerada? 

Estamos recebendo valores que não estão respeitando o pattern definido, devemos aceitar payloads com o valor original iguais aos exemplos abaixo?
```
Valor enviado: [39.9]
Valor enviado: [113.1]
Valor enviado: [107.7]
Valor enviado: [97]
Valor enviado: [357]
```

**Comment by mliberato** [comment]
Eu concordo que deveria ser padronizado em todos os lugares na documentação, de maneira a não dar margem para interpretação. Acho que o que gera maior confusão são os exemplos "aderentes ao padrão", pois entendo que eles não são uma lista exaustiva e não contemplam "todos exemplos válidos".

Existem PSPs que recusam pagamentos com apenas uma casa decimal no BRCode, mas na prática a serialização padrão de diversas linguagens formata com apenas 1 casa quando a segunda casa é zero.

**Comment by ninrod** [comment]
Bom dia @wesleygonalv. O que vale é o que está na especificação openapi. O pattern é `\d{1,10}.\d{2}` e isso encerra a questão. Na próxima versão do Manual de iniciação eu vou reescrever esse parágrafo. que você indicou.

**Comment by wesleygonalv** [comment]
Obrigado pelo esclarecimento @ninrod!

**Comment by ninrod** [comment]
Obrigado pelo reporte.

**Comment by wesleygonalv** [comment]
@ninrod esse formato para o valor do EMV é aplicado para qr estático?

**Comment by ninrod** [comment]
@wesleygonalv , não. Para o estático seguimos estritamente o que está na spec EMV MPM.
