### ISSUE TITLE
Validação do nome e CPF/CNPJ devedor

### ISSUE THREAD

**Issue by esantanapr** [bacen/pix-api#369]
Olá,

Considerando que o usuário final será o responsável por preencher os campos de nome e CPF/CNPJ do devedor, é necessário fazer uma validação se oficialmente o nome do devedor corresponde ao CPF/CNPJ antes de gerar o QR Code dinâmico?

Obrigado!

**Comment by ninrod** [comment]
bom dia @esantanapr. Acredito que essa pergunta já [foi respondida](https://github.com/bacen/pix-api/issues/218#issuecomment-742707875). Não há nenhuma regra, no momento, que obriga o PSP recebedor a efetuar a validação mencionada. 

link: #218
