### ISSUE TITLE
[Dúvida] na API PIX 2.0 - Expiração

### ISSUE THREAD

**Issue by mariapessoacaldas** [bacen/pix-api#37]
Por favor, pode esclarecer se devemos utilizar o default 86400 (24h) caso esse campo não seja informado na API Pix 2.0? 

Na documentação da api esse campo é opcional , mas não indica default. Já na documentação Padrão de iniciação esse default é especificado.

Além disso, gostaria de esclarecer se o campo expiração pode ou não ser utilizado em conjunto com o vencimento (em outros canais). No padrão de iniciação as descrições dos campos calendário.expiração e calendario.vencimento  estão divergentes.

Obrigada.

**Sistema ou Área**
QR Code

**Comment by ninrod** [comment]
boa tarde @mariapessoacaldas , 

> Na documentação da api esse campo é opcional , mas não indica default. Já na documentação Padrão de iniciação esse default é especificado.

Obrigado pelo reporte. Vamos adicionar essa observação a respeito do default na versão `2.1.0`. 

> Além disso, gostaria de esclarecer se o campo expiração pode ou não ser utilizado em conjunto com o vencimento (em outros canais). No padrão de iniciação as descrições dos campos calendário.expiração e calendario.vencimento estão divergentes.

Sim, pode ser utilizado em conjunto. O texto que consta no manual de iniciação está "desatualizado" e será reescrito para a próxima versão. Obrigado pelo Reporte. 

Já adiantando o funcionamento: a expiração é relativa ao timestamp de criação se a data de vencimento não existir. Se a data de vencimento existir, a expiração estará relacionada à data de vencimento.

**Comment by ninrod** [comment]
@mariapessoacaldas , 

Reformo aqui, a minha resposta, ficou perdida nas  issues:

> Sim, pode ser utilizado em conjunto. O texto que consta no manual de iniciação está "desatualizado" e será reescrito para a próxima versão. Obrigado pelo Reporte.

Não, não pode. Até porque este campo não existe na API. Aguardar a versão 2.1.0 para verificar como melhor utilizar este novo campo relacionado ao vencimento.
