### ISSUE TITLE
Relatório de Acompanhamento - Percentil 50 e Percentil 99 relacionado à experiência do usuário pagador

### ISSUE THREAD

**Issue by glaucianealves** [bacen/pix-api#370]
@ninrod boa tarde. Sou analista de negócio da Zoop, estou revisando o relatório de Acompanhamento e fiquei com dúvidas sobre o quais seriam os fluxos calculados no "Percentil 50  do tempo relacionado à experiência do usuário pagador" e no "Percentil 99 do tempo relacionado à experiência do usuário pagador", poderiam confirmar meus entendimentos:

1. Fiquei na dúvida se o  Percentil 99 seria calculado apenas pelo PSP Direto, logo PSPs Indiretos não precisam realizar essa apuração. "A apuração é realizada apenas para mensagens enviadas para participantes diretos do SPI, estejam eles atuando como PSP creditado, PSP debitado ou liquidante."

2. Nos demais tempos, no Percentil 50 será calculado a ação e no Percentil 99 o tempo de leitura ou criação da mensagem.

Exemplo: Tempo dispendido pelo PSP do recebedor ou pelo liquidante do PSP do recebedor na autorização do Pix. (t1-t0')
percentil50: momento no qual o PSP do pagador recebe a confirmação do usuário pagador para envio da ordem de pagamento.
percentil99: criação da pacs.008.

**Comment by glaucianealves** [comment]
@ninrod uma outra dúvida sobre o Relatório de Acompanhamento foi em relação ao tempo "Percentil 99 do tempo decorrido entre o recebimento (acknowledge) no DICT e a notificação ao usuário doador em ambiente logado". 
Esse processo se inicia com o PSP Direto, identificando uma Reivindicação em aberto junto ao Dict. Os PSPs indiretos devem considerar essa etapa também?

**Comment by ninrod** [comment]
Olá @glaucianealves, bom dia. 

Essa pergunta teria que ser endereçada ao pix-operacional. Este repo foca especificamente na API Pix.

**Comment by glaucianealves** [comment]
@ninrod o que seria o pix-operacional. Me desculpe, mas sou nova aqui no canal.

**Comment by ninrod** [comment]
Olá, sem problemas. Seria a caixa de correio eletrônico pix-operacional no servidor bcb.gov.br.
