### ISSUE TITLE
Validação de QR Codes disponíveis na ferramenta do Bacen.

### ISSUE THREAD

**Issue by glaucianealves** [bacen/pix-api#373]
@ninrod ao efetuar o pagamento de QR Codes Válidos, disponibilizados na ferramenta de testes do Bacen estamos recebendo o retorno: "DS04 - Pagamento rejeitado pelo PSP do recebedor". Aparentemente esse erro é retornado pelo PSP Recebedor. Ao efetuar os mesmos testes, alterando os dados da conta de recebimento tivemos sucesso no pagamento.
Gostaríamos de entender se é necessário alterar os dados da conta para efetuar os testes de  pagamento ou se existe alguma inconsistência nos dados do recebedor que esteja impedindo os testes.

**Dados do recebedor disponibilizados pelo Bacen**
ispb: 99999008
branch: 0001,
number: 12345678

Request:
curl --location --request POST 'https://banking-pix-payments-internal.staging.zoop.tech/marketplaces/f71a8951368a4cc085cf7875ff44e61c/banking/pix/holders/9ac845bf072142a69a3d5b9612e65e67/accounts/f6ffa4348a63448998bf66d309c66ab2/payments' \
--header 'Content-Type: application/json' \
--data-raw '{
  "amount": 95000,
  "transaction_id": "c7068402a1014cfe9c79052c7",
  "creditor": {
    "account": {
      "number": "12345678",
      "routing_number": "0001",
      "type": "cacc"
    },
    "name": "QRTester",
    "national_registration": "11111111000191",
    "psp": "99999008"
  }
}'

**Response:**
{
    "id": "81ffd5412a094c2ab2e7372c1223c5af",
    "transaction_id": "c7068402a1014cfe9c79052c7",
    "marketplace_id": "f71a8951368a4cc085cf7875ff44e61c",
    "status": "failed",
    "end_to_end_id": "E19468242202104262000ef4615d9ddb",
    "message_id": "M19468242442fe84a06688b28862e88e",
    "amount": 95000,
    "created_at": "2021-04-26T17:00:04.564809",
    "debtor": {
        "national_registration": "36808762000166",
        "name": "Empresa do Teste",
        "type": "individual",
        "holder_id": "9ac845bf072142a69a3d5b9612e65e67",
        "account": {
            "psp": {
                "code": "19468242",
                "name": "Zoop Tecnologia e Meios de Pagamento S.A."
            },
            "digital_account_id": "f6ffa4348a63448998bf66d309c66ab2",
            "number": "673909481",
            "routing_number": "0001",
            "type": "cacc"
        }
    },
    "creditor": {
        "national_registration": "11111111000191",
        "name": "QRTester",
        "type": "individual",
        "account": {
            "psp": {
                "code": "99999008"
            },
            "number": "12345678",
            "routing_number": "0001",
            "type": "cacc"
        }
    },
    "refunded_amount": 0
}
**Erro:**
{
    "data": {
        "clearing_system_party_identification": "19468242",
        "message_definition_identifier": "pacs.002.spi.1.4",
        "message_identification": "M6070119020210426170018669278179",
        "document": {
            "financial_institution_to_financial_institution_payment_status_report": {
                "transaction_information_and_status": [
                    {
                        "original_instruction_identification": "E19468242202104262000ef4615d9ddb",
                        "original_end_to_end_identification": "E19468242202104262000ef4615d9ddb",
                        "transaction_status": "RJCT",
                        "status_reason_information": {
                            "reason": {
                                "code": "DS04"
                            },
                            "additional_information": "Pagamento rejeitado pelo PSP do recebedor"
                        }
                    }
                ]
            }
        }
    }
}

**Comment by ninrod** [comment]
Olá @glaucianealves, boa noite. 

o caminho adequado a seguir em relação a essa questão é acionar o pix-operacional.
