### ISSUE TITLE
Cenário atipico no recebimento de mensagens, levando a  continuos "connection reset" ou "broken pipe"

### ISSUE THREAD

**Issue by netstart** [bacen/pix-api#376]
Dia 26/abril/2021 a tarde estavamos experimentando um cenário curioso e atipico, que pode ter iniciado por alguma oscilação na rede, vou relatar abaixo, e gostaria de recomendação de como proceder no futuro. Oque aconteceu foi:

1. Iniciamos o stream de recebimento de dados com start
2. Uma das mensagens teve a conexão abruptamente abortada, causando “connection reset”, ou “broken pipe”
3. Esperamos alguns milisegundos
4. Tentamos pegar a mesma mensagem
5. Voltamos ao passo 2 e entramos.

Isso aconteceu por horas, até forçarmos o sistema a desistir de pegar as 12 mensagens que estavam passando pro este cenário.

Gostaria também de recomendação de como proceder neste caso. É válido criar um algoritmo que detecte este cenário e desista de pegar a mensagem, fechando o stream de recebimento de dados e abrindo novamente?

Não relacionado diretamente a este caso, mas a dúvida ficou por aqui, gostaria de entender um pouco sobre como funciona o mecanismo de reentrega de mensagens do BACEN. 
Quando ele tenta reentregar a mesma mensagem em caso de falha? 
Como dele detecta que houve falha para decidir reentregar?

**Comment by ninrod** [comment]
Prezado @netstart, boa tarde. O canal adequado para essa questão seria o pix-operacional.

**Comment by netstart** [comment]
@ninrod pode me ajudar, não conheço esse canal de comunicação.

Como chego até ele e o utilizo?

**Comment by ninrod** [comment]
seria o e-mail pix-operacional no server bcb gov br.

**Comment by andredesouzafarias** [comment]
prezados, Bom dia!  estou com o mesmo erro na API do Banco Central e o Pix Operacional esta demorando na resposta, @netstart qual foi a solução para erro informado??
