### ISSUE TITLE
Dúvida sobre Retorno do JWS de QR Dinâmico para QR Expirados ou Vencidos

### ISSUE THREAD

**Issue by mzavarize** [bacen/pix-api#378]
Boa tarde,

Estou com uma dúvida, quando um PSP Pagador realizar a consulta de um QR Code Dinâmico para receber o JWS e o mesmo estiver expirado (Imediato) ou vencido ( com Vencimento ter ultrapassado a quantidade de dias que o QR Code é válido após o vencimento), como devo devolver para o mesmo?
Estou retornando 410,  conforme no manual de Padrão de iniciação do Pix no item 1.6.5 Sobre cobranças Concluídas informa, "A critério do PSP recebedor, payloads que representem cobranças já concluídas, expiradas ou removidas podem retornar um http status que apresente semântica adequada", mas alguns apps estão retornando erro de comunicação, com isso fico preocupado em o usuário do PSP Pagador identificar como um problema ao consultar e não que o mesmo não pode ser mais pago.
Inclusive no QR Tester quando tento verificar um QR Code Expirado ele retorna o erro "STATUS_ERRO_INTERNO" "A URL é inválida".

**Comment by ninrod** [comment]
boa tarde @mzavarize. 

Nesse caso, a URL é mesmo inválida. Mas não é, necessariamente, um "ERRO". Talvez essa mensagem esteja muito forte. 

Recomendo externar essa preocupação para o DECEM, porque é uma preocupação de UX.
