### ISSUE TITLE
[Dúvida] Sobre a migração de contas de recebimentos

### ISSUE THREAD

**Issue by sadycoimbraGn** [bacen/pix-api#38]
Em discussão a respeito da migração de conta de recebimentos, nos deparamos com um ponto de questionamento que julgamos pertinente. A API Pix é estruturada buscando dar autonomia ao usuário, de forma que ele consiga alterar o PSP fornecedor da sua API sem impactar seu negócio.

Sendo assim, temos o seguinte caso:
Migração do PSP A para PSP B

- Altera-se a URL base da API Pix para o PSP B
- Define-se novo webhook no PSP B
- Efetua-se a portabilidade das chaves para conta transacional do PSP B

Após a conclusão da migração, as confirmações de cobranças emitidas no PSP A passarão a ser entregues ao PSP B, que nesse caso não possui tais títulos salvos em sua base de dados, logo, como o PSP B deve prosseguir? Ele simplesmente aceita e cadastra as informações em sua base? E se o integrador precisar listar as cobranças ativas? Como está sendo pensada a migração de cobranças em um cenário de troca de PSP?

**Comment by ninrod** [comment]
@sadycoimbraGn , bom dia. 

Gostaria de listar alguns elementos que poderiam ser utilizados pelo usuário recebedor para trabalhar com essa situação: 

1. O PSP A poderia fornecer contratualmente um "perído extra para coleta dos recebíveis". Do ponto de vista da automação do recebedor, haveria, por tempo determinado, integração com 2 PSPs. 
2. Em caso de uma "virada de chave", o fluxo de portabilidade funciona desde que não tenha sido utilizada a chave `EVP`. Se a chave `EVP` foi utilizada, então a única maneira de se confirmar o recebimento da cobrança é via a solução 1. 
3. No caso de realmente ter sido executada a portabilidade das chaves, é verdade que o PSP B não possui os registros de cobrança em sua base. Em particular, para um dado `txid` que representava uma cobrança no PSP A, a chamada `GET /cob/{txid}` não deveria ser utilizada, inclusive por risco de colisão. Por outro lado, o usuário recebedor tem a posse dos dados que representam a cobrança original no PSP A e pode se valer desse fato para conciliar o recebimento via a chamada `GET /pix?txid={txid}` no PSP B, como estivesse conciliando um QR Estático. 


Posso responder mais alguma questão?

**Comment by rubenskuhl** [comment]
O consumidor típico de API Pix tende mais a usar EVP do que chave portável, o que reforça a tendência à estratégia de migração ativo-ativo com 2 PSPs. Também como boa prática vale considerar adorar um TxID sem colisão por parte do recebedor mesmo com mais de um PSP; os PSPs não tem como enforçar isso de cobranças em PSPs diferentes, mas o recebedor pode diminuir suas dores de migração ao garantir isso.
