### ISSUE TITLE
API para autenticação que viabilize a criação de testes automatizados, utilizando a ferramenta de geração de QRCode disponibilizada pelo Bacen.

### ISSUE THREAD

**Issue by glaucianealves** [bacen/pix-api#385]
Olá @ninrod,
Estamos realizando alguns testes referentes a Pix Cobrança e conseguimos acessar  as APIs que geram os QR Codes no site do Bacen (qr-h.sandbox.pix.bcb.gov.br). No entanto, é necessário um cookie JSESSION para que a sessão da autenticação seja mantida e as APIs possam ser executadas. 
O Bacen possui e disponibiliza alguma API, onde possamos nos autenticar e coletar os dados de sessão da autenticação?

Obrigada!

**Comment by ninrod** [comment]
@glaucianealves, boa noite. O canal adequado para tratar de QRTester é o pix-operacional. 

Em tempo, o QR Tester não disponibiliza APIs para "gerar" QR Codes, então deve estar havendo alguma confusão.
