### ISSUE TITLE
DÚVIDA - Status Cobrança com Vencimento

### ISSUE THREAD

**Issue by eduardosomavilla** [bacen/pix-api#387]
Prezados, Gostaríamos de ratificar o entendimento quanto ao status do PIX Cobrança com vencimento. Um QRdinâmico com vencimento com o status para REMOVIDA_PELO_USUARIO_RECEBEDOR ou REMOVIDO_PELO_PSP pode retornar ao status ATIVA?

**Comment by ninrod** [comment]
@eduardosomavilla 

> Prezados, Gostaríamos de ratificar o entendimento quanto ao status do PIX Cobrança com vencimento. Um QRdinâmico com 
vencimento com o status para REMOVIDA_PELO_USUARIO_RECEBEDOR ou REMOVIDO_PELO_PSP pode retornar ao status ATIVA?

Não, são status "finais".
