### ISSUE TITLE
TxID nulo em /pix

### ISSUE THREAD

**Issue by rubenskuhl** [bacen/pix-api#39]
Uma query com txid= (ou seja, em branco) em GET /pix deveria retornar os Pix recebidos sem TxID ou retornar erro ?

**Comment by ninrod** [comment]
@rubenskuhl , bom dia. 

Acredito que deveria retornar os Pix recebidos sem txid. Mas não tenho certeza de que isso fica super bonito. 

ideias?

**Comment by rubenskuhl** [comment]
Eu vejo um caso de uso válido de checar Pix que não tenham TxID, então a dúvida é se isso seria com txid="" ou com txid= ou com txid="NULL".

**Comment by ninrod** [comment]
@rubenskuhl, perfeito. 

estamos desenhando um endpoint adicional e uma conversa parecida apareceu. Acredito que o caminho aqui seria criar um parâmetro no estilo: `GET /pix?txidPresente=false`. E aí, claro, o `GET /pix?txid=` seria um erro.

**Comment by rubenskuhl** [comment]
Como dizia o Hunter de "Tiro Certo", works for me...

**Comment by ninrod** [comment]
resolvido na 2.1.0.
