### ISSUE TITLE
Dúvida em relação ao cálculo do desconto

### ISSUE THREAD

**Issue by isabellekoga** [bacen/pix-api#390]
Boa tarde prezados,

Uma situação em relação ao desconto gerou dúvida.

Considerando seguinte configuração:
desconto  modalidade 1 - (**Valor Fixo até a data informada**)
![image](https://user-images.githubusercontent.com/60149804/118171135-5fca6a00-b401-11eb-818b-5c475c6158ce.png)

Se o pagamento for realizado no dia **05/04/2021**:
_Obs:_ _dia 02/04 é feriado, e pela especificação:_
![image](https://user-images.githubusercontent.com/60149804/118171355-930cf900-b401-11eb-85db-3b277af89c06.png)
Como dia **02/04** é feriado na sexta-feria, o próximo dia útil é dia **05/04**. Neste caso qual o desconto deve ser considerado? Visto que para o dia 05/04 há dois valores diferentes de desconto. Qual seria o comportamento correto?

**1.** Considerar o maior valor de desconto, no caso **R$3.00**
**2.** Seguir na risca o valor do desconto referente ao dia de pagamento, no caso **R$2.00**

**Comment by ninrod** [comment]
@isabellekoga , dada na sua configuracão, entendo que a leitura seria a seguinte: 

| Data de Pagamento   | Desconto         |          explicação            |
|-------------------- |----------------- |--------------------------------|
| 2021.04.02          | 3,00             | data 1, sexta-feira, feriado   |
| 2021.04.03          | 3,00             | no dia anterior era feriado    |
| 2021.04.04          | 3,00             | domingo e na sexta era feriado |
| 2021.04.05          | 2,00             | data 2, segunda-feira          |
| 2021.04.06          | 1,00             | entre data2 e data3            |
| 2021.04.07          | 1,00             | entre dada2 e data3            |
| 2021.04.08          | 1,00             | data 3                         |

Vou pedir para o DECEM confirmar esse entendimento.
