### ISSUE TITLE
Alguns bancos não reconhecem o QR Code [RESOLVIDO]

### ISSUE THREAD

**Issue by alexlana** [bacen/pix-api#393]
Olá! Gerei um QR Code sem acessar APIs de bancos e ele funciona no Nubank e no Modal, por exemplo, mas não funciona na Juno e no Bradesco. Isso pode acontecer, teria um motivo? Ou existe alguma ferramenta onde eu possa validar o código gerado?

Obrigado!

**Comment by joelemanoel** [comment]
Tem uma ferramenta (não oficial): https://pix.nascent.com.br/tools/pix-qr-decoder/

**Comment by alexlana** [comment]
@joelemanoel excelente esse validador! Consegui resolver, tinha 2 problemas com o código gerado. Valeu demais!!!
