### ISSUE TITLE
Dúvida sobre a criação e alteração de um lote

### ISSUE THREAD

**Issue by wesleygonalv** [bacen/pix-api#395]
Na alteração de um lote pelo método PUT /lotecobv/{id}, é necessário informar as cobranças alteradas com o mesmo txid?

Por exemplo: 

Criar um lote com as cobranças 
{ txid: A }, 
{ txid: B }, 
{ txid: C }

Eu poderia enviar uma alteração desse lote com txids diferentes? respeitando as posições ou teria que respeitar os txids informados anteriormente?

**Comment by ninrod** [comment]
@wesleygonalv, boa noite. 

> Eu poderia enviar uma alteração desse lote com txids diferentes?

Não. 

> ou teria que respeitar os txids informados anteriormente?

Sim.

**Comment by wesleygonalv** [comment]
Já que não podemos passar um lote para revisão com txids diferentes como devemos tratar o cenário abaixo?

**1 - A Revisão do lote deve ser realizado em cima do mesmo Id da criação?** 

**2 - Revisar uma cobrança que não pertence ao lote.**

Exemplo:

Criação do primeiro lote  `PUT /lotecobv/{id} = ID: 1`, com as seguintes cobranças:
```
> { txid: A },
> { txid: B },
> { txid: C }
```

Criação do segundo lote `PUT /lotecobv/{id} = ID: 2`, com as seguintes cobranças:
```
> { txid: D },
> { txid: E },
> { txid: F }
```

Ao consultar ambos os lotes individualmente irei receber no total 3 cobranças, cada uma com os status de CRIADA.

Na tentativa de revisar as cobranças, enviei para o `PATCH /lotecobv/{id} = ID: 1` as seguinte cobranças:

```
> { txid: A },
> { txid: F }
```

A resposta do endpoint  `PATCH /lotecobv/{id} = ID: 1`, deveríamos negar antes de salvar a solicitação de alteração pois existe um TXID que não pertence ao lote ou deveríamos ignorar e no momento do processamento do lote negar somente o `Txid F`? 

Ignorando no processamento do lote ou gravando que não existe aquela cobrança para o lote, qual é o retorno da consulta `GET /lotecobv/{id} = ID: 1`?

```
> { txid: A },
> { txid: B },
> { txid: C }
```

ou 

```
> { txid: A },
> { txid: B },
> { txid: C },
> { txid: F }
```

**3 - A mensagem do erro 400 do método `PATCH /lotecobv/{id}` indica que não pode ser revisado um registro NEGADO no lote de criação  `PUT /lotecobv/{id}`, está correto? Pois essa cobrança não foi criada de fato.**

![image](https://user-images.githubusercontent.com/19338037/118711753-5290ef00-b7f6-11eb-9825-1fa8047c2571.png)

_Relacionado a conversa anterior que tivemos na [issue 360](https://github.com/bacen/pix-api/issues/360#issuecomment-814133975)._

**Comment by ninrod** [comment]
boa tarde @wesleygonalv 

> 1 - A Revisão do lote deve ser realizado em cima do mesmo Id da criação?

Sim. 

> 2 - Revisar uma cobrança que não pertence ao lote.

Não se pode fazer isso, segundo a definição da API. Veja o trecho abaixo: 

![image](https://user-images.githubusercontent.com/8352747/118875054-fbf0e700-b8c1-11eb-9a62-3c40604f6292.png)

**Comment by wesleygonalv** [comment]
@ninrod entendi e sobre a terceira pergunta?

3 - A mensagem do erro 400 do método PATCH /lotecobv/{id} indica que não pode ser revisado um registro NEGADO no lote de criação PUT /lotecobv/{id}, está correto? Pois essa cobrança não foi criada de fato.

**Comment by ninrod** [comment]
> 3 - A mensagem do erro 400 do método PATCH /lotecobv/{id} indica que não pode ser revisado um registro NEGADO no lote de criação PUT /lotecobv/{id}, está correto? Pois essa cobrança não foi criada de fato.

@wesleygonalv, boa noite. Desculpe, acabou passando. Então, não é bem isso. O que o exemplo diz é que só podem ser revisadas cobranças "ATIVAS". Cobranças que não estejam "ATIVAS" e que sofram solicitação de alteração via lote, serão respondidas com status NEGADO para a solicitação de alteração.
