### ISSUE TITLE
> > A ideia é diferenciar na consulta os status, dado que ele será usado para consultar o resultado da emissão e da revisão.

### ISSUE THREAD

**Issue by wesleygonalv** [bacen/pix-api#397]
> > A ideia é diferenciar na consulta os status, dado que ele será usado para consultar o resultado da emissão e da revisão.
> > Exemplo: revisado, em revisão ou revisão negada quando uma alteração e manter o status: criada, em processamento ou negada, quando for uma emissão de um novo qr code.
> 
> entando, mas eles são semanticamente equivalentes.
> 
> em revisao = em processamento
> criada = revisado
> revisão negada = negada.

@ninrod Já conversamos sobre isso na issue #360 mas, apesar dos status serem semanticamente equivalente, seria interessante o parceiro diferenciar uma cobrança criada de uma cobrança revisada, por exemplo.

Uma cobrança criada pelo processo do lote, pode ter os status:

- EM PROCESSAMENTO
- CRIADA
- NEGADA

Mas quando a cobrança do lote for revisada, o parceiro acaba recebendo os mesmo status sem ter indicação de número de revisão ou que foi revisada.

Seguindo o exemplo da @biancaOliveiraSantos para as cobranças que foram enviadas por lote para revisão, ficariam com um status identificando do que ocorreu na revisão, segue:

- EM PROCESSAMENTO 
- REVISADA
- REVISÃO NEGADA ( Esse status indicaria que a cobrança foi criada anteriormente porém a solicitação de revisão está negada )

Eu entendo e concordo que o status NEGADA está semanticamente equivalente e faz sentido para a funcionalidade do lote, mas poderia ser uma melhoria interessante para Api PIx, a justificativa para utilizar esses status seria para que não fosse preciso consultar a cobrança, verificando se houve ou não a alteração solicitada.

Em resumo, ao consultar o lote as cobrança teriam os seguintes status:

- EM PROCESSAMENTO
- CRIADA
- REVISADA
- NEGADA
- REVISÃO NEGADA

_Originally posted by @wesleygonalv in https://github.com/bacen/pix-api/issues/273#issuecomment-838926008_

**Comment by ninrod** [comment]
@wesleygonalv , 

> Mas quando a cobrança do lote for revisada, o parceiro acaba recebendo os mesmo status sem ter indicação de número de revisão ou que foi revisada.

Você sempre pode verificar se a cobrança foi revisada via `GET /cobv/{txid}` verificando o atributo `revisao`. Isso resolve seu problema, não?

**Comment by wesleygonalv** [comment]
Sim resolveria, mas não seria um ponto de apoio para o parceiro que está utilizando o serviço do lote? 

Eu vejo que ficaria custoso o parceiro ter que fazer uma checagem no `GET /cobv/{txid}` para saber se aconteceu ou não o processo de revisão pelo lote, quando um status na consulta do lote resolveria.

O que achas?

**Comment by ninrod** [comment]
@wesleygonalv , apenas complementando que você também pode usar: 

`GET /cobv?loteCobVId={loteid}`

E aí você poderia consultar o status de todas as cobranças do lote de uma vez. 

Ressalto que existe um grande esforço de nossa parte no sentido de não criar caminhos adicionais para se fazer a mesma coisa, na medida do possível.
