### ISSUE TITLE
Webhook para devolução

### ISSUE THREAD

**Issue by HMPannuti** [bacen/pix-api#40]
Ao ser solicitada uma devolução (PUT ​/pix​/{e2eid}​/devolucao​/{id} ), deve haver uma notificação via webhook, com a atualização do pix (inclusão do campo 'devolucoes')?

Ou as devoluções só são verificáveis através de consulta (GET ​/pix​/{e2eid}​/devolucao​/{id} )?

**Comment by rubenskuhl** [comment]
No caso dos Pix que tenham TxID a minha expectativa é de que a conclusão da devolução seja sim sinalizada via Webhook.

**Comment by ninrod** [comment]
@HMPannuti , boa noite.

> Ao ser solicitada uma devolução (PUT ​/pix​/{e2eid}​/devolucao​/{id} ), deve haver uma notificação via webhook, com a atualização do pix (inclusão do campo 'devolucoes')?

Sim, para pix associados a um txid.

> No caso dos Pix que tenham TxID a minha expectativa é de que a conclusão da devolução seja sim sinalizada via Webhook.

Exatamente. 

> Ou as devoluções só são verificáveis através de consulta (GET ​/pix​/{e2eid}​/devolucao​/{id} )?

As devoluções associadas a um Pix que não esteja vinculado a um txid são somente verificáveis via `GET /pix/{e2eid}/devolucao/{id}`.
