### ISSUE TITLE
Arredondamento de valores no cálculo da cobrança com vencimento

### ISSUE THREAD

**Issue by cinrcazangi** [bacen/pix-api#404]
Na cobrança com vencimento o manual de padrões para iniciação do Pix não menciona como resolver problemas de arredondamento. A especificação da API PIX prevê que os valores e percentuais devem sempre ter 2 casas decimais de precisão. 

Dado o cenário abaixo:

**Valor original = 10.00
Abatimento = Modalidade 2 (Percentual) no valor de 0.05%**

Ao calcular o valor de abatimento, teremos:

**Abatimento: 10.00 x 0.0005 = 0.005
Valor final: 10.00 - 0.005 = 9.995**

Quando o PSP pagador realizar a leitura desta cobrança, os valores devem ser exibidos com 2 casas decimais. Qual seria o comportamento esperado?

**A) Valor abatimento = 0.00 e Valor final = 10.00?
B) Valor abatimento = 0.01 e Valor final = 9.99?**

Ou seja, qual deve ser a regra para arredondamento?

**Comment by renatofrota** [comment]
(não sou do BACEN, comentário colaborativo)

Eu vejo como etapas separadas. O abatimento de `0.005` resultaria, na prática, seguindo exatamente a orientação de que "os valores devem ter 2 casas de precisão" em `R$ 0.01`. Portanto, `R$ 10,00 - R$ 0,01 = R$ 9,99`.

**Comment by rubenskuhl** [comment]
Me parece que a norma ABNT NBR 5891:2014 seria o ponto de partida para decisões de arredondamento. Talvez o BACEN pudesse incluir isso nos manuais do Pix. 

```1) Quando o algarismo a ser conservado for seguido de algarismo
inferior a 5, permanece o algarismo a ser conservado e retiram-se os
posteriores.
EXEMPLO: 1,333 3 arredondado à primeira decimal torna-se 1,3

2) Quando o algarismo a ser conservado for seguido de algarismo
superior a 5, ou igual a 5 seguido de no mínimo um algarismo
diferente de zero, soma-se uma unidade ao algarismo a ser
conservado e retiram-se os posteriores.
EXEMPLO 1: 1,666 6 arredondado à primeira decimal torna-se 1,7
EXEMPLO 2: 4,850 5 arredondado à primeira decimal torna-se 4,9
3) Quando o algarismo a ser conservado for ímpar, seguido de 5 e
posteriormente de zeros, soma-se uma unidade ao algarismo a ser
conservado e retiram-se os posteriores
EXEMPLO: 4,550 0 arredondado à primeira decimal torna-se 4,6
4) Quando o algarismo a ser conservado for par, seguido de 5 e
posteriormente de zeros, permanece o algarismo a ser conservado e
retiram-se os posteriores.
EXEMPLO: 4,850 0 arredondado à primeira decimal torna-se 4,8```
(Fonte: http://www.luisguilherme.adm.br/download/Alfa_MatFinanceira/00-Regras%20de%20Arredondamento.pdf)

**Comment by renatofrota** [comment]
Então 0.005 seria arredondado para 0.00 e não 0.01. Bastante contraintuitivo.

**Comment by renatofrota** [comment]
Jesus amado. Isso foi definido em 2014! Onde estavam com a cabeça? Já estamos na era da computação há muito tempo. Olha um exemplo da complicação pra se adequar à norma: https://www.dirceuresende.com/blog/sql-server-arredondamento-de-numeros-seguindo-a-norma-abnt-nbr-5891/

Eu queria muito saber os argumentos que justificam essa bizarrice.

**Comment by rubenskuhl** [comment]
> Jesus amado. Isso foi definido em 2014! Onde estavam com a cabeça? Já estamos na era da computação há muito tempo. Olha um exemplo da complicação pra se adequar à norma: https://www.dirceuresende.com/blog/sql-server-arredondamento-de-numeros-seguindo-a-norma-abnt-nbr-5891/
> 
> Eu queria muito saber os argumentos que justificam essa bizarrice.

A NBR 5891 é de 1997, 2014 é só da edição mais recente. 

Me parece que isso objetiva ter uma soma zero em muitas transações, fazendo com que as partes não tenham (em grandes números) vantagem ou desvantagem.

**Comment by ninrod** [comment]
@cinrcazangi, 

bastante pertinente o questionamento. 

Entendo que a questão não é tão problemática assim porque o PSP recebedor pode estabelecer a melhor estratégia para tratar o arredondamento. No entanto, seu ponto é relevante porque poderia surgir estratégias diferentes de arredondamento entre diferentes PSPs, o que poderia causar alguma confusão para o usuário recebedor. 

Vou levar o questionamento para o DECEM.

**Comment by mzavarize** [comment]
@cinrcazangi, pelo que vi no Manual de Padrões para Iniciação do Pix,  ele informa na parte da fórmula (página 48) "O valor calculado para Va deve ser truncado com duas casas decimais.", entendo que quando calcular o abatimento, deverá desconsiderar a terceira casa decimal.

**Comment by rubenskuhl** [comment]
> @cinrcazangi, pelo que vi no Manual de Padrões para Iniciação do Pix, ele informa na parte da fórmula (página 48) "O valor calculado para Va deve ser truncado com duas casas decimais.", entendo que quando calcular o abatimento, deverá desconsiderar a terceira casa decimal.

De um lado pode ser visto como vantajoso para o pagador, de outro como um desequilíbrio entre atores do sistema. 
Acho que vale considerar um método com valor médio nulo, seja ou não o da NBR 5891.

**Comment by renatofrota** [comment]
O truncamento é do Va (Valor de abatimento). Truncar o abatimento de 0.005 para 0.00 não é exatamente vantajoso para o pagador. Mas também não vejo prejuízo perder "meio centavo". De qualquer forma, está documentado como deve ser feito o cálculo.

**Comment by cinrcazangi** [comment]
Obrigado pelas contribuições pessoal, estou entendo que a orientação do documento então é truncar, sem nenhum tipo de arredondamento. Ou seja:

0.005 vira 0.00
0.009 vira 0.00
0.119 vira 0.11

**Comment by rubenskuhl** [comment]
> O truncamento é do Va (Valor de abatimento). Truncar o abatimento de 0.005 para 0.00 não é exatamente vantajoso para o pagador. Mas também não vejo prejuízo perder "meio centavo". De qualquer forma, está documentado como deve ser feito o cálculo.

Tem razão, e aí ser truncado e não arredondado pode ser sim considerado detrimental para o consumidor que tem previsão legal de hipossuficiência.

**Comment by ninrod** [comment]
> @cinrcazangi, pelo que vi no Manual de Padrões para Iniciação do Pix, ele informa na parte da fórmula (página 48) "O valor calculado para Va deve ser truncado com duas casas decimais.", entendo que quando calcular o abatimento, deverá desconsiderar a terceira casa decimal.

@cinrcazangi , obrigado, isso mesmo.
