### ISSUE TITLE
DÚVIDA - Portabilidade DICT

### ISSUE THREAD

**Issue by eduardosomavilla** [bacen/pix-api#405]
Prezados, 
Gostaria de esclarecer o entendimento quanto ao comportamento esperado quando há a portabilidade de chave DICT em QRCode dinâmico já previamente cadastrado. 
Exemplo: Credor emitiu QRCode dinâmico com vencimento para data futura no PSP "A" e antes do vencimento do documento solicitou a portabilidade da sua chave DICT utilizada para gerar o referido QRCode ao PSP "B". Neste cenário o QRcode deve ter sua url REMOVIDA, ou seja, deveria ficar indisponível? Ou esta deve ficar ativa e em caso de pagamento o financeiro o valor é creditado ao PSP B. Questionamos ainda se, neste cenário, ao identificarmos que houve a portabilidade da Chave DICT, há alguma restrição normativa em cancelarmos os QRCodes ativos?

**Comment by ninrod** [comment]
@eduardosomavilla , bom dia. 

> Neste cenário o QRcode deve ter sua url REMOVIDA, ou seja, deveria ficar indisponível?

É uma liberalidade do PSP recebedor "A" tratar esse cenário como lhe parecer mais conveniente. 

Para o PSP "A", parece lógico e conveniente adotar um de dois caminhos: 

1. Pode-se alterar o status da cobrança para "REMOVIDA_PELO_PSP_RECEBEDOR". 
2. Pode-se alterar o endpoint para retornar 404 ou 410 para os chamadores. 

> há alguma restrição normativa em cancelarmos os QRCodes ativos?

Não pode haver. Até porque cancelar QR Codes ativos é uma "feature" da API, então seria um conflito entre a API e a norma. 

Existem vários motivos que o PSP pode utilizar para "cancelar" um QR Code dinâmico: pagamento já realizado: timeout, fraude, usuário recebedor inadimplemente, para citar alguns.

**Comment by thiagolvlsantos** [comment]
Dúvida aparentemente esclarecida.

Atenciosamente,
Thiago Santos.
