### ISSUE TITLE
DÚVIDA - Certificado do PSP

### ISSUE THREAD

**Issue by igor-pimenta-araujo** [bacen/pix-api#406]
Estou desenvolvendo o pagamento por pix em um site para um cliente, o PSP dele é o Banco do Brasil, entretanto não estou conseguindo o certificado na parte de homologação deles. Além disso o site deles está muito instável e o forum não abre e o suporte não aceita o client id que me passaram. Alguém passou por isso e sabe como resolver?

**Comment by rubenskuhl** [comment]
Eu até o momento só vi mensagens de gente com problemas... talvez outro dos PSPs listados em #76 ?

**Comment by igor-pimenta-araujo** [comment]
O certificado digital o PSP me fornece ou eu tenho que gerar? Aparetemente a GerenciaNet fornece mas o Bradesco por exemplo não fornece. Sabe como funciona o Banco do Brasil?

**Comment by ninrod** [comment]
@igor-pimenta-araujo, obrigado pelo reporte. Recomendo acionar pix-operacional@bcb.gov.br
