### ISSUE TITLE
Dúvida sobre limite de requisição e Pix agendado

### ISSUE THREAD

**Issue by glaucianealves** [bacen/pix-api#407]
@ninrod Estamos desenvolvendo o Pix Cobrança Agendado e ficamos na dúvida de como seria o funcionamento do limite de requisições no agendamento. Visto que, uma consulta ao Dict deve sempre estar relacionada a uma transação, por meio do E2E, como ficaria no agendamento, onde a consulta ao Dict é realizada, no momento da decodificação e dias depois a transação é efetuada?

**Comment by ninrod** [comment]
@glaucianealves , boa tarde. Foge um pouco do fórum, mas você pode acionar o DECEM diretamente em pix@bcb.gov.br e encaminhar a questão.
