### ISSUE TITLE
Cobranca - Valor de desconto maior que o original

### ISSUE THREAD

**Issue by BrunoKayser** [bacen/pix-api#408]
Bom dia,

Uma dúvida referente aos descontos no fluxo de exposição.

Quando o somatório de desconto por dia útil/corrido ultrapassar o valor original, o que devo fazer, retornar um erro, ou zerar ?

Exemplo.
Crio uma cobrança com desconto na modalidade 6 (Percentual por antecipação dia útil), o valor de desconto é 10%, o valor original  é R$ 123,45, a data de vencimento é dia 2021-07-05, e a data de exposição é 2021-05-06, a quantidade de dias úteis é 43 dias, com isso o valor de desconto seria R$ 259,24, ultrapassando o valor original e gerando um valor final negativo.

**Comment by ninrod** [comment]
Bom dia. Foi pertinente a dúvida @BrunoKayser. 

Meu entendimento é que isso é uma situação de erro, não faz sentido inclusive porque não pode existir uma cobrança com valor zerado. 

Eu acredito que essa situação deveria ser travada na criação da cobrança. Você tem como saber, na criação, se uma situação dessas poderia se configurar e aí negar a criação da cobrança para o usuário recebedor com uma mensagem apropriada na linha: "se essa cobrança for criada, o valor de desconto pode ser maior do que o valor da cobrança em si dada uma antecipação grande o suficiente". 

Acho melhor do que deixar o erro aparecer para o usuário final. 

Dito isso, sugiro acionar o DECEM em pix@bcb.gov.br e compartilhar o caso.

**Comment by thiagolvlsantos** [comment]
Questão encaminhada ao pix at bcb.gov.br.

Caso queira compartilhar com a comunidade as respostas obtidas, por favor, adicione novos comentários.

Atenciosamente,
Thiago Santos.
