### ISSUE TITLE
Dúvida cobrança com vencimento quando não informado data pretendida de pagamento

### ISSUE THREAD

**Issue by monise** [bacen/pix-api#409]
Olá! Gostaria de tirar uma dúvida sobre a leitura de uma cobrança com vencimento.

No manual de iniciação tem a seguinte definição:
![image](https://user-images.githubusercontent.com/5355541/121177594-fa1ca280-c833-11eb-89a8-bd559168ea38.png)

1 - Então se o usuário **não informar** a data pretendida, o PSP sempre tem que considerar como data do pagamento a data de vencimento?

2 - Ou seja, se o dia atual que está sendo feito a consulta, for antes da data de vencimento e ele tiver direito a desconto por antecipação, não deve ser calculado os descontos, correto?

**Comment by ninrod** [comment]
bom dia @monise 

> 1 - Então se o usuário não informar a data pretendida, o PSP sempre tem que considerar como data do pagamento a data de vencimento?

Não é exatamente isso que está escrito. É isso _se_ a data da consulta for menor ou igual à data de vencimento. 

> 2 - Ou seja, se o dia atual que está sendo feito a consulta, for antes da data de vencimento e ele tiver direito a desconto por antecipação, não deve ser calculado os descontos, correto?

R: se o dia atual em que está sendo realizada a consulta for anterior à data de vencimento e o usuário pagador puder ser beneficiado com desconto por antecipação, porém o PSP pagador não enviar a `DPP`, aí sim assume-se que a DPP é a data de vencimento, e, portanto, não há o que se falar em termos de desconto por antecipação, por definição. 

Veja que essa é uma situação de exceção em que o PSP pagador, por erro ou omissão, não envia a DPP. A DPP é um requisito de UX. Em parâmetros normais de temperatura e pressão, deveria ser enviada sempre.

**Comment by thiagolvlsantos** [comment]
Dúvida aparentemente esclarecida.

Atenciosamente,
Thiago Santos.
