### ISSUE TITLE
Data de expiração - campo calendario.expiracao 

### ISSUE THREAD

**Issue by vivicupola** [bacen/pix-api#41]
Gostaria de confirmar se o campo calendario.expiração pode ser superior a  86400 segundos. No informe 048/2020 faz referência que o pagamento será apenas imediato em 16/11/2020.

**Comment by ninrod** [comment]
Boa noite @vivicupola 

> Gostaria de confirmar se o campo calendario.expiração pode ser superior a 86400 segundos. 

Não vejo óbice e acredito que não há um limite superior estabelecido. 

>  No informe 048/2020 faz referência que o pagamento será apenas imediato em 16/11/2020.

Não entendi a questão. Qual seria a relação de o pagamento ser apenas imediato com a expiração?
