### ISSUE TITLE
Validade após vencimento

### ISSUE THREAD

**Issue by MagnoCanto** [bacen/pix-api#413]
No documento https://www.bcb.gov.br/content/estabilidadefinanceira/pix/Regulamento_Pix/II_ManualdePadroesparaIniciacaodoPix_versao2-3-0.pdf , anexo 3:

- No item "2.1 Estrutura para criação e atualização de uma cobrança para pagamento com vencimento", indica que o campo "Validade Após Vencimento" tem multiplicidade [1..1], ou seja, **obrigatório**
- No mesmo item, na explicação do campo "calendario.validadeAposVencimento", indica que o campo é **opcional**.

O campo deve ser obrigatório ou opcional?

**Comment by ninrod** [comment]
Opcional com default 30 na criação do QR. Ou seja, sempre estará "atribuído". Por isso o 1..1. 

![image](https://user-images.githubusercontent.com/8352747/122995448-02222980-d380-11eb-81a6-4dbabc7135d7.png)

**Comment by thiagolvlsantos** [comment]
As versões 2.6.1 do manual e da ApiPix foram compatibilizadas para o campo ser obrigatório na leitura, mas opcional na criação.

Atenciosamente,
Thiago Santos
