### ISSUE TITLE
Retorno do valor calculado pelas modalidades

### ISSUE THREAD

**Issue by delimafcarol** [bacen/pix-api#415]
É possível que o serviço de consulta de Pix recebidos ([GET] /pix) e o callback do Webhook devolvam os valores de multa, juros, desconto e abatimento calculados?

Para que o recebedor possa lançar os valores de cada ‘item’ separadamente, é necessário efetuar o cálculo da cobrança após identificar o seu recebimento.
Como o PSP já fez este cálculo, não seria possível devolver os valores calculados?

O CNAB750 por exemplo, devolve os valores já calculados.

**Comment by ninrod** [comment]
bom dia @delimafcarol. Sim, seria tecnicamente possível alterar a API para contemplar essa informação. Entretanto, vale lembrar que todos esses valores são deduzíveis com base nos parâmetros de configuração do QR e nas regras definidas no manual de iniciação.

**Comment by delimafcarol** [comment]
> bom dia @delimafcarol. Sim, seria tecnicamente possível alterar a API para contemplar essa informação. Entretanto, vale lembrar que todos esses valores são deduzíveis com base nos parâmetros de configuração do QR e nas regras definidas no manual de iniciação.

@ninrod obrigada.
Sim, por ora, podemos realizar o cálculo segundo o manual.
É que como o cálculo já foi realizado, entendo que seria mais vantajoso retorná-lo, assim o cálculo não seria realizado 2 vezes.

É possível incluir esta funcionalidade em alguma release?

**Comment by ninrod** [comment]
@delimafcarol,

> É possível incluir esta funcionalidade em alguma release?

Possível é, mas para priorizar essa inclusão os PSPs teriam que instar o DECEM a fazê-lo. O seu PSP pode se comunicar com o DECEM e pedir priorização para essa demanda.

**Comment by thiagolvlsantos** [comment]
Boa tarde @delimafcarol,

Informamos que esse detalhamento agora está disponível no campo `componentesValor` da versão `2.6.0` da ApiPix.

Atenciosamente,
Thiago Santos.
