### ISSUE TITLE
homologação PIX 

### ISSUE THREAD

**Issue by nathsena1** [bacen/pix-api#417]
Ola,
Tudo bem?

Nas nossas homologações, precisamos validar o recebimento de PIX.. para isso outro PSP precisa enviar para nos, o que nem sempre é possível devido a disponibilidade, aos cenarios especificos q precisamos e etc..

Existem alguma recomendação de como podemos testar? algo similar a ferramenta QR tester, porem para validar recebimento de pix?

**Comment by ninrod** [comment]
@nathsena1, para esta questão, sugiro entrar em contato com pix-operacional@bcb.gov.br
