### ISSUE TITLE
[RFC] mensagem para a pessoa ao solicitar uma devolução Pix

### ISSUE THREAD

**Issue by sibelius** [bacen/pix-api#418]
https://developers.openpix.com.br/pix#tag/Pix/paths/~1pix~1{e2eid}~1devolucao~1{id}/put

`pix/{e2eid}/devolucao/{id}`

![image](https://user-images.githubusercontent.com/2005841/124278846-2965bd00-db1d-11eb-8da1-af363298fbdd.png)

Hoje só conseguimos informar o valor para solicitar uma devolução, diversos dos nossos clientes gostariam de poder enviar uma mensagem informando a motivação da devolução.
O caso de uso mais comum para devolução Pix é quando o pagamento Pix foi realizado via chave Pix (transferencia Pix, pix estático), invés de pagar um QRCode dinâmico, o que impossibilita saber porque aquela transferencia foi realizada

## Proposta

Permitir um novo campo no payload opcional `mensagem` que indicaria porque a devolução foi efetuada

```jsx
{
   valor: "100.00",
   mensagem: "Realize o pagamento via QRCode inves de transferir para a chave Pix"
}
```

**Comment by rubenskuhl** [comment]
Mesmo para recebimento via QR-Code dinâmico, uma devolução parcial pode acontecer por falta de um produto. E aí a descrição ajudaria a identificar o motivo "Devolvemos o valor relativo ao produto ABCXYZ pq não será possível enviá-lo".

**Comment by ninrod** [comment]
@sibelius , sugestão é pertinente. Levarei ao time.

**Comment by thiagolvlsantos** [comment]
Demanda atendida na versão 2.6.0.

Atenciosamente,
Thiago Santos
