### ISSUE TITLE
Dúvida - Split de Pagamentos

### ISSUE THREAD

**Issue by samuel-lujan** [bacen/pix-api#419]
Hoje já é possível criar um payload pix, para dividir entre 2 ou mais Recebedores?

**Comment by ninrod** [comment]
@samuel-lujan , ainda não. Já surgiram algumas issues sobre o assunto, como [#229](https://github.com/bacen/pix-api/issues/229). Está sendo discutido no roadmap.

**Comment by Jeopi2** [comment]
Olá. Alguma novidade a respeito dessa função?

**Comment by rubenskuhl** [comment]
> Olá. Alguma novidade a respeito dessa função?

Não, ela ainda está em agenda evolutiva futura então pode vir a ser discutida de 2023 em diante, mas em 2022 é praticamente certo que não venha a acontecer. 
As funções previstas para 2022 são:
- Débito automático
- Pix Cobrança (arquivo padronizado)
- Liquidação não prioritária
- Remuneração da conta PI

Fonte: https://www.bcb.gov.br/content/estabilidadefinanceira/pix/Forum_Pix_Plenaria/20211124-Forum_Pix.pdf

**Comment by AppMatutoDelivery** [comment]
Olá. Alguma novidade a respeito dessa função?

**Comment by rubenskuhl** [comment]
> Olá. Alguma novidade a respeito dessa função?

Nem foi citada no último Fórum Pix, o que sugere que não venha a ser padronizada pelo BACEN. O que não impede sua oferta pelo mercado. Como já acontece por exemplo com o "Pix Crédito", onde já há bancos que ofertam pagar Pix com limite de crédito ao invés de saldo em conta.

**Comment by estevaosa** [comment]
Olá, pessoal. Tudo bem?
O split evoluiu pelo BACEN, ou de fato esta funcionalidade não existirá?

**Comment by rubenskuhl** [comment]
> Olá, pessoal. Tudo bem? O split evoluiu pelo BACEN, ou de fato esta funcionalidade não existirá?

Pelo BACEN não tem sido priorizado na agenda evolutiva. Mas como a reforma tributária já vai criar obrigatoriamente split entre o recebedor e a autoridade tributária, é bem possível que isso tenha como efeito colateral estruturar o split entre partes privadas.
