### ISSUE TITLE
[Duvida] Utilização da Api

### ISSUE THREAD

**Issue by Cainan94** [bacen/pix-api#42]
olá, gostaria de saber se a API esta disponível, pois tenho projeto que envolve o PIX e gostaria de entender melhor sua utilização, se tiverem algum material que possam me ajudar fico agradecido.

**Comment by rubenskuhl** [comment]
Está publicada em https://github.com/bacen/pix-api/releases/tag/2.0.0 . Release 2.1.0 sai em alguns dias.

**Comment by ninrod** [comment]
@Cainan94 , boa tarde. 

> Está publicada em https://github.com/bacen/pix-api/releases/tag/2.0.0 . Release 2.1.0 sai em alguns dias.

Perfeito.
