### ISSUE TITLE
[DÚVIDA] Regex dos campos

### ISSUE THREAD

**Issue by Bigua** [bacen/pix-api#420]
Olá,

Em varias partes da API vcs forneceram o regex que deve validar os campos, por exemplo :
    
Pessoa Física{
cpf*    string
title: CPF
pattern: /^\d{11}$/

CPF do usuário.

Pessoa Jurídica{
cnpj*   string
title: CNPJ
pattern: /^\d{14}$/

CNPJ do usuário.

O problema:

Aqui do nosso lado usamos o Sonar para verificar a qualidade do código e segundo ele essas / iniciais e finais são desnecessárias, https://rules.sonarsource.com/java/RSPEC-5996

Podemos simplesmente removê-las de nossa API ? Não sei c isso é alguma caracteristica da linguagem que usamos aqui (java)

Grato

**Comment by ninrod** [comment]
@Bigua , boa noite. 

Você deve estar lendo diretamente o source. Na API "renderizada" não constam esses chars `/`. 

![image](https://user-images.githubusercontent.com/8352747/126232417-002066a5-16ed-4a5a-981e-b82f04b6e3b3.png)

Acredito que esse `/` está no source porque [para escrever um regex literal em JS](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions#creating_a_regular_expression) (API está em JSON) você começa com `/` e termina com `/`.

![image](https://user-images.githubusercontent.com/8352747/126232833-4a81c6fb-78a5-4efb-83d0-7d7849c82f46.png)
