### ISSUE TITLE
Exemplo de URL válida e real para testes de Pix dinâmicos

### ISSUE THREAD

**Issue by pedrofurtado** [bacen/pix-api#421]
Olá pessoal!

Existe, na documentação oficial do Bacen ou em outro local, exemplos de URLs válidas e reais para testes de Pix dinâmicos?

Pix estáticos são mais fáceis de testar, justamente por sua natureza estática (única informação que precisa ser real nele é a chave Pix).

Contudo, no caso de Pix dinâmicos, me surgiu essa questão.

Suponho que só seja possível o teste mediante pagamento de uma integração com PSP, mas gostaria de confirmar de todo modo.

Obrigado!

**Comment by pedrofurtado** [comment]
Por enquanto, testamos com URLs "genéricas", mas fato é que com uma URL real (mesmo que de homologação, mas real no sentido de debitar e etc) seria jóia 🤩

**Comment by rafaelchagasb** [comment]
@pedrofurtado  Existe uma possibilidade. 

Alguns PSPs estão ofertando a APi Pix um ambiente Sandbox ou de homologação. Você pode procurar o site de Dev de algumas das grandes instituições para ver os passos para utilizar.

Pela Api Pix você pode gerar uma cobrança imediata(cob) ou cobrança com vencimento(cobv). Ambas irão retornar um atributo chamado location que é o que você coloca na tela do Create Pix do site https://pix.nascent.com.br/tools/pix-qr-decoder/.

Alguns PSPs já estão retornando o próprio qrcode em algum atributo específico ou até em outro endpoint.

**Comment by pedrofurtado** [comment]
Não sabia dessa possibilidade. Legal!

É possível você me informar algum PsP que tenha esse serviço? Ou não é permitido?
