### ISSUE TITLE
DÚVIDA - Restrições de Uso

### ISSUE THREAD

**Issue by samuel-lujan** [bacen/pix-api#422]
Exite alguma restrição de uso dessa API? Devo ter alguma homologação com o Bacen? devo ser um tipo específico de empresa? Ou o uso é liberado para todos?

**Comment by renatofrota** [comment]
Esse repositório especifica como deve ser a API ofertadas pelas instituições financeiras aos consumidores finais (correntistas). Elas podem ofertar endpoints adicionais, mas nunca endpoints a menos ou endpoints com um padrão comportamento ou um fluxo de autenticação/funcionamento diferente do especificado aqui.

Se você é um consumidor final, você pode se guiar por essa especificação para saber o que a API ofertada pela sua instituição financeira oferece (ou deve oferecer em breve). Também é útil se a documentação da sua instituição for escassa, por exemplo.

Aparentemente, a issue #76 será útil para você.

**Comment by rubenskuhl** [comment]
> Exite alguma restrição de uso dessa API? Devo ter alguma homologação com o Bacen? devo ser um tipo específico de empresa? Ou o uso é liberado para todos?

Você não precisa de qualquer homologação do BACEN, mas a instituição financeira que você contratar para usar a API pode requerer homologações ligadas a segurança se assim optar. Eu ainda não vi nenhuma instituição fazendo esse tipo de homologação, mas pode acontecer. 

Sua empresa, ou mesmo pessoa física, pode ser de qualquer tipo que a instituição financeira tenha como público-alvo. Se a instituição quiser atender apenas algum tipo de pessoa jurídica ela pode, pois a API tem oferta opcional. Mas em ofertando, a API precisa seguir a API de referência do Banco Central... mas há algumas instituições resistentes a esse padrão se aproveitando da ausência temporária de multas para não seguir o padrão. No issue já citado se tenta separar que instituições tentam fazer essa oferta corretamente e quais não.

**Comment by thiagolvlsantos** [comment]
Dúvida aparentemente esclarecida.

Atenciosamente,
Thiago Santos.
