### ISSUE TITLE
Recebimento de Webhook

### ISSUE THREAD

**Issue by IcaroIbernon** [bacen/pix-api#423]
Existe alguma forma de criar ou adicionar um webhook a uma cobrança pix? Eu preciso apenas saber se o pagamento foi realizado em tempo real, algum PsP fornece isso?

**Comment by renatofrota** [comment]
Todos os PSPs que oferecem API devem oferecer webhook, [está na especificação](https://github.com/bacen/pix-api/blob/master/openapi.yaml#L424).

* [Issues abertos sobre o assunto](https://github.com/bacen/pix-api/issues?q=is%3Aissue+is%3Aopen+webhook)
* [Issues fechados sobre o assunto](https://github.com/bacen/pix-api/issues?q=is%3Aissue+webhook+is%3Aclosed)

**Comment by eduardohr-muniz** [comment]
Tbm estou tentando coloca webhook e não estou conseguindo você conseguiu?

**Comment by rubenskuhl** [comment]
> Tbm estou tentando coloca webhook e não estou conseguindo você conseguiu?

Vários já conseguiram com os diversos PSPs que oferecem API Pix. Lista em #76.
