### ISSUE TITLE
As EC devem possuir apenas 1 certificado por PSP?

### ISSUE THREAD

**Issue by delimafcarol** [bacen/pix-api#425]
Os certificados para acesso à API Pix (desconsiderando o Webhook) são únicos por EC e PSP?
Ou podem existir certificados diferentes? 

Ex: A "EC" ao acessar o serviço [/cobv] do "PSP A" utilizaria o `certificado 1` e ao acessar o serviço [/cob] do mesmo PSP o `certificado 2`

Entendo que a conexão à API Pix deve utilizar apenas 1 certificado por EC e PSP (com exceção ao Webhook), mas gostaria de confirmar esse entendimento :)

**Comment by rubenskuhl** [comment]
Não me parece que a documentação do Pix (tanto o manual de iniciação quanto o de segurança) estabeleça nem que o certificado seja único nem que não seja, e que isso seja algo para o PSP definir. 

O que com certeza faz mais sentido para mim é que seja o mesmo, mas a Gerencianet por exemplo tem o conceito de aplicações, e cada aplicação tem um certificado diferente. E cada aplicação pode selecionar granularmente que escopos tem acesso, então até poderia ficar da maneira que você descreveu. 

E tentando pensar um caso de uso para isso, de que o EC tem conta no PSP mas contrata duas plataformas tecnológicas distintas, essa diferenciação não vai resolver pq o /pix seria o mesmo. O webhook até dá para diferenciar por chave Pix, e alocar uma chave para cada plataforma, mas empaca no /pix.

**Comment by ninrod** [comment]
@delimafcarol , boa tarde. 

O @rubenskuhl está correto em seu entendimento.

**Comment by thiagolvlsantos** [comment]
Dúvida aparentemente esclarecida.

Atenciosamente,
Thiago Santos.
