### ISSUE TITLE
Existem endpoints públicos para gerar um payload e transmitir um payload pela rede?

### ISSUE THREAD

**Issue by Anderson-Juhasc** [bacen/pix-api#428]
Hoje consigo gerar o payload e o qrcode, mas não tenho como consultar se o mesmo foi recebimento.

**Comment by rubenskuhl** [comment]
Da API Pix você é informado do recebimento de 3 maneiras: webhook, GET em /cob (aparece o objeto Pix com E2EID quando pago), GET em /pix (retorna objeto se foi pago).

**Comment by Anderson-Juhasc** [comment]
É público? Como consigo acesso ao token caso contrario?

**Comment by rubenskuhl** [comment]
> É público? Como consigo acesso ao token caso contrario?

Não existe API pública que dê acesso a informações de uma conta, ou o sigilo bancário estaria prejudicado. Quem pode fornecer a API é a instituição financeira ou de pagamento onde você tem conta; este repositório especifica o padrão da API, mas quem a fornece são as IFs/IPs.

**Comment by thiagolvlsantos** [comment]
Dúvida aparentemente esclarecida.

Atenciosamente,
Thiago Santos.
