### ISSUE TITLE
Dúvida - Rejeitar recebimento se não informado DPP e o pagamento aconteceu antes da data de vencimento

### ISSUE THREAD

**Issue by monise** [bacen/pix-api#433]
Olá! Gostaria de tirar uma dúvida com relação a DPP para cobrança com vencimento.

Exemplo:
- Cobrança com vencimento: 20 reais
- Data de vencimento: 20/08/2021
- Usuário está lendo QR Code no dia 11/08 sem informar data de pagamento (DPP)

Se o usuário está lendo um QR Code antes da data de vencimento e **não informa uma data** (DPP), o valor que deve ser retornado no payload é o valor da cobrança para a data de vencimento, assumindo que o pagamento acontecerá apenas no dia do vencimento correto?

Neste cenário, onde não foi passado a DPP, se o pagamento for feito no dia 11/08, o PSP recebedor tem que rejeitar o recebimento, porque ele está acontecendo antes da data de vencimento? (já que o PSP Recebedor só tem a memória de cálculo para a data de vencimento)
 
Entendemos que o recebimento teria que ser recusado, pois como não foi informado o DPP na leitura, o sistema não vai considerar descontos, portanto, ele espera que o pagamento ocorra apenas na data de vencimento.

**Comment by ninrod** [comment]
Bom dia @monise 

> Entendemos que o recebimento teria que ser recusado, pois como não foi informado o DPP na leitura, o sistema não vai considerar descontos, portanto, ele espera que o pagamento ocorra apenas na data de vencimento.

O PSP *pode escolher* rejeitar o pagamento, não porque não foi atribuído um DPP na consulta, mas sim porque o valor estaria descasado com o valor esperado para aquela data de pagamento.

**Comment by rubenskuhl** [comment]
> Bom dia @monise
> 
> > Entendemos que o recebimento teria que ser recusado, pois como não foi informado o DPP na leitura, o sistema não vai considerar descontos, portanto, ele espera que o pagamento ocorra apenas na data de vencimento.
> 
> O PSP _pode escolher_ rejeitar o pagamento, não porque não foi atribuído um DPP na consulta, mas sim porque o valor estaria descasado com o valor esperado para aquela data de pagamento.

Mas isso se houver condição de desconto naquele cobv, não ? Pq se não houver, o valor é o mesmo...

**Comment by ninrod** [comment]
> Mas isso se houver condição de desconto naquele cobv, não ? Pq se não houver, o valor é o mesmo...

Isso mesmo.

**Comment by thiagolvlsantos** [comment]
Dúvida aparentemente esclarecida.

Atenciosamente,
Thiago Santos.
