### ISSUE TITLE
Datas para a versão 2.4.0 entrar em homologação e produção

### ISSUE THREAD

**Issue by TawanReis1** [bacen/pix-api#434]
Bom dia, pessoal! 

Gostaria de saber se existe uma data prevista para que a versão 2.4.0 entre em homologação e produção. Tentei encontrar nos documentos e não consegui achar.

**Comment by ninrod** [comment]
Olá @TawanReis1 , bom dia. 

Pode perguntar diretamente para o DECEM em pix at bcb.gov.br
