### ISSUE TITLE
[SEGURANÇA] Endpoint Criar Cobrança – Nome do devedor divergente da SRF

### ISSUE THREAD

**Issue by leosn** [bacen/pix-api#44]
Aqui em nosso PSP, sempre validamos os campos de CPF/CNPJ na SRF. A dúvida seria se o cliente colocar um nome diferente do cadastrado na SRF qual manteremos na base para apresentar ao PSP do pagador?

Exemplo: na API chegou Dentran-DF, mas na SRF está João Antonio.

**Comment by rubenskuhl** [comment]
Essa é uma dúvida interessante, e algo que pode ajudar a apontar um caminho são as condições de uso dos dados recebidos da SRF. Elas especificam que os dados são para uso específico da instituição com contrato de acesso à base e não podem ser repassados a terceiros... então no exemplo acima, precisaria ser repassado Dentran-DF. 

O que pode ser usado porém para evitar fraudes é recusar a emissão de cobranças com nome muito diferente do especificado na SRF. Há algoritmos bons em comparar grafias diferentes mas ainda do mesmo nome que podem ser usados. Esse tipo de uso próprio da informação da SRF é permitido.

**Comment by ninrod** [comment]
@leosn , interessante a pergunta, vou levar para o time.

**Comment by ninrod** [comment]
@leosn , neste momento o BACEN não está exigindo esta validação.
