### ISSUE TITLE
location vs loc.location 

### ISSUE THREAD

**Issue by SeanWykes** [bacen/pix-api#443]
O GET /cob retorna uma string location e também retorna um objeto loc contendo, além do id, uma string location.
Já o /cobv contém apenas o objeto loc.

1) Está correta essa duplicação de campos (location, loc.location) no /cob?
2) Está correta essa diferença entre /cob e /cobv?

**Comment by ninrod** [comment]
@SeanWykes , 1. sim, 2. sim. 

`/cob` veio antes que `/cobv` e já havíamos soltado uma versão com `location` só a string, o objeto `loc` veio depois.

**Comment by thiagolvlsantos** [comment]
Dúvida aparentemente esclarecida.

Atenciosamente,
Thiago Santos.
