### ISSUE TITLE
QR Code com CRC inválido deve ser recusado?

### ISSUE THREAD

**Issue by delimafcarol** [bacen/pix-api#444]
Tenho uma dúvida com relação ao CRC calculado.. 
Se o QR Code possuir o CRC inválido, devemos recusar?

Pergunto isto, pois, estamos homologando uma funcionalidade com o cliente e este possui CRC inválido

Como o QR Code possui o CRC inválido, não permitimos prosseguir.
No entanto, o cliente questiona, pois, quando ele efetua o pagamento diretamente por um banco X funciona.

Devemos permitir a utilização de QR Code com CRC inválido? (não gostaria)
Ou devemos avisar o gerador do QR Code que o CRC é inválido, e avisar também o banco que está aceitando, que não deveria?

**Comment by ninrod** [comment]
@delimafcarol , CRC inválido deve ser recusado. 

recomendo levar o caso urgentemente para pix@bcb.gov.br.

**Comment by delimafcarol** [comment]
@ninrod obrigada!
