### ISSUE TITLE
Dúvida - Modalidade do agente de saque no QR Code Estático

### ISSUE THREAD

**Issue by monise** [bacen/pix-api#445]
Não sei se esse seria o fórum correto, mas eu gostaria de tirar uma dúvida com relação ao QR Code Estático para Pix Saque, pois talvez no BC seja a mesma equipe que atua com a API Pix.

No manual "II_ManualdePadroesparaIniciacaodoPix-versao2-5-0.pdf" foi adicionado um campo opcional no QR Code estático para identificar o PSS, ou seja, o ISPB do prestador de serviço de saque.

![image](https://user-images.githubusercontent.com/5355541/132598007-5c47710b-c6e9-41e3-84d4-25eadee9ab08.png)

Porém, na PACS.008 é necessário além de enviar a identificação do prestador (PSS), também é obrigatório informar a modalidade do agente de saque quando a finalidade da transação for Pix Saque ou Pix Troco.
Domínios dos modalidades de agentes:

- AGPSS: Agente Prestador de Serviço de Saque
- AGTEC: Agente Estabelecimento Comercial
- AGTOT: Agente Outra Espécie de Pessoa Jurídica

![image](https://user-images.githubusercontent.com/5355541/132598029-646226a9-7ec5-4918-a535-47c5597586b3.png)

Em qual campo do QR Code estático deve ser informado a modalidade do agente de saque?

Ou se a modalidade não é informada na geração do QR Code estático, qual dos domínios de modalidade deve ser informado na PACS.008 pelo PSP do Pagador?

**Comment by ninrod** [comment]
@monise , é sempre `AGTEC` no estático. 

Acabou que não incluímos essa informação na `2.5.0`, obrigado por apontar a dúvida. Será incluído em uma provável `2.5.1`.

**Comment by thiagolvlsantos** [comment]
Demanda atendida na versão 2.6.0.

Atenciosamente,
Thiago Santos
