### ISSUE TITLE
Funcionalidade de saque e troco no COB

### ISSUE THREAD

**Issue by vivicupola** [bacen/pix-api#446]
Boa tarde.
Visto que as funcionalidades de saque e troco foram inseridas nos serviços já existentes do COB, então todos os clientes que possuem acesso a esses serviços atualmente teriam acesso às funcionalidades.  A empresa provedora dos serviços poderia limitar a utilização (permitir que um e-commerce utilize somente a funcionalidade de cobrança imediata e não utilize saque e troco, por exemplo).

**Comment by rubenskuhl** [comment]
Na regulamentação me parece claro que saque e troco só com acordo prévio entre correntista e instituição, inclusive para definir a percentagem de repasse do intercâmbio, e se vai ter saque, troco ou saque+troco.

Aliás, como há a possibilidade de só ter saque, isso automaticamente já limita a emissão de cob para fins de cobrança que não o saque... tanto o troco quanto a venda de produto ou serviço pelo EC via API Pix. 

Então por mais que a resposta usual sobre temas de negócio, escrever para o DECEM, se aplique neste caso, eu não consigo ler a regulação de nenhum jeito que proíba a limitação de cobrança, saque ou troco conforme definição do PSP.

**Comment by ninrod** [comment]
@vivcupola, bom dia. Realmente, nesse caso, a questão deve ser encaminhada ao DECEM em pix at bcb.gov.br

**Comment by thiagolvlsantos** [comment]
Questão encaminhada ao pix at bcb.gov.br.

Caso queira compartilhar com a comunidade as respostas obtidas, por favor, adicione novos comentários.

Atenciosamente,
Thiago Santos.
