### ISSUE TITLE
Devolução de Pix Troco

### ISSUE THREAD

**Issue by HMPannuti** [bacen/pix-api#447]
Existe alguma restrição no valor da devolução do Pix Troco, em relação aos seus valores da compra e do troco?
Ou seja, não é permitida, por exemplo, uma única devolução somando os valores da compra e o troco?

Ou a devolução pode ter qualquer valor, entre R$ 0,01 e o valor máximo (componentesValor.original.valor + componentesValor.troco.valor - devoluções anteriores)?
Se sim, como ficaria o campo 'natureza', neste caso?

**Comment by ninrod** [comment]
@HMPannuti , boa tarde. 

A devolução sempre tem uma natureza específica. Ou é referente à cobrança ou é referente à retirada. Se o usuário recebedor não disser nada, ou seja, se não preencher o campo `natureza`, assume-se que é uma devolução referente à cobrança. 

A devolução sempre é um valor positivo e o valor máximo seria dinâmico: ou é o máximo da cobrança ou o máximo da retirada.

**Comment by thiagolvlsantos** [comment]
Demanda atendida na versão 2.6.0 da ApiPix.

Atenciosamente,
Thiago Santos
