### ISSUE TITLE
PACS004 e Devolução do pix troco ou saque

### ISSUE THREAD

**Issue by wesleygonalv** [bacen/pix-api#448]
Oi pessoal tudo bem? espero que sim.

Sobre a devolução, como identificamos a utilização do código SL02 na solicitação da devolução da api pix? Hoje no swagger está apenas para MD06 como será a regra para SL02?

![image](https://user-images.githubusercontent.com/19338037/133641566-f8e48f23-6506-426d-9498-82fff14e8231.png)

![image](https://user-images.githubusercontent.com/19338037/133640487-c46b02e3-1aa6-4de1-b017-616235bc55e5.png)

**Comment by ninrod** [comment]
@wesleygonalv , boa tarde. 

Pela natureza, campo opcional. Se não preenchido, assume-se `ORIGINAL`, e, portanto, `MD06`. Se preenchido com `RETIRADA`, significa `SL02`. 

![image](https://user-images.githubusercontent.com/8352747/133826235-13cea651-3f21-4c1d-a7c0-ef7116aa3502.png)

**Comment by wesleygonalv** [comment]
Dúvida resolvida, obrigado!
