### ISSUE TITLE
Pix estático consegue enviar um webhook para notificação de pagamento?

### ISSUE THREAD

**Issue by pedrofurtado** [bacen/pix-api#449]
Olá a todos!

Ao gerar um Pix estático, é possível definir um webhook para notificação do pagamento dele?

Ou é necessário obrigatoriamente, nesse caso, eu me integrar a um PSP, que por sua vez me possibilita essa questão de notificação/webhook?

Obrigado!

**Comment by rubenskuhl** [comment]
Precisa de um PSP, que só pode te notificar se houver txid.

**Comment by pedrofurtado** [comment]
Muito obrigado por esclarecer, @rubenskuhl ! 🤝
