### ISSUE TITLE
PACS.008: infoAdicionais

### ISSUE THREAD

**Issue by grazipellecchia** [bacen/pix-api#45]
Bom dia.
Por favor, solicitamos auxilio com os pontos abaixo:

1) QR Estático campo infoAdicionais será trafegado pela PACS.008, assim como no QR Dinâmico? Ou seja, o PSP Pagador é obrigado a exibir a informação no momento do pagamento, ao concluir a ordem de pagamento (qr estático), teremos que devolver o campo intacto ao PSP recebedor?

2) No caso QR Dinâmico é facultativo entrada em 16/11 para PSP Recebedor realizar a emissão do QR, porém o PSP enquanto PSP Pagador, deverá estar disponível em 16/11, correto? Caso contrário, os usuários não conseguirão efetuar pagamentos nas instituições que não aderiram ao QR Dinâmico.

**Comment by ninrod** [comment]
@grazipellecchia, bom dia.

> QR Estático campo infoAdicionais será trafegado pela PACS.008, assim como no QR Dinâmico? Ou seja, o PSP Pagador é obrigado a exibir a informação no momento do pagamento, ao concluir a ordem de pagamento (qr estático), teremos que devolver o campo intacto ao PSP recebedor?

Não, o array `infoAdicionais` não trafega na PACS.008. Trata-se de uma informação que serva apenas para conferência.

> No caso QR Dinâmico é facultativo entrada em 16/11 para PSP Recebedor realizar a emissão do QR, porém o PSP enquanto PSP Pagador, deverá estar disponível em 16/11, correto? Caso contrário, os usuários não conseguirão efetuar pagamentos nas instituições que não aderiram ao QR Dinâmico.

Correto.

**Comment by jocimarcan** [comment]
@ninrod , quanto à resposta à questão 2, isso implica que a implementação do primeiro endpoint da PIX API é na verdade obrigatória para novembro? 
Isso vai de encontro à resposta recebida nessa issue (questão 8) https://github.com/bacen/pix-api-recebimentos/issues/10 e ao comunicado de que a PIX API não seria obrigatória para novembro.
