### ISSUE TITLE
Dúvida sobre nomenclatura do campo prestadorDoServicoDeSaque

### ISSUE THREAD

**Issue by wesleygonalv** [bacen/pix-api#452]
Oi pessoal, 

Uma dúvida rápida, a nomenclatura é para ser repetida mesmo ou será um para saque e outro para troco?

![image](https://user-images.githubusercontent.com/19338037/134397451-158f7ed6-c9a8-4abd-bfee-30d159049697.png)

**Comment by ninrod** [comment]
@wesleygonalv , acredito que há um problema com esse exemplo exibido por você. "Saque" e "Troco" são mutuamente excludentes.

**Comment by wesleygonalv** [comment]
Obrigado resolvido!
