### ISSUE TITLE
Dúvidas devolução de Pix Saque e Pix Troco

### ISSUE THREAD

**Issue by monise** [bacen/pix-api#453]
Olá! Boa tarde, gostaria de tirar algumas dúvidas sobre a devolução de Pix Saque e Pix Troco.

1 - As regras definidas para devolução de Pix Saque/Troco na API Pix, se aplicam para outros canais do PSP que permitem a devolução? ex: via app, se o cliente for devolver um Pix Saque/Troco as regras devem ser as mesmas?

![image](https://user-images.githubusercontent.com/5355541/134535309-918cef55-b8b0-4f87-9360-6c9eba982c53.png)

2 - No caso de devolução de Pix Saque/Troco será permitida devolução parcial? 

3 - No começo da descrição do serviço é mencionado apenas o código MD06, mas quando for a devolução de um Pix Saque e Troco deve ser usado o código SL02, correto?
![image](https://user-images.githubusercontent.com/5355541/134535537-4f22f39c-16d7-4a0f-afa3-90b0ba762ebe.png)

4 - Se é uma transação de Pix Troco, mas o usuário só quer devolver a parte da compra, deve ser usado o código MD06 ou por ser uma transação que a finalidade é Pix Troco, mesmo sendo devolvido só a parte da compra deve ser usado o código SL02?

**Comment by monise** [comment]
Olá @thiagolvlsantos só gostaria de confirmar o item 4.
Se a devolução for da **parte da compra** de um **Pix Troco**, o código que deve ser usado é o MD06 ou o SL02?

**Comment by thiagolvlsantos** [comment]
Bom dia @monise,

Se o instrumento usado é um Pix Troco o código na devolução é o SL02.

Atenciosamente,
Thiago Santos

**Comment by monise** [comment]
Boa tarde @thiagolvlsantos obrigada pelo retorno!

Mais uma dúvida, então neste caso o PSP Pagador (que precisa responder se acata ou não a devolução), não terá como validar se o valor informado na devolução está dentro do máximo permitido para o valor da compra ou do valor máximo permitido para o valor do troco, porque sempre que a finalidade da transação for Pix Troco, o código que será recebido é o SL02, é isso mesmo?
Pois na mensagem de devolução (PACS.004) não existe o campo natureza, apenas o código de erro.

Pergunto isso, pois para o PSP Recebedor (que é quem envia a devolução), antes de de enviar a devolução, pelo campo natureza ele consegue verificar se o valor devolvido está dentro do valor máximo de cada parte (parte da compra ou troco), mas o PSP Pagador não conseguirá fazer essa validação.

**Comment by thiagolvlsantos** [comment]
Bom dia @monise,

Quanto ao uso do SL02 a resposta é sim.

Em complemento, dividiremos a resposta em duas partes: 

1. O lado do PSP Pagador:

No lado do PSP Pagador a limitação de devoluções pode ser verificada junto à `PACS.008` original (Pix/Pix Saque/Pix Troco). Como a `PACS.004` tem a referência ao `e2eId` desta mensagem original o PSP Pagador tem toda informação para saber que o somatório das devoluções deste `e2eId` não pode ser maior que o valor compra, da retirada ou da compra + retirada. Estas informações estão presentes na `PACS.008` conforme o catálogo de mensagens.

2. O lado do PSP Recebedor:

Compete ao PSP Recebedor o controle dos limites em cada grupo `ORIGINAL`, ou `RETIRADA` de forma que pedidos realizados em conformidade com os limites de cada grupo, por natureza do Pix inicial, sejam respeitados. Todo registro de devolução recebido vai ser devidamente registrado junto com sua natureza.


Atenciosamente,
Thiago Santos.

**Comment by monise** [comment]
Olá @thiagolvlsantos muito obrigada pelo retorno!!

Mais uma dúvida rs, apenas para confirmar o entendimento.

Você comenta que o PSP Pagador (que precisa responder se acata ou não a devolução) tem toda a informação para fazer o somatório para saber que o valor da devolução não pode ser maior que o valor compra, da retirada ou da compra + retirada.

Mas imagina que é um Pix Troco, onde valor da compra é de 50 reais e o troco é de 30 reais. 
A PACS.004 recebida tem o valor de 40 reais e tem o código de erro SL02. 
Como a mensagem PACS.004 **não tem o campo natureza**, não da para saber se esses 40 reais é da parte da compra ou do troco. Se fosse da compra, o PSP Pagador deveria aceitar a devolução, porém se fosse da parte do troco, a devolução teria que ser rejeitada.

Só quero confirmar, o PSP Pagador não terá condições de fazer essa validação, pois o código de motivo de devolução para uma transação Pix Troco **sempre será SL02**, **independente** de qual parte (original ou retira) está sendo devolvida, correto?

**Comment by thiagolvlsantos** [comment]
Boa tarde @monise,

> Mas imagina que é um Pix Troco, onde valor da compra é de 50 reais e o troco é de 30 reais.
> A PACS.004 recebida tem o valor de 40 reais e tem o código de erro SL02.
> Como a mensagem PACS.004 não tem o campo natureza, não da para saber se esses 40 reais é da parte da compra ou do troco. Se fosse da compra, o PSP Pagador deveria aceitar a devolução, porém se fosse da parte do troco, a devolução teria que ser rejeitada.

Imaginamos esse cenário sim, por isso que na descrição `natureza` estão delimitados os valores máximos para cada tipo de natureza e instrumento (Pix, Pix Saque, Pix Troco). O PSP Recebedor deve restringir os pedidos aos limites lá descritos, de forma que  o PSP Recebedor (que implementa ApiPix) não aceitará um pedido de devolução de 40 reais com `natureza=RETIRADA`. O PSP Pagador não tem conhecimento desse campo natureza, ele recebe um pedido de devolução (PACS.004) e dadas as restrições de valor do Pix original encaminha ou não para o SPI, conforme resposta anterior.

> Só quero confirmar, o PSP Pagador não terá condições de fazer essa validação, pois o código de motivo de devolução para uma transação Pix Troco sempre será SL02, independente de qual parte (original ou retira) está sendo devolvida, correto?

Correto, conforme respondemos anteriormente.

Atenciosamente,
Thiago Santos

**Comment by thiagolvlsantos** [comment]
Dúvida aparentemente esclarecida.

Atenciosamente,
Thiago Santos.
