### ISSUE TITLE
Dúvida QR Code no response da API-PIX

### ISSUE THREAD

**Issue by WeserRodrigues** [bacen/pix-api#454]
Olá!

Na versão 2.6 da API-PIX, podemos devolver o pixCopiaeCola no resposta da cobrança. 
Minha dúvida, podemos incluir no response mais um campo com o link da imagem do QR Code?

**Comment by joelemanoel** [comment]
> Olá!
> 
> Na versão 2.6 da API-PIX, podemos devolver o pixCopiaeCola no resposta da cobrança.
> Minha dúvida, podemos incluir no response mais um campo com o link da imagem do QR Code?

Em respostas anteriores o BACEN deixou aberto a possibilidade de incrementar endpoints e respostas (desde que estes não conflitem com a padrão).
A Gerencianet por exemplo implementa vários endpoints e respostas a mais, veja em: https://documenter.getpostman.com/view/13574984/TVzVgvBA

**Comment by rubenskuhl** [comment]
Mas quando há um padrão ele passa a precisar ser seguido...

**Comment by ninrod** [comment]
> Minha dúvida, podemos incluir no response mais um campo com o link da imagem do QR Code?

Sim, como uma "extensão" da API.

**Comment by thiagolvlsantos** [comment]
Dúvida aparentemente esclarecida.

Atenciosamente,
Thiago Santos.
