### ISSUE TITLE
endToEndId do reembolso

### ISSUE THREAD

**Issue by sibelius** [bacen/pix-api#455]
Faz sentido retornar o endToEndId de um reembolso Pix?

**Comment by thiagolvlsantos** [comment]
Prezado @sibelius,

o `endToEndId` do Pix original (aquele do qual se deseja uma ou mais devoluções) é parte necessária e imprescindível para a criação de uma `PACS.004` de forma que só existe devolução se existe um `e2eId`. Ao detalhar um Pix na API pelo `e2eId` tem-se todas devoluções relacionadas aquele Pix, bem como o GET da devolução pressupõe o conhecimento do `e2eId`.

Atenciosamente,
Thiago Santos.

**Comment by sibelius** [comment]
gostaria de saber qual seria o endToEndID da transação do reembolso em si, e não da transação que foi solicitado o reembolso
