### ISSUE TITLE
Duvida - pixCopiaECola na Cobrança dados retroativos

### ISSUE THREAD

**Issue by pelichero** [bacen/pix-api#459]
Boa tarde.

Diante da necessidade da alteração **pixCopiaECola** nas apis de cobrança

![image](https://user-images.githubusercontent.com/8244958/136824405-cb91e4e2-21f9-4a92-9812-bfe82717ec42.png)

![image](https://user-images.githubusercontent.com/8244958/136824318-0500a9aa-4f84-4a48-b9d4-6d3ac68e1a73.png)

A inclusão de tal campo deve aparecer em cobranças emitidas/pagas posteriores à data da especificação?

**Comment by rubenskuhl** [comment]
Eu acho que sendo opcional, nem é a data da especificação do BACEN que importa, é a regra que você definir. O seu "contrato" com seus clientes. 
- Vai retornar só para as novas ? Diz isso, e a partir de quando. 
- Vai retornar para todas ? Diz isso, e a partir de quando. 
- Só vai retornar para quem pedir ? Diz isso, e diz como pedir para receber. 
- Vai retornar para todo mundo, mas pode pedir opt-out ? Diz isso, e e diz como pedir para sair.
