### ISSUE TITLE
Dúvida data de criação deve ser retornada em UTC

### ISSUE THREAD

**Issue by monise** [bacen/pix-api#460]
Olá! Gostaria de tirar uma dúvida, a data de criação da cobrança que são retornadas nos serviços de GET da API Pix devem ser em UTC?
Se sim, qual deve ser o comportamento pros demais campos de data/hora? devem ser em formato GMT-3 ou UTC ?

**Comment by thiagolvlsantos** [comment]
> Olá! Gostaria de tirar uma dúvida, a data de criação da cobrança que são retornadas nos serviços de GET da API Pix devem ser em UTC?

Sim.

>Se sim, qual deve ser o comportamento pros demais campos de data/hora? devem ser em formato GMT-3 ou UTC ?

UTC

Atenciosamente,
Thiago Santos
