### ISSUE TITLE
Dúvida no QR Code estático de pix Saque

### ISSUE THREAD

**Issue by erikaaseg** [bacen/pix-api#466]
No manual de iniciação do PIX consta que o campo pss fica dentro do campo Merchant Account Information (Id 26-51).
![image](https://user-images.githubusercontent.com/37914243/140788262-0671c631-5cc4-4d27-815b-892058ee76f4.png)

No ambiente de homologação do Bacen, o qrcode disponibilizado possui o campo pss no Id 3, fora do Id 26.
![PixSaque](https://user-images.githubusercontent.com/37914243/140788346-41a65aa8-0c63-4697-81c5-1cd5f1eb0f39.png)

Qual seria o correto?

**Comment by thiagolvlsantos** [comment]
Boa tarde Erika, 

Estamos analisando o Pix Tester, te daremos retorno em breve.

Atenciosamente,
Thiago Santos.

**Comment by thiagolvlsantos** [comment]
Boa tarde @erikaaseg ,

Obrigado pelo relato, o Pix Tester foi ajustado conforme manual.

Por favor, repita o teste.

Atenciosamente,
Thiago Santos.

**Comment by thiagolvlsantos** [comment]
Bom dia @erikaaseg,

Por favor, feche esta issue caso o problema tenha sido sanado.

Atenciosamente,
Thiago Santos.
