### ISSUE TITLE
Dúvida mudar status de cobrança REMOVIDA_PELO_PSP para REMOVIDA_PELO_USUARIO_RECEBEDOR

### ISSUE THREAD

**Issue by monise** [bacen/pix-api#468]
Olá!! Gostaria de tirar uma dúvida sobre atualização de status de uma cobrança.
Se a cobrança está no status REMOVIDA_PELO_PSP , o status dela pode ser alterado via API Pix para REMOVIDA_PELO_USUARIO_RECEBEDOR?

**Comment by thiagolvlsantos** [comment]
Bom dia @monise,

acho que faltou observar as pré-condições (violações) dos patches:

> Violações específicas para o endpoint PATCH /cob/{txid}:
> - A cobrança não está ATIVA, e a presente requisição busca alterá-la.

> Violações específicas para o endpoint PATCH /cobv/{txid}:
> - A cobrança não está ATIVA, e a presente requisição busca alterá-la

Desta forma, não há porque se considerar esse tipo de transição de estado.

Obs.: Caso a dúvida tenha sido esclarecida, peço que feche a issue.

Atenciosamente,
Thiago Santos.
