### ISSUE TITLE
Erro na análise de qrcode saque/troco (plataforma qrcode tester)

### ISSUE THREAD

**Issue by TawanReis1** [bacen/pix-api#469]
Boa tarde, pessoal!

Estou passando por alguns problemas ao validar um qrcode gerado aqui na minha empresa. Estou recebendo na plataforma que os atributos loc, location e pixCopiaECola são inválidos. Mas olhando o swagger que vocês disponibilizaram, esses atributos ainda estão lá, e devem ser retornados na criação de uma cobrança, e com isso, não entendi o que estou fazendo de errado. Conseguem me dar uma força, por favor?

Anexo a esta mensagem, estou encaminhando o print da documentação

![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/40872077/142671983-892d6c23-5283-4857-b5e0-54a1102e75cb.png)
![Screenshot 2021-11-19 151747](https://user-images.githubusercontent.com/40872077/142671986-64a53511-0862-4d98-bdbb-ab65ad6cc9eb.jpg)
e o print dos erros recebidos na plataforma.

Atenciosamente,
Tawan Reis.

**Comment by thiagolvlsantos** [comment]
Questão já sendo tratada junto ao pix at bcb.gov.br.

Caso queira compartilhar com a comunidade as respostas obtidas, por favor, adicione novos comentários.

Atenciosamente,
Thiago Santos.
