### ISSUE TITLE
Qr Code dinâmico - "API Criar Cobrança"

### ISSUE THREAD

**Issue by vivicupola** [bacen/pix-api#47]
No retorno 200 da API Criar Cobrança, não seria necessário ter o campo para retornar a imagem no formato base64 do Qr?

**Comment by rubenskuhl** [comment]
O BACEN já informou que não em https://github.com/bacen/pix-api/issues/7 .

**Comment by ninrod** [comment]
@vivicupola , bom dia. 

Realmente, como @rubenskuhl afirmou, a issue está duplicada. Ver issue #7.
