### ISSUE TITLE
Deprecado parâmetros de retorno dos serviços de consulta

### ISSUE THREAD

**Issue by monise** [bacen/pix-api#470]
Olá! Vimos que na versão 2.6.1 os filtros das duas consultas de lista de cobranças (imediatas e vencimento) estão como deprecados.
Já está em vigor o desuso destes campos ou existe uma data prevista para eles serem descontinuados?

![image](https://user-images.githubusercontent.com/5355541/142952702-f5b347ec-251d-4231-b8ef-08a17a6b1edb.png)

**Comment by thiagolvlsantos** [comment]
Boa tarde @monise,

A prática de software com uso de "DEPRECATED" é avisar que algo vai sair de uso (no futuro), e na versão que não valer mais coloca-se no changelog explicitamente quais itens foram removidos.

Como não informamos a remoção na versão corrente (2.6.1) os atributos encontram-se em vigor. Só saindo quando uma versão específica futura informar a remoção e passando a valor a partir das datas de implantação que forem informadas (homologação e produção).

Obs. Se sua dúvida foi esclarecida, pedimos que feche a issue.

Atenciosamente,
Thiago Santos
