### ISSUE TITLE
Gerenciamento de Pix recebidos - deve trazer pix efetuados?

### ISSUE THREAD

**Issue by GustavoSTZ** [bacen/pix-api#473]
Na parte de Gerenciamento de Pix recebidos, no endpoint de "Consulltar PIX" temos a mensagem "Dados do Pix Efetuado" no retorno 200:

![image](https://user-images.githubusercontent.com/48111506/143310736-3b8c3143-286d-4150-92d8-b33d179f6ebd.png)

Devido ao nome da aba ser "Gerenciamento de **Pix recebidos**", penso que só se refere aos pix recebidos, esta mensagem está incorreta ou devemos buscar pelos pix efetuados?

**Comment by thiagolvlsantos** [comment]
Boa tarde @GustavoSTZ,

O endpoint retorna o Pix recebido para aquele e2eId (e suas eventuais devoluções), ou seja o Pix (e suas devoluções) com processamento efetuado (sucesso ou erro).

Obs.: Se sua dúvida foi sanada, pedimos que feche a issue.

Atenciosamente,
Thiago Santos

**Comment by rubenskuhl** [comment]
Eu acho que ele se referia a Pix enviados por API, algo que não faz parte da API Pix padrão atualmente mas é ofertado por alguns PSPs.
