### ISSUE TITLE
Campo location na cobrança com vencimento

### ISSUE THREAD

**Issue by monise** [bacen/pix-api#474]
Olá! Gostaria de tirar algumas dúvidas com relação a cobrança com vencimento em lote.
Vimos que na cobrança imediata, assim que a cobrança é criada, já é possível ser retornada a location mesmo sem ter sido informado um loc específico na requisição.

![image](https://user-images.githubusercontent.com/5355541/144404495-e2573e20-3116-4359-95e2-3133c7654595.png)

Porém, para cobrança com vencimento, não existe o campo location fora da estrutura de loc.

1 - Então no caso da cobrança com vencimento, é **sempre necessário informar um loc** no resquest para que ela já seja gerada contendo a url para acessar o payload?

2 - É possível retornar no response o campo location fora da estrutura de loc?

![image](https://user-images.githubusercontent.com/5355541/144404733-bb122529-fdab-448a-93c3-328e1077b06f.png)

**Comment by thiagolvlsantos** [comment]
Boa tarde @monise,

> 1 - Então no caso da cobrança com vencimento, é sempre necessário informar um loc no resquest para que ela já seja gerada contendo a url para acessar o payload?

Não. Quando não informado o PSP pode gerar o 'location' que quiser no response. Se for informado na criação, na saída o valor é respeitado, caso o PayloadLocation não tenha sido manipulado posteriormente.

> 2 - É possível retornar no response o campo location fora da estrutura de loc?

A informação já está disponível dentro de 'loc' não havendo necessidade de subir 1 nível na estrutura.

Caso a dúvida tenha sido esclarecida, pedimos que feche a issue.

Atenciosamente,
Thiago Santos

**Comment by celobento** [comment]
Se possível gostaria de tirar uma dúvida com relação a este tópico!

@thiagolvlsantos quando você fala:

> Não. Quando não informado o PSP pode gerar o 'location' que quiser no response.

Mas na mensagem de retorno do **cobv** não tem o 'location', apenas o 'loc'. O 'loc' é criado através do PayloadLocation. Então fiquei confuso! Pode dar um help?
