### ISSUE TITLE
Descrição os Codigos de Devolução

### ISSUE THREAD

**Issue by MarcosJoseNunes** [bacen/pix-api#477]
Pessoal, por favor alguem pode  me ajudar dizendo onde posso conseguir a descrição dos códigos de devolução do PIX?
AM05, AM09, BE08, DS28, FOCR, FR01, MD06, NARR, RUTA, SL02, SL11, SL12, UPAY

**Comment by MarcosJoseNunes** [comment]
Achei....https://www.bcb.gov.br/estabilidadefinanceira/comunicacaodados

**Comment by thiagolvlsantos** [comment]
Dúvida aparentemente esclarecida.

Atenciosamente,
Thiago Santos.
