### ISSUE TITLE
Dúvidas cobrança em lote com status igual a negada

### ISSUE THREAD

**Issue by monise** [bacen/pix-api#478]
Olá! Gostaria de tirar algumas dúvidas sobre os serviços de cobrança em lote.

Cenário: É enviado no serviço de PUT 3 cobranças e uma delas fica com o status de negada.

1 - Se for enviado uma alteração pelo PUT de cobrança em lote, só passando as outras 2 cobranças, deveria dar erro porque falta a terceira cobrança, mesmo ela estando com o status de negada? 

2 - Nesse cenário que há uma cobrança negada, devemos considerar que a cobrança não existe, correto?

3 - Se for passado apenas a cobrança que está com o status de negada no serviço de PATCH de cobrança em lote, o sistema deve aceitar a requisição e criar a  cobrança a partir do serviço de PATCH?

Obrigada!

**Comment by ninrod** [comment]
Bom dia @monise.

1. Certo.
2. Certo.
3. Certo.

**Comment by thiagolvlsantos** [comment]
Dúvida aparentemente esclarecida. 

Atenciosamente,
Thiago Santos.
