### ISSUE TITLE
Dúvidas básicas sobre a API PIX e integração com ERP

### ISSUE THREAD

**Issue by JackelineVenson** [bacen/pix-api#482]
Olá, primeiramente, desculpe a minha ignorância neste espaço com discussões já tão avançadas, mas, 
estou iniciando a integração no ERP da software house que trabalho e possuo algumas dúvidas básicas. 
Desde já agradeço a quem se disponibilizar a responde-las =)

Meu cenário: Pretendo integrar ao meu ERP o recebimento por PIX imediato, onde no momento da emissão da nota fiscal, o ERP gera o Qrcode no valor da nota, o pagador paga pelo celular dele, e o ERP consulta se a transação foi paga.  

1- Para gerar o Qrcode estático com o valor das notas e os dados do recebedor, há necessidade de contatar PSP ou usar API PIX? Posso gerar com as informações bancárias ou chave pix do recebedor? A necessidade de certificado digital?

2- Para automatizar a consulta de recebimento do PIX, o único meio é entrando em contato com cada PSP (banco) dos possíveis recebedores e ver se ja está disponível esta consulta? Se o PSP não tiver esta opção ainda, tem outra solução?

Obrigada.

**Comment by rubenskuhl** [comment]
1 - Há necessidade de contratar um PSP (lista em #76), mas a API Pix não tem método de criação de QR-Code estático, então neste caso só seria usada a parte de gestão de Pix (/pix e /webhook) e não a criação de cobranças (/cob). Aliás, pq você decidiu usar QR-Code estático ? O dinâmico parece ter melhor adequação ao caso de uso (1 NF -> 1 Cobrança -> 1 Pix). 

2 - Outra solução é o cliente usar um PSP com API para o recebimento, e posteriormente transferir o dinheiro para uma instituição que ele prefira.

**Comment by JackelineVenson** [comment]
Oi Rubens, obrigada por responder. 
Irei entrar em contato e tirar as dúvidas com um primeiro PSP, vou olhar a lista #76.
No caso do QR-Code, irei pensar melhor qual utilizar ainda. Acredito que o dinâmico seja mais útil mesmo. 
Valeu!

**Comment by rubenskuhl** [comment]
Os casos naturais de uso do estático para mim são onde há múltiplos pagamentos. Por exemplo, um QR-Code na gôndola que identifica um produto para pagamento imediato, ou um QR-Code no caixa que identifica a loja+caixa. 
Há quem tenha usado QR-code estático para pagamento único (uma start-up fez isso para tentar driblar a API padrão, mas esqueceu que as notificações e /pix estavam cobertas pelo padrão), e há as possibilidades (não implementadas por todos os PSPs) de reuso do location do dinâmico ou de permitir alteração do valor do dinâmico. Mas acaba sendo um pouco de enviar a peça redonda no buraco quadrado.

**Comment by JackelineVenson** [comment]
Entendi, estou em contato tbm com uma desenvolvedora grande no mercado que oferece uma solução única e tem alguns bancos homologados já. Mas estou vendo ainda se vale a pena no meu caso.

Obrigada novamente pelo retorno.

**Comment by rubenskuhl** [comment]
> Entendi, estou em contato tbm com uma desenvolvedora grande no mercado que oferece uma solução única e tem alguns bancos homologados já. Mas estou vendo ainda se vale a pena no meu caso.
> 
> Obrigada novamente pelo retorno.

Há agregadores com APIs proprietárias, e eles não sendo PSPs eles de fato não precisam seguir a API padrão do BACEN. Porém, algo para você considerar é se o lock-in que isso traz não é ruim para a estratégia de vocês... pq depois para mudar pode estar envolvido considerável esforço e investimento. A Internet cresceu e alcançou a importância que tem hoje exatamente por causa dos padrões; é esse ganho para o ecossistema que eu imagino fosse o objetivo do BACEN com uma API padronizada, e você pode estar trocando um eventual pequeno ganho no curto prazo por um problemão mais à frente.

**Comment by joelemanoel** [comment]
> Um adendo: não há impeditivo para um não PSP oferecer a API Pix padrão do BACEN. A licença de uso é livre. Mas ainda não soube de nenhum que fizesse isso... pelo contrário, todos tem um discurso de que isso é bom para você, quando o real beneficiado é o fornecedor pelo lock-in.

Essa parte até me deixa desanimado, um exemplo é o Paghiper que poderia implementar a API Pix padrão do BACEN e posteriormente tentar virar um PSP.

**Comment by JackelineVenson** [comment]
Entendi. Realmente trabalhar de forma independente neste caso me ajuda a caminhar conforme eu quiser, me adaptando as regras sem depender do lock-in de terceiros.
Irei considerar suas palavras e analisar a melhor estratégia. Obrigada.

**Comment by joelemanoel** [comment]
> Um adendo: não há impeditivo para um não PSP oferecer a API Pix padrão do BACEN. A licença de uso é livre. Mas ainda não soube de nenhum que fizesse isso... pelo contrário, todos tem um discurso de que isso é bom para você, quando o real beneficiado é o fornecedor pelo lock-in.

Essa parte até me deixa desanimado, um exemplo é o Paghiper que poderia implementar a API Pix padrão do BACEN e posteriormente tentar virar um PSP.

**Comment by thiagolvlsantos** [comment]
Dúvida aparentemente esclarecida. Agradecemos a todos que contribuíram.

Caso já esteja satisfeito/satisfeita com as informações compartilhadas, por favor, finalize a demanda.

Atenciosamente,
Thiago Santos.

**Comment by JackelineVenson** [comment]
Obrigada.
