### ISSUE TITLE
[LoteCobv] Alterar/Atualizar cobranças que já foram criadas com algum erro na requisição.

### ISSUE THREAD

**Issue by RicardoFGuimaraes** [bacen/pix-api#487]
Bom dia, lendo as Issues sobre a funcionalidade de LoteCobV, um ponto foi levantado numa discussão da equipe:

Digamos que exista um lote de cobranças [a,b,c], todas com status "CRIADA" e é feita uma requisição, via PUT ou PATCH, de alteração dessas cobranças onde existe um campo errado em cada uma dessas cobranças, o que fará com que seus status sejam alterados para "NEGADA".

Contudo, como essas cobranças haviam sido criadas anteriormente, seus registros já existiram na base e caso alguém tentasse consultá-las via GET/cobv/{txid}, o response traria o estado original da cobrança.

Isso parece estar em contradição com a regra que diz que "uma cobrança que possui status 'EM_PROCESSAMENTO' ou 'NEGADA'" não deve ser exibida no endpoint  GET/cobv/{txid}.
![image](https://user-images.githubusercontent.com/71861417/149781523-fedbb28f-0fb1-4546-9e04-2f09cac4012c.png)

Dado esse cenário, quais seriam as opções?

1 -  Permitir a consulta das cobranças com seu estado original.
2 - Deletar as cobranças para que as mesmas não possam ser consultadas.

**Comment by thiagolvlsantos** [comment]
Boa tarde @RicardoFGuimaraes,

Um pedido de lote saudável de cobranças não será modificado por envios posteriores que retornem ‘NEGADO’. Em outras palavras, não se corrompe o estado original das cobranças uma vez que o pedido de mudança delas via lote posterior foi ‘negado’. Desta forma, após uma tentativa desse tipo, as consultas ao lote ou às cobranças criadas ainda retornarão os dados iniciais.

Caso já esteja satisfeito/satisfeita com as informações compartilhadas, por favor, finalize a demanda.

Atenciosamente,
Thiago Santos
