### ISSUE TITLE
Pix dinâmico pode ter data de expiração não definida (infinita)?

### ISSUE THREAD

**Issue by pedrofurtado** [bacen/pix-api#488]
Olá! 👋 

Um Pix dinâmico pode ter data de expiração não definida (infinita)? Ou necessariamente todo pix gerado através de alguma instituição financeira deve possuir um limite de tempo? Caso seja obrigatorio, o bacen tem um valor máximo estabelecido?

Obrigado!

**Comment by rubenskuhl** [comment]
O valor máximo é um signed int de 64 bits em segundos. Isso dá 63 anos, que apesar de não ser infinito, é mais tempo do que muitos usuários do Pix tem de tempo restante... ;-)

**Comment by pedrofurtado** [comment]
Maravilha, 63 anos é um bom limite, tempo suficiente para pagar! 😄 

Obrigado pelo esclarecimento, @rubenskuhl 🤝

**Comment by thiagolvlsantos** [comment]
Dúvida aparentemente esclarecida. Agradecemos a todos que contribuíram.

Caso já esteja satisfeito/satisfeita com as informações compartilhadas, por favor, finalize a demanda.

Atenciosamente,
Thiago Santos.
