### ISSUE TITLE
Dúvida sobre o schema da cobrança em lote.

### ISSUE THREAD

**Issue by keji100** [bacen/pix-api#489]
Boa tarde,

Estou em dúvida em relação ao schema do lote de cobrança com vencimento, sendo elas:

1. O id do lote deve ser uma string ou inteiro ? 

![image](https://user-images.githubusercontent.com/36178537/150192988-b90f5261-08f7-4906-b68c-79fd6f418982.png)

2. Qual o tamanho máximo da descrição do lote ?

![image](https://user-images.githubusercontent.com/36178537/150193986-de63de0d-ab81-404c-81eb-26dcc228cc5c.png)

**Comment by thiagolvlsantos** [comment]
Boa tarde @keji100,

Os campos citados são semanticamente equivalentes, devem conter a mesma informação (texto e sua versão numérica). Naturalmente, há que se evitar strings iniciadas por '0' (zeros) para que essa essa consistência seja mais explícita.

Inicialmente ajustaremos os textos para a próxima minor version, e quando houver oportunidade para uma versão com quebra de contrato, envolvendo mudança de tipos, ajustaremos também a descrição para um tamanho máximo, a definir. 

No momento não há que se restringir o tamanho da descrição no momento sob risco de quebra nas chamadas dos clientes que porventura estejam mandando descrições longas.

Agradecemos as questões apontadas, e caso já esteja satisfeito com as informações compartilhadas, por favor, finalize a demanda.

Atenciosamente,
Thiago Santos

**Comment by keji100** [comment]
Olá @thiagolvlsantos,

Só para ver se entendi sobre o ponto 1.

Supondo que as informações devem ser a mesma, eu posso concluir que o **ID só deverá possuir números inteiros**, pois:
- Um inteiro pode ser convertido para uma string (Exemplo: 12345 = "12345")
- Nem toda string pode ser um inteiro. (Exemplo: id = "i1b3x45w123" não pode ser convertido para inteiro.)

**Correto ?**

**Comment by keji100** [comment]
Muito obrigado pelos esclarecimentos @thiagolvlsantos !

At.te,
Willian Rosa
