### ISSUE TITLE
[Dúvida] GET ​/{pixUrlAcessToken}

### ISSUE THREAD

**Issue by mariapessoacaldas** [bacen/pix-api#49]
Essa API retorna o payload do QR Code Dinâmico. Percebemos que os campos data de vencimento, juros, multa, desconto e valor final também foram retirados do response, porém se mantiveram no Padrão de Iniciação.

Qual orientação devemos seguir para prover a consulta dos QR codes (url) no momento do pagamento para outras instituições - Manual de Padrão de iniciação 1.1 ou GET ​/{pixUrlAcessToken} ?

**Comment by ninrod** [comment]
Bom dia @mariapessoacaldas , acredito que é uma duplicada de #50, mas respondo aqui também: os campos voltarão na versão `2.1.0`, na API, com uma semântica específica. 

A questão de os campos "multa, juros, etc..." constarem no manual, mas não constarem na API Pix realmente é uma fonte de confusão. Para resolver essa questão estamos trabalhando intensamente para entregar a API `2.1.0` o mais rápido possível.
