### ISSUE TITLE
API para obtenção de pix saque e troco

### ISSUE THREAD

**Issue by reelopes** [bacen/pix-api#497]
Olá, boa tarde.

Existem endpoints para que seja possível logar no pix tester e gerar os QR Codes do tipo pix saque e troco com o objetivo de automação de testes?

**Comment by thiagoiaia** [comment]
Os endpoints são os mesmos para ambiente de testes e homologação, o que muda é se o PSP fornece esses 2 ambientes.

**Comment by reelopes** [comment]
Show! Consegui aqui o que precisava. Na verdade queria, via Postman, criar as chamadas para obter os QR Codes de todos os tipos, realizar os pagamentos e fazer a verificação. Ex (qr estatico): https://qr-h.sandbox.pix.bcb.gov.br/rest/qr/cobe/esta/generate
