### ISSUE TITLE
Dúvida sobre end-point com payload

### ISSUE THREAD

**Issue by rubenskuhl** [bacen/pix-api#5]
Na versão 2.0.0, passou a ser especificado também o endpoint usado por apps pagadores para baixar o QR-Code dinâmico, https://{fdqnPSPRecebedor}/{pixEndpoint}/v1/{pixUrlAcessToken} . 

Isso é uma adição para que o estabelecimento comercial possa baixar diretamente o payload se quiser checá-lo, ou o mesmo end-point que atende os apps das outras IFs/IPs deve ser usado para atender os consumidores da API de Recebimento ? Ou nenhuma das duas coisas é a junção é apenas para documentar num único repositório mas são end-points independentes ?

**Comment by ninrod** [comment]
@rubenskuhl, nós movemos todas as definições sobre o "payload" que estavam no doc. de iniciação para esse especificação. 

Essa entrada descreve o endpoint que será acessado pelo app do psp pagador no ato da leitura do QR Code dinâmico. Essa URL `https://{fdqnPSPRecebedor}/{pixEndpoint}/v1/{pixUrlAcessToken}` é a URL que efetivamente estará codificada dentro do QR dinâmico. 

Importante notar que a segurança e o "server" dessa URL difere dos outros endpoints (o server pode ser igual, ser o PSP quiser, mas não é necessário).
