### ISSUE TITLE
[Dúvida] Vencimento, juros, multa e desconto

### ISSUE THREAD

**Issue by mariapessoacaldas** [bacen/pix-api#50]
Esses campos foram retirados da API Pix 2.0. Havíamos entendido que poderiam ser ofertados nos aplicativos, mas a padronização do GET​/{pixUrlAcessToken} nos trouxe dúvida.

Podemos ofertar data de vencimento, juros, multa e desconto nos aplicativos?

**Comment by ninrod** [comment]
boa tarde @mariapessoacaldas , 

> Esses campos foram retirados da API Pix 2.0. Havíamos entendido que poderiam ser ofertados nos aplicativos, mas a padronização do GET​/{pixUrlAcessToken} nos trouxe dúvida.

Sim, a API Pix 2.0 temporariamente removeu esses campos, mas já na versão `2.1.0`, a ser publicada muito em breve, voltaremos com essas funcionalidades, estabelecendo uma semântica específica. 

> Podemos ofertar data de vencimento, juros, multa e desconto nos aplicativos?

Sim. Em relação à experiência do usuário, poucos elementos devem mudar.

**Comment by ninrod** [comment]
funcionalidade implementada na release `2.1.0`
