### ISSUE TITLE
[Dúvida] Utilização da API PIX

### ISSUE THREAD

**Issue by LucasManerich** [bacen/pix-api#51]
**Descreva sua dúvida ou problema**

Bom dia,
Trabalho em uma empresa que oferece softwares ERP para gestão pública municipal (pagamentos de IPTU, ISS, ITBI, contas de água, etc) e temos interesse em integrar com o PIX. Porém não estamos conseguindo entender muito bem o funcionamento da API e a forma que iremos receber o acesso a ela.

- Como que faço para conseguir acesso a API? 
- Para qual URL temos que fazer as chamadas para criar uma cobrança? 
- Tenho que entrar em contato com algum PSP para ter acesso a API? (na documentação a URL está sendo representada por https://{fdqnPSPRecebedor} ou https://pix.example.com)

**Sistema ou Área**
APi Pix, QR code

**Comment by rubenskuhl** [comment]
O acesso a API deve ser conseguido junto a um PSP. O BACEN apenas especifica e padroniza a API, não a provê diretamente a correntistas no sistema financeiro. 
A URL será diferente em cada PSP.

**Comment by LucasManerich** [comment]
Obrigado @rubenskuhl 
Vou entrar em contato com um PSP para prosseguir com os próximos passos.
