### ISSUE TITLE
QRTester não consegue ler QR Code

### ISSUE THREAD

**Issue by MagnoCICanto** [bacen/pix-api#512]
Os QR Codes dinâmicos gerados pela IF obtem erro de acesso negado no QR Tester. Já verifiquei o acesso por fora da rede (internet), o certificado SSL já foi enviado no STA e o site JWK apontado no header está acessivel também. 

Saberiam o que pode estar de errado com este QR Code?

00020101021226960014BR.GOV.BCB.PIX2574pix-h.realizecfi.io/pix-qrcode/pix/v2/cob/2a7705f1491d4e8986ef092df8a516bd52040000530398654040.015802BR5916HOMOLOGA REALIZE6012Porto Alegre62070503***6304E39B

![image](https://user-images.githubusercontent.com/108304665/176037003-8e362fb8-aa3c-496a-b507-9a522a1c1919.png)

**Comment by arantesxyz** [comment]
Olá, tudo bem?

Estou com o mesmo problema, consegue me informar o que fez para resolver?

**Comment by FelipeEmerimRandon** [comment]
No nosso caso, faltou fazer uma solicitação de liberação das nossas URLs de Payload e JWKS no Firewall do BACEN. Uma vez feito isso, não tivemos mais o erro de acesso negado.
