### ISSUE TITLE
[Dúvida] API Pix - Criar Cobrança - Campos "required"

### ISSUE THREAD

**Issue by leonarff** [bacen/pix-api#52]
Na criação da cobrança os campos devedor/cpf, devedor/cnpj, devedor/nome, infoAdicionais/nome e infoAdicionais/valor são colocados como "required".
Isto esta correto ?
Uma cobrança é OBRIGADA a conhecer nome, cpf ou cnpj do pagador ?
Como um ponto de venda qualquer teria esta informação ?
As informações adicionais (infoAdicionais) são obrigatórias ?
Se são campos quaisquer para informações adicionais faz sentido serem obrigatórias ?
O próprio "Exemplo1" não contém infoAdicionais.

**Comment by rubenskuhl** [comment]
Entendo que a cobrança precisa sim especificar quem está sendo cobrado. Para ponto de venda o QR-Code estático, não coberto pelo /cob mas coberto pelo /pix desde que tenha TxID faz mais sentido. 

infoAdicionais me parece opcional sim.

**Comment by leonarff** [comment]
Deixe-me entender melhor.
Com a utilização do QR Code estático não existe a necessidade de se criar a cobrança, apenas a necessidade de monitorar o pix recebido e portanto não utiliza o comando criar cobrança, que necessita dos dados do pagador.
Com isto o ponto de venda seria "obrigado" a utilizar QR Code estatíco correto ?
Com relação a infoAdicionais não vejo outro cenário que não seja opcional.

**Comment by rubenskuhl** [comment]
Sim, mas notar que o /webhook só sinaliza Pix com TxID. Então se o objetivo for ter uma confirmação assíncrona do pagamento, o QR-Code estático precisa ter TxID. Notar o que o estático do QR-Code estático não é tão estático assim devido a possibilidade de ter TxID.

**Comment by leonarff** [comment]
Sim concordo plenamente.
Na verdade não poderia ser um QR Code desses impressos como vemos, mas sim um QR Code gerado no momento do pagamento para que o txid também seja gerado pelo PDV.

**Comment by rubenskuhl** [comment]
Esse caso de uso parece sim apropriado para QR-Code estático com TxID. O único cuidado a se tomar aqui é ver se o valor recebido é o esperado para aquela transação.

**Comment by ninrod** [comment]
@leonarff, boa tarde. 

deve estar havendo alguma confusão. Esses campos que você citou não são obrigatórios.

**Comment by leonarff** [comment]
Boa tarde @ninrod,

Estava visualizando apenas o arquivo spec.html e nele os campos são "required".
O que pode estar acontecendo ?

![image](https://user-images.githubusercontent.com/48833530/95383278-4f796c00-08c1-11eb-9fab-0dc8bf0d3849.png)

**Comment by rubenskuhl** [comment]
Meu entendimento é que infoAdicionais, que não é required, se existir, aí tem nome e valor como required.

**Comment by christianf2029** [comment]
Esse é o meu entendimento: tanto o campo `devedor` como o campo `infoAdicionais` não são obrigatórios, porém, uma vez que se queira preencher esses campos, aí existem os seus campos `required`.

**Comment by ninrod** [comment]
@rubenskuhl: 

> Meu entendimento é que infoAdicionais, que não é required, se existir, aí tem nome e valor como required.

Perfeito. 

@christianf2029 : 

> Esse é o meu entendimento: tanto o campo devedor como o campo infoAdicionais não são obrigatórios, porém, uma vez que se queira preencher esses campos, aí existem os seus campos required.

Exato. 

@leonarff , as respostas acima estão corretas e resolvem a sua dúvida.
