### ISSUE TITLE
Remoção do 'pagador' como campo obrigatório do 'Pix' no seu respectivo schema na versão 2.6.3 da API

### ISSUE THREAD

**Issue by vivicupola** [bacen/pix-api#524]
Bom dia.

Não encontrei a alteração referenciada como:
"Remoção do 'pagador' como campo obrigatório do 'Pix' no seu respectivo schema."

Poderiam me ajudar a identicar qual ou quais os serviços afetados?

Obrigada :)

**Comment by thiagolvlsantos** [comment]
Bom dia @vivicupola ,

observe a mudança na linha 4454, houve apenas a remoção de um campo que era _renderizado_ como obrigatório mas não existia no objeto. A issue que o colega reportou este ponto é a #495.

Em tempo, de fato faltou a referência à issue para ajudar a entender o contexto. Pedimos desculpas pela ausência no changelog.

Atenciosamente,
Thiago Santos

Obs.: Caso sua dúvida tenha sido esclarecida, peço que feche a issue.

**Comment by vivicupola** [comment]
@thiagolvlsantos, muito obrigada pelo esclarecimento.
Abraços.
