### ISSUE TITLE
Formato do campo chave

### ISSUE THREAD

**Issue by HMPannuti** [bacen/pix-api#53]
Por favor, poderiam confirmar se o campo chave deve ser informado na API Pix do mesmo modo que é formatado no DICT?
Ou seja: 
- CNPJ e CPF: apenas números, sem separador
- telefone: no formato internacional (+55AANNNNNNNNN, AA = código de área; NNNNNNNNN = número do telefone celular)
- e-mail: fulano_da_silva.recebedor@example.com, case insensitive
- chave aleatória: no formato canônico de UUID, "8-4-4-4-12", case insensitive

**Comment by ninrod** [comment]
@HMPannuti , bom dia. 

> Por favor, poderiam confirmar se o campo chave deve ser informado na API Pix do mesmo modo que é formatado no DICT?

Sim. Essa informação não está clara na API e vamos consertar já para a versão `2.1.0`. 

Obrigado pelo reporte.
