### ISSUE TITLE
API Pix - QR Code Dinâmico - Casos de Uso

### ISSUE THREAD

**Issue by brunoparis01** [bacen/pix-api#54]
Boa Noite.

Continuando a discussão iniciada em https://github.com/bacen/pix-api/issues/35...

Em que cenários então o QR code dinâmico deve ser gerado por meio da API Pix? Seria o caso de comércios/e-commerce que não tem nenhuma relação com PIX e dependem de SW de automação comercial para habilitar o PIX como forma de pagamento? Quais casos de uso vamos gerar o QR Code dinâmico sem ser pela API Pix?

Se puderem fornecer alguns exemplos, agradeceria.

Bruno

**Comment by rubenskuhl** [comment]
Eu não consigo pensar em nenhum caso de uso de QR-Code dinâmico via app ou Internet Banking que não fosse adequamente resolvido com QR-Code estático,  no máximo QR-Code estático com TxID. Mas nada impede que seja feito também por QR-Code dinâmico, com a ressalva de que suporte a QR-Code dinâmico como recebedor não é requisito do arranjo, diferente de pagar QR-Code dinâmico que é mandatório.  


Já via API, e-commerce é o cenário mais propício para uso do QR-Code dinâmico, especialmente pela capacidade de controle de duplicidade de pagamento e de checagem de se o valor cobrado está sendo efetivamente pago.

**Comment by ninrod** [comment]
bom dia @brunoparis01 

> Em que cenários então o QR code dinâmico deve ser gerado por meio da API Pix?

Há uma gama diversa de cenários. Eu poderia listar vários cenários aqui, mas por coesão eu gostaria de trazer sua atenção para o Anexo I do "Manual de padrões de iniciação do Pix" (atualmente na versão 1.1), entitulado "API PIX: Conceitos de Negócio". 

> Quais casos de uso vamos gerar o QR Code dinâmico sem ser pela API Pix?

A única opção "sem ser pela API PIx", no meu entendimento, é a geração via app mobile. Como exemplo eu pensaria na seguinte linha: considerando que o QR Dinâmico, na versão `2.1.0` (a ser lançada em breve), fica mais poderoso, dotado de [reuso de location](https://github.com/bacen/pix-api/issues/19), você poderia imaginar um cenário de uso em um EC pequeno que resolve utilizar QR dinâmico impresso em papel cujas cobranças a serem exibidas sejam controladas via app mobile.

**Comment by brunoparis01** [comment]
Oi, obrigado a todos pela resposta. Tendo em vista essa descrição da API PIX: 
> A API Pix padroniza serviços oferecidos pelo PSP recebedor no contexto do arranjo Pix...

Eu entendo como sendo o PSP oferecendo serviços para SW de automação ou diretamente para e-commerce. \\

Vendo a lista de empresas que aderiram ao PIX no lançamento em Novembro, temos caso de instituições de pagamento que também possuem um e-commerce.  Nesse caso, caso PIX venha a ser uma forma de pagamento, ainda seria necessário ofertar PIX via PIX API, dado que é a "mesma empresa"?

**Comment by rubenskuhl** [comment]
> Oi, obrigado a todos pela resposta. Tendo em vista essa descrição da API PIX:
> 
> > A API Pix padroniza serviços oferecidos pelo PSP recebedor no contexto do arranjo Pix...
> 
> Eu entendo como sendo o PSP oferecendo serviços para SW de automação ou diretamente para e-commerce. \
> 
> Vendo a lista de empresas que aderiram ao PIX no lançamento em Novembro, temos caso de instituições de pagamento que também possuem um e-commerce. Nesse caso, caso PIX venha a ser uma forma de pagamento, ainda seria necessário ofertar PIX via PIX API, dado que é a "mesma empresa"?

Mesma empresa seria mesmo CNPJ, no máximo desconsiderando a parte da filial no CNPJ. Agora, se no mesmo grupo econômico caracteriza ou não oferta de serviços é um questionamento interessante.

**Comment by brunoparis01** [comment]
Oi Filipe.

Eu estava esperando ainda um direcionamento para minha dúvida abaixo que eu fiz.

> Oi, obrigado a todos pela resposta. Tendo em vista essa descrição da API PIX:
> 
> > A API Pix padroniza serviços oferecidos pelo PSP recebedor no contexto do arranjo Pix...
> 
> Eu entendo como sendo o PSP oferecendo serviços para SW de automação ou diretamente para e-commerce. \
> 
> Vendo a lista de empresas que aderiram ao PIX no lançamento em Novembro, temos caso de instituições de pagamento que também possuem um e-commerce. Nesse caso, caso PIX venha a ser uma forma de pagamento, ainda seria necessário ofertar PIX via PIX API, dado que é a "mesma empresa"?

**Comment by ninrod** [comment]
@brunoparis01 , bom dia. 

Se a "mesma empresa" oferece, direta ou indiretamente (via um gateway, por exemplo, pertencente ao mesmo grupo econômico), integração via software incluindo acesso a informações Pix, esta empresa deve oferecer a API Pix. Esse é o intuito, o princípio, a ideia da API Pix: que o usuário recebedor, o resource owner, tenha assegurada uma maneira padronizada de trabalhar com o arranjo Pix por meio de sua conta, se o PSP quiser entrar neste mercado (de "oferecer integração automatizada", o PSP não é obrigado a entrar neste mercado).
