### ISSUE TITLE
Problema ao acessar url do QrCode dinâmico Sandbox bacen

### ISSUE THREAD

**Issue by Cleuber** [bacen/pix-api#547]
Criamos alguns QrCodes no sandbox do bacen, porém ao consultar endpoint para visualizar o payload (JWS) está dando erro 503. 
Consegui acessar só 1x e todas outras 9999 tentativas retornaram 503 ou timeout

Endpoint: qr-h.sandbox.pix.bcb.gov.br/rest/api/802f93eebd6b46c2a4c53fdf6a2aa443

QrCode: 00020126910014br.gov.bcb.pix2569qr-h.sandbox.pix.bcb.gov.br/rest/api/802f93eebd6b46c2a4c53fdf6a2aa4435204000053039865802BR5903Pix6008BRASILIA62070503***630419F7

![image](https://user-images.githubusercontent.com/16212436/223709980-85527c54-b0e3-4add-8352-1f101457bf83.png)

**Comment by kennedimalheiros** [comment]
Bom dia, testa novamente, eu fiz o teste aqui e da segunda vez deu certo, pode ser uma intermitência, [https://qr-h.sandbox.pix.bcb.gov.br/rest/api/802f93eebd6b46c2a4c53fdf6a2aa443](url)


`eyJ4NXQjUzI1NiI6IkVBZ0VCSzFSNHNtTnF4WFFhUE9zaHBiSTBQT1UyWlN4Nks1Q3RLRFpub28iLCJqa3UiOiJodHRwczpcL1wvcXItaC5zYW5kYm94LnBpeC5iY2IuZ292LmJyXC9yZXN0XC9qd2tzLmpzb24iLCJraWQiOiJOMjNOSVg5R3Z3bm4ycGktV09IOG9RQ2JkSGlaSFdpbnJvWllxZGhxMlYwUENJIiwiYWxnIjoiUlMyNTYifQ.eyJjYWxlbmRhcmlvIjp7ImNyaWFjYW8iOiIyMDIyLTA5LTI5VDIwOjEwOjQ1LjQwOFoiLCJhcHJlc2VudGFjYW8iOiIyMDIzLTAzLTA4VDEzOjAzOjU2LjYwMVoiLCJleHBpcmFjYW8iOjg2NDAwfSwiY2hhdmUiOiI0MDA0OTAxZC1iZDg1LTQ3NjktOGU1Mi1jYjRjNDJjNTA2ZGMiLCJzdGF0dXMiOiJBVElWQSIsInZhbG9yIjp7Im9yaWdpbmFsIjoiMC4wMCIsInJldGlyYWRhIjp7InNhcXVlIjp7InZhbG9yIjoiODkzLjI3IiwibW9kYWxpZGFkZUFnZW50ZSI6IkFHUFNTIiwicHJlc3RhZG9yRG9TZXJ2aWNvRGVTYXF1ZSI6Ijk5OTk5MDA4In19fSwiaW5mb0FkaWNpb25haXMiOlt7Im5vbWUiOiJFbnRyZWdhIiwidmFsb3IiOiJSZXNpZGVuY2lhbCJ9XSwiZGV2ZWRvciI6eyJub21lIjoiRnVsYW5vIGRlIFRhbCIsImNwZiI6IjE4NTgxMDEyNzEwIn0sInR4aWQiOiI4MDJmOTNlZWJkNmI0NmMyYTRjNTNmZGY2YTJhYTQ0MyIsInJldmlzYW8iOjB9.usyLtNTqxZX6VgDxuoGe3xRkRgpTN3Pmwby98iLdALMnswbzMmOSPTr4MNBTWm85WhbgkflgU_sDlpeoUUHM_2F0WfEGJ6152LEBvFfNztx6zliZjRVUhrgswIOsdELjbVaOC8gr2cUSTShddOu_B4i90gJnUJjt4U_3jLQY02kVmitAaCoLkYq1zMO1dWVXKgiPzWcTTvqBlfayusvZpYAYNGki0bke7Ti8U21s-jkvUcf2bnK6X2XArCTcC0tPIUkF4sTvo_R98f2_oV3i9TwMXbjyG_1dll4P-HhDz1_Gvyto7XwvGh_0CGIPsnHPskBjUsK5qi9J7ioc9B6Erg`

**Comment by Cleuber** [comment]
Boa noite, @kennedimalheiros 
Aqui agora está indo também, aparentemente era uma instabilidade mesmo.

Obrigado
