### ISSUE TITLE
LGPD - Pagador anônimo

### ISSUE THREAD

**Issue by flaviolenz** [bacen/pix-api#55]
Fizeram uma análise de aderência à Lei Geral de Proteção de Dados, que entrou recentemente em vigor?

Não sei se isso foi coberto, mas tem uma questão de privacidade aderente ao principio da necessidade da LGPD:
**O usuário pode querer não se identificar para o Lojista.**

Nesse caso, o PSP recebedor nem deveria receber o CPF do pagador - essa informacao ficaria restrita ao PSP pagador. 
Seria como se eu pagasse em dinheiro (nao tem porque o lojista saber quem sou, se eu nao quiser dizer). 
E, de fato, essa nao eh uma informacao relevante para ele receber os devidos fundos em sua conta.
E o PSP recebedor tambem nao precisa de nada alem do "endToEndId" pra efetuar o deposito ou processar alguma devolucao.

Em que circunstância a especificacao prevê a property "pagador" nao preenchida no objeto Pix?

_Por sinal, as informacoes trocadas pelos sistemas das adquirentes, hoje violam esse princípio e elas podem ter problemas com isso no futuro._

**Comment by rubenskuhl** [comment]
Art. 26 da LGPD:

V - na hipótese de a transferência dos dados objetivar exclusivamente a prevenção de fraudes e irregularidades, ou proteger e resguardar a segurança e a integridade do titular dos dados, desde que vedado o tratamento para outras finalidades.    

----

Me parece que tanto no Pix quanto em outros arranjos a transferência das informações incluindo o CPF tem base legal. Porém, a ANPD quando existir pode interpretar diferente... se ela já existisse, o BACEN poderia ter submetido a ela um código de conduta do arranjo Pix, e isso poderia ter sido pacificado. 

Na falta porém de uma autoridade administrativa, vamos ter que esperar processos judiciais correrem em instâncias superiores para pacificar um entendimento... quer à favor de como está o Pix agora, quer contra demandando alterações.

**Comment by flaviolenz** [comment]
Acho bem fácil interpretar que nao cabe nesse caso (forcando muito, o PSP-Recebedor poderia trabalhar algo anti-fraude, mas nunca o lojista)

Pessoalmente, como pagador, gostaria de ter minha privacidade preservada.

Eu já faria desde o inicio sob o conceito _privacy by design_

**Comment by rubenskuhl** [comment]
Se fosse fácil interpretar já não haveriam 2 opiniões discordantes neste issue... a solução para isto é provocar a ANPD quando ela estiver estabelecida.

**Comment by M4N0V3Y** [comment]
Senhores: desde que o pagamento anônimo seja visível para o PSP-pagador então isso vai implicar na possibilidade de rastreabilidade das transações financeiras e manter o controle necessário para manter os mecanismos anti fraude. Se houver um grau de isolamento entre PSP recebedor e PSP pagador então eu não estou entendendo o problema de se omitir o CPF no envio das informações ao PSP recebedor.

**Comment by flaviolenz** [comment]
Em termos de proteção do cidadão,  eu não vejo MOTIVO pra repassar o CPF, se este não explicitar que o depósito deve ser identificado (vai haver esse caso, de qualquer maneira)

Seria melhor a procuradoria do BC se manifestar, mas com uma Lei tão recente, ainda sem jurisprudência, será difícil se posicionar.


> Senhores: desde que o pagamento anônimo seja visível para o PSP-pagador então isso vai implicar na possibilidade de rastreabilidade das transações financeiras e manter o controle necessário para manter os mecanismos anti fraude. Se houver um grau de isolamento entre PSP recebedor e PSP pagador então eu não estou entendendo o problema de se omitir o CPF no envio das informações ao PSP recebedor.

**Comment by ninrod** [comment]
Prezados, compartilho da preocupação, a LGPD é um tema interessante e novo. 

Levarei a questão para o time e tento voltar com uma posição oficial.

**Comment by ninrod** [comment]
Prezados, esse realmente não é o fórum adequado para tratar de temas especificamente jurídicos, mas agradecemos pela contribuição. O github institucional do BCB apresenta um objetivo estritamente técnico/tecnológico. Eu recomendaria utilizar a caixa corporativa do Pix para tratar de temas negociais ou jurídicos.
