### ISSUE TITLE
Como seria possivel solicitar para que o banco santander melhore seus comprovantes de PIX?

### ISSUE THREAD

**Issue by daniloab** [bacen/pix-api#552]
Pessoal, hoje o comprovante de PIX do santander não possui nenhuma informação do PIX.

Não existe a possibilidade sequer de confirmar o e2eid da transacao, da onde veio, quem mandou, nada.

Como poderia ser feito a solicitação para que eles melhorassem essa questão?

<img src="https://user-images.githubusercontent.com/19939822/235215847-4f76c008-c34d-497b-9434-e62fda147b14.png" width="200" height="400" />

**Comment by Jvpasquini** [comment]
Ola @daniloab! Você pode consultar os comprovantes com todos os detalhes no menu, no canto superior direito da home. Basta escolher transações > comprovantes e depois a opção Pix. 

Outra forma é consultar no menu Pix, a opção extrato Pix, ali você poderá ver todos os lançamentos e ter maiores informações, de acordo com os padrões de experiência definidos pelo Bacen.

**Comment by daniloab** [comment]
> Ola @daniloab! Você pode consultar os comprovantes com todos os detalhes no menu, no canto superior direito da home. Basta escolher transações > comprovantes e depois a opção Pix.
> 
> Outra forma é consultar no menu Pix, a opção extrato Pix, ali você poderá ver todos os lançamentos e ter maiores informações, de acordo com os padrões de experiência definidos pelo Bacen.

Ola, @Jvpasquini 

Sim! Consegui identificar pelo extrato do Pix. A dificuldade é que estavamos olhando para o extrato geral da conta corrente e o mesmo apresenta o comprovante acima.
