### ISSUE TITLE
[Dúvida] Divergência do EndToEndId nas definições das mensagens e API Pix

### ISSUE THREAD

**Issue by isabellekoga** [bacen/pix-api#56]
Nas Definições detalhadas das mensagens do Catálogo de Mensagens do SPI (19/08/2020) o parâmetro EndToEndId está definido como 32 caracteres alfanuméricos, com o primeiro caractere fixo "E". Já na API Pix 2.0.0, o EndToEndId está com um pattern [A-Z0-9-]{1,35}. Qual seria o padrão correto a se considerar?

**Comment by rubenskuhl** [comment]
Me parece uma aplicação do princípio de Postel ("be conservative in what you send, be liberal in what you accept"). A API Pix prepara os consumidores da API para E2EID que precise de crescimento no futuro, e o catálogo de mensagens especifica o padrão atual.

**Comment by ninrod** [comment]
bom dia @isabellekoga 

> Nas Definições detalhadas das mensagens do Catálogo de Mensagens do SPI (19/08/2020) o parâmetro EndToEndId está definido como 32 caracteres alfanuméricos, com o primeiro caractere fixo "E". Já na API Pix 2.0.0, o EndToEndId está com um pattern [A-Z0-9-]{1,35}. Qual seria o padrão correto a se considerar?

obrigado pelo reporte. Trata-se provavlemente de um bug API Pix na versão `2.0.0` e será consertado na versão `2.1.0`. Pode considerar como correto o padrão do catálogo de mensagens.

**Comment by ninrod** [comment]
@isabellekoga, verificamos essa questão com mais atenção e vamos deixar como está. A regex que abrigaria o formato específico definido pelo end2end na pacs.008 estaria dotada de uma complexidade [razoável](https://stackoverflow.com/a/29309567) e acredito que nesse caso, o [princípio de Robustez](https://en.wikipedia.org/wiki/Robustness_principle) se aplica (@rubenskuhl).
