### ISSUE TITLE
[Dúvida] Tempo de expiração mínimo

### ISSUE THREAD

**Issue by edumaciel10** [bacen/pix-api#561]
Dentro da especifição tem-se que o default do campo expiração é 86400, e que deve ser maior ou igual a zero.
Há mais alguma restrição, valor mínimo?
![image](https://github.com/bacen/pix-api/assets/54045014/7a15147a-9807-4e8f-aa9c-4bf523bb1c9d)

**Comment by rubenskuhl** [comment]
Eu acho bastante exótico uma duração menor que o SLA do Pix que é conclusão em 40 segundos.

**Comment by edumaciel10** [comment]
> Eu acho bastante exótico ter uma duração menor que o SLA do Pix que é conclusão em 40 segundos.

Pois é, mas é possível criar um pix com expiração de 180 segundos, certo?
