### ISSUE TITLE
Criar um QRCODE(Ou Pix copia e Cola) e Verificar se foi pago.

### ISSUE THREAD

**Issue by victormarconi** [bacen/pix-api#574]
Boa tarde, dei uma estudada na API Pix do Bacen e vi outras de uns bancos, queria usar a API para criar um QRCODE(Ou pix copia e cola) com um valor especifico e depois verificar se foi pago. Porém olhei bastante a API e teve uns pontos que não entendi, tem algum material de apoio em relação a isso?

**Comment by rubenskuhl** [comment]
> Boa tarde, dei uma estudada na API Pix do Bacen e vi outras de uns bancos, queria usar a API para criar um QRCODE(Ou pix copia e cola) com um valor especifico e depois verificar se foi pago. Porém olhei bastante a API e teve uns pontos que não entendi, tem algum material de apoio em relação a isso?

Alguns bancos tem uma documentação com mais conteúdo, você pode olhar por exemplo esta:
https://dev.efipay.com.br/docs/api-pix/credenciais/

**Comment by victormarconi** [comment]
Vou dar uma olhada, por que estou tentando entender a API para fazer um sistema sem conter API's de terceiros(contem custos). Vou dar uma olhada nisso, obrigado.

**Comment by rubenskuhl** [comment]
> Vou dar uma olhada, por que estou tentando entender a API para fazer um sistema sem conter API's de terceiros(contem custos). Vou dar uma olhada nisso, obrigado.

Não tem como, o Banco Central não é um banco de varejo. Ele apenas definiu o padrão da API Pix para os participantes Pix oferecerem e isso permitir portabilidade entre os participantes.

**Comment by victormarconi** [comment]
Entendi, pensei q o BACEN tinha uma API especifica e não fosse apenas um padrão, então devo procurar um banco especifico para ver a documentação e criar. No caso quando falo sem terceiros, não digo os bancos e sim outras empresas de fora. Meu objetivo é apenas criar o QRCODE dinâmico e ver se o usuário pagou aquele QRCODE.

**Comment by rubenskuhl** [comment]
> Entendi, pensei q o BACEN tinha uma API especifica e não fosse apenas um padrão, então devo procurar um banco especifico para ver a documentação e criar. No caso quando falo sem terceiros, não digo os bancos e sim outras empresas de fora. Meu objetivo é apenas criar o QRCODE dinâmico e ver se o usuário pagou aquele QRCODE.

Eu mantenho uma lista no issue #76 que pode ser útil...

**Comment by ofmarconi** [comment]
@victormarconi Eai chará de sobrenome, conseguiu como fazer isso? To querendo a mesma coisa, similar a esse site: https://www.gerarpix.com.br/

**Comment by rubenskuhl** [comment]
> @victormarconi Eai chará de sobrenome, conseguiu como fazer isso? To querendo a mesma coisa, similar a esse site: https://www.gerarpix.com.br/

O que esse site faz é apenas a parte de geração do QR-Code, ele não oferece (e não tem como oferecer) checagem de se foi pago.

**Comment by ofmarconi** [comment]
@rubenskuhl verdade, esqueci desse detalhe que ele pediu.

Vi que no #76 tem as integrações mais completa.

Mas se eu quiser usar um gerador de PIX estático e verificar via API do meu banco como por exemplo Nubank, isso é possivel certo?

Aí a taxa seria zero ou aproximada a zero.

**Comment by rubenskuhl** [comment]
> @rubenskuhl verdade, esqueci desse detalhe que ele pediu.
> 
> Vi que no #76 tem as integrações mais completa.
> 
> Mas se eu quiser usar um gerador de PIX estático e verificar via API do meu banco como por exemplo Nubank, isso é possivel certo?
> 
> Aí a taxa seria zero ou aproximada a zero.

Mesmo para verificar o pagamento de um PIX estático a API é a mesma e incidem sim taxas.

**Comment by victormarconi** [comment]
@ofmarconi Os bancos não abrem mãos das taxas, então meio que isso serve apenas para uso no seu sistema ou se você pagar taxas a terceiros. E sim consegui dar certo, gero o QRCODE e verifico se foi pago ou não. Fiz com a API do Itaú.

**Comment by ofmarconi** [comment]
@rubenskuhl @victormarconi Ahhh sim, tem razão....

Não que eu seja contra pagar pelo trabalho de outros hehehe, só queria ter certeza que não exista alternativas.

Na minha cabeça (ainda não pesquisei sobre isso) o Nubank deixa eu consultar meu extrato por API, se fosse gratuito isso era só consultar se no extrato tem algum pagamento com aquele identificador, aí não usaria a API do PIX, mas sim da conta... sabe?

**Comment by rubenskuhl** [comment]
> @rubenskuhl @victormarconi Ahhh sim, tem razão....
> 
> Não que eu seja contra pagar pelo trabalho de outros hehehe, só queria ter certeza que não exista alternativas.
> 
> Na minha cabeça (ainda não pesquisei sobre isso) o Nubank deixa eu consultar meu extrato por API, se fosse gratuito isso era só consultar se no extrato tem algum pagamento com aquele identificador, aí não usaria a API do PIX, mas sim da conta... sabe?

Outra "poor man's API" seria usar o alerta por e-mail ou SMS de que o Pix foi recebido... acho que extrato por API no Nubank só via OpenFinance, e aí você precisaria de licença para operar dentro do OpenFinance.

**Comment by ofmarconi** [comment]
### poor man's API

Adorei isso! Resume bem! O e-mail poderia ser interceptado pelo CloudFlare e um worker trabalhar com essa info hahaha

Mas valeu o exercício acho que temos um caminho rs
