### ISSUE TITLE
Mudar chave PIX para CNPJ diferente do titular das credenciais do PSP

### ISSUE THREAD

**Issue by victormarconi** [bacen/pix-api#576]
Já fiz uns sistemas automaticos de cobrança e recebimento PIX.  E no PSP(Itaú), você só pode usar a chave PIX da conta titular de acordo com as credenciais do mesmo. Tem algum banco que mude isso?

**Comment by rubenskuhl** [comment]
> Já fiz uns sistemas automaticos de cobrança e recebimento PIX. E no PSP(Itaú), você só pode usar a chave PIX da conta titular de acordo com as credenciais do mesmo. Tem algum banco que mude isso?

Me parece que isso seja requisito do manual de iniciação, e que quem permitir isso estará em violação...

**Comment by victormarconi** [comment]
Entendo, obrigado!
