### ISSUE TITLE
QRCode/PixCopiaECola Expirado

### ISSUE THREAD

**Issue by victormarconi** [bacen/pix-api#577]
Eu crio uns QRCodes com prazo de 5 minutos, após expirarem não consigo pagar, mas a condição deles continuam "ATIVA", mesmo ele estando expirado, isso prejudica de alguma forma?

**Comment by rubenskuhl** [comment]
> Eu crio uns QRCodes com prazo de 5 minutos, após expirarem não consigo pagar, mas a condição deles continuam "ATIVA", mesmo ele estando expirado, isso prejudica de alguma forma?

Não prejudica nada, inclusive pq estando ATIVA, ela permite que você use o método PATCH e mude a expiração. Se o status fosse CONCLUIDA ou REMOVIDA_PELO_USUARIO_RECEBEDOR, você não conseguiria mais mudar a expiração.

**Comment by victormarconi** [comment]
Entendo, perfeito então. Fiz vários testes e ficam várias "ATIVA" e realmente consigo mudar o tempo de expiração. Vou fechar o tópico, obrigado!
