### ISSUE TITLE
Dúvida geração de QR code dinâmico exclusivamente via API Pix

### ISSUE THREAD

**Issue by monise** [bacen/pix-api#58]
Olá! Enviei alguns questionamentos por e-mail, mas talvez o canal mais adequado para algumas questões sejam aqui.

1- Sobre a definição no Manual de Padrões para Iniciação do Pix, v1.1, os trechos abaixo (págs. 11, 13 e 21) destacados falam sobre o QR Code dinâmico ser exclusivamente gerado pela API Pix:

![image](https://user-images.githubusercontent.com/5355541/95483149-45a94480-0965-11eb-8081-12f421b644f3.png)

**Dúvida**: o manual cita que a API Pix surgiu para padronizar o cenário de automação. Entretanto nas definições acima, sobre a iniciação do QR Code dinâmico, diz que o uso dela é obrigatório para todos os cenários e não apenas os cenários de automação. Observando que o próprio informe 048/2020 explica que a API Pix será evoluída para tratar outros cenários como a de cobranças com juros, multa e atraso e também pensando em casos de uso de geração de QR Code Dinâmico através do próprio aplicativo do PSP, _é permitido a geração de QR Code dinâmico sem API Pix para demais casos ainda não cobertos pela API?_

**Comment by ninrod** [comment]
Boa tarde @monise, 

>  diz que o uso dela é obrigatório para todos os cenários e não apenas os cenários de automação.

Esta redação coloca um contorna restritivo na situação, vamos alterar: 

* O QR Code dinâmico deve ser gerado via API Pix, __exceto no caso de geração via aplicativo mobile do PSP recebedor__. 
* O QR Dinâmico não pode ser criado diretamente __pelo usuário recebedor__ (ou é criado via app, ou via API).
