### ISSUE TITLE
Participante direto - comunicação ao gerar QrCode dinâmico 

### ISSUE THREAD

**Issue by arihSiqueira** [bacen/pix-api#581]
Galera, 

Entendi que pra gerar QrCode dinâmico preciso seguir o seguinte fluxo 

1 -  Criar uma cobrança "PUT /cob/{txid}"
2 - Com a informação da cobrança posso gerar um QRCode usando o padrão EMV QRCPS que será lido pelo cliente pra pagar 

Minha duvida é quem são os atores envolvidos, sendo direto no arranjo. 
A comunicação deve acontecer entre Recebedor (/cob) >  Participante Direto(/cob) > Banco central (SPI) ? Ou apenas entre Recebedor(/cob) > Participante Direto (sem comunicar com Banco central)? 

Em que momento a cobrança passa a ser reconhecida pelo SPI? Somente no momento em que o cash-in é iniciado (PACS.008)?

**Comment by rubenskuhl** [comment]
> Galera,
> 
> Entendi que pra gerar QrCode dinâmico preciso seguir o seguinte fluxo
> 
> 1 - Criar uma cobrança "PUT /cob/{txid}" 2 - Com a informação da cobrança posso gerar um QRCode usando o padrão EMV QRCPS que será lido pelo cliente pra pagar
> 
> Minha duvida é quem são os atores envolvidos, sendo direto no arranjo. A comunicação deve acontecer entre Recebedor (/cob) > Participante Direto(/cob) > Banco central (SPI) ? Ou apenas entre Recebedor(/cob) > Participante Direto (sem comunicar com Banco central)?
> 
> Em que momento a cobrança passa a ser reconhecida pelo SPI? Somente no momento em que o cash-in é iniciado (PACS.008)?

Como você mencionou no final, somente no momento que o cash-in é iniciado que o SPI é envolvido. E isso independe de se o PSP do recebedor e do pagador são diretos ou indiretos, inclusive pq um PSP indireto não precisa do seu direto para obter o payload da cobrança, que está acessível na Internet e não na RSFN.

**Comment by arihSiqueira** [comment]
Obg @rubenskuhl

**Comment by arihSiqueira** [comment]
@rubenskuhl reabrindo aqui, pq conversando com mais gente, fiquei na duvida de novo. 

O que significa essa parte? 
> inclusive pq um PSP indireto não precisa do seu direto para obter o payload da cobrança


Minha duvida ainda é relacionada a essa parte da documentação:
```
Serviço invocado: PUT /cob/{txid} → Devem ser informados todos os dados necessários
para criação do payload da cobrança, conforme especificação detalhada.
Alternativamente, se o usuário recebedor não quiser identificar a cobrança imediata
com seu próprio número {txid}, pode-se optar por utilizar o método POST /cob77

```

Fonte: https://www.bcb.gov.br/content/config/Documents/BR_Code_MANUAL_Version_2_May_2020.pdf


Sobre a chamada para o recurso  POST /cob/ 
 - Essa chamada é feita para o Bacen para ficar registrado a existência da cobrança ? E ai com a resposta, o QRCode (pix copia e cola) pode ser gerado ?

**Comment by rubenskuhl** [comment]
O payload trafega fora da RSFN e diretamente entre os PSPs, por isso que o indireto não precisa do direto para obter o payload. 

Nenhuma chamada da API Pix causa transação no Banco Central. Cobranças não são registradas no Banco Central, elas são geradas nos PSPs, e os outros PSPs acessam. Só a liquidação da cobrança passa (potencialmente) pelo Banco Central.
