### ISSUE TITLE
Api Pix Exclusiva Itaú - Webhooks

### ISSUE THREAD

**Issue by RaphaelSousaSilva** [bacen/pix-api#589]
Olá, estou estudando o uso da [api exclusiva do Itaú](https://devportal.itau.com.br/nossas-apis/itau-ep9-gtw-pix-recebimentos-conciliacoes-v2-ext) ao invés da [api regulatória](https://devportal.itau.com.br/nossas-apis/itau-ep9-gtw-pix-recebimentos-ext-v2) disponibilizada por eles , porém nesta api eles não fornecem o cadastro de webhook para atualização de status de pagamento. 

Alguém sabe me dizer quando a cobrança for cadastrada pelo [endpoint da api exclusiva](https://devportal.itau.com.br/nossas-apis/itau-ep9-gtw-pix-recebimentos-ext-v2#tag/QR-Code-imediato-(COB)) e o cadastro do webhook pela api regulatória, se eles notificarão neste webhook?

**Comment by cairogreco** [comment]
Olá, estou no mesmo processo de implantação da API EXCLUSIVA e sua dúvida é muito interessante, já tem alguma luz sobre?

**Comment by cairogreco** [comment]
Bom ponto!
Estou integrando uma empresa que é cliente Itaú e precisa automatizar o processo de cobrança via PIX... Nesse caso eu também tenho que trabalhar com as APIs regulatórias, correto?

**Comment by RaphaelSousaSilva** [comment]
> Bom ponto!
> 
> Estou integrando uma empresa que é cliente Itaú e precisa automatizar o processo de cobrança via PIX... Nesse caso eu também tenho que trabalhar com as APIs regulatórias, correto?

Exato, para Clientes o uso para automatização de cobrança (um ecommerce por ex) é da api regulatória, mas você pode utilizar a api exclusiva para fazer conciliação se achar necessário, já que oferecem alguns filtros e funcionalidades a mais. 

Participantes indiretos são aqueles que oferecem o pix como produto, por exemplo oferecendo um ambiente próprio para o gerenciamento de chaves.

**Comment by cairogreco** [comment]
Obrigado pelos esclarecimentos meu querido, me elucidou diversas dúvidas. Grande abraço e sucesso no seu projeto!

**Comment by micaelsroque** [comment]
ESTOU FAZENDO UMA INTEGRACAO COMO PARCEIRO, COM O PIX ITAU -- SIMPLESMENTE, NÃO CONSIGORECEBER O CONSENTIMENTO DO BANCO. NÃO FICA CLARO SE A AUTENTICACAO É mTLS ou OAuth -- como parceiro, qual tipo? Estou usando clouflare, vcs tbm usam?
