### ISSUE TITLE
[Dúvida] Solicitar devolução

### ISSUE THREAD

**Issue by christianf2029** [bacen/pix-api#59]
Prezados, eu estou com uma dúvida sobre **qual entidade uma devolução pertence**. Na documentação, temos a seguinte afirmação:

![image](https://user-images.githubusercontent.com/16386736/95576228-755c5900-0a06-11eb-984e-56ca9dedb7e1.png)

Já na hora de detalhar o campo `valor`, no _request body_ desse endpoint, temos a seguinte afirmação:

![image](https://user-images.githubusercontent.com/16386736/95576420-cb310100-0a06-11eb-8532-5aaeba89b692.png)

Porém, uma cobrança pode ter vários pix associados à ela e no meu entendimento eu não posso devolver um valor acima de um pix recebido. Por exemplo:

- Cobrança no valor de R$ 100,00;
- Pix 1 recebido no valor de R$ 50,00 (isso porque não há bloqueio no valor);
- Pix 2 recebido associado à cobrança no valor de R$ 200,00 (isso porque não há bloqueio no valor);

Imagine que preciso devolver R$ 150.00, não posso devolver no Pix 1 porque ele não tem o valor suficiente, devo então devolver no Pix 2 porém é um valor acima do valor da cobrança.

Não sei se meu exemplo ficou muito bem claro, mas o que eu quero dizer é que tenho a impressão de que em devoluções eu devo me preocupar com os Pixs recebidos e não com a cobrança em si.

**Comment by ninrod** [comment]
@christianf2029 , bom dia. 

> Pix 2 recebido associado à cobrança no valor de R$ 200,00 (isso porque não há bloqueio no valor);

Eu questionaria a sua premissa de que "não há bloqueio no valor". O PSP do recebedor, no contexto de iniciação de pagamentos, pode implementar uma lógica sofisticada para recusar, por exemplo, pagamentos duplicados, pagamento que não bate com o valor, pagamento após o vencimento (quando o vencimento for implementado, na API, em breve), etc...

>  uma cobrança pode ter vários pix associados à ela

Pode, está modelado, mas o único cenário em que isso aconteceria é um cenário de erro e seria um erro nas duas pontas: na pagadora e na recebedora. Uma cobrança normalmente estará associada a um e apenas um Pix. 


> Por exemplo:
Cobrança no valor de R$ 100,00;
Pix 1 recebido no valor de R$ 50,00 (isso porque não há bloqueio no valor);
Pix 2 recebido associado à cobrança no valor de R$ 200,00 (isso porque não há bloqueio no valor);
Imagine que preciso devolver R$ 150.00, não posso devolver no Pix 1 porque ele não tem o valor suficiente, devo então devolver no Pix 2 porém é um valor acima do valor da cobrança.


>  devo então devolver no Pix 2 porém é um valor acima do valor da cobrança.

Obrigado, você acabou de encontrar um erro na redação. O total das devoluções não pode ultrapassar o valor do __Pix__, e não da cobrança. Vamos consertar para a release `2.1.0`.

**Comment by christianf2029** [comment]
Bacana você ter falado sobre isso daqui, que está a cargo do PSP Recebedor:

> Eu questionaria a sua premissa de que "não há bloqueio no valor". O PSP do recebedor, no contexto de iniciação de pagamentos, pode implementar uma lógica sofisticada para recusar, por exemplo, pagamentos duplicados, pagamento que não bate com o valor, pagamento após o vencimento (quando o vencimento for implementado, na API, em breve), etc...

Obrigado @ninrod .
