### ISSUE TITLE
Onde posso debater sobre alternativas de bitcoin, pix?

### ISSUE THREAD

**Issue by ghost** [bacen/pix-api#594]

**Comment by rubenskuhl** [comment]
> Oi Bacen,
> 
> Onde posso debater sobre alternativas de bitcoin, pix? Existe algum fórum onde podemos saber onde e quais propostas estão sendo regulamentadas? Onde posso estudar sobre as propostas de economia e tecnologias relacionadas?
> 
> como ajudo aqui?

Me parece que discutir alternativas crypto-oriented seria em outros fóruns... por exemplo o Discord da ChainLink:
https://discord.gg/chainlink

Este repositório é especificamente da API Pix padrão.
