### ISSUE TITLE
[Dúvida] na [API Pix] -  Endpoint Criar Cobrança – txId informado pelo cliente na requisição

### ISSUE THREAD

**Issue by leosn** [bacen/pix-api#6]
/cob/{txid}  Criar Cobrança

Entendemos que o campo TxId fica a cargo do PSP do recebedor. Então esse campo não deveria ser passado pelo cliente na API do PSP, certo?

_II_ManualdePadroesparaIniciacaodoPix-versao1.pdf
 “1.6.11.O campo 6: txid
....
Quanto ao seu conteúdo, a maneira específica que será empregada pelo PSP do recebedor para implementar a funcionalidade de conciliação de pagamentos por meio da utilização do txid transcende o escopo deste Manual. De outra maneira, estando habilitado o recebedor a conciliar pagamentos conforme especificados no âmbito do Pix, o preenchimento do txid fica a cargo do PSP do recebedor._ “

Salientamos que esse campo é o único elo entre o Pix (pagamento) e a cobrança (qr-code). Entendemos que é uma chave forte e deveria ser gerada pelo PSP.

**Comment by rubenskuhl** [comment]
A criação de um identificador único pelo estabelecimento recebedor é necessária para garantir idempotência e evitar cobranças duplicadas. Se esse identificador único vai ou não no QR-Code ou fica só no PSP Recebedor é uma decisão a ser tomada, mas algum unique ID do recebedor é necessário. 
E normalmente já há identificadores simples para usar nisso como número de pedido, fatura, nota fiscal etc.

**Comment by leosn** [comment]
Prezado Rubens, será que não ficaria mais simples e uma idempotência maior se o PSP do Recebedor gerar o ID e o estabelecimento vincular a cobrança a um pedido/venda, já que ele deve utilizar a API para gerar uma alteração(revisão)?

Segundo o manual os campos id e revisão deverão ser a chave para identificar uma única cobrança(qr-code) no PSP do recebedor e entendemos o exemplo dado pelo BACEN, mas acreditamos que ficou um pouco confuso devido a não termos esses dados no payload do qr-code e nem na informação do Pix(pagamento) na pac008. 

Exemplos de problemas:
- Na leitura do qr-code no pagamento, devemos mostrar qual cobrança(qr-code) se o cliente possuir várias revisões sem Pix(pagamento)? Seria a mais atual? Lembrando que no payload do qr-code não temos essa informação
- Devemos validar os valores de uma pac008 com sempre com a mais atual? Se apresentamos ao pagador uma cobrança e ele pagou, mas por questões de segurança ela ficou sendo analisada por pela área de segurança do PSP do pagador e nesse meio tempo o cliente criou mais uma versão para aquela mesma cobrança (qr-code) e só depois chegou a pac008. Devemos negar ao pagador?

Uma sugestão para manter a idempotência seria o campo txId (gerado pelo PSP do recebedor) ser a chave única da cobrança (qr-code) e toda vez que o estabelecimento vier ao PSP através da API ganha esse número e relaciona com o seu identificador do seu pedido/venda. Assim pensamos que ficaria mais simples, tanto para os intervenientes quanto para os sistemas. Principalmente porque esse campo estaria na cobrança, no pagamento e relacionado no estabelecimento.

**Comment by rubenskuhl** [comment]
Se é o PSP que gera, pode ser duplicado. A idempotência não está assegurada. 

Minha visão sobre os problemas:
- O QR-Code é mostrado pelo estabelecimento, o PSP só disponibiliza o payload. Mas o payload seria da revisão mais atual. 
- No caso de Pix selecionado para análise de fraude no PSP Pagador, ele só chega depois que essa análise foi feita. Mas genericamente esse problema sempre pode acontecer e sim eu entendo que o PSP Recebedor deva recusar pagamentos com divergência da revisão atual.

**Comment by leosn** [comment]
Prezado Rubens,

Se o PSP do Recebedor gerar, garantimos com certeza que esse ID nunca será duplicado, semelhante ao 2endId

**Comment by leosn** [comment]
Bastando o BACEN regulamentar.

**Comment by ninrod** [comment]
@leosn, apenas estamos seguindo aqui o conceito de idempotência que é tema recorrente no contexto do arranjo. O e2eID funciona da mesma maneira: o PSP pagador, que inicia a PACS008, cria um e2eID que identifica a transação de ponta a ponta. 

Da mesma maneira aqui, o usuário recebedor cria um identificador próprio que identifica a cobrança de ponta a ponta. 

O problema aqui em termos de utilizar um `POST` e deixar o PSP criar o `txid` é que em um cenário de falha, o usuário recebedor não sabe se o QR foi criado ou não e nem tem um identificador para fazer essa pergunta específica acerca deste QR.
