### ISSUE TITLE
RC1 Pix Automático - "destinatário" opcional nas solicitações de recorrências

### ISSUE THREAD

**Issue by christianf2029** [bacen/pix-api#611]
Prezados, bom dia.

Na **RC1** da especificação dos endpoints do **Pix Automático**, o campo `destinatario` está como opcional nas solicitações de recorrência.

![image](https://github.com/user-attachments/assets/ded9f832-be45-43c0-996c-a2efa6b0c72d)

Entendo que a utilização de solicitações de recorrência diz respeito à **Jornada 1**, onde preciso especificar o "pagador pretendido". Nas demais jornadas, as interações se darão via QR Codes, onde está especificado o `devedor` somente.

Meu entendimento está equivocado?

**Comment by christianf2029** [comment]
Se puder apoiar por favor, @thiagolvlsantos (marcando por ser o autor do commit).

**Comment by thiagolvlsantos** [comment]
> Prezados, bom dia.
> 
> Na **RC1** da especificação dos endpoints do **Pix Automático**, o campo `destinatario` está como opcional nas solicitações de recorrência.
> 
> ![image](https://private-user-images.githubusercontent.com/16386736/377078735-ded9f832-be45-43c0-996c-a2efa6b0c72d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkxMDg1MTAsIm5iZiI6MTcyOTEwODIxMCwicGF0aCI6Ii8xNjM4NjczNi8zNzcwNzg3MzUtZGVkOWY4MzItYmU0NS00M2MwLTk5NmMtYTJlZmE2YjBjNzJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE2VDE5NTAxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkyYjEzNDBkYWI3MWZlOGYxZGQzNTZjZWQ5ZDVmMTY0ODU2YjhjYjZmMTQxYmY3ZmMwNTE3MzYyMmZkNzRkYTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.MU_A-IY5cQixQ_vgpi3PxyelaO-IGTH7H6l6crE4Bi0)
> 
> Entendo que a utilização de solicitações de recorrência diz respeito à **Jornada 1**, onde preciso especificar o "pagador pretendido". Nas demais jornadas, as interações se darão via QR Codes, onde está especificado o `devedor` somente.
> 
> Meu entendimento está equivocado?

Não. Não está equivocado.

Atenciosamente.

**Comment by christianf2029** [comment]
Obrigado, @thiagolvlsantos.

Você pode clarear o porquê de estar opcional? Já que na **Jornada 1** eu preciso especificar o "pagador pretentido". Há algum caso de uso que eu não esteja considerando?

**Comment by christianf2029** [comment]
Obrigado, @thiagolvlsantos.

Pode esclarecer por que é opcional? Não entendi se é um ajuste a ser feito na especificação ou se há algum caso de uso que não percebi.
