### ISSUE TITLE
[Dúvida] Revisões de cobranças

### ISSUE THREAD

**Issue by christianf2029** [bacen/pix-api#63]
Estou com uma dúvida no entendimento do que é uma revisão de cobrança. Quando eu reviso uma cobrança, eu preciso armazenar a versão corrente e a nova versão revisada, isto quer dizer que terei que armazenar todas as revisões que faço em uma dada cobrança. Existe essa referência na documentação mas ainda não consegui ter o entendimento final:

> ![image](https://user-images.githubusercontent.com/16386736/95635202-22b08a80-0a62-11eb-8d41-67c28d664236.png)

- Preciso manter locations distintos apontando para o payload de cada revisão?
- Eu posso aceitar pagamento de qualquer revisão de uma cobrança? Inclusive a revisão 1 da cobrança pode ter um pagamento, a revisão 2 da cobrança pode ter outro?
- Como controlar o status de cada revisão da cobrança?

**Comment by ninrod** [comment]
bom dia @christianf2029 

> Preciso manter locations distintos apontando para o payload de cada revisão?

Não.

> Eu posso aceitar pagamento de qualquer revisão de uma cobrança? Inclusive a revisão 1 da cobrança pode ter um pagamento, a revisão 2 da cobrança pode ter outro?

Você só aceita o Pix se o Pix estiver aderente à especificação da última revisão.

> Como controlar o status de cada revisão da cobrança?

Somente revisões ATIVAS podem ser revisadas.

**Comment by christianf2029** [comment]
Bom dia @ninrod ,

> Não.

Então, desde a primeira versão até a revisão **n**, a url do payload é sempre a mesma?

> Você só aceita o Pix se o Pix estiver aderente à especificação da última revisão.

Perfeito.

> Somente revisões ATIVAS podem ser revisadas.

Concluo então que ao criar uma nova revisão, eu devo desativar as revisões antigas? Se sim, qual status ficaria?

**Comment by ninrod** [comment]
@christianf2029 , 

> Então, desde a primeira versão até a revisão n, a url do payload é sempre a mesma?

Com a entrada da versão `2.1.0`, a resposta correta é "não necessariamente". A nova funcionalidade "reuso de locations" possibilita que o "location" (a url do payload) seja alterada via patch. 

> Concluo então que ao criar uma nova revisão, eu devo desativar as revisões antigas? Se sim, qual status ficaria?

Não vejo desta forma. Acredito que as "revisões antigas" necessariamente ficariam "ATIVAS", por definição. Como são revisões antigas, "históricas", não servem para mais nada a não ser histórico mesmo. Se a cobrança "histórica" tivesse um status diferente de `ATIVA` você poderia questionar o motivo de o seu software ter permitido a alteração já que somente cobranças `ATIVAS` podem ser alteradas.

**Comment by christianf2029** [comment]
> Com a entrada da versão 2.1.0, a resposta correta é "não necessariamente". A nova funcionalidade "reuso de locations" possibilita que o "location" (a url do payload) seja alterada via patch.

Ok, veremos como se dará.

> Não vejo desta forma. Acredito que as "revisões antigas" necessariamente ficariam "ATIVAS", por definição. Como são revisões antigas, "históricas", não servem para mais nada a não ser histórico mesmo. Se a cobrança "histórica" tivesse um status diferente de ATIVA você poderia questionar o motivo de o seu software ter permitido a alteração já que somente cobranças ATIVAS podem ser alteradas.

Perfeito, muito bem esclarecido.

Obrigado @ninrod .
