### ISSUE TITLE
PIX Agendado

### ISSUE THREAD

**Issue by mvsusp** [bacen/pix-api#65]
Segundo **Resolução BCB n° 1 de 12/8/2020**:
*Art. 9º  A solicitação de um Pix Agendado deve ficar retida nos sistemas internos do participante, não sensibilizando os saldos em conta transacional do usuário pagador, até o momento da efetiva iniciação do Pix...*

A minha dúvida é:
- Essa solicitação vai ser armazenada no PSP do pagador ou do recebedor?
- Será possível, para o PSP do recebedor, verificar o agendamento, via API PIX?
- Dado que essa feature é opcional, ela precisa estar disponível em ambos PSPS do recebedor e pagador?

Desde já obrigado

**Comment by renatofrota** [comment]
>     * Essa solicitação vai ser armazenada no PSP do pagador ou do recebedor?

Pagador. Assim como uma transação de pagamento de boleto/conta ou transferência pode ser agendada (e cancelada) atualmente.

>     * Será possível, para o PSP do recebedor, verificar o agendamento, via API PIX?

Não. Esse agendamento só existe no PSP do pagador. Somente estará disponível via API se for efetivado.

>     * Dado que essa feature é opcional, ela precisa estar disponível em ambos PSPS do recebedor e pagador

Não. A partir do momento que a data de agendamento é alcançada, a transação é realizada como se tivesse sido comandada naquele momento, então para o PSP recebedor (assim como para o próprio PSP pagador), aquele é um Pix como qualquer outro.

**Comment by ninrod** [comment]
> Pagador. Assim como uma transação de pagamento de boleto/conta ou transferência pode ser agendada (e cancelada) atualmente.

Correto

> Não. Esse agendamento só existe no PSP do pagador. Somente estará disponível via API se for efetivado.

Correto

> Não. A partir do momento que a data de agendamento é alcançada, a transação é realizada como se tivesse sido comandada naquele momento, então para o PSP recebedor (assim como para o próprio PSP pagador), aquele é um Pix como qualquer outro.

Correto.

**Comment by mvsusp** [comment]
Faz todo o sentido, muito obrigado pela resposta. Vou fechar esse ticket.
