### ISSUE TITLE
[Nova Funcionalidade] "Split"

### ISSUE THREAD

**Issue by alexandresanlim** [bacen/pix-api#66]
Pelo que eu entendi, as software houses não acessarão diretamente as APIs do Pix, dependerão de um terceiro que esse sim fornece as APIs conforme as padronizações do Pix.

Levando em conta por exemplo, eu desenvolvo um aplicativo de venda para a empresa "Padaria do seu Zé", porem eu como software house (que consome uma API de terceiro) gostaria de receber 1 real por cada venda, pelo pix será possível fazer o "Split", o 1 real da venda da Padaria do seu Zé vem para minha conta, e o restante para a Padaria do seu Zé? 

Lembrando que esse processo já acontece pra algumas APIs de pagamento como Pagar.me, iugu e outras...

**Comment by rubenskuhl** [comment]
O BACEN tem citado mais recentemente esse tipo de recurso(citado como "marketplace") como na agenda evolutiva do Pix. Mas agora no Go Live ele ainda não existe, porém ele poderia ser implementado de forma automatizada fazendo um pagamento Pix tendo como gatilho um recebimento Pix.

**Comment by ninrod** [comment]
bom dia @alexandresanlim 

> Pelo que eu entendi, as software houses não acessarão diretamente as APIs do Pix

Eu não entendo assim. Você acessará diretamente a API do PSP recebedor em nome da "padaria do zé".

**Comment by alexandresanlim** [comment]
> bom dia @alexandresanlim
> 
> > Pelo que eu entendi, as software houses não acessarão diretamente as APIs do Pix
> 
> Eu não entendo assim. Você acessará diretamente a API do PSP recebedor em nome da "padaria do zé".

Entendido este ponto, e no ponto do suporte a split?

**Comment by ninrod** [comment]
@alexandresanlim 

> Entendido este ponto, e no ponto do suporte a split?

O suporte a split não é uma feature "mapeada", no momento. Mas você pode me ajudar a vender essa feature internamente. 
Qual é exatamente a necessidade de negócio que essa feature atende? Entendo que com o "split", o caixa da sua software house vai sendo abastecido "online" no momento em que as transações são efetuadas versus um modelo em que a cobrança é realizada "a posteriori". Esse seria o principal benefício? Há algum outro?

**Comment by rubenskuhl** [comment]
O caso de uso de um marketplace é comissionar uma plataforma de vendas que dê maior alcance a um estabelecimento. Ele existe tanto no mundo físico, os shopping centers, como no comércio eletrônico, aonde o chamado modelo "3P" faz com que um marketplace ou só tenha vendedores terceiros (caso do Mercado Livre) ou tenha produtos próprios e de terceiros (Magalu, Amazon, Americanas etc.). 

O caso de uso na API é quando o PSP e o Marketplace não são a mesma entidade, pois se o fossem, o próprio PSP já poderia fazer o débito da comissão(é o que imagine que o MercadoPago e o MercadoLivre irão fazer). O que não sei de cara como fazer é a sinalização para o Marketplace de que um determinado recebedor aceitou as condições e configurou o split numa determinada conta ou chave.
Essa comunicação tripartite é um pouco mais sofisticada do que o hoje presente na API, tanto na definição da regra de split (que pode ter valores mínimos, valores máximos, percentuais escalonados etc.) quanto na aceitação.

**Comment by alexandresanlim** [comment]
> o próprio PSP já poderia fazer o débito da comissão(é o que imagine que o MercadoPago e o MercadoLivre irão fazer)

@rubenskuhl , como vc tirou essa conclusão? pois olhando a versão 2.0.0 da API não consigo pensar e aparente não suporta algum tipo de comissão.

**Comment by rubenskuhl** [comment]
> > o próprio PSP já poderia fazer o débito da comissão(é o que imagine que o MercadoPago e o MercadoLivre irão fazer)
> 
> @rubenskuhl , como vc tirou essa conclusão? pois olhando a versão 2.0.0 da API não consigo pensar e aparente não suporta algum tipo de comissão.

Como @ninrod escreveu abaixo, isso seria regra do negócio do PSP. Por isso só imagino isso funcionando inicialmente quando PSP e marketplace são a mesma entidade, como no meu exemplo do Mercado Pago e Mercado Livre.

**Comment by alexandresanlim** [comment]
> Como @ninrod escreveu abaixo, isso seria regra do negócio do PSP. Por isso só imagino isso funcionando inicialmente quando > PSP e marketplace são a mesma entidade, como no meu exemplo do Mercado Pago e Mercado Livre.

@rubenskuhl 

Certo, mas como o pix identifica "a mesma entidade"?

Pois tendo em vista o que foi informado, eu penso que esta poderia ser uma funcionalidade do próprio PSP,  caso tanto  a software house quanto o estabelecimento recebedor estiver no mesmo PSP, como por exemplo num formato "Conta" (que identifica a software house) e "Subconta" (que identifica o estabelecimento recebedor), e assim tendo essas duas entidades identificadas dentro do PSP, por que não fazer um "booktransfer " buscando de alguma configuração? 

Vc consegue enxergar esta possibilidade?

**Comment by ninrod** [comment]
@alexandresanlim obrigado pela sugestão. Encaminhei para triagem por parte da equipe de negócio.
