### ISSUE TITLE
[Dúvida] APi Pix 2.0 - Indiretos

### ISSUE THREAD

**Issue by mariapessoacaldas** [bacen/pix-api#68]
**Descreva sua dúvida ou problema**
A API Pix padronizada é obrigatória para os Indiretos? 

**Sistema ou Área**
Api Pix, Qr Code

**Comment by rubenskuhl** [comment]
> **Descreva sua dúvida ou problema**
> A API Pix padronizada é obrigatória para os Indiretos?
> 
> **Sistema ou Área**
> Api Pix, Qr Code

E em outra possível interpretação da sua pergunta, o relacionamento entre PSPs diretos e PSPs indiretos não tem API padronizada. E a relação entre PSPs (diretos ou indiretos) e seus correntistas que é padronizada.

**Comment by ninrod** [comment]
> E em outra possível interpretação da sua pergunta, o relacionamento entre PSPs diretos e PSPs indiretos não tem API padronizada. E a relação entre PSPs (diretos ou indiretos) e seus correntistas que é padronizada.

Correto.
