### ISSUE TITLE
Dúvida tipo de autenticação do callback de recebimento

### ISSUE THREAD

**Issue by monise** [bacen/pix-api#69]
Bom dia! Qual seria a forma de autentificarão do callback sobre o recebimento?
Seria mTLS?

![image](https://user-images.githubusercontent.com/5355541/95863261-5decdb00-0d3a-11eb-865c-be1a1fa4c047.png)

**Comment by ninrod** [comment]
Olá @monise . 

>  Seria mTLS?

Sim.
