### ISSUE TITLE
[Sugestão] Criar Cobrança – Inclusão do campo payloadQrcode no retorno

### ISSUE THREAD

**Issue by leosn** [bacen/pix-api#7]
/cob/{txid} Criar Cobrança

Prezados,

Alguns de nossos clientes nos pediram que essa API de criação de cobrança (e até nas de consultas) retornasse também a String do payload. Desta forma o próprio estabelecimento pode apresentar ao seu cliente a imagem do qr-code para que possa ser pago através do app do PSP do pagador.

**Comment by rubenskuhl** [comment]
Me parece que já é assim que está especificado... a resposta da criação de cobrança é uma URL, e essa URL que é encoded no QR-Code, não uma imagem.

**Comment by leosn** [comment]
Prezado Rubens, o payload contém o link(url), mas não é o qr-code no formato Br Code que imprimimos para que nossos apps decodifiquem.

**Comment by jocimarcan** [comment]
Também tenho essa dúvida, se poderíamos adicionar campos para facilitar a integração com a API. Além do location, adicionar um campo payloadText, ou até mesmo um payloadImage (base64)

**Comment by rubenskuhl** [comment]
@jocimarcan o BACEN já respondeu que não no issue https://github.com/bacen/pix-perguntas-e-respostas/issues/287 .

**Comment by ninrod** [comment]
Prezados, o único elemento necessário para criar um QR dinâmico é realmente a URL denotada por `fdqnPSPrecebedor/pixendpoint/pixURLAcessToken`. 

De posse dessa URL, criar a "string" que representa o QR dinâmico é uma operação direta. 

@jocimarcan, para ficar mais claro, gerar a string que represesenta o QR Dinâmico, ou ainda gerar a string que representa o QR Estático é uma operação que está fora da API Pix, então pode ser provida porque __qualquer__ elemento de sofware: uma lib, uma função ou uma API qualquer. 

Por exemplo, você poderia escrever uma API sua em que, entrando com a URL, tem-se como saída a string do QR Dinâmico.
