### ISSUE TITLE
Headers Customizados

### ISSUE THREAD

**Issue by ikenofh** [bacen/pix-api#71]
Boa tarde!
O PSP poderá, a sua escolha, exigir o envio de headers customizados nas requests para a API de Recebimento?
Entendam por "header customizado" qualquer cabeçalho que não esteja especificado na documentação OpenAPI da API de Recebimento.

**Comment by EvertonSA** [comment]
gostaria de clarificações nesse ponto também! não entendo nada saudável os parceiros PSP colocarem headers customizados de autenticação. RFC?????

**Comment by rubenskuhl** [comment]
Eu vi isso também num banco grande e vermelho, e para mim é uma violação da API, que deixa claros TLS e OAuth 2. 
Mas como esse banco é um dos mais caros PSPs também, não vou sentir falta dele.

**Comment by EvertonSA** [comment]
> Eu vi isso também num banco grande e vermelho, e para mim é uma violação da API, que deixa claros TLS e OAuth 2.
> Mas como esse banco é um dos mais caros PSPs também, não vou sentir falta dele.

vi o mesmo com o bancão laranja e azul

**Comment by rubenskuhl** [comment]
> > Eu vi isso também num banco grande e vermelho, e para mim é uma violação da API, que deixa claros TLS e OAuth 2.
> > Mas como esse banco é um dos mais caros PSPs também, não vou sentir falta dele.
> 
> vi o mesmo com o bancão laranja e azul

O laranja e azul é o mesmo preço por transação do grande e vermelho. Ambos precisam ver que o mundo mudou, tanto em padronização quanto em competitividade.

**Comment by rubenskuhl** [comment]
@mariapessoacaldas

**Comment by ninrod** [comment]
@ikenofh , 

> Boa tarde!
O PSP poderá, a sua escolha, exigir o envio de headers customizados nas requests para a API de Recebimento?
Entendam por "header customizado" qualquer cabeçalho que não esteja especificado na documentação OpenAPI da API de Recebimento.

Preciso de mais informações para avaliar: que headers específicos seriam esses, exatamente.

**Comment by ikenofh** [comment]
> @ikenofh ,
> 
> > Boa tarde!
> > O PSP poderá, a sua escolha, exigir o envio de headers customizados nas requests para a API de Recebimento?
> > Entendam por "header customizado" qualquer cabeçalho que não esteja especificado na documentação OpenAPI da API de Recebimento.
> 
> Preciso de mais informações para avaliar: que headers específicos seriam esses, exatamente?

Existem alguns, mas o principal exemplo seria o header de autorização.

**Comment by ninrod** [comment]
@ikenofh , 

> Existem alguns, mas o principal exemplo seria o header de autorização.

Certo, mas o que exatamente você está que está "customizado" no "header de autorização"?

@rubenskuhl , se puder ajudar aqui também em relação à sua experiência com os "headers customizados". Preciso entender com mais detalhes.

**Comment by rubenskuhl** [comment]
> @ikenofh ,
> 
> > Boa tarde!
> > O PSP poderá, a sua escolha, exigir o envio de headers customizados nas requests para a API de Recebimento?
> > Entendam por "header customizado" qualquer cabeçalho que não esteja especificado na documentação OpenAPI da API de Recebimento.
> 
> Preciso de mais informações para avaliar: que headers específicos seriam esses, exatamente?


Um PSP específico que citei acima requer os seguintes parâmetros no header:

Authorization - conteúdo Bearer e uma chave
X-Brad-Nonce - nonce aleatório
X-Brad-Timestamp - 2020-03-10T12:17:06-00:00
X-Brad-Algorithm - SHA256
X-Brad-Signature - Assinatura do request

**Comment by rubenskuhl** [comment]
> @rubenskuhl , se puder ajudar aqui também em relação à sua experiência com os "headers customizados". Preciso entender com mais detalhes.

Eu documentei acima o de um PSP que chegou a me mandar o manual de integração antes de me mandar uma proposta muito cara. O de outro já citado nesse tópico veio a proposta (cara) primeiro então não cheguei a ver o manual de integração, mas já marquei uma pessoa que pode levar para dentro dessa organização a mensagem de que isso é uma infração.

**Comment by ikenofh** [comment]
> @ikenofh ,
> 
> > Existem alguns, mas o principal exemplo seria o header de autorização.
> 
> Certo, mas o que exatamente você entende que está "customizado" no "header de autorização"? O que exatamente o PSP X ou Y estaria pedindo de específico? Pode descer no baixo nível mesmo.
> 
> @rubenskuhl , se puder ajudar aqui também em relação à sua experiência com os "headers customizados". Preciso entender com mais detalhes.
> 
> @EvertonSA, agradeceria se compartilhasse suas impressões também.

Em vez de usar o padrão da RFC 6750 (header Authorization), usar um outro header customizado ("chaveapi", p.ex.) para enviarmos o Access Token na hora de fazer o request na API de Recebimento.

**Comment by ninrod** [comment]
> Um PSP específico que citei acima requer os seguintes parâmetros no header:

> Authorization - conteúdo Bearer e uma chave
X-Brad-Nonce - nonce aleatório
X-Brad-Timestamp - 2020-03-10T12:17:06-00:00
X-Brad-Algorithm - SHA256
X-Brad-Signature - Assinatura do request

Exigir esses elementos consiste em uma violação da API Pix.

> Em vez de usar o padrão da RFC 6750 (header Authorization), usar um outro header customizado ("chaveapi", p.ex.) para enviarmos o Access Token na hora de fazer o request na API de Recebimento.

Trata-se de uma  violação da API PIx.

**Comment by EvertonSA** [comment]
> > Um PSP específico que citei acima requer os seguintes parâmetros no header:
> 
> > Authorization - conteúdo Bearer e uma chave
> > X-Brad-Nonce - nonce aleatório
> > X-Brad-Timestamp - 2020-03-10T12:17:06-00:00
> > X-Brad-Algorithm - SHA256
> > X-Brad-Signature - Assinatura do request
> 
> Exigir esses elementos consiste em uma violação da API Pix.
> 
> > Em vez de usar o padrão da RFC 6750 (header Authorization), usar um outro header customizado ("chaveapi", p.ex.) para enviarmos o Access Token na hora de fazer o request na API de Recebimento.
> 
> Trata-se de uma violação da API PIx.

Obrigado pelo esclarescimento @ninrod, como fazemos para comunicar essas inconsistências para os bancões?

**Comment by rubenskuhl** [comment]
> > > Um PSP específico que citei acima requer os seguintes parâmetros no header:
> > 
> > 
> > > Authorization - conteúdo Bearer e uma chave
> > > X-Brad-Nonce - nonce aleatório
> > > X-Brad-Timestamp - 2020-03-10T12:17:06-00:00
> > > X-Brad-Algorithm - SHA256
> > > X-Brad-Signature - Assinatura do request
> > 
> > 
> > Exigir esses elementos consiste em uma violação da API Pix.
> > > Em vez de usar o padrão da RFC 6750 (header Authorization), usar um outro header customizado ("chaveapi", p.ex.) para enviarmos o Access Token na hora de fazer o request na API de Recebimento.
> > 
> > 
> > Trata-se de uma violação da API PIx.
> 
> Obrigado pelo esclarescimento @ninrod, como fazemos para comunicar essas inconsistências para os bancões?

Eu por enquanto tenho denunciado para pix@bcb.gov.br, mas seria interessante o @ninrod ou @dmkamers dizer se é esse mesmo o canal apropriado.

**Comment by ninrod** [comment]
> Eu por enquanto tenho denunciado para pix@bcb.gov.br, mas seria interessante o @ninrod ou @dmkamers dizer se é esse mesmo o canal apropriado.

Sim, acredito que é um meio apropriado. Também busquei encaminhar a questão internamente.

**Comment by anderpascini** [comment]
@ninrod Temos um gerenciador de API que necessita de uma chave para identificar o parceiro... Esta chave pode ser enviada atraves de querystring ou header. Neste caso como fica?

**Comment by anderpascini** [comment]
@ninrod No caso do gateeway de API necessitar de uma chave de desenvolvedor para identificar o parceiro... Como fica? Pois esta chave geralmente é passada via querystring ou header.

**Comment by rubenskuhl** [comment]
> @ninrod No caso do gateeway de API necessitar de uma chave de desenvolvedor para identificar o parceiro... Como fica? Pois esta chave geralmente é passada via querystring ou header.

Certificado mTLS, client-id e client-secret do OAuth2 já não identificam univocamente o correntista ?

**Comment by ninrod** [comment]
@anderpascini 

> @ninrod No caso do gateeway de API necessitar de uma chave de desenvolvedor para identificar o parceiro... Como fica? Pois esta chave geralmente é passada via querystring ou header.

A resposta do @rubenskuhl está aderente:

> Certificado mTLS, client-id e client-secret do OAuth2 já não identificam univocamente o correntista ?

**Comment by anderpascini** [comment]
@rubenskuhl e @ninrod 

A chave de desenvolvedor (chave de API) identifica o dev/projeto que faz a chamada a uma API. Atraves desta chave o gateway de API pode fazer alguns controles como por exemplo quota.

Já os tokens de autenticação identificam um usuário (correntista como no seu exemplo) que está usando o aplicativo ou site.

**Comment by rubenskuhl** [comment]
> @rubenskuhl e @ninrod
> 
> A chave de desenvolvedor (chave de API) identifica o dev/projeto que faz a chamada a uma API. Atraves desta chave o gateway de API pode fazer alguns controles como por exemplo quota.
> 
> Já os tokens de autenticação identificam um usuário (correntista como no seu exemplo) que está usando o aplicativo ou site.

Esse tipo de chave apartada dos outros parâmetros não me parece aderente à API. Uma alternativa que vi ser utilizada num PSP é associar um par clientid/clientsecret a uma metáfora específica, como determinado clientid/clientsecret significa correntista tal na aplicação/gateway tal. 

Outra opção, como o PSP gera o certificado para o mTLS, é colocar algum dos parâmetros do certificado com essa informação. O X.509 permite extensões e como para o client (no sentido client-server) tem que apresentar um certificado, o conteúdo dele é indiferente.

**Comment by ninrod** [comment]
> Esse tipo de chave apartada dos outros parâmetros não me parece aderente à API

correto.

**Comment by LeoBOrtigoza** [comment]
Bom dia Pessoal, tudo bem? 

como ficou esse tema? Qual é o posicionamento? Sabemos se tem algum PSP criando Headers personalizados?

**Comment by GustavoSTZ** [comment]
@LeoBOrtigoza acredito que dependa do caso, **aconselho mandar email diretamente para o Bacen especificando o seu cenário.**

Pois trabalho em um Bank as a Service e devido ao fato de não conseguirmos identificar o cliente do nosso cliente(outro banco) através da autenticação (pois quem estaria autenticado no nosso sistema seria o nosso cliente e não o cliente do cliente) , foi permitido que adicionassemos uma propriedade a mais no header para identificar quem seria o cliente final.

Vale ressaltar que no email que enviamos para o Bacen pedindo permissão para tal, ele deixou claro que caso algum momento ele defina regras para os banks as services deveríamos nos adaptar para tal.

Ou seja, no meu entendimento, pode-se alterar sim, entretanto tais headers não podem quebrar o contrato do Bacen. Caso quebre, DEVE ser alinhado com o Bacen, conforme fizemos, pois precisavamos identificar o dono final de tal cobrança.

**Comment by rubenskuhl** [comment]
> 

O @ninrod já respondeu no comentário https://github.com/bacen/pix-api/issues/71#issuecomment-731309254 , não pode.

**Comment by rubenskuhl** [comment]
> @LeoBOrtigoza acredito que dependa do caso, **aconselho mandar email diretamente para o Bacen especificando o seu cenário.**
> 
> Pois trabalho em um Bank as a Service e devido ao fato de não conseguirmos identificar o cliente do nosso cliente(outro banco) através da autenticação (pois quem estaria autenticado no nosso sistema seria o nosso cliente e não o cliente do cliente) , foi permitido que adicionassemos uma propriedade a mais no header para identificar quem seria o cliente final.
> 
> Vale ressaltar que no email que enviamos para o Bacen pedindo permissão para tal, ele deixou claro que caso algum momento ele defina regras para os banks as services deveríamos nos adaptar para tal.
> 
> Ou seja, no meu entendimento, pode-se alterar sim, entretanto tais headers não podem quebrar o contrato do Bacen. Caso quebre, DEVE ser alinhado com o Bacen, conforme fizemos, pois precisavamos identificar o dono final de tal cobrança.

O BaaS não é coberto pelo contrato do BACEN. A API pode ser qualquer uma entre vocês e seus clientes.... o cliente de vocês(que é ente regulado) é que precisa respeitar o contrato com o cliente deles(que é ente protegido pela regulação). Se vocês por facilidade usaram algo muito similar à API Pix, ok... mas é quase uma coincidência. 

Agora, dava para fazer sem cabeçalho especial... pois como o mTLS se refere a uma PKI, os parâmetros do certificado poderiam ser usados para identificar o banco cliente. Por exemplo, vocês emitirem certificados de uma CA privada de vocês, e ou estabelecer semânticas específicas para CN/O/OU ou colocar uma extensão X.400 no certificado que identifica o cliente. Seu BaaS, suas regras. ;-)

Por exemplo, os certificados TLS usados em https://registro.br/tecnologia/provedores-de-hospedagem/epp/solicitacao-certificado/ tem um requisito específico para o CN de que seja o número pelo qual aquele provedor de serviços tem cadastro no sistema. Acho que ficaria mais simples para seus clientes não terem que colocar header específico, o que nem toda linguagem ou framework de back-end permite.
