### ISSUE TITLE
Dúvidas sobre retentativas do callback de recebimento

### ISSUE THREAD

**Issue by monise** [bacen/pix-api#72]
Olá! Tenho algumas duvidas referente ao callback (webhook):

1 -  Se um PDV tiver fora do ar, pode-se ignorar o callback depois de um tempo ? 
2 - Os eventos de callback tem um Time-to-live ?

**Comment by ninrod** [comment]
@monise , são questões interessante que gostaríamos de endereçar na `2.1.0`. 

A principal ideia vigente seria configurar esses elementos no ato da criação do "webhook". 

- no. de tentativas.
- intervalo entre tentativas. 
- número de reqs. concorrentes. 

isso por webhook. 

O que acha?

**Comment by monise** [comment]
@ninrod Acreditamos que as duas primeiras opções são interessantes, da para fazer o controle de tentativas desta forma.
Já a opção "número de reqs. concorrentes" não limita a possibilidade de escalabilidade do sistema do PSP? 
Não seria melhor o serviço de callback retornar um 429 caso tenha sido ultrapassado o número de requisições?

**Comment by rubenskuhl** [comment]
> @monise , são questões interessante que gostaríamos de endereçar na `2.1.0`.
> 
> A principal ideia vigente seria configurar esses elementos no ato da criação do "webhook".
> 
> * no. de tentativas.
> * intervalo entre tentativas.
> * número de reqs. concorrentes.
> 
> isso por webhook.
> 
> O que acha?


Configurar o número de tentativas e o intervalo entre tentativas é interessante sim. 
Mas pensando nisso, uma adição seria ter uma opção no GET de /pix de transações que não tenham tido ACK do Webhook. Assim, seria possível obter as transações que tenham sido perdidas no canal de retorno.

**Comment by franciscotfmc** [comment]
@monise @ninrod 

Um recuo exponencial entre uma tentativa e outra já é algo que estava no nosso radar aqui para implementar. Acredito que isso possa também ser padronizado, gosto da ideia. Só não tenho certeza se o integrador precisaria informar isso. Número de tentativas eu concordo que faz muito sentido vir do integrador.

@rubenskuhl gosto dessa opção alternativa no GET, caso o número de tentativas se esgote, o integrador precisa ter uma ferramenta desse tipo em mãos.

**Comment by ninrod** [comment]
@monise 

> Já a opção "número de reqs. concorrentes" não limita a possibilidade de escalabilidade do sistema do PSP? 
Não seria melhor o serviço de callback retornar um 429 caso tenha sido ultrapassado o número de requisições?

Tem razão.

**Comment by ninrod** [comment]
@rubenskuhl 

> Mas pensando nisso, uma adição seria ter uma opção no GET de /pix de transações que não tenham tido ACK do Webhook. Assim, seria possível obter as transações que tenham sido perdidas no canal de retorno.

Bem interessante a sugestão.

**Comment by ninrod** [comment]
@franciscotfmc 

> recuo exponencial entre uma tentativa e outra 

Gosto da ideia de "recuo exponencial", mas não tenho certeza se seria fácil comunicar e documentar essa funcionalidade na API de maneira didática e clara. Parece que atribuir um intervalo linear ao webhook ficaria mais simples inclusive de implementar. Qual é a opinião de vocês: @monise @rubenskuhl @franciscotfmc?

**Comment by franciscotfmc** [comment]
@ninrod ,

Tecnicamente, não é complicado não. Documentar a funcionalidade deve ser mais difícil que implementar...

**Comment by renatofrota** [comment]
Quando vocês falam em recuo exponencial, querem dizer intervalos crescentes entre as tentativas (até obter um retorno 200), como nesse exemplo abaixo?

![image](https://user-images.githubusercontent.com/3386314/96154995-ccba6780-0ee5-11eb-97a1-26a81173b25b.png)

**Comment by rubenskuhl** [comment]
> @franciscotfmc
> 
> > recuo exponencial entre uma tentativa e outra
> 
> Gosto da ideia de "recuo exponencial", mas não tenho certeza se seria fácil comunicar e documentar essa funcionalidade na API de maneira didática e clara. Parece que atribuir um intervalo linear ao webhook ficaria mais simples inclusive de implementar. Qual é a opinião de vocês: @monise @rubenskuhl @franciscotfmc?

Como um exponential back-off não é fator crítico de interoperabilidade, mas é uma funcionalidade interessante, eu acho que a API podia documentar que o tempo de retentativa deve aumentar a cada falha de chamada do Webhook, mas nunca ser superior a um determinado teto, por exemplo 60 minutos. Já a regra de aumento fica por conta do PSP: PA x PG x tabela, qual razão se for PA/PG etc.

**Comment by franciscotfmc** [comment]
@renatofrota exatamente, seja o tempo para retentativas uma PA ou PG. 

@rubenskuhl importante essa questão de ter um teto mesmo.

**Comment by ninrod** [comment]
@renatofrota , 

> Quando vocês falam em recuo exponencial, querem dizer intervalos crescentes entre as tentativas (até obter um retorno 200), como nesse exemplo abaixo?

sim. 

Mas gosto da ideia do @rubenskuhl de mesmo assim estabelecer um teto.

**Comment by franciscotfmc** [comment]
Sobre o teto, pensando em um servidor de cliente que fique indisponível por um tempo aleatório, acredito que possamos pensar em 120 minutos, sendo que quanto mais próximo do minuto 120, maior foi o intervalo.

Caso ele permaneça indisponível por mais tempo, aí já terá que pensar na reconciliação via GET de /pix de transações sem ACK _(isso poderia ficar explicitamente documentado tanto pela spec do BC, quanto na doc do PSP)_.

Faz sentido pra vocês? @ninrod @rubenskuhl @renatofrota

**Comment by rubenskuhl** [comment]
> Sobre o teto, pensando em um servidor de cliente que fique indisponível por um tempo aleatório, acredito que possamos pensar em 120 minutos, sendo que quanto mais próximo do minuto 120, maior foi o intervalo.
> 
> Caso ele permaneça indisponível por mais tempo, aí já terá que pensar na reconciliação via GET de /pix de transações sem ACK _(isso poderia ficar explicitamente documentado tanto pela spec do BC, quanto na doc do PSP)_.
> 
> Faz sentido pra vocês? @ninrod @rubenskuhl @renatofrota

Para mim 60 minutos e 120 minutos estão dentro da mesma ordem de grandeza então tudo bem. Só não pode mudar para muito mais do que isso, IMHO.

**Comment by ninrod** [comment]
pessoal, estamos achando que essa é uma questão que poderia ficar a cargo do PSP recebedor. (VocÊ configuraria esses parâmetros no dashboard, por exemplo.). 

Poderíamos estabelecer um teto entre as retentativas, mas só. 

O que acham?

**Comment by ninrod** [comment]
Pessoal, vamos decidir pela liberdade do PSP recebedor em implementar suas estratégias em relação a essa questão. 
Precisamos liberar essa nova versão rapidamente. Futuramente, se esta questão se constituir um problema, podemos rever a decisão.

> Olá! Tenho algumas duvidas referente ao callback (webhook):

> 1 - Se um PDV tiver fora do ar, pode-se ignorar o callback depois de um tempo ?
2 - Os eventos de callback tem um Time-to-live ?

@monise , resposta  Estas questões estão dentro da esfera de liberdade do PSP recebedor e, portanto, fora do escopo da API.

Eu diria que é importante comunicar ao cliente a política de retentativas e desistência de notificações e, se aplicável, como se configura o comportamento, se é via dashboard, etc...
