### ISSUE TITLE
Dúvidas bem básicas quanto ao Pix

### ISSUE THREAD

**Issue by LucianoMass** [bacen/pix-api#74]
Pessoal, bom dia

Tenho uma dúvidas bem básicas sobre o Pix e gostaria de ver se é possível esse esclarecimento por aqui.

1) Meu sistema de gestão precisa gerar as cobranças para os meus clientes (emito a nota e gero uma cobrança, que hj é um boleto e desejo substituir pelo Pix para quem solicitar). É essa API desse repositório que devo utilizar para geração do QR Code dinâmico que acompanha a cobrança?
2) O QRCode dinâmico é sempre devolvido pelo meu banco através de uma resposta a minha solicitação ou eu posso gerar ele direto pelo meu sistema sem o conhecimento do banco?
3) Essa API é um padrão para todos os bancos? Vou precisar desenvolver apenas sob essa documentação e estarei apto a gerar QR Code dinâmico por todos eles ou cada um vai ter a sua própria api? Não encontrei nenhum banco disponibilizando API do Pix para o recebedor.

Obrigado pelos esclarecimentos

**Comment by rubenskuhl** [comment]
> Pessoal, bom dia
> 
> Tenho uma dúvidas bem básicas sobre o Pix e gostaria de ver se é possível esse esclarecimento por aqui.
> 
> 1. Meu sistema de gestão precisa gerar as cobranças para os meus clientes (emito a nota e gero uma cobrança, que hj é um boleto e desejo substituir pelo Pix para quem solicitar). É essa API desse repositório que devo utilizar para geração do QR Code dinâmico que acompanha a cobrança?

Sim, notando que a escolha entre QR Code dinâmico ou estático é sua. 
Mas mesmo que você escolha o estático, os métodos /pix se aplicam; só os métodos /cob que só se aplicam a dinâmicos. 

> 2. O QRCode dinâmico é sempre devolvido pelo meu banco através de uma resposta a minha solicitação ou eu posso gerar ele direto pelo meu sistema sem o conhecimento do banco?

O dinâmico só com o banco, o estático pode ser gerado no seu sistema. A equivalência do dinâmico é com boleto registrado e do estático com boleto não registrado. 


> 3. Essa API é um padrão para todos os bancos? Vou precisar desenvolver apenas sob essa documentação e estarei apto a gerar QR Code dinâmico por todos eles ou cada um vai ter a sua própria api? Não encontrei nenhum banco disponibilizando API do Pix para o recebedor.

Ela é padrão para todos os bancos, e recebi pelo menos 20 propostas diferentes com a mesma API Pix padrão. 
Mas encontrei também muita falta de informação das equipes de bancos grandes que não sabiam  da existência disso, então chegar às pessoas corretas foi complicado mesmo.

**Comment by LucianoMass** [comment]
Perfeito amigo, muito obrigado pelas respostas.

**Comment by ninrod** [comment]
obrigado @rubenskuhl
