### ISSUE TITLE
Padrão Restful

### ISSUE THREAD

**Issue by cruzcunha** [bacen/pix-api#80]
1) Porque foi definida a utilização de siglas e abreviações no nome dos recursos? Não seria melhor seguir o padrão restfull e utilizar um nome mais inteligível, como "/cobranca"  ou invés de "/cob"? Seria melhor que sejam possível entender negócio somente lendo as URLs. É mais prático para os desenvolvedores. 

2) O recurso "/cob/" está com uma barra no final e o recurso "/pix" está sem barra para o método GET. Entendo que o "/cob/" deveria ser "/cob".

**Comment by rubenskuhl** [comment]
Eu prefiro /cobranca, mas não vejo problema em ficar /cob. Imagino que cob tenha sido escolhido por ter 3 letras, assim como Pix.

**Comment by ninrod** [comment]
> O recurso "/cob/" está com uma barra no final e o recurso "/pix" está sem barra para o método GET. Entendo que o "/cob/" deveria ser "/cob".

Ok, obrigado pelo reporte, vamos consertar na `2.1.0`

> Porque foi definida a utilização de siglas e abreviações no nome dos recursos? Não seria melhor seguir o padrão restfull e utilizar um nome mais inteligível, como "/cobranca" ou invés de "/cob"? Seria melhor que sejam possível entender negócio somente lendo as URLs. É mais prático para os desenvolvedores.

a definição de nomes é por vezes uma atividade cercada de polêmicas e não foi diferente neste caso específico. De qualquer maneira, esses nomes já estão estabelecidos e não devem mudar.
