### ISSUE TITLE
[Dúvida] - Api Consulta PIX - Status

### ISSUE THREAD

**Issue by adrianbp** [bacen/pix-api#81]
Boa Tarde!

A api de consulta PIX não deveria conter o status do envio/recebimento da pagamento original? Eu verifiquei que só temos o campo status dentro da estrutura de devoluções do PIX.

**Comment by ninrod** [comment]
boa tarde @adrianbp , 

>  status do envio/recebimento da pagamento original? 

O que exatamente você quer dizer com esse trecho? o que seria esse status?

**Comment by adrianbp** [comment]
Boa noite,

Estou me referindo ao status do PIX que é enviado através de uma PACS008.  Por exemplo: "Em procesamento", "Rejeitado", "Liquidado".

Na documentação só temos o status das devoluções realizadas através de PACS004. (EM_PROCESSAMENTO, DEVOLVIDO e NAO_REALIZADO). Se não existir devolução para o end to end Id informado, como o consumidor da API irá saber o status da liquidação do PIX enviado ou recebido ?

**Comment by ninrod** [comment]
@adrianbp , 

se você consultar um `GET /cob/{txid}` e você constatar que existe um pix aninhado a este objeto, só existe uma possibilidade: o pix está liquidado e nada pode alterar este fato. 

da mesma maneira, se você consultar `GET /pix/{e2eid}`, somente será retornado um erro ou um pix liquidado. 

Em outras palavras, sempre que você encontrar um pix na API Pix, ele estará liquidado.

**Comment by adrianbp** [comment]
@ninrod , Boa tarde,

Me tira uma dúvida ? Qual é o contexto destas API´s ? É serem utilizadas apenas no contexto de cobrança onde txtid é obrigatório ou seria utilizado na transferência de valores entre contas onde podemos não ter o txid ?

**Comment by ninrod** [comment]
Contexto de cobrança. 

Sugiro explorar a documentação relacionada: Manual de padrões para iniciação do Pix [link](https://www.bcb.gov.br/estabilidadefinanceira/pagamentosinstantaneos), clique no botão verde "regulamentação relacionada...", é o segundo documento.
