### ISSUE TITLE
Removido campo calendario.recebivelAposVencimento do payload JSON

### ISSUE THREAD

**Issue by monise** [bacen/pix-api#82]
Olá! Gostaria de confirmar, o campo “calendario.**recebivelAposVencimento**" foi **removido** do payload JSON?

Pergunto, pois na versão 2.0 do manual "_II.ManualdePadroesparaIniciacaodoPix-versao2.0_" ele ainda é apresentado na tabela abaixo (página 14), porém na seção 1.6.8 ele não é mais mencionado:

![image](https://user-images.githubusercontent.com/5355541/96170268-c2a26400-0ef9-11eb-910a-3c5d8db2167d.png)

**Comment by ninrod** [comment]
> Olá! Gostaria de confirmar, o campo “calendario.recebivelAposVencimento" foi removido do payload JSON?

Sim. 

No lugar dele entra um outro que é o "número de dias em que a cobrança vencida poderá ser paga". Mais informações na `2.1.0`.

**Comment by monise** [comment]
Olá! Esse campo "número de dias em que a cobrança vencida poderá ser paga" não seria o campo calendario.expiracao?
Porque na documentação diz que se existir a data de vencimento, o pagamento pode ser realizado até a data de expiração (que vale a partir da data de vencimento).

![image](https://user-images.githubusercontent.com/5355541/96295095-bbe02380-0fc3-11eb-9c53-faad7ffd3aba.png)

**Comment by ninrod** [comment]
> não seria o campo calendario.expiracao?

Não. O expiração é em segundos e esse novo campo é em dias.

**Comment by fernandogodoy** [comment]
@ninrod  Pelo nosso entendimento a versão que entra em produção agora é a 2.0.0. Nessa versão não ficou claro se o campo “calendario.recebivelAposVencimento" existe ou não.

Entendemos que ele vai ser removido na versão 2.1.0, ou não, ele já foi removido na versão 2.0.0 mesmo?

**Comment by ninrod** [comment]
@fernandogodoy 

isso. a versão 2.1.x é uma RC e deve ser tratada com cautela.

**Comment by ccmario** [comment]
Bom dia!

@ninrod, mas podemos considerar então o payload publicado no manual da versão 2.0, sem o atributo calendario.recebivelAposVencimento?

**Comment by ninrod** [comment]
@ccmario, sim. Se você notar, deve constar uma nota de rodapé indicando que este campo está "em revisão", no manual.
