### ISSUE TITLE
Retorno de requisições PUT deveria ser 201 Created

### ISSUE THREAD

**Issue by VitorTrin** [bacen/pix-api#85]
Quando um recurso é criado, como é o caso das requisições PUT nessa api,  o retorno deveria ser 201 Created ao invés do 200 como de alguns endpoints atuais

**Comment by ninrod** [comment]
@VitorTrin , 

> Quando um recurso é criado, como é o caso das requisições PUT nessa api, o retorno deveria ser 201 Created ao invés do 200 como de alguns endpoints atuais

Obrigado pelo reporte, vamos consertar para a próxima release.

**Comment by rubenskuhl** [comment]
Mas responder 201 precisaria mandar uma URI, não ?

**Comment by renatofrota** [comment]
> Mas responder 201 precisaria mandar uma URI, não ?

Segundo a [RFC 7231, 6.3.2](https://tools.ietf.org/html/rfc7231#section-6.3.2), quando o endereço de consulta for exatamente a mesma URI (mudando apenas o método para GET), não.

> The 201 (Created) status code indicates that the request has been fulfilled and has resulted in one or more new resources being created.  The primary resource created by the request is identified by either a Location header field in the response __or__, if no Location field is received, by the __effective request URI__.

**Comment by ninrod** [comment]
resolvido na `2.1.0`
