### ISSUE TITLE
Dúvida - Controle de Calendário - Identificador calendário.expiracao

### ISSUE THREAD

**Issue by nataliapaivafreitas** [bacen/pix-api#86]
Olá!
O QRCode é válido para pagamento após atingir o limite informado no identificador calendário.expiracao? Este campo possui limite máximo de segundos?

**Comment by ninrod** [comment]
boa noite @nataliapaivafreitas 

> O QRCode é válido para pagamento após atingir o limite informado no identificador calendário.expiracao?

Após atingido o limite, o PSP pagador não deveria permitir que o QR seja pago. 

> Este campo possui limite máximo de segundos?

Não estabelecemos limite máximo.
