### ISSUE TITLE
Dúvida - QrCode Dinâmico X Estático

### ISSUE THREAD

**Issue by nataliapaivafreitas** [bacen/pix-api#88]
Olá!! Para a data do dia 16/11, é obrigatório que a instituição disponibilize a geração dos dois tipos de QRCode (estático e dinâmico)?

**Comment by rubenskuhl** [comment]
A API Pix não precisa ser obrigatoriamente disponibilizada, apenas precisa seguir o padrão se alguma API for disponibilizada. 

Agora, fora do escopo da API talvez este não seja o local apropriado para a pergunta.

**Comment by ninrod** [comment]
No app: Geração não. Leitura, acredito que sim, mas vou confirmar. 

API:

> A API Pix não precisa ser obrigatoriamente disponibilizada, apenas precisa seguir o padrão se alguma API for disponibilizada.

É o que o @rubenskuhl disse.

**Comment by franciscotfmc** [comment]
Acredito que a leitura do QR Code Dinâmico pelos aplicativos dos PSP's deveria ser obrigatória sim. Se não for, o pagador sai perdendo _(e consequentemente o recebedor daquele QR Code)_, pois ficaria difícil saber como/onde efetuar o pagamento.

**Comment by rubenskuhl** [comment]
> Acredito que a leitura do QR Code Dinâmico pelos aplicativos dos PSP's deveria ser obrigatória sim. Se não for, o pagador sai perdendo _(e consequentemente o recebedor daquele QR Code)_, pois ficaria difícil saber como/onde efetuar o pagamento.

Isso já é assim. Os PSPs pagadores são obrigados a suportar o pagamento de QR-Code dinâmicos através do aplicativo mobile e de seu principal canal digital (se não for o mobile). O que é opcional é o PSP recebedor ter suporte a gerar QR-Code dinâmico, quer através de API, quer através de outro canal.

**Comment by ninrod** [comment]
@nataliapaivafreitas , resposta oficial: 

> Olá!! Para a data do dia 16/11, é obrigatório que a instituição disponibilize a geração dos dois tipos de QRCode (estático e dinâmico)?

Sim. Os apps devem estar preparados para ler QRs estáticos e dinâmicos já a partir do dia 3/11 (para os clientes que estarão participando da operação restrita) e a partir do dia 16/11 para todos os clientes do participante.
