### ISSUE TITLE
Exemplos de QR Codes Dinâmicos - com payloads válidos

### ISSUE THREAD

**Issue by franciscotfmc** [bacen/pix-api#89]
Boa tarde pessoal!

Seria possível o BC disponibilizar, neste repositório (ou até mesmo nesta issue), QR Codes Dinâmicos com URL de payload válidas? _(que utilizem os certificados ativos da camada de homologação?)_

Outra ideia seria centralizar aqui alguns QR Codes Dinâmicos gerados pelos próprios PSP's.

**Comment by ninrod** [comment]
@franciscotfmc 

> Seria possível o BC disponibilizar, neste repositório (ou até mesmo nesta issue), QR Codes Dinâmicos com URL de payload válidas? (que utilizem os certificados ativos da camada de homologação?)

No momento, o BACEN não disponibiliza estas informações.
