### ISSUE TITLE
[Dúvida] no [QR Code] - Validação de campos do BR Code

### ISSUE THREAD

**Issue by jocimarcan** [bacen/pix-api#90]
Prezados, 

O BR Code exige que alguns campos sejam de preenchimento obrigatório. A dúvida é se estes campos devem ser validados no pagamento e qual deve ser o rigor no preenchimento deles na geração de um QR code por meio de aplicativo mobile. Mais especificamente nos campos abaixo:
1) Transaction Currency (M): Este campo pode ser preenchido com valor diferente do Real (ex.: Dólar)? Caso sim, o PSP do pagador poderá negar essa operação quando diferente do Real? Ou ainda, o PSP do pagador deverá se preocupar em validar esse campo na leitura?
2) Merchant Name (M): Como deverá proceder o PSP pagador quando o campo Merchant Name diferir do nome do recebedor recuperado no DICT? Isso vai ocorrer, por exemplo, após uma reivindicação de posse bem sucedida de uma chave já atrelada a algum QR code. Nesse caso, o PSP do pagador deve fazer alguma validação desse campo para aceitar ou recusar um pagamento? Isso implica, na verdade, se um QR code, já impresso, pode ou não mudar de dono.
3) Merchant City (M): Considerando que possa haver limitação em identificar o local da agência do usuário recebedor ou ainda que alguns PSP sequer possuem agências físicas; poderá o PSP recebedor preencher esse campo com a cidade que faz mais sentido?

**Comment by rubenskuhl** [comment]
Posso mencionar a minha expectativa como correntista:
- Caso se use a opção Pix do app ou site, o PSP confirmar que a moeda é BRL, e se não for já rejeitar a transação
- Um QR-Code gerado anteriormente deveria ser invalidado após reinvidicação de uma chave, mas não após portabilidade de uma chave
- A cidade do merchant pode ser preenchida com a informação de geolocalização no caso de app mobile, ou com a informação da conta caso a geolocalização não esteja disponível.

**Comment by dmkamers** [comment]
@jocimarcan @rubenskuhl agradecemos as contribuições. Favor referir-se aos manuais abaixo:
- [Manual de Padrões para Iniciação do Pix](https://www.bcb.gov.br/content/estabilidadefinanceira/pix/Regulamento_Pix/II.ManualdePadroesparaIniciacaodoPix-versao2.0.pdf)
- [Manual do BRCode](https://www.bcb.gov.br/content/estabilidadefinanceira/spb_docs/ManualBRCode.pdf)

Quanto às questões:
1. **Não há previsão** no Manual do BRCode para `Transaction Currency` diferente de _986 – BRL: real brasileiro_. Assim, se o campo for diferente, não se trata de um BRCode (que deve ser o padrão para iniciar pagamento no Brasil).
2. O `MerchantName` sempre é ignorado no contexto do Pix (Manual de Iniciação, nota de rodapé 24).
3. O `MerchantCity` na definição EMV (BRCode) é a cidade onde o recebimento (QR) é gerado. Quando isto não faz sentido (como em transações _online_) pode ser utilizada _a cidade da agência do recebedor ou a cidade-sede do recebedor_ (Manual do BRCode, nota de rodapé 8).
