### ISSUE TITLE
Dúvida - calendario.expiracao e calendario.vencimento

### ISSUE THREAD

**Issue by nataliapaivafreitas** [bacen/pix-api#91]
Os identificadores calendario.expiracao e calendario.vencimento são excludentes? Ou seja, o cliente deve optar entre uma ou outra opção, ou pode utilizar as duas ao mesmo tempo?

**Comment by ninrod** [comment]
Bom dia @nataliapaivafreitas 

> Os identificadores calendario.expiracao e calendario.vencimento são excludentes? Ou seja, o cliente deve optar entre uma ou outra opção, ou pode utilizar as duas ao mesmo tempo?

São excludentes, mas a resposta mais precisa seria: "aguarde a publicação da versão `2.1.0`". Observe que não existe esse campo vencimento, na API, na versão `2.0.0`.
