### ISSUE TITLE
Dúvida - Cálculo do Valor da Cobrança

### ISSUE THREAD

**Issue by nataliapaivafreitas** [bacen/pix-api#93]
No caso de recebimento de Pix, cada instituição ficará responsável por realizar o cálculo do valor da cobrança após a data de vencimento? Se sim, o Bacen irá disponibilizar algum padrão de cálculo?

**Comment by nataliapaivafreitas** [comment]
Oi @ninrod, bom dia!

Vocês tem alguma expectativa para publicação da versão 2.1.0?

**Comment by ninrod** [comment]
@nataliapaivafreitas , olá

> Oi @ninrod, bom dia!
> Vocês tem alguma expectativa para publicação da versão 2.1.0?

Ontem de manhã publicamos: https://github.com/bacen/pix-api/releases

Devo publicar em instantes a 2.1.0-rc.3 corrigindo um bug semântico identificado em #104 e #106

**Comment by nataliapaivafreitas** [comment]
Deve sair uma nova versão do documento "Manual de Padrões para Iniciação do Pix"?
Obrigada pelo retorno!

**Comment by ninrod** [comment]
> Deve sair uma nova versão do documento "Manual de Padrões para Iniciação do Pix"?
Obrigada pelo retorno!

Sim, possivelmente ainda esta semana.
