### ISSUE TITLE
Dúvida - Cobrança de Juros/Multa

### ISSUE THREAD

**Issue by nataliapaivafreitas** [bacen/pix-api#94]
Caso um Pix possua data de vencimento em dia não útil, haverá de cobrança de juros/multa se o cliente realizar o pagamento no próximo dia útil? No caso de QRCode contendo cobrança de multa/juros, o cliente deve informar os valores por dia, mês ou ano?

**Comment by ninrod** [comment]
Bom dia @nataliapaivafreitas , 

> Caso um Pix possua data de vencimento em dia não útil, haverá de cobrança de juros/multa se o cliente realizar o pagamento no próximo dia útil? No caso de QRCode contendo cobrança de multa/juros, o cliente deve informar os valores por dia, mês ou ano?

Os aspectos relacionados a vencimento estarão estabelecidos na versão `2.1.0` da API a ser publicada muito em breve.
