### ISSUE TITLE
Dúvida quanto à URL no QR CODE Dinâmico

### ISSUE THREAD

**Issue by masyaf** [bacen/pix-api#95]
Prezados, bom dia.

No requisito QR Code dinâmico, a URL que estará contido na estrutura do QR Code é a URL que é obtida no campo **location**, cujo é resposta  da chamada PUT cob/{txid} ?

No manual de Iniciação do PIX esta relação não ficou clara, tampouco o campo é mencionado.

Olhando a especificação da Api do pix é possível ver no retorno desta chamada o campo **location**.

"location": "pix.example.com/qr/9d36b84f-c70b-478f-b95c-12729b90ca25",

**Comment by ninrod** [comment]
@masyaf Bom dia. 

> No requisito QR Code dinâmico, a URL que estará contido na estrutura do QR Code é a URL que é obtida no campo location, cujo é resposta da chamada PUT cob/{txid} ?

Sim. 

> No manual de Iniciação do PIX esta relação não ficou clara, tampouco o campo é mencionado.

O manual não dirá nada sobre isso mesmo; contudo, observe que o manual referencia a API Pix (este repo).

> Olhando a especificação da Api do pix é possível ver no retorno desta chamada o campo location.
"location": "pix.example.com/qr/9d36b84f-c70b-478f-b95c-12729b90ca25",

Isso mesmo.
