### ISSUE TITLE
Homologação

### ISSUE THREAD

**Issue by SANTOSADEMAR** [bacen/pix-api#96]
Estou fazendo testes com meu projeto em C# para criar uma cobrança, estou usando a URL https://pix-h.example.com/api/v1/cob/{txid} só ocorre o seguinte erro "O nome remoto não pôde ser resolvido"

**Comment by rubenskuhl** [comment]
O domínio example.com é usado para documentação de chamadas a domínios que precisam ser trocados pelos efetivos domínios. Você precisa contactar um PSP e obter junto com a ele um acesso a sandbox para testes. Uma lista não exaustiva de possíveis PSPs pode ser vista neste issue: https://github.com/bacen/pix-api/issues/76 .

**Comment by ninrod** [comment]
@SANTOSADEMAR ,  bom dia.

> O domínio example.com é usado para documentação de chamadas a domínios que precisam ser trocados pelos efetivos domínios. Você precisa contactar um PSP e obter junto com a ele um acesso a sandbox para testes. Uma lista não exaustiva de possíveis PSPs pode ser vista neste issue: #76 .

@rubenskuhl obrigado.
