### ISSUE TITLE
[Dúvida] Formato dos Escopos do OAuth

### ISSUE THREAD

**Issue by cinrcazangi** [bacen/pix-api#97]
A documentação da API PIX pede para trabalharmos com os seguintes escopos:

cob.write
cob.read
pix.write
pix.read
webhook.read
webhook.write

O nome destes escopos são fixos ou o PSP recebedor tem a liberdade de altera o formato para "cob_write" ao invés de "cob.write", por exemplo?

**Comment by rubenskuhl** [comment]
Os únicos caracteres ASCII que não podem fazer parte de scope são os de controle, espaço, DEL, " e \ (delete, aspas e barra reversa). Ponto é um caracter válido para scope, então como o padrão diz para usar ponto, sair do padrão significa não obedecer à API padrão.

**Comment by fernandogodoy** [comment]
Acho que o ponto mais é, preciso utilizar exatamente estes escopos, ou, o PSP Recebedor que já possui seus proprios escopos, poderia utilzá-los, desde que siga a segregação por escrita e leitura?

**Comment by rubenskuhl** [comment]
> Acho que o ponto mais é, preciso utilizar exatamente estes escopos, ou, o PSP Recebedor que já possui seus proprios escopos, poderia utilzá-los, desde que siga a segregação por escrita e leitura?

O scope é um dos parâmetros do request, então ele precisa ser padronizado.

**Comment by ninrod** [comment]
@cinrcazangi , boa tarde.

> Os únicos caracteres ASCII que não podem fazer parte de scope são os de controle, espaço, DEL, " e \ (delete, aspas e barra reversa). Ponto é um caracter válido para scope, então como o padrão diz para usar ponto, sair do padrão significa não obedecer à API padrão.

Exatamente

> O scope é um dos parâmetros do request, então ele precisa ser padronizado.

Correto

obrigado @rubenskuhl
