### ISSUE TITLE
Webhook: API Pix

### ISSUE THREAD

**Issue by grazipellecchia** [bacen/pix-api#98]
Boa tarde, por favor já existe previsão para entrega da normatização do webhook? 
Muito obrigada, Grazi

**Comment by ninrod** [comment]
@grazipellecchia , boa tarde. 

> Boa tarde, por favor já existe previsão para entrega da normatização do webhook?
Muito obrigada, Grazi

O que seria exatamente esta "normatização"?

**Comment by grazipellecchia** [comment]
> @grazipellecchia , boa tarde. 
> 
> 
> 
> > Boa tarde, por favor já existe previsão para entrega da normatização do webhook?
> 
> Muito obrigada, Grazi
> 
> 
> 
> O que seria exatamente esta "normatização"? 

@ninrod oie, no comunicado que recebemos em 23/09 existia uma informação de que o webhook teria um manual/documento padronizado. 

obs:Sabe admiro sua rapidez.

**Comment by ninrod** [comment]
@grazipellecchia , boa noite. 

> @ninrod oie, no comunicado que recebemos em 23/09 existia uma informação de que o webhook teria um manual/documento padronizado.

Olá, eu não consigo recuperar o inteiro teor do comunicado, mas acredito que estava referindo-se à versão `2.0.0` desta API que estabeleceu os endpoints `/webhook`. 

> obs:Sabe admiro sua rapidez.

Agradeço, o Bacen está realizando um esforço para prover o mercado com informações tempestivas em relação à implementação do Pix. Continuaremos nesta linha.

**Comment by grazipellecchia** [comment]
> @grazipellecchia , boa noite. 
> 
> 
> 
> > @ninrod oie, no comunicado que recebemos em 23/09 existia uma informação de que o webhook teria um manual/documento padronizado.
> 
> 
> 
> Olá, eu não consigo recuperar o inteiro teor do comunicado, mas acredito que estava referindo-se à versão `2.0.0` desta API que estabeleceu os endpoints `/webhook`. 
> 
> 
> 
> > obs:Sabe admiro sua rapidez.
> 
> 
> 
> Agradeço, o Bacen está realizando um esforço para prover o mercado com informações tempestivas em relação à implementação do Pix. Continuaremos nesta linha. 

@ninrod Perfeito, isso mesmo. No comunicado veio a informação da versão `2.0.0` que estabeleceu os endpoints `/webhook. Entendemos que receberemos alguma instrução do modelo a ser seguido, o entendimento está correto?  Caso sim, existe previsão de entrega? A grande dúvida é se podemos usar no nosso modelo.

**Comment by ninrod** [comment]
@grazipellecchia, 

>  Entendemos que receberemos alguma instrução do modelo a ser seguido, o entendimento está correto? Caso sim, existe previsão de entrega? A grande dúvida é se podemos usar no nosso modelo.

Eu não sei se entendi muito bem o que se quer dizer com "modelo a ser seguido", mas a ideia seria que o PSP recebedor implementaria as callbacks definidas nesta especificação OpenAPI 3.0. O usuário recebedor, por sua vez, se escolher integrar-se via webhook, perceberia estes callbacks à medida que os Pix sejam recebidos.

**Comment by grazipellecchia** [comment]
> @grazipellecchia, 
> 
> 
> 
> >  Entendemos que receberemos alguma instrução do modelo a ser seguido, o entendimento está correto? Caso sim, existe previsão de entrega? A grande dúvida é se podemos usar no nosso modelo.
> 
> 
> 
> Eu não sei se entendi muito bem o que se quer dizer com "modelo a ser seguido", mas a ideia seria que o PSP recebedor implementaria as callbacks definidas nesta especificação OpenAPI 3.0. O usuário recebedor, por sua vez, se escolher integrar-se via webhook, perceberia estes callbacks à medida que os Pix sejam recebidos. 

@ninrod Show! Então vamos integrar como estava estabelecido. 
Aproveitando a consulta pública está finalizada? 
Muito obrigada pela ajuda.

**Comment by rubenskuhl** [comment]
Lembrando que a API 2.1 deve sair em alguns minutos...

**Comment by masyaf** [comment]
Aproveitando, o cenário de webhook é válido apenas para o cenário do qr code dinâmico ou é válido também para o cenário de qr code estático?

**Comment by franciscotfmc** [comment]
Entendo que é válido para o estático também, caso exista ali um txid.

**Comment by ninrod** [comment]
> Lembrando que a API 2.1 deve sair em alguns minutos...

Deve sair hoje pela manhã, tivemos um contratempo ontem

**Comment by ninrod** [comment]
> Entendo que é válido para o estático também, caso exista ali um txid.

correto

**Comment by fernandogodoy** [comment]
@ninrod qual a chance da url do webhook passar para dentro do payload de request da cobrança? 

Acredito que dessa forma ganhamos mais flexibilidade tanto no lado do psp quanto do usuário da api.

No lado do PSP não seria necessário configuração de webhook, e do lado do usuário da api seria possível que cobraças distintas possam ser notificadas em endpoits distintos sem necessidade da alteração de configuração do webhook.

**Comment by ninrod** [comment]
> @ninrod qual a chance da url do webhook passar para dentro do payload de request da cobrança?

Desde que seja muito bem fundamentado, há chance. Ainda não entendi este caso de uso específico. Em particular, essa funcionalidade abriria a possibilidade de haver, do ponto de visto do PSP recebedor, uma infinidade de URLs diferentes para que notificações sejam efetivadas. Problemas de segurança também me ocorrem: como garantir que cada uma dessas urls esteja inserida em um contexto de segurança adequado? 

acredito que  @renatofrota, @rubenskuhl, @feinstein e @felipedelima19 tem interesse nesta discussão. 

Aliás, acredito que é interessante concentrarmos a discussão em uma issue só: já há uma discussão semelhante em #62, acredito.

**Comment by grazipellecchia** [comment]
@ninrod Também tenho interesse nessa discussão. Por mim, ok concentrar na #62

**Comment by ninrod** [comment]
Ok pessoal, vamos concentrar em #62, fechando essa.
