### ISSUE TITLE
Minor issue na API 2.1 rc0

### ISSUE THREAD

**Issue by rubenskuhl** [bacen/pix-api#99]
Na tag cobPayload, Payload JSON que representa uma cobrança, era para haver um exemplo de retorno 200, porém após a frase "Segue um exemplo" aparece um quadro de cor única sem o texto de exemplo.

**Comment by ninrod** [comment]
@rubenskuhl , vamos verficar, obrigado.

**Comment by ninrod** [comment]
corrigido via f5882a65f9d56d127965240ce485de3427951df7
